---
title: "Red, green and blue: student group work in subhonours tutorials"
author: Tom Coleman
date: 2026-06-25
format: 
  revealjs:
    theme: [default, starmast-presentation-blue.scss]
    brand: false
---

## Activity 

- Want to encourage students to do a few things:

    - do mathematics/statistics
    - talk to and work with each other
    - discuss how best to present mathematics/statistics
    - explain their working more than they usually would

- Idea is to split tutorial group into three small teams based on a pen colour (red, green, blue), where each team works on a pre-selected problem on the board, and then informally explains their answer to the wider group afterwards

## Beforehand 

- Select three (or more) questions for students to do at the board

    - if question has many parts, can allocated 

- Split the board into three 

- Write the questions in the colour pen on the board where you want them to work

## Starting up {.smaller}

- Distribute pens among students (one pen per student) based on teams 

    - based on tutorial work, can split up stronger students into each of the three teams
    - or go row-by-row, column-by-column
    
- Explain that they will be solving the problem written in their pen colour on the board

- Set a time limit - 10-15 minutes usually more than enough

- Ask for a **'perfect answer'** - not only a correct answer, but a perfect one

## During {.smaller}

- Students work on the problem;

    - each student has their own pen, subtly encouraging all of them to write at least something on the board

- Tutor goes around all of the teams and;

    - talks to the students about how they are finding the material
    - facilitates the teamwork by making sure everyone has a say in the input
    - encourages students to ask each other if they have any concerns about the input
    - provides gentle correction if there are any errors in working
    - explain good page layout and answer structure, promoting discussion of a 'perfect answer'
    
- Important **not** to stand in the corner and let the students do it all!

## After {.smaller}

- Encourage each team to explain their answer to the group 

    - if no-one is forthcoming, the tutor could do it and ask the students in the team for reassurance on their steps
    
- Tutor then summarises the work, highlighting good points and areas for improvement, provides corrections if needed

- Repeat for each team

- Once all teams have had their say, encourage students to take photos of their (now) model answers, and complete the activity

## Pros (1/2) {.smaller}

- Promotes active rather than passive learning

    - gets students doing mathematics/statistics
    - talking to each other in the process

- Promotes discussion of what constitutes a 'perfect' answer

    - how much explanation is required
    - good page layout and answer structure
    - appropriately sized diagrams (if applicable)
    
- Less pressure on students participating in a tutorial; students are happier to talk to each other/in teams rather than answering questions to the tutor in front of the entire class

## Pros (2/2) {.smaller}

- Activity lasts for only half the length of a tutorial, leaving space for a more traditional tutorial setting afterwards (for example, to explain any questions the entire group struggled with)

- More tutorial material is covered in the same time

    - working in parallel, rather than in series

- Students have their own (and their peers) work to refer to, and 

    - are able to compare the model answers on the board to their attempts prior to the tutorial
    - have at least some model answers if they did not attempt the questions beforehand

## Cons

- Space dependent (works in 1A, 1B, 1C, works but is tight in 1D and 1E, probably won't work in 3B)

- Sometimes certain students dominate the team

    - good facilitation can mitigate this

- Sometimes students don't finish the work / have a wrong answer at the end of the tutorial

    - good facilitation can mitigate this
    - critical evaluation at end will correct errors

## Any questions?

**thank you for listening :)**