---
title: "Radians: Answers"
author: "Ifan Howells-Baines, Mark Toner"
abstract-title: Summary
abstract: Answers to the questions relating to the guide on radians.
---

*These are the answers to [Questions: Radians](qs-radians.qmd).* **Please attempt the questions before reading these answers!**

## Q1 {-}

Convert the following angle measures in degrees into radians, simplifying all fractions and give answers to $3$ significant figures.

1.1. Mulitplying $30 ^\circ$ by $\pi$ and dividing by $180$ gives $\frac{30\pi}{180} \textrm{rad} = \frac{\pi}{6} \textrm{rad} \approx 0.524 \textrm{rad}$.

1.2. Mulitplying $105^\circ$ by $\pi$ and dividing by $180$ gives $\frac{105\pi}{180} \textrm{rad} = \frac{7\pi}{12} \textrm{rad} \approx 1.83 \textrm{rad}$.

1.3. Mulitplying $298^\circ$ by $\pi$ and dividing by $180$ gives $\frac{298\pi}{180} \textrm{rad} = \frac{149\pi}{90} \textrm{rad} \approx 5.20 \textrm{rad}$.

1.4. Mulitplying $61^\circ$ by $\pi$ and dividing by $180$ gives $\frac{61\pi}{180} \textrm{rad} \approx 1.06 \textrm{rad}$.

1.5. Mulitplying $353^\circ$ by $\pi$ and dividing by $180$ gives $\frac{353\pi}{180} \textrm{rad} \approx 6.16 \textrm{rad}$.

## Q2 {-}

Convert the followig angle measures in radians into degrees. Giving answers to $3$ significant figures.

2.1. Multiplying $\frac{\pi}{3} \textrm{rad}$ by $180$ and dividing by $\pi$ gives $\frac{180\pi}{3\pi} ^\circ = 60 ^\circ$.

2.2.  Multiplying $\frac{2\pi}{3}\textrm{rad}$ by $180$ and dividing by $\pi$ gives $\frac{360\pi}{3\pi} ^\circ = 120 ^\circ$.

2.3.  Multiplying $\frac{\pi}{7} \textrm{rad}$ by $180$ and dividing by $\pi$ gives $\frac{180\pi}{7\pi} ^\circ \approx 25.7 ^\circ$.

2.4.  Multiplying $\frac{5\pi}{7}\textrm{rad}$ by $180$ and dividing by $\pi$ gives $\frac{900\pi}{7\pi} ^\circ \approx 128 ^\circ$.

2.5.  Multiplying $5\textrm{rad}$ by $180$ and dividing by $\pi$ gives $\frac{900}{\pi} ^\circ = \frac{5}{\pi} ^\circ \approx 286 ^\circ$.

2.6. Multiplying $\frac{3}{4} \textrm{rad}$ by $180$ and dividing by $\pi$ gives $\frac{540}{4\pi} ^\circ = \frac{135}{\pi} ^\circ \approx 43.0 ^\circ$.