---
title: "Trigonometric identities: answers"
author: "Dzhemma Ruseva"
abstract-title: Summary
abstract: A selection of questions on trigonometric identities.

---

*These are the answers to [Questions: Trigonometric identities](qs-trigident.qmd).*
**Please attempt the questions before reading these answers!**


## Questions {-}

### Q1 {-}
Using trigonometric identities find the values of the following equations:

1.1.  $\ \quad2(6\sin^2(\theta))+3(4\cos^2(\theta))$.   

**Answer:**$\ 2(6\sin^2(\theta))+3(4\cos^2(\theta)) = 12(\sin^2(\theta)+\cos^2(\theta)) = 12$

1.2.  $\ \quad10(7\sin^2(\theta))+14(5\cos^2(\theta))$.

**Answer:**$\ 70$

1.3.  $\ \quad5(\frac{6}{\csc^2(\theta)})+15(\frac{2}{sec^2(\theta)})$.

**Answer:**$\ 5(\frac{6}{\csc^2(\theta)})+15(\frac{2}{sec^2(\theta)}) = 30\sin^2(\theta)+30\cos^2(\theta) = 30$

1.4.  $\ \quad(\cos^2(\theta)-\sin^2(\theta))^2 + 4sin^2(\theta)\cos^2(\theta)$

**Answer:** $\ (\cos^2(\theta)-\sin^2(\theta))^2 + 4\sin^2(\theta)\cos^2(\theta) = \cos^2(2\theta) + \sin^2(2\theta) = 1$

1.5.  $\ \quad7\cos(90^\circ-\theta)\sin(\theta)+7\sin(90^\circ-\theta)\cos(\theta)$

**Answer:** $\ 7\cos(90^\circ-\theta)\sin(\theta)+7\sin(90^\circ-\theta)\cos(\theta) = 7\sin^2(\theta) + 7\cos^2(\theta) = 7$

1.6.  $\ \quad6\sin(\theta+2\pi)\sin(\theta+4\pi)+6\cos(\theta-2\pi)\cos(\theta-4\pi)$

**Answer:** $\ 6\sin(\theta+2\pi)\sin(\theta+4\pi)+6\cos(\theta-2\pi)\cos(\theta-4\pi) = 6\sin^2(\theta) + 6\cos^2(\theta) = 6$

1.7.  $\ \quad2\sin(30^\circ)\cos(15^\circ)+2\cos(30^\circ)\sin(15^\circ)$

**Answer:** $\ 2\sin(30^\circ)\cos(15^\circ)+2\cos(30^\circ)\sin(15^\circ) = \sin(30^\circ+15^\circ) = \sin(45^\circ) = \frac{1}{\sqrt2}$

1.8.  $\ \quad3\cos(45^\circ)\cos(15^\circ)-3\sin(45^\circ)\sin(15^\circ)$

**Answer:** $\ 3\cos(45^\circ)\cos(15^\circ)-3\sin(45^\circ)\sin(15^\circ) = 3\cos(60^\circ) = \frac{3}{2}$

1.9.  $\ \quad\sin(150^\circ)+\sin(30^\circ)$

**Answer:**$\ \sin(150^\circ)+\sin(30^\circ) = 2\sin(\frac{180^\circ}{2})\cos(\frac{120^\circ}{2}) = 2\sin(90^\circ)\cos(60^\circ) = 1$ 

1.10. $\quad\cos(150^\circ)+\cos(30^\circ)$

**Answer:**$\ \cos(150^\circ)+\sin(30^\circ) = 2\cos(90^\circ)\cos(60^\circ) = 0$  


### Q2 {-}
Simplify the following equations:

2.1. $\ \quad\tan(\theta)\cos(-\theta)$

**Answer:** $\ \tan(\theta)\cos(-\theta) = \frac{\sin(\theta)}{\cos(\theta)}cos(\theta) = \sin(\theta)$

2.2  $\ \quad\tan(-\theta)\csc(-\theta)\sec(-\theta)$

**Answer:** $\ \tan(-\theta)\csc(-\theta)\sec(-\theta) = (-\frac{\sin(\theta)}{\cos(\theta)})(\frac{1}{-\sin(\theta)})(\frac{1}{\cos(\theta)}) = (\frac{1}{\cos^2(\theta)}) = \sec^2(\theta)$

2.4. $\ \quad\tan^2(\theta)+\sin^2(\theta)+\cos^2(\theta)$

**Answer:** $\ \tan^2(\theta)+\sin^2(\theta)+\cos^2(\theta) = \tan^2(\theta)+1 = \sec^2(\theta)$

2.5. $\ \quad\frac{2\sin(\theta)}{\cos(\theta)(1-\tan^2(\theta))}$

**Answer:**$\ \frac{2\sin(\theta)}{\cos(\theta)(1-\tan^2(\theta))} = \tan(2\theta)$

2.6. $\ \quad\sin(90^\circ+\theta)-\sin(90^\circ-\theta)$

**Answer:** $\ \sin(90^\circ+\theta)-\sin(90^\circ-\theta) = 2\sin(90^\circ)\cos(\theta) = 2\cos(\theta)$

2.7. $\ \quad\frac{\sin(7\theta)+\sin(3\theta)}{\cos(7\theta)-\cos(3\theta)}$

**Answer:** $\ \frac{\sin(7\theta)+\sin(3\theta)}{\cos(7\theta)-\cos(3\theta)} = \frac{2\sin(5\theta)\cos(2\theta)}{-2\sin(5\theta)\sin(2\theta)} = -\cot(\theta)$

2.8. $\ \quad\frac{\sin(5\theta)-\sin(1\theta)}{\cos(5\theta)+\cos(1\theta)}$

**Answer:** $\ \frac{\sin(5\theta)-\sin(1\theta)}{\cos(5\theta)+\cos(1\theta)} = \tan(2\theta)$
 

### Q3 {-}
Using trigonometric identities find the values of(Hint - use the sum and difference identities):

3.1. $\ \quad\sin(15^\circ) =\ ?$

**Answer:** $\ \sin(15^\circ) = \sin(45^\circ-30^\circ) = \sin(45^\circ)\cos(30^\circ) - \cos(45^\circ)\sin(30^\circ) = \frac{\sqrt3}{2\sqrt2} - \frac{1}{2\sqrt2} = \frac{\sqrt3-1}{2\sqrt2}$ 

3.2. $\ \quad\cos(15^\circ) =\ ?$

**Answer:** $\ \frac{\sqrt3+1}{2\sqrt2}$

3.3. $\tan(15^\circ) =\frac{\sqrt3+1}{\sqrt3-1}$

**Answer:**

3.4. $\ \quad\sin(75^\circ) =\ ?$

**Answer:** $\ \sin(75^\circ) = \sin(45^\circ)\cos(30^\circ) + \cos(45^\circ)\sin(30^\circ) = \frac{\sqrt3+1}{2\sqrt2}$

3.5. $\ \quad\cos(75^\circ) =\ ?$

**Answer:** $\ \frac{\sqrt3-1}{2\sqrt2}$

3.6. $\ \quad\tan(75^\circ) =\ ?$

**Answer:**$\ \frac{\sqrt3+1}{\sqrt3-1}$



