---
title: "STARMAST: For contributors"
format: html
---

# How to contribute

Here at STARMAST, we welcome **any** contributions from you, the user. Whether it is pointing out a typo in the middle of a guide, suggestions for future guides on certain topics, or even writing guides yourself, we want to hear from you.

If you have a github account, then you can leave comments on individual pages by using the inbuilt `utterances` package. This is ideal for leaving feedback on individual guides.

If you do not have a github account, please feel free to email **tdhc (at) st-andrews (dot) ac (dot) uk** with *any* issues. 

In particular, if you would like to contribute, please email tdhc (at the address above), and see the [list of wanted topics](ttdl.qmd), the [style guide](styleguide.qmd), and the [readme file on the github repository](https://github.com/tdhc153/starmast).

# Back-end stuff

- [Style guide for STARMAST materials](styleguide.qmd)

- [Tom's to-do list (TTDL): drafts in progress, wanted guides, and more](ttdl.qmd)