---
title: "STARMAST full index"
summary: A full index of every STARMAST written resource.
format: html
---

<!-- Public facing manual index. Only fully complete resources may be added to the tables below. -->

This is a complete index of links to all available written materials on the STARMAST site. You can find all interactive materials at the [app list page](applist.qmd).

Each topic is marked with: 

- (✕) when its QuickCheck problem remains incomplete
- (✓) when all questions have been answered correctly

# Study guides, questions, answers

## Arithmetic and algebra {-}

| **Topic**                                                                                        | Link to guide      | Link to questions  | Link to answers    |
|:-------------------------------------------------------------------------------------------------|:------------------:|:------------------:|:------------------:|
| <span class="topic-item" data-topic="ITCN1">Introduction to complex numbers</span>               | [guide](./studyguides/introtocomplexnumbers.qmd) | [questions](./questions/qs-introtocomplexnumbers.qmd) | [answers](./answers/as-introtocomplexnumbers.qmd) |
| <span class="topic-item" data-topic="AOCN1">  Arithmetic on complex numbers</span>                  | [guide](./studyguides/arithmeticoncomplexnumbers.qmd) | [questions](./questions/qs-arithmeticoncomplexnumbers.qmd) | [answers](./answers/as-arithmeticoncomplexnumbers.qmd) |
| <span class="topic-item" data-topic="ITQE1">  Introduction to quadratic equations</span>            | [guide](./studyguides/introtoquadratics.qmd) | [questions](./questions/qs-introtoquadratics.qmd) | [answers](./answers/as-introtoquadratics.qmd) |
| <span class="topic-item" data-topic="CTS1">  Completing the square</span>                          | [guide](./studyguides/completingthesquare.qmd) | [questions](./questions/qs-completingthesquare.qmd) | [answers](./answers/as-completingthesquare.qmd) |
| <span class="topic-item" data-topic="TQF1">   The quadratic formula</span>                          | [guide](./studyguides/quadraticformula.qmd) |[questions](./questions/qs-quadraticformula.qmd) | [answers](./answers/as-quadraticformula.qmd) |
| <span class="topic-item" data-topic="LOI1">   Laws of indices</span>                                | [guide](./studyguides/lawsofindices.qmd) | [questions](./questions/qs-lawsofindices.qmd) | [answers](./answers/as-lawsofindices.qmd) |
| <span class="topic-item" data-topic="SEE1">   Solving exponential equations</span>                  | [guide](./studyguides/solvingeqsindices.qmd) | [questions](./questions/qs-solvingeqsindices.qmd) | [answers](./answers/as-solvingeqsindices.qmd) |
| <span class="topic-item" data-topic="ITL1">   Introduction to logarithms</span>                     | [guide](./studyguides/logarithms.qmd) | [questions](./questions/qs-logarithms.qmd) | [answers](./answers/as-logarithms.qmd) |
| <span class="topic-item" data-topic="ITSN1">  Introduction to sigma notation</span>                 | [guide](./studyguides/sigmanotation.qmd) | [questions](./questions/qs-sigmanotation.qmd) | [answers](./answers/as-sigmanotation.qmd) |
| <span class="topic-item" data-topic="ITRE1">  Introduction to rearranging equations</span>          | [guide](./studyguides/introtorearrange.qmd) | [questions](./questions/qs-introtorearrange.qmd) | [answers](./answers/as-introtorearrange.qmd) |
| <span class="topic-item" data-topic="RTD1">   Rationalizing the denominator</span>                  | [guide](./studyguides/rationalizingthedenominator.qmd) | [questions](./questions/qs-rationalizingthedenominator.qmd) | [answers](./answers/as-rationalizingthedenominator.qmd) |
| <span class="topic-item" data-topic="ITSSE1"> Introduction to solving simultaneous equations</span> | [guide](./studyguides/introtosimeqs.qmd) | [questions](./questions/qs-introtosimeqs.qmd) | [answers](./answers/as-introtosimeqs.qmd) |
| <span class="topic-item" data-topic="FACT1"> Factorization</span> | [guide](./studyguides/factorization.qmd) | [questions](./questions/qs-factorization.qmd) | [answers](./answers/as-factorization.qmd) |


: {tbl-colwidths="[55,15,15,15]"}

<!-- | Further sigma notation               | [guide](./studyguides/furthersigmanotation.qmd) | [questions](./questions/qs-furthersigmanotation.qmd) | [answers](./answers/as-furthersigmanotation.qmd) | -->
<!-- | Rearranging trig and logs            | [guide](./studyguides/rearrangingtrigandlogs.qmd) | [questions](./questions/qs-rearrangingtrigandlogs.qmd) | [answers](./answers/as-rearrangingtrigandlogs.qmd) | -->


## Angles and trigonometry {-}

| **Topic**                                                                                  | Link to guide      | Link to questions  | Link to answers    |
|:-------------------------------------------------------------------------------------------|:------------------:|:------------------:|:------------------:|
| <span class="topic-item" data-topic="R1"> Radians</span>                                   | [guide](./studyguides/radians.qmd) | [questions](./questions/qs-radians.qmd) | [answers](./answers/as-radians.qmd) |
| <span class="topic-item" data-topic="ITTD1"> Introduction to trigonometry (degrees)</span> | [guide](./studyguides/trigonometry-degrees.qmd) | [questions](./questions/qs-trigonometry-degrees.qmd) | [answers](./answers/as-trigonometry-degrees.qmd) |
| <span class="topic-item" data-topic="ITTR1"> Introduction to trigonometry (radians)</span> | [guide](./studyguides/trigonometry-radians.qmd) | [questions](./questions/qs-trigonometry-radians.qmd) | [answers](./answers/as-trigonometry-radians.qmd) |
| <span class="topic-item" data-topic="TID1">  Trigonometric identities (degrees)</span>     | [guide](./studyguides/trigonometricidentities-degrees.qmd) | [questions](./questions/qs-trigonometricidentities-degrees.qmd) | [answers](./answers/as-trigonometricidentities-degrees.qmd) |
| <span class="topic-item" data-topic="TIR1">  Trigonometric identities (radians)</span>     | [guide](./studyguides/trigonometricidentities-radians.qmd) | [questions](./questions/qs-trigonometricidentities-radians.qmd) | [answers](./answers/as-trigonometricidentities-radians.qmd) |

: {tbl-colwidths="[55,15,15,15]"}

## Vectors {-}

| **Topic**                                                                                      | Link to guide      | Link to questions  | Link to answers    |
|:-----------------------------------------------------------------------------------------------|:------------------:|:------------------:|:------------------:|
| <span class="topic-item" data-topic="ITV1">   Introduction to vectors</span>                   | [guide](./studyguides/introductiontovectors.qmd) | [questions](./questions/qs-introductiontovectors.qmd) | [answers](./answers/as-introductiontovectors.qmd) |
| <span class="topic-item" data-topic="VAASM1"> Vector addition and scalar multiplication</span> | [guide](./studyguides/addandsm.qmd) | [questions](./questions/qs-addandsm.qmd) | [answers](./answers/as-addandsm.qmd) |
| <span class="topic-item" data-topic="TSP1">   The scalar product</span>                        | [guide](./studyguides/scalarproduct.qmd) | [questions](./questions/qs-scalarproduct.qmd) | [answers](./answers/as-scalarproduct.qmd) |

: {tbl-colwidths="[55,15,15,15]"}

## Calculus {-}

| **Topic**                                                                                                | Link to guide      | Link to questions  | Link to answers    |
|:---------------------------------------------------------------------------------------------------------|:------------------:|:------------------:|:------------------:|
| <span class="topic-item" data-topic="ITDATD1"> Introduction to differentiation and the derivative</span> | [guide](./studyguides/introtodifferentiation.qmd) | [questions](./questions/qs-introtodifferentiation.qmd) | [answers](./answers/as-introtodifferentiation.qmd) |
| <span class="topic-item" data-topic="PROD1"> The product rule</span> | [guide](./studyguides/productrule.qmd) | [questions](./questions/qs-productrule.qmd) | [answers](./answers/as-productrule.qmd) |
| <span class="topic-item" data-topic="QUOT1"> The quotient rule</span> | [guide](./studyguides/quotientrule.qmd) | [questions](./questions/qs-quotientrule.qmd) | [answers](./answers/as-quotientrule.qmd) |
| <span class="topic-item" data-topic="CHAIN1"> The chain rule</span> | [guide](./studyguides/chainrule.qmd) | [questions](./questions/qs-chainrule.qmd) | [answers](./answers/as-chainrule.qmd) |
| <span class="topic-item" data-topic="IPD1"> Introduction to partial differentiation</span> | [guide](./studyguides/introtopartialdifferentiation.qmd) | [questions](./questions/qs-introtopartialdifferentiation.qmd) | [answers](./answers/as-introtopartialdifferentiation.qmd) |
| <span class="topic-item" data-topic="II1"> Introduction to integration</span> | [guide](./studyguides/introtointegration.qmd) | [questions](./questions/qs-introtointegration.qmd) | [answers](./answers/as-introtointegration.qmd) |


: {tbl-colwidths="[55,15,15,15]"}

## Probability and statistics {-}

| **Topic**                                                                              | Link to guide      | Link to questions  | Link to answers    |
|:---------------------------------------------------------------------------------------|:------------------:|:------------------:|:------------------:|
| <span class="topic-item" data-topic="PROB1"> Introduction to probability</span>                   | [guide](./studyguides/introtoprobability.qmd) | [questions](./questions/qs-introtoprobability.qmd) | [answers](./answers/as-introtoprobability.qmd) |
| <span class="topic-item" data-topic="PPC1"> PMFs, PDFs, CDFs</span>                   | [guide](./studyguides/pmfspdfscdfs.qmd) | [questions](./questions/qs-pmfspdfscdfs.qmd) | [answers](./answers/as-pmfspdfscdfs.qmd) |
| <span class="topic-item" data-topic="EVVSD1"> Expected value, variance, standard deviation</span>                   | [guide](./studyguides/expectedvariance.qmd) | [questions](./questions/qs-expectedvariance.qmd) | [answers](./answers/as-expectedvariance.qmd) |
| <span class="topic-item" data-topic="CP1"> Conditional probability</span>                   | [guide](./studyguides/conditionalprobability.qmd) | [questions](./questions/qs-conditionalprobability.qmd) | [answers](./answers/as-conditionalprobability.qmd) |
| <span class="topic-item" data-topic="TPBT1">  Law of total probability and Bayes' theorem</span>                   | [guide](./studyguides/bayestheorem.qmd) | [questions](./questions/qs-bayestheorem.qmd) | [answers](./answers/as-bayestheorem.qmd) |
| <span class="topic-item" data-topic="ITHT1"> Introduction to hypothesis testing</span> | [guide](./studyguides/hypothesistesting.qmd) | [questions](./questions/qs-hypothesistesting.qmd) | [answers](./answers/as-hypothesistesting.qmd) |

: {tbl-colwidths="[55,15,15,15]"}

# Overviews

| **Topic**                            | Link to overview      |
|:-------------------------------------|:----------------------:| 
| Probability distributions            | [overview](./overviews/o-distribution.qmd) |

: {tbl-colwidths="[40,20]"}

# Factsheets

## Mathematics {-}

| **Topic**                            | Link to factsheet      |
|:-------------------------------------|:----------------------:| 
| Laws of logarithms                   | [factsheet](./factsheets/f-lawsoflogarithms.qmd) | 
| Laws of indices                      | [factsheet](./factsheets/f-lawsofindices.qmd) | 
| Greek letters                        | [factsheet](./factsheets/f-greekletters.qmd) |

: {tbl-colwidths="[40,20]"}

## Statistics {-}

| **Topic**                            | Link to factsheet      |
|:-------------------------------------|:----------------------:| 
| Beta distribution                   | [factsheet](./factsheets/f-betadist.qmd) | 
| Binomial distribution               | [factsheet](./factsheets/f-binomialdist.qmd) | 
| Chi-squared distribution            | [factsheet](./factsheets/f-chisquareddist.qmd) | 
| Continuous uniform distribution     | [factsheet](./factsheets/f-contunifdist.qmd) | 
| Discrete uniform distribution       | [factsheet](./factsheets/f-dunifdist.qmd) | 
| Exponential distribution            | [factsheet](./factsheets/f-expdist.qmd) | 
| $F$-distribution                   | [factsheet](./factsheets/f-fdist.qmd) | 
| Gamma distribution                   | [factsheet](./factsheets/f-gammadist.qmd) | 
| Geometric distribution              | [factsheet](./factsheets/f-geomdist.qmd) | 
| Lognormal distribution              | [factsheet](./factsheets/f-lognormaldist.qmd) | 
| Negative binomial distribution      | [factsheet](./factsheets/f-negbinomialdist.qmd) | 
| Normal distribution                   | [factsheet](./factsheets/f-normaldist.qmd) | 
| Poisson distribution                   | [factsheet](./factsheets/f-poissondist.qmd) | 
| $t$-distribution                   | [factsheet](./factsheets/f-tdist.qmd) | 

: {tbl-colwidths="[40,20]"}

# Proof sheets

| **Topic**                            | Link to proof sheet      |
|:-------------------------------------|:----------------------:| 
| Quadratic formula                    | [proof sheet](./proofsheets/ps-quadraticformula.qmd) | 
| Scalar product                       | [proof sheet](./proofsheets/ps-scalarproduct.qmd) | 
| Derivatives of functions from first principles  | [proof sheet](./proofsheets/ps-introtodifferentiation.qmd) | 
| Rules of differentiation  | [proof sheet](./proofsheets/ps-rulesofdifferentiation.qmd) | 
| PMFs, PDFs, CDFs  | [proof sheet](./proofsheets/ps-pmfspdfscdfs.qmd) | 
| Law of total probability and Bayes' theorem  | [proof sheet](./proofsheets/ps-bayestheorem.qmd) | 

: {tbl-colwidths="[40,20]"}