---
title: "STARMAST Index"
---

# Templates

[Guide: Introduction to quadratic equations](./studyguides/introtoquadratics.qmd) ([pdf](introtoquadratics.pdf), [word](introtoquadratics.docx))

[Questions: Introduction to quadratic equations](qs-introtoquadratics.qmd) ([pdf](qs-introtoquadratics.pdf), [word](qs-introtoquadratics.docx))

[Answers: Introduction to quadratic equations](as-introtoquadratics.qmd) ([pdf](as-introtoquadratics.pdf), [word](qs-introtoquadratics.docx))

## Arithmetic and algebra {-}

| **Topic**                            | Link to guide      | Link to questions  | Link to answers    |
|:------------------------------------:|:------------------:|:------------------:|:------------------:|
| Introduction to quadratic equations  | [guide](./studyguides/introtoquadratics.qmd) | [questions](./questions/qs-introtoquadratics.qmd) | [answers](./answers/as-introtoquadratics.qmd) |
| The quadratic formula                | [guide](./studyguides/quadraticformula.qmd) |[questions](./questions/qs-quadraticformula.qmd) | [answers](./answers/as-quadraticformula.qmd) |
| Laws of indices                      | [guide](./studyguides/lawsofindices.qmd) | [questions](./questions/qs-lawsofindices.qmd) | [answers](./answers/as-lawsofindices.qmd) |
| Powers and $n$th roots               | [guide](./studyguides/powersandnthroots.qmd) | [questions](./questions/qs-powersandnthroots.qmd) | [answers](./answers/as-powersandnthroots.qmd) |
| Logarithms                           | [guide](./studyguides/logarithms.qmd) | [questions](./questions/qs-logarithms.qmd) | [answers](./answers/as-logarithms.qmd) |

## Trigonometry {-}

## Vectors {-}

| **Topic**                            | Link to guide      | Link to questions  | Link to answers    |
|:------------------------------------:|:------------------:|:------------------:|:------------------:|
| Introduction to vectors              | [guide](./studyguides/introductiontovectors.qmd) | [questions](./questions/qs-introductiontovectors.qmd) | [answers](./answers/as-introductiontovectors.qmd) |
| Addition and scalar multiplication   | [guide](./studyguides/additionandscalarmultiplication.qmd) | [questions](./questions/qs-additionandscalarmultiplication.qmd) | [answers](./answers/as-additionandscalarmultiplication.qmd) |
| The scalar product                   | [guide](./studyguides/scalarproduct.qmd) | [questions](./questions/qs-scalarproduct.qmd) | [answers](./answers/as-scalarproduct.qmd) |

