---
title: "Introduction to rearranging equations"
authors: "Shanelle Advani, Ciara Cormican"
abstract-title: Summary
abstract: Being able to rearrange equations is a crucial skill in mathematics as it can help us to simplify problems and better understand the relationships between variables. This will guide introduce the concept and take you through how to undo common operations.
---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this guide, it is recommended that you read [Guide: Introduction to quadratic equations](introtoquadratics.qmd)*

## How to approach rearranging equations

It is useful to be able to rearrange an equation to focus on a specific variable. For this guide we will refer to the specific variable as the 'subject' of the equation.

To rearrange an equation to make a variable the subject of the equation you may need to 'undo' certain operations which are applied to the equation.

Additionally, when rearranging equations, commutative, associative and distributive laws are important. 


### Why it is useful to be able to rearrange equations

Rearranging equations can be useful. You may want to rearrange an equation to get an expression for a specific value which can be then solved by substitution.
 e.g $x = \sqrt{45y}$


You may also have multiple equations where rearranging an equation allows for a substitution.

For example

::: {.callout-note}
## Example 1
Consider the following simultaneous equations

$$1)\quad x + y = 4z$$

$$2)\quad \frac{5z}{x} + \frac{1}{x} = 5 + 5\frac{y}{x}$$


the second equation can be simplified by a number of steps 

$$ \frac{1}{x}(5z + 1) = 5 + 5\frac{y}{x}$ $$

$$ \frac{1}{x}(5z + 1) = 5(1 + \frac{y}{x}) $$

$$ \frac{1}{5}(5z + 1) = x(1 + \frac{y}{x}) $$

$$ \frac{1}{5}(5z + 1) = x + y $$

As we have another expression for $x+y$ above $x+y=4z$ we can substitute $4z$ into the simplified expression above to get

$$ \frac{1}{5} (5z + 1) = 4z$$

which further simplifies to

$$ z + \frac{1}{5} = 4z$$

$$ 3z = \frac{1}{5}$$

$$ z = \frac{1}{15}$$

:::

## 'Undoing' Operations

For each mathematical operation, to 'undo' one operation you can use the opposite operation to do so.

### Addition and Subtraction
To undo addition in an equation, you use its inverse: subtraction and vice versa.
The example below uses subtraction to rearrange an equation in $x$.

::: {.callout-note}
## Example 2
Given the equation $x + a = b$ you can make $x$ the subject of the equation by
subtracting the variable $a$ from both sides of the equation. 

This will give you

$$x + a − a = b − a$$

as $a - a$ is equivalent to 0, the expression 
should simplify to

$$x = b − a$$
:::

Similarly, to undo subtraction, you do the 'opposite' action: addition.
The example below uses addition to 'undo' the subtraction in the equation in $x$.

::: {.callout-note}
## Example 3

Similarly, if you want to make $x$ the subject of the equation $x − 8 = a$ you add
8 to both sides. 

Doing this gives you

$$x − 8 + 8 = a + 8$$

which simplifies to

$$x = a + 8$$
:::

### Multiplication and Division

You can undo multiplication in an equation by using its inverse: division.
The example below uses division to 'undo' the multiplication in the equation in $x$.

::: {.callout-note}
## Example 4
Given the equation $ax = b$ we can make $x$ the subject by dividing both sides
by $a$. 
This gives you

$$\frac{ax}{a} = \frac{b}{a}$$

This can then be simplified. As $\frac{a}{a}$ is equivalent to 1, the expression simplifies to

$$1 * x = \frac{b}{a}$$

which can be expressed as 

$$x = \frac{b}{a}$$
:::

Similarly, you can undo division in an equation by using its inverse: multiplication.

::: {.callout-note}
## Example 5
To make $x$ the subject of the equation $\frac{3}{4}x + a = 6$ you start by undoing the operation furthest away from the variable you want to subject. 

In this case it is the addition of the variable $a$. 
You can remove it from the right hand side of the equation by subtracting it from both sides. 

This gives us 

$$\frac{3}{4}x + a - a = 6 - a$$

which simplifies to

$$\frac{3}{4}x = 6 - a$$

Now in order to get rid of the fraction on the right hand side you first multiply
the whole equation by the denominator 4, giving you

$$3x = (6 − a)*4$$

$$3x = 24 − 4a$$

Then finally you divide both sides of the equation by 3 to get
$$x = 8 − \frac{4}{3}a$$

Tip: Make sure that whatever action you do to one side of the equation you
do to the other. For example, if you multiply one side of the equation by
3, you have to multiply the other side by 3 as well.
:::


### Powers and roots
To undo powers in an equation, you use roots which acts as its inverse.

::: {.callout-note}
## Example 6
If you want to make $x$ the subject of the equation $x^a = b$, you take the $a^{th}$ root of both sides. 
This gives you
$$x = ± \sqrt[a]{b}$$

• Tip:  Make sure when you take the root of a power, you are aware of what sign the value is. For a square root, the value could have a positive or negative sign.
:::

::: {.callout-note}
## Example 7
You are given the equation $2z = x^2 + 5y$. To make $x$ the subject isolate $x^2$ on
one side of the equation like so:

$$4x^2 = 5y − 2z$$

and then take the square root of both sides to get

$$x = ±\sqrt{5y − 2z}$$
:::

For roots in equations, the inverse operation of taking the equation to a power can be used.

::: {.callout-note}
## Example 8
If you want to make $x$ the subject of the equation $\sqrt{xa + 2} = b$, you need to get rid of the square root around $xa + 2$. This can be done by 'squaring' both sides.

This gives you 
$$\sqrt{xa + 2}^2 = b^2$$

As $\sqrt{xa + 2} ^2$ is $xa + 2$, the equation simplifies to

$$xa + 2 = b^2$$

$$xa + 2 - 2 = b^2 - 2$$

$$xa = b^2 - 2$$

$$x = \frac{b^2 - 2}{a}$$
:::


## Using Factorisation
What if the variable you want to subject is linked to more than one term?

In this instance, we can use factorisation to help us rearrange the equation. 
Let’s have a look at some examples.

::: {.callout-note}
## Example 9
In the equation $xy + 2x = 3y$ you can see that $x$ appears twice in the first two
terms. 

To rewrite the equation in terms of x you can factorise the right-hand side, this gives you

$$x(y + 2) = 3y$$

Next, divide both side of the equation to get the final form:

$$x = \frac{3y}{y+2}$$
:::

::: {.callout-note}
## Example 10
Here, the equation $xyz − 2z = 4y + x$ contains the variable $x$ on both sides. 

You can start by bringing all the terms with $x$ to one side and moving the others so your equation look like this:

$$xyz − x = 4y + 2z$$

Now you can factorise $x$ out the right-hand side, giving you

$$x(yz − 1) = 4y + 2z$$

Finally, divide both side by $(yx − 1)$ to get

$$x = 4y + 2z yz − 1$$

• Tip: If the variable you wish to subject appears more than once in an
equation, it is generally a good idea to start by bringing all the terms that
include the variable to one side of the equation so you can factorise it out.
:::

## Putting it all together

Often expressions will include multiple operations which you will have to undo part by part to rearrange an equation. 
The example below includes an expression which requires multiple steps in order to make $x$ the subject of the equation. 

::: {.callout-note}
## Example 11
Consider the following equation $3(x^2 + a) = \frac{x^3}{xb} - a$
When rearranging this equation, the order of operations is important to keep in mind. 

To rearrange the equation to make $x$ the focus, the first operation which you need to 'undo' is the bracket.

 $\frac{3(x^2 + a)}{3} = \frac{\frac{x^3}{xb} - a}{3}$
 
 $x^2 + a = \frac{1}{3}(\frac{x^3}{xb} - a)$
 
This can be simplified to 

 $x^2 + a = \frac{1}{3}(\frac{x^2}{b} - a)$

Now the $x$ on the right hand side needs to be moved to the left. This can be done by subtracting the expression in x from both sides. 
This can be done as soon as any brackets have been multiplied out.

 $$x^2 + a = \frac{x^2}{3b} - \frac{a}{3}$$
 
 $$x^2 + a -\frac{x^2}{3b} = \frac{x^2}{3b} - \frac{a}{3} - \frac{x^2}{3b}$$

 $$x^2 + a -\frac{x^2}{3b} = - \frac{a}{3}$$
 
The $a$ term on the left hand side can be moved to the right hand side using subtraction again.

 $$x^2 + a -\frac{x^2}{3b} - a = - \frac{a}{3} - a$$
 
 $$x^2 -\frac{x^2}{3b}= - \frac{a}{3} - a$$
 
 $$x^2 (1 - \frac{1}{3b}) = -a(1 + \frac{1}{3})$$
 
 $$x^2 (1 - \frac{1}{3b}) = -a(1 + \frac{1}{3})$$
 
 $$x^2 = \frac{-a(1 + \frac{1}{3})}{1 - \frac{1}{3b}}$$
 
 $$x = ±\sqrt{\frac{-a(1 + \frac{1}{3})}{1 - \frac{1}{3b}}}$$
 
:::



## Quick check problems {-}

::: {.content-visible when-format="html"}

::: {.webex-check .webex-box}

1. What is the subject of the following equation $x^3 - \frac{x}{7} - 16 = y$?

Answer: The subject of the equation is `r fitb("y")`.

2. You are given the quadratic equation $4l^2 - m = n^2 + 8$. How many operations need to be undone to get $l$ as the subject of the equation. 

Answer: The number of operations is `r fitb(3)`.

3. You are given three statements below. Decide whether they are true or false.

(a) The equation $m^2 + 4m = 7l + m$ is equivalent to $m + 7l = m^2 + 4m$.
 Answer: `r torf(TRUE)`.

(b) The equation $p = \sqrt{q + 4r^2}$ has $q$ as the subject of the equation.
 Answer: `r torf(FALSE)`.
 
(c) The equation $\sqrt{a^2 + 4b + 2c} = c^2$ is equivalent to $c^4 - 2c = a^2 + 4b$.
 Answer: `r torf(TRUE)`.


:::

:::

::: {.content-hidden when-format="html"}

1. What is the subject of the following equation $x^3 - \frac{x}{7} - 16 = y$?

2. You are given the quadratic equation $4l^2 - m = n^2 + 8$. How many operations need to be undone to get $l$ as the subject of the equation. 

3. You are given three statements below. Decide whether they are true or false.

(a) The equation $m^2 + 4m = 7l + m$ is equivalent to $m + 7l = m^2 + 4m$.

(b) The equation $p = \sqrt{q + 4r^2}$ has $q$ as the subject of the equation.

(c) The equation $\sqrt{a^2 + 4b + 2c} = c^2$ is equivalent to $c^4 - 2c = a^2 + 4b$.



:::

## Further reading {-}
For more information on quadratic equations: [Guide: Using the quadratic formula](quadraticformula.qmd)



