---
title: "Introduction to quadratic equations: questions"
author: "Tom Coleman"
abstract-title: Summary
abstract: A selection of questions for the study guide on introduction to quadratic equations.

---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to quadratic equations](introtoquadratics.qmd).*

## Q1 {-}

For each of the quadratic equations below, identify the variable and the coefficients $a,b,c$.

1.1. $\quad x^2 - 7x + 6 = 0$.

1.2. $\quad y^2 + 14y + 49 = 0$.

1.3. $\quad h^2 - h - 56 = 0$.

1.4. $\quad y^4 - y^2 = 0$ 

1.5. $\quad 5n^2 - 14n + 100 = 0$.

1.6. $\quad A^2 - 144 = 0$. 

1.7. $\quad 25M^2= 0$. 

1.8. $\quad e^{2x} - 4e^x + 4 = 0$.

1.9. $\quad -9s^2 + 3s - 1 = 0$.

1.10. $\quad 2e^{6x} + e^{3x} + 1 = 0$.

1.11. $\quad \cos^2(x) + 4\cos(x) - 4 = 0$. 

1.12. $\quad 8x^8 - 4x^4 - 1 = 0$.


## Q2 {-}

Find the discriminant of every equation in Question 1, and comment on the possible number of real roots in the variable given. You do not need to find the roots of the equation in order to do this question.

You may use the facts that for all real numbers $x$, then $e^x > 0$, $x^2, x^4 > 0$, and $-1 < \cos(x), \sin(x) < 1$. In addition, you may also use the facts that if $\cos(x) = y$ and $y$ is between $-1$ and $1$, then there are infinitely many solutions in $x$; if $e^x = y$ and $y$ is positive, then $x = \ln(y)$.

## Q3 {-}

Although it may not look like it, the following equations are quadratic equations. In each of these cases, comment on the number of real roots of the equation. 

3.1. $\quad x = 1/x - 1$.

3.2. $\quad (y-1)(y-4) = -(y+2)(y+3)$.

3.3. $\quad \displaystyle 1 - \frac{4}{m} - \frac{1}{m^2} = 5$.

3.4. $\quad (t^2-1)(t^2+1) = -2$.

3.5. $\quad \displaystyle \frac{x-1}{x-2} = 5x$.

3.6. $\quad \displaystyle \frac{e^{x} - e^{-x}}{2} = 1$.

---

[Please click this link to find the answers.](as-introtoquadratics.qmd)

---