---
title: "Trigonometric identities: questions"
author: "Dzhemma Ruseva"
abstract-title: Summary
abstract: A selection of questions on trigonometric identities.

---

*Before attempting these questions, it is recommended that you read [Guide: Trigonometric identities(trigidentities.qmd)].*

## Questions {-}

### Q1 {-}
Using trigonometric identities find the values of the following equations:

1.1.  $\ \quad2(6\sin^2(\theta))+3(4\cos^2(\theta))$.

1.2.  $\ \quad10(7\sin^2(\theta))+14(5\cos^2(\theta))$.

1.3.  $\ \quad5(\frac{6}{\csc^2(\theta)})+15(\frac{2}{sec^2(\theta)})$.

1.4.  $\ \quad(\cos^2(\theta)-\sin^2(\theta))^2 + 4sin^2(\theta)\cos^2(\theta)$

1.5.  $\ \quad7\cos(90^\circ-\theta)\sin(\theta)+7\sin(90^\circ-\theta)\cos(\theta)$

1.6.  $\ \quad6\sin(\theta+2\pi)\sin(\theta+4\pi)+6\cos(\theta-2\pi)\cos(\theta-4\pi)$

1.7.  $\ \quad2\sin(30^\circ)\cos(15^\circ)+2\cos(30^\circ)\sin(15^\circ)$

1.8.  $\ \quad3\cos(45^\circ)\cos(15^\circ)-3\sin(45^\circ)\sin(15^\circ)$

1.9.  $\ \quad\sin(150^\circ)+\sin(30^\circ)$

1.10. $\quad\cos(150^\circ)+\cos(30^\circ)$


### Q2 {-}
Simplify the following equations:

2.1. $\ \quad\tan(\theta)\cos(-\theta)$

2.2  $\ \quad\tan(-\theta)\csc(-\theta)\sec(-\theta)$

2.4. $\ \quad\tan^2(\theta)+\sin^2(\theta)+\cos^2(\theta)$

2.5. $\ \quad\frac{2\sin(\theta)}{\cos(\theta)(1-\tan^2(\theta))}$

2.6. $\ \quad\sin(90+\theta)-\sin(90-\theta)$

2.7. $\ \quad\frac{\sin(7\theta)+\sin(3\theta)}{\cos(7\theta)-\cos(3\theta)}$

2.8. $\ \quad\frac{\sin(5\theta)-\sin(1\theta)}{\cos(5\theta)+\cos(1\theta)}$
 

### Q3 {-}
Using trigonometric identities find the values of(Hint - use the sum and difference identities):

3.1. $\ \quad\sin(15) =\ ?$

3.2. $\ \quad\cos(15) =\ ?$

3.3. $\ \quad\tan(15) =\ ?$

3.4. $\ \quad\sin(75) =\ ?$

3.5. $\ \quad\cos(75) =\ ?$

3.6. $\ \quad\tan(75) =\ ?$




