---
title: "Using the quadratic formula"
author: "Tom Coleman"
abstract-title: Summary
abstract: Solving quadratic equations of the form $ax^2 + bx + c$ is a core skill in mathematics. A guaranteed method to solve these is use of the quadratic formula. This guide explains the terminology and usage of the quadratic formula, as well as an explanation of why the quadratic formula works. 

---

*Before reading this guide, it is recommended that you read (Guide: Introduction to quadratic equations) In addition, the proof of the quadratic formula relies on the technique of 'completing the square'; see (Guide: Completing the square) for more.*

## What is the quadratic formula? {-}

The quadratic formula is useful!

::: {.callout-note}

## The quadratic formula

Let $ax^2 + bx + c = 0$ be a quadratic equation (where $a\neq 0$). Then the roots to this quadratic equation are given by
$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$
where one of the roots is given by the positive term $(-b+\sqrt{b^2 - 4ac})/2a$ and the other given by the negative term $(-b-\sqrt{b^2 - 4ac})/2a$.
:::

### Why use the quadratic formula? {-}

(BLURB)

## Using the quadratic formula {-}

Here are some examples of quadratic equations which are solved using the quadratic formula. To do this, you need to be able to identify the variable and the coefficients $a,b,c$.

The first of these examples illustrates the importance of making sure the correct signs are inputted into the quadratic formula.

::: {.callout-note appearance="simple"}

## Example 1

What are the roots of the quadratic equation $x^2 - 5x + 6 = 0$?

Here, you could factorise the quadratic equation $x^2 - 5x + 6 = 0$ to get $(x-2)(x-3) = 0$. This is zero precisely when $x - 2 = 0$ or $x - 3 = 0$; so the roots are $x = 2$ and $x = 3$.

You can also work this out using the quadratic formula. In this case, you'll need to identify the values of $a,b,c$ in the equation $x^2 - 5x + 6 = 0$; here, $a = 1$, $b = -5$ and $c = 6$. Taking care of the signs, you can put these into the quadratic formula and simplify to get
$$ x = \frac{-(-5) \pm \sqrt{(-5)^2 - 4(1)(6)}}{2(1)} = \frac{5 \pm \sqrt{25 - 24}}{2} = \frac{5 \pm \sqrt{1}}{2} = \frac{5\pm 1}{2}$$
Therefore, the roots are $x = 4/2 = 2$ and $x = 6/2 = 3$, as was found above.

:::

This next example illustrates the importance of the quadratic equation having $0$ on one side in order to find the roots.

::: {.callout-note appearance="simple"}

## Example 2

What are the roots of the quadratic equation $-8x - 8 = x^2 + 8$?

In order to use the quadratic formula, you need to first put the equation into the form $ax^2 + bx + c = 0$. So rearranging $-8x - 8 = x^2 + 8$ to get zero on the left hand side gives
$$0 = x^2 + 8x + 16$$
So in this case, you can take $a = 1$, $b = 8$ and $c = 16$ and put these in the quadratic formula to get
$$ x = \frac{-(8) \pm \sqrt{(8)^2 - 4(1)(16)}}{2(1)} = \frac{-8 \pm \sqrt{64 - 64}}{2} = \frac{-8 \pm \sqrt{0}}{2} = \frac{-8}{2}$$
In this case, the discriminant $D = 0$ and so there is one distinct root that must be counted twice. Therefore, the roots are $x = -8/2 = -4$ twice.

:::

This next example is the first where $a \neq 1$; you should be prepared to solve any quadratic equation in the form $ax^2 + bx + c = 0$.

::: {.callout-note appearance="simple"}

## Example 3

What are the roots of the quadratic equation $4x^2 + 4x + 5 = 0$?

This equation is already in the form $ax^2 + bx + c = 0$, with $a = 4$, $b = 4$ and $c = 5$. Putting these into the quadratic formula gives
$$ x = \frac{-(4) \pm \sqrt{(4)^2 - 4(4)(5)}}{2(4)} = \frac{-4 \pm \sqrt{16 - 80}}{8} = \frac{-4 \pm \sqrt{-64}}{8}$$
In this case, the discriminant $D < 0$. You can say that $\sqrt{-64} = 8i$, as $8$ is the square root of $64$ and $i$ is the square root of $-1$. This means that 
$$x = \frac{-4 \pm \sqrt{-64}}{8} = \frac{-4 \pm 8i}{8} = \frac{1}{2}\pm i$$
and these are the two roots of this quadratic equation.

:::

The next example changes the name of the variable used. You should be able to recognise a quadratic equation in the wild, regardless of what symbol is used as the variable.

::: {.callout-note appearance="simple"}

## Example 4

What are the roots of the quadratic equation $m^2 - m - 1 = 0$?

Here, the quadratic equation is of the required form $am^2 + bm + c = 0$ with $a = 1, b = -1$ and $c = -1$. Putting these into the quadratic formula gives:
$$ m = \frac{-(-1) \pm \sqrt{(-1)^2 - 4(1)(-1)}}{2(1)} = \frac{1 \pm \sqrt{1 - (-4)}}{2} = \frac{1 \pm \sqrt{5}}{2}$$
Therefore, the two roots of the quadratic equation are $m = (1 -\sqrt{5})/2$ and $m = (1 + \sqrt{5})/2$. (The second of these is a well-known mathematical constant known as the [**golden ratio**](https://en.wikipedia.org/wiki/Golden_ratio))

:::

The final two examples deal with changes of variable and also a change in the typical structure of a quadratic equation. 

::: {.callout-note appearance="simple"}

## Example 5

What are the roots of the equation $y^4 - 3y^2 + 2 =0$?

You can notice here that the equation given is not strictly a quadratic equation, as it is not of the form given in the definition above. However, by taking $y^2$ as the variable instead of $y$, you can rewrite this equation as
$$y^4 - 3y^2 + 2 = (y^2)^2 - 3y^2 + 2 = 0$$
and so this *is* a quadratic equation, with $y^2$ as the variable. You can then use the quadratic formula with $y^2$ as the variable, $a = 1$, $b = -3$ and $c = 2$ to get
$$ y^2 = \frac{-(-3) \pm \sqrt{(-3)^2 - 4(1)(2)}}{2(1)} = \frac{3 \pm \sqrt{9 - 8}}{2} = \frac{3 \pm 1}{2}$$
Therefore, the two solutions for $y^2$ are $y^2 = 2/2 = 1$ and $y^2 = 4/2 = 2$. This gives *four* solutions for $y$, which are $y = 1, -1, \sqrt{2}, -\sqrt{2}$.

:::

::: {.callout-note appearance="simple"}

## Example 6

What are the solutions to the equation $4q - 13 = -3/q$?

You can notice here that this equation does not look like a quadratic equation at all; so some rearranging needs to be done. First of all, you can multiply both sides by $q$ to get 
$$4q^2 - 13q = -3$$
and so 
$$4q^2 - 13q + 3 = 0$$
So this really was a quadratic equation, with $a = 4$, $b = -13$ and $c = 3$. Putting this into the quadratic formula gives
\begin{align*}
q &= \frac{-(-13) \pm \sqrt{(-13)^2 - 4(4)(3)}}{2(4)} = \frac{13 \pm \sqrt{169 - 48}}{8}\\[1em] 
&= \frac{13 \pm \sqrt{121}}{8} = \frac{13 \pm 11}{8}
\end{align*}
Therefore, the two solutions to the equation are $q = 2/8 = 1/4$ and $q = 24/8 = 3$.

:::

## Why does the quadratic formula work? {-}

It's important to note that the quadratic formula does not come out of thin air. In order to be able to use a result like this, you will have to **prove** that the formula gives the roots for the quadratic equation $ax^2 + bx + c$. 

To do this; you can **complete the square** on $ax^2 + bx + c$ using the fact that $a\neq 0$. See (Guide: Completing the square) for why this works. 

::: {.callout-note appearance="simple"}

## Proof of the quadratic formula

The proof of this relies on completing the square. First of all, as $a\neq 0$ you can divide $ax^2 + bx + c = 0$ through by $a$ to get 
$$x^2 + \frac{b}{a} x + \frac{c}{a} = 0$$
Taking the $c/a$ term over to the other side gives
$$x^2 + \frac{b}{a} x = -\frac{c}{a}$$
Completing the square gives
$$\left(x + \frac{b}{2a}\right)^2 - \frac{b^2}{4a^2} = -\frac{c}{a}$$
You can rearrange to get $$\left(x + \frac{b}{2a}\right)^2 = \frac{b^2}{4a^2} - \frac{c}{a} = \frac{b^2 - 4ac}{4a^2}$$ Now the result is starting to come together. Taking square roots of both sides (not forgetting that it could be positive or negative) gives
$$x + \frac{b}{2a} = \pm\frac{\sqrt{b^2 - 4ac}}{2a}$$
and rearranging gives
$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$
as required.

:::

## Quick check problems {-}



## Further reading {-}




