---
title: "Radians"
author: "Ifan Howells-Baines, Mark Toner"
abstract-title: Summary
abstract: tbc

---


## What are Radians? {-}

**Radians**, like Degrees are a way of measuring the size of angles that can often be identified by the presence of **$\pi$.**

Radians are derived from the **radius of a circle** which makes them especially useful when working with circles. You will see this relationship more in the following section.

Radians are denoted by the symbol **rad**. 

This guide will firstly describe the relationship between Radians and Circles. Then describe the relationship between Radians and Degrees showing how to convert between them. Lastly, it will provide a table of some useful Degree to Radians conversions for common angle sizes.


## Radians and circles

Before you see the close relationship between radians and circles, it's important to understand what an **arc** and **sector** is.

::: {.callout-note}
## Definition of a circular arc
Pick any two different points on a circle and draw a curve between them, following the circle. We call this curve a **circular arc**, but we usually abbreviate this to just **arc**.
:::

::: {.callout-tip}
A **circle** does not include the interior of the circle. We call a circle and its interior a **disk**.
:::


::: {.callout-note appearance="simple"}
## Example 1
This is an example of an arc.
:::

::: {.callout-note}
## Definition of a circular sector
Pick two different points on a circle and draw a two lines between them and the centre. The area between these two lines and an arc between the points is called a **circular sector**, but we usually abbreviate this to just **sector**.
:::

::: {.callout-note appreance="simple"}
## Example 2
This is an example of a sector.
:::


You can now begin to precisely explain the relationship between radians and circles!

Pick any two points on a circle such that the length of the arc between them is equal to the radius of the circle and draw straight lines between these points and the centre. The angle between these two lines at the centre is $1$ rad. A precise way to say this is:

::: {.callout-note}
## Definition of a radian
A **radian** is the angle subtended at the centre of a circle by an arc that is equal in length to the radius.
:::

::: {.callout-tip}
The size of the circle doesn't change the value of $1$ rad - it's the same in any circle.
:::

Now, you can get the number of radians in a full circle. The well-known equation $c = 2 \pi r$, where $c$ is the circumference of a circle and $r$ the radius, tells you that you can fit sectors with arc length $r$ side by side into the circle $2\pi$ times. Since each of these sectors has an angle of $1$ rad at the centre, it follows that there are $2\pi$ radians in the whole circle.

ADD FIGURE HERE

## Converting between Radians and Degrees

The process for converting from Radians to Degrees and from Degrees to Radians are direct opposites.

### Converting from Degrees to Radians

Starting from an angle in Degrees.

- Multiply the angle in Degrees by $\pi$
- Divide the result by 180

Your angle is now in Radians. 

**Remember to simplify fractions**

#### Example 1

You are given the angle $180\textdegree$ to convert to Radians.

- Multipying by $\pi$ gives $180\pi$
- Dividing by 180 gives $\pi$

This means that $180\textdegree$ is equal to $\pi$ rad.

#### Example 2

You are given the angle $45\textdegree$ to convert to Radians.

- Multiplying by $\pi$ gives $45\pi$
- Dividing by 180 gives $\frac{\pi}{4}$

This means that $45\textdegree$ is equal to $\frac{\pi}{4}$ rad.

### Converting from Radians to Degrees

Starting from an angle in Radians.

- Multiply the angle in Radians by 180
- Divide the result by $\pi$

Your angle is now in Degrees.

#### Example 3

You are given the angle $\pi$ rad to convert to Degrees.

- Multiplying by 180 gives $180\pi$
- Dividing the result by $\pi$ gives 180

This means that $\pi$ rad is equal to $180\textdegree$.

#### Example 4

You are given the angle $\frac{\pi}{4}$ rad to convert to degrees

- Multiplying by 180 gives $45\pi$
- Dividing the result by $\pi$ gives 45

This means that $\frac{\pi}{4}$ rad is equal to  $45\textdegree$.


## Useful conversions to know

Here is a table of useful conversions of degrees to radians that come up often:

| Degrees ($\textdegree$) | Radians ($\textrm{rad}$) |
| :-: | :-: |
| $360$ | $2 \pi$ |
| $210$ | $\frac{7\pi}{6}$ |
| $180$ | $\pi$ |
| $120$ | $\frac{2\pi}{3}$ |
| $90$ | $\frac{\pi}{2}$ |
| $60$ | $\frac{\pi}{3}$ |
| $45$ | $\frac{\pi}{4}$ |
| $30$ | $\frac{\pi}{6}$ |



## Arc Length and Sector Area

If you have two straight lines from the centre of a circle to the circumference and know the angle, in radians, between these lines at the centre, then you can calculate the length of the arc between these lines. 

::: {.callout-note}
## Equation for arc length
The length $s$ of an arc between two points is given by $s = r \theta$, where $r$ is the radius of the circle and $\theta$ is the angle, in radians, between the straight lines from the two points to the centre.
:::

To see why this equation holds, convince yourself that this equality is true ($c$ is the circumference of the circle): $$\frac{s}{c} = \frac{\theta}{2\pi}.$$ If you substitute $c = 2\pi r$ into this equality, you get $$\frac{s}{2\pi r} = \frac{\theta}{2\pi}.$$ Finally, rearranging gives you the equation $$s = r \theta.$$


Similar to arc length, you can get an equation in terms of radians to calculate the area of a sector.

::: {.callout-note}
## Equation for sector area
The area $A$ of a sector of a circle with radius $r$ and angle $\theta$ at the centre (in radians) is given by $A = \frac{1}{2}r^2\theta$.
:::

Showing this is true is left to you in the exercises.


