---
title: "Rationale for accessibility and inclusion"
author: "Jakub Brzozowski, Jacob Carey, Tom Coleman"
abstract-title: Summary
abstract: Our main principles when it comes to writing accessible and inclusive mathematics resources. 
format: html
---

# Introduction {-}

## Aims {-}

The aim of this website is to produce accessible and inclusive online resources for any and all interested students in mathematics and statistics. Here are 

- **accessible**: ensuring that the way that material is presented is accessible to any user. These include things like ability to screen-read, ability to zoom, correct colour contrasts, etc.

- **inclusive**: ensuring that the material itself is both understandable by all who read it, and representative of diverse backgrounds and cultures. 

# Content

Our aim is to make our guides are readable as possible to suit all learning styles and backgrounds. To that end, we are aiming to provide the following in all our study guides:

- **chunked content**: information organised into digestible units with summaries and worked examples

- **multiple representations**: use of diagrams, symbolic notation, text explanations, audio, and interactive elements.

- **consistency and predictability**: stable layouts, repeated patterns, and uniform instructions.

- **guidance and prompts**: step-by-step instructions, examples before tasks, scaffolded explanations.

- **clarity of language, purpose and formatting**: minimized jargon, active voice, nothing is easy, as well as ease of readability in all of our materials. 

We aim to achieve this by our choices in our **global content style**, which is detailed below.

## Global content style

### Global formatting

The key points across all of our text formatting are:

- sans serif font used in all materials, as letters appear less 'crowded' and easier to read.

- emphasis is provided by bold text, as italic text can be difficult to read for dyslexic learners; no underlining

- all internal hyperlinks look the same (Content type: Title of resource) so these are identifiable as hyperlinks regardless of colour

### Typical structure of a guide

- summary at start explaining what's in the guide and what the point of the subject is. 

- any **recommended reading** at the start of every guide, detailing the STARMAST resources needed to understand the content of the guide at hand. 

- clear headings and structure throughout every document.

- content contained in **action boxes** containing key points, each in a specific style, with their own icon and colour

  - **important**: things to remember
  - **warning**: things not to do
  - **note**: key definition or result
  - **note (simple)**: worked example
  - **tip**: something to consider in the future
  
- **quick check problems**, designed to provide instant true/false feedback to students' understanding on the key points of the guide.

### Context free

It is tempting for our authors to relate everything written in the website to some form of personal education ('saw this in A-level/Higher', 'this is used in physics'). However, this is not very useful to those who have no knowledge of what these things may contain. So we **avoid educational context** where possible, linking only internally within STARMAST. 

In general, we **aim to avoid subject-specific examples**. It's important to remember that the reader could be of any background; so including (say) a physics problem may put readers off who have absolutely no knowledge of (or interest in) physics.

There are some exceptions; particularly when motivating the subject at hand, where we try to give at least **three** different applications of the material in the guide. 

## Wider structure of content

Each of our guides is designed to be as self-contained as possible; however we understand that prior knowledge in mathematics and statistics is unavoidable in certain circumstances. For example, solving a quadratic equation is dependent is knowing what a quadratic equation is; this in turn is dependent is knowing what an equation is. 

To minimize the amount of searching that a learner would need to do, we include a **recommended reading** section at the start of every guide, detailing the STARMAST resources needed to understand the content of the guide at hand. 

At the other end, a **further reading** section included at the bottom of every guide signposts learners to further topics in the subject. 

Each study guide is sorted into its own **category**, which can be explored through the [study guide index (clickable link)](studyguidelist.qmd).

Eventually, with enough content behind us, we'll be able to provide **structured pathways for learning**, leading to competency in key skills in any area of mathematics and statistics. 

## Language {-}

When writing for learners using these materials, it's important to know that these learners could be coming from any level of mathematical knowledge or any level of literal knowledge. In particular, a reader can have **any** level of confidence in their ability to do mathematics or statistics.

Our aim is to write using plain English to make our resources as reader-friendly as possible. Writing in this style can help users with: specific learning difficulties (such as dyslexia or attention deficit disorder), low literacy skills, international readers where English is not their first language, or even younger people looking for more mathematical support. In addition, the way that materials are presented can directly affect the mathematical confidence of the reader; it's really important that this affect is minimized. 

There are a few main principles that are followed in the creation of resources for this website.

### It's you, not we. {-}

Traditionally, mathematical writing uses the first-person plural 'we', intending to lead the reader on a journey through the material. This is all well and good if you assume that the reader is confident with the work; but what if they are **not** confident in their ability?

If introductory material is written in an exclusive manner, then a student with absolutely no confidence will struggle. Every student needs to feel included and inspired when reading about mathematics or statistics; so write inclusively and in the active voice.

The problem is that 'we' could be inclusive (including the reader) or exclusive (not including the reader). If this is married to concepts which are quite difficult, it can be quick to feel excluded; not part of the journey. In addition, using 'we' can be passive -- if you want your reader to do mathematics, saying 'we see this' and 'we deduce that' may create a false sense of security.

Therefore, **the writing for this project will use the second-person singular 'you', with an emphasis on the active voice**. Saying 'you can do this' rather than 'we can see that' helps to instill confidence in the reader, and shifts the focus to the reader doing mathematics. 

<!-- | Old phrase                          | New phrase                       | -->
<!-- |:------------------------------------|:------------------------------------| -->
<!-- | 'We see that...'                    | 'You can see that...'            | -->
<!-- | 'We deduce that...'                 | 'You can work this through to get...' | -->
<!-- | 'We will come back to this later'   | 'This will be used later at (reference)...' -->

### Nothing is easy. {-}

Your experiences with mathematics are unique, and will not be generally applicable to all students reading your work. If you think that something is 'easy' or 'obvious', then good for you; but even mentioning this in your writing could crush the confidence of any student reading your work.

So **nothing is easy**. Not even things you learned in high school. Everyone has to start somewhere, and that somewhere might be here. A consequence of this is that *nothing should be hard* either; present your material objectively.

Below is a table of banned adjectives, which does not claim to be complete. You can change most of these into adverbs by adding 'ly' to the end; these adverbs are banned too.

| Don't use these. Ever. | | | | 
|:----------------|:----------------|:----------------|:----------------|
| Easy            | Obvious         | Trivial         | Straightforward |
| Simple          | Effortless      | Painless        | Not hard        |
| Foolproof       | Elementary      | Basic           | Clear           |
| Run-of-the-mill | Unchallenging   | No trouble      | Just            |

: A list of banned words. {tbl-colwidths="[25,25,25,25]"}

Please feel free to let tdhc know if you want to make any addition to the list.

### Minimise jargon. {-}

If a difficult concept is explained behind jargon or symbols that the student has to look up while trying to understand, then that concept becomes far harder to master. Learning mathematics is hard enough without students trying to translate what is going on.

However, at some point, students will need to be introduced to mathematical terminology. It is a language after all. It is too much to expect to eliminate mathematical or statistical terms entirely, so we **minimize jargon** where we can, and provide references to terms if needed. This includes symbols including the therefore symbol, quantifier symbols, the implied sign, etc; these are often substituted in place for explanation, and learning resources without explanation aren't good learning resources.

<!-- One of the main aims of this project is going to be a glossary of mathematical terms, so a link to this could be included in every study guide. -->

### Keep it simple. {-}

Which is easier to read or understand: 'so', or 'whenceforth'? How about: 'deduction' or 'working'? 

Again, there may be significant linguistic barriers to understanding; barriers which should not be in place when trying to learn mathematics. Therefore, **writing is as simple as practically possible.** This includes

- **avoiding Latin/Greek terms**; confusion between 'e.g' and 'i.e.' is rife. 

- **idioms/proverbs**; these are particularly problematic for non-native users of English and some neurodivergent students. 

Exceptions of course should be made for mathematical terms, which should be clearly defined. 

### It's not magic. {-}

The idea of a stage magician conjures up illusory elements; of sleight-of-hand, of work behind the screen, of misdirection and mystery. This is the opposite of our stated mission to make mathematics and statistics accessible for everybody and as inclusive as possible.

Pervasive in mathematics and statistics is the idea of quick 'tricks' to help with mathematics; things like the difference of two squares, or creative addition of 0/multiplication by 1. The trouble is that these steps can be hard to see or justify to a mathematician who is low on confidence. 

Therefore, there's **no such thing as a trick** on this website. 'Technique' or 'tool' are far better words for our purposes. Writing out the working in full helps to properly convey the material. 

# Presentation

The website is written in the Quarto markup language, which was specifically chosen to satisfy web accessibility requirements and cater to multiple outputs, using only a single set of source code.

## Multiple outputs

The Quarto rendering process uses Pandoc together with some custom templates in pdf and word to output all materials to html, pdf, and word simultaneously. Here are some of the key features of our multiple outputs

### html template

This template uses custom scss files (starmast-base, starmast-typography, can be found in the GitHub repository) on top of the standard Quarto html output to make the site look as clean as possible. This includes:

- sans-serif font used throughout (Arial)
- off-white background picked for readability for all audiences
- multiple line spacing 
- in-built dark mode for all pages
- in-built Google Translate widget to output our content to 170+ languages

### printable pdf template

This customized LaTeX class file ensures that the pdf output uses all of the power of LaTeX while still being as accessible as print material can be. This includes

- sans-serif font used throughout (Computer Modern Sans Serif)
- multiple line spacing 
- options in class to output to large print fonts
- all maths done in LaTeX

### editable MS Word template

The custom STARMAST word template makes sure the editable word documents look as close to the html as possible  This includes

- sans-serif font used throughout (Helvetica)
- multiple line spacing 
- all maths re-rendered in Microsoft Equation Editor format, which can be screen-read

### mp3 narration

Every study guide comes with a downloadable mp3 narration. This is made possible by code written by Sophie Chowgule, one of our very first VIP students. She wrote a Jupyter notebook that takes a html page and turns it into a .txt file, which after minor edits is turned into an mp3 file. This has the following advantages:

- produced using computerized text-to-speech to make it as understandable as possible with no specific regional accents
- downloadable for offline use with printed versions of the guide
- has a modifiable playback speed for faster or slower narrations

The Jupyter notebook is available on our GitHub repository. 

### video examples

We have recently been able to start rolling out video examples. Developed by our VIP team in 2025/26 and hosted on our [STARMAST YouTube channel (clickable link)](https://www.youtube.com/@starmast-video), these short videos illustrate specific examples from selected study guides. 

- all videos are captioned
- faces are recorded in order for lip-reading to take place if needed
- examples are written clearly and accessibly, and match the source material
- using YouTube allows for accessible playback options such as speed modification
- full transcripts are given in the guide along with the video

[Our video making process can be found by clicking on this link.](videostyleguide.qmd)

## Colours and branding

Our colour palette has been picked to be colourblind-safe according to [this webpage (clickable link)], and all figures and interactive figures use this palette. As is standard, we never use colour on its own to distinguish between different objects.

## Interactive figures

We are privileged to have some of our interactive figures provided by Desmos, which has its own set of accessibility tools. We also try and build in keyboard accessibility into our html and R Shiny figures as well. 

---

---

## Version history {-}

v1.0: initial version created 03/26 by tdhc.

