---
title: "Sigma notation"
author: Tom Coleman, Ifan Howells-Baines, Mark Toner
abstract-title: Summary
abstract: Sigma notation is used to express many additions at once. Understanding what this notation is, how it works, and how to manipulate them is a valuable skill to learn for use in almost any area of mathematics.

---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this guide, it is recommended that you read GUIDE and GUIDE*

## What is sigma notation? {-}

If you want to add many things together, then it would be nice to have a quick way of writing this down! This is where **sigma notation** comes in.

::: {.callout-note}

## Definition of sum and sigma notation

A **sum** is any addition of two or more real numbers. If $a_k,a_{k+1}, \ldots, a_n$ are real numbers (where $k$ and $n$ are some natural numbers with $k\leq N$), then you can use **sigma notation** to write their sum as $$a_k + a_{k+1} + \ldots + a_N = \sum_{i = k}^N a_i$$ where the right hand side reads 'the sum from $i = k$ to $i = n$ of the elements $a_i$'. The symbol $i$ is known as the **index** of the sum; the index of a sum can notionally be any letter.
:::

#### Examples {-}

Here's some examples of sigma notation.


::: {.callout-note appearance="simple"}
## Example 1

What is the value of $\displaystyle\sum_{i=1}^{10} i$?

  You can use the definition above to write this out as a sum and then calculate it: $$\displaystyle\sum_{i=1}^{10} i = 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 +9 + 10 = 55.$$
:::

::: {.callout-note appearance="simple"}
## Example 2
What is the value of $\displaystyle\sum_{n=2}^5 n^2$?
    
  Before tackling a problem using sigma notation, it can be best to read it out loud. Here, $$\sum_{n=2}^5 n^2\textsf{ is 'the sum from $n = 2$ to $n = 5$ of $n^2$'.}$$ This translates to $$\sum_{n=2}^5 n^2 = 2^2 + 3^2 + 4^2 + 5^2$$ and $2^2 + 3^2 + 4^2 + 5^2 = 4 + 9 + 16 + 25 = 54$.
:::

::: {.callout-note appearance="simple"}
## Example 3
What is the value of $\displaystyle\sum_{n=1}^N n = S$?

  In this case, you're being asked to find $S = 1 + 2 + 3 + \ldots + N$. The following method is due to [Gauss](https://mathshistory.st-andrews.ac.uk/Biographies/Gauss/), who came up with this answer during a maths lesson at school when he was seven (hinting at the genius to follow).

  First of all, you can reorder $S$ to write that $S = N + (N-1) + \ldots + 2 + 1$. Adding two lots of $S$ together gives the following:

$$
\begin{array}{cccccccccccc}
& S & = & 1 & + & 2 & + & 3 & + & \ldots & + & N \\
+ & S & = & N & + & (N-1) & + & (N-2) & + & \ldots & + & 1\\\hline
& 2S & = & (N+1) & + & (N+1) & + & (N+1) & + & \ldots & + & (N+1)
\end{array}
$$

  Therefore, $2S$ is $N$ lots of $(N+1)$; you can write this as $2S = N(N+1)$. Dividing both sides by $2$ gives $S = N(N+1)/2$.

:::

## Writing sums using sigma notation

In this section, you will learn how to do the opposite of the above. That is, given a sequence of numbers, you will learn how to write their sum using sigma notation. The crux of this process is to recognise a pattern in the sequence of given numbers. It's best to learn this using examples.

::: {.callout-note appearance="simple"}
## Example 4

Write $2 + 4 + 6 + 8 + 10 + 12$ using sigma notation.
    
  You can tell that these are the first six multiples of $2$; so you can list these elements as $2n$ for $n = 1$ up to $n = 6$. Therefore, you can write that $$2 + 4 + 6 + 8 + 10 + 12 = \sum_{n=1}^6 2n.$$
    
:::
   
::: {.callout-note appearance="simple"} 
## Example 5
Write $1 + 2 + 4 + 8 + 16 + 32$ using sigma notation.

  These are the first 6 numbers in the sequence $2^n$ for $n=0$ up to $n=5$. Therefore, you can write $$1 + 2 + 4 + 8 + 16 + 32 = \sum_{n=0}^5 2^n.$$
  
:::

::: {.callout-note appearance="simple"}
## Example 6

Write $-1 + 2 -3 + 4 - 5$ using sigma notation.

  For these types of sequences it's useful to keep in mind the sequence $(-1)^n$, which alternates between $1$ and $-1$. Hence, you can write these elements as $(-1)^nn$ for $n=1$ up to $n=5$. Using sigma notation, it will look like this: $$\sum_{n=1}^5 (-1)^nn.$$

:::   
## Properties

In this section you will learn about a few properties of sigma notation which means you'll have a toolkit to rearrange sums!

The first property you'll learn about sigma notation is *distribuitivity*. This property allows you to take constants from inside the sigma notation to outside the summation.

::: {.callout-note}
## Distribuitivity

  Let $a_k,a_{k+1}, \ldots, a_n$ be a sequence of numbers (where $k$ and $n$ are integers with $k \leq n$) and $C$ be any constant. Then $$\sum_{i=k}^n Ca_i = C \sum_{i=k}^n a_i.$$ 

:::

You can see this is true by writing the entire sum out, like this: $$\begin{equation}\begin{split} \sum_{i=k}^nCa_i & = Ca_k + Ca_{k+1} + Ca_{k+2} + \ldots + Ca_n \\ & = C(a_k + a_{k+1} + a_{k+2} + \ldots + a_n) \\ & = C\sum_{i=k}^n a_k \end{split}\end{equation}$$

::: {.callout-note appearance="simple"}
## Example 7

  What is the value of $\sum_{n=2}^56n^2$?
  
  Using distribuitivity, $\sum_{n=2}^56n^2 = 6\sum_{n=2}^5n^2$. From Example 2, you know that $\sum_{n=2}^5n^2 = 54$. Therefore, $6\sum_{n=2}^5n^2 = 6 \times 54 = 324$.
:::

Another property of sigma notation is something we'll call *combining sums*. This lets you write two sums in sigma notation as one sum.

::: {.callout-note}
## Combining sums

  Let $a_k,a_{k+1},\ldots,a_n$ and $b_k,b_{k+1},\ldots,b_{n}$ be two sequences of numbers (where $k$ and $n$ are numbers with $k \leq n$). Then $$\sum_{i=k}^na_i + \sum_{i=k}^n b_i = \sum_{i=k}^n(a_i + b_i)$$ and $$\sum_{i=k}^na_i - \sum_{i=k}^n b_i = \sum_{i=k}^n(a_i - b_i).$$

:::

::: {.callout-warning}

  Note in the property above that both sequences start at $k$ and end at $n$.
  
:::

Similar to the distribuitive property, you can show this is true by writing the entire sum out: $$\begin{equation}\begin{split} \sum_{i=k}^na_i + \sum_{i=k}^n b_i & = (a_{k} + a_{k+1} + \ldots + a_n) + (b_k + b_{k+1} + \ldots + b_n) \\ & = (a_k + b_k) + (a_{k+1} + b_{k+1}) + \ldots + (a_n + b_n) \\ & = \sum_{i=k}^n (a_k + b_k).\end{split}\end{equation}$$ In a similar way, you can show that $\sum_{i=k}^n a_i - \sum_{i=k}^n b_i = \sum_{i=k}^n(a_i-b_i)$ is also true.

::: {.callout-note appearance="simple"}
## Example 8

  Write $\sum_{n=1}^62n + \sum_{n=0}^52^n$ as a single sum.
  
  First, notice that the indices of these sequences are different, so before we can use the combining sums property we need to do a process called *reindexing*. Reindexing a sum in sigma notation means rewriting the same sum using different indicies. For your purposes, you can reindex $\sum_{n=1}^6 2n$ as $\sum_{n=0}^5 (2n+2)$. You can now use the combining sums property: $$\sum_{n=1}^62n + \sum_{n=0}^52^n = \sum_{n=0}^5 (2n+2) + \sum_{n=0}^52^n = \sum_{n=0}^5 (2n + 2^n + 2).$$

:::

::: {.callout-note}
  In the above example, you could also reindex $\sum_{n=0}^52^n$ instead of $\sum_{n=1}^62n$. Give it a go!
:::

::: {.callout-note}
## Splitting a sum

  Let $a_k,a_{k+1},\ldots,a_n$ and $b_k,b_{k+1},\ldots,b_{n}$ be two sequences of numbers (where $k$ and $n$ are integers with $k < n-1$). Then for any integer $m$ such that $k \leq m < n$, $$\sum_{i=k}^n a_i = \sum_{i=k}^m a_i + \sum_{i=m+1}^n a_i.$$

:::

Again, similar to above you can show this by writing the entire sum out. We leave this to you. 

::: {.callout-note appearance="simple"}
## Example 9

Write $\sum_{i=10}^{100}i$ as the product of three sums

There are a large number of ways to do this an example of which is: 

$$\sum_{i=10}^{11} i + \sum_{i=12}^{98} i + \sum_{i=99}^{100} i.$$
Note that this example has not been particularly useful but is to illustrate the property in action. 

This property is used more when working with infinite summations.

:::

## Double sums

Sometimes, you'll want to multiply two sums together. This can be written succinctly using something called *double sums*.

::: {.callout-note appearance="simple"}
## Double sums
  Let $a_{k},a_{k+1},\ldots,a_n$ and $b_t,b_{t+1},\ldots,b_m$ be two sequences of numbers (where $k,n,t$, and $m$ are integers with $k \leq n$ and $t \leq m$). Then the **double sum** $\sum_{i=k}^n\sum_{j=t}^m a_i b_j$ is defined as  $$\begin{multline*} \sum_{i=k}^n\sum_{j=t}^m a_i b_j = a_kb_t + a_kb_{t+1} + \ldots + a_kb_m \\+ a_{k+1}b_t + a_{k+1}b_{t+1} + \ldots + a_{k+1}b_m + \ldots + a_nb_m.\end{multline*}$$  
:::

::: {.callout-tip}
  You might find it easier to remember the above by thinking of $\sum_{i=k}^n\sum_{j=t}^m a_i b_j$ as $a_1(\sum_{j=t}^mb_j) + a_2(\sum_{j=t}^mb_j) + \ldots + a_n(\sum_{j=t}^mb_j).$
:::

You will now see how this relates to multiplying two sums together. Suppose that $a_k,a_{k+1},\ldots,a_n$ and $b_t,b_{t+1},\ldots,b_m$ are like above, and consider the product $(\sum_{i=k}^na_i)(\sum_{j=t}^mb_j)$. Writing it all out and performing the multiplication, you get $$\begin{equation}\begin{split} (\sum_{i=k}^na_i)(\sum_{j=t}^mb_j) &= (a_k+a_{k+1}+\ldots+a_n)(b_t + b_{t+1}+\ldots+b_m) \\ &= a_kb_t + a_kb_{t+1} + \ldots + a_kb_m + a_{k+1}b_t + a_{k+1}b_{t+1} + \\ & \quad \ldots + a_{k+1}b_m + a_{k+2}b_t + \ldots + a_nb_m \\ &= \sum_{i=k}^n\sum_{j=t}^m a_i b_j\end{split}.\end{equation}$$ You can write this as a result:

::: {.callout-note}
## Double sums and products of two sums
  Let $a_{k},a_{k+1},\ldots,a_n$ and $b_t,b_{t+1},\ldots,b_m$ be two sequences of numbers (where $k,n,t$, and $m$ are integers with $k \leq n$ and $t \leq m$). Then $$\sum_{i=k}^n\sum_{j=t}^m a_i b_j = (\sum_{i=k}^na_i)(\sum_{j=t}^mb_j).$$

:::

::: {.callout-note appearance="simple"}

## Example 10

Write $(1+2+3+4+5+6)(2+4+6+8+10+12)$ as a double sum and as a product of two sums

First, notice you can write out the above expression in the form $(1)(2) + (1)(4) + ... (1)(12) + (2)(2) + (2)(4) ... (3)(2) + ...(6)(12)$ 

From the definition above you may now rewrite the expression to the double sum 

$$\sum_{i=1}^6\sum_{j=1}^6 i*2j$$
using the distrubitivity property this can be written as $$2\sum_{i=1}^6\sum_{j=1}^6 ij$$

This can then be written using the product of two sums rule above to $$2\sum_{i=1}^6i\sum_{j=1}^6j$$

It is evident that the two sums are the same with different index variables this means that they can be combined to form $$2\sum_{k=1}^6k^2$$ 

$k$ has been used to differentiate the new sum from the ones involving i and j before but as always the choice of index variable is relatively unimportant

:::

::: {.callout-note appearance="simple"}

## Additional sums

A **sum** is any addition of two or more real numbers. If $a_k,a_{k+1}, \ldots, a_n$ are real numbers (where $k$ and $n$ are some natural numbers with $k\leq N$), then you can use **sigma notation** to write their sum as $$a_k + a_{k+1} + \ldots + a_N = \sum_{i = k}^N a_i$$ where the right hand side reads 'the sum from $i = k$ to $i = n$ of the elements $a_i$'. The symbol $i$ is known as the **index** of the sum; the index of a sum can notionally be any letter.

:::

## Quick check problems {-}


<!-- add facility to check answers at end rather than one at a time -->

::: {.webex-check .webex-box}

1. What is the value of  $$\sum_{i = 2}^{6} i$$

Answer: The value of the above is: `r fitb(20)`.

2. Given $$\sum_{j = 1}^{100} i$$ Identify the index of the sum.

Answer: The index is `r fitb("i")`

3. You are given several statements below based on the properties of sums. Identify whether they are true or false.

(a) The sum $3 + 6 + 9 + 12$ can be expressed as $$\sum_{i = 0}^{4} 3i$$ Answer: `r torf(TRUE)`.

(b)  The sum $-1 + 1 - 1 + 1$ can be expressed as $$\sum_{i = 1}^{4} -i$$ Answer: `r torf(FALSE)`.

(c)  $$\sum_{i = 1}^{100} i = \sum_{i = 0}^{101} i$$  Answer: `r torf(FALSE)`.

(d)  $$\sum_{i = 1}^{100} 6i = 6 \sum_{i = 0}^{100} i$$  Answer: `r torf(TRUE)`.

(e)  $$\sum_{i = 1}^{100} 9i + \sum_{i = 1}^{100} 3i = \sum_{i = 1}^{100} 27i^2$$  Answer: `r torf(FALSE)`.

(f) $$\sum_{i = 1}^{100} 12i - \sum_{i = 1}^{100} 4i = 8 \sum_{i = 1}^{100} i$$  Answer: `r torf(TRUE)`.

4. You are given several statements below based on the properties of sums. Identify whether they are true or false.

(a) $\sum_{i=1}^{10}\sum_{j=2}^6 ij$ can be expressed as $(\sum_{i=2}^6i)(\sum_{j=1}^{10} j)$ Answer: `r torf(FALSE)`.

(b) $(\sum_{i=1}^52i)(\sum_{j=5}^{10} 3j)$ can be expressed as $6(\sum_{i=1}^5\sum_{j=5}^{10} ij)$ Answer: `r torf(TRUE)`.


(c) The sum $(1+2+3+4+5+6)(-1-2)(3+6+9)$ can be expressed as $$\sum_{i=1}^6\sum_{j=1}^2\sum_{k=1}^3 -3ijk$$ Answer: `r torf(TRUE)`.

:::

[For more questions on the subject, please go to Questions: Sigma Notation.](qs-sigma-notation.qmd)

## Further reading

