---
title: "Sutton Trust Summer School 2026"
format: html
---

Here are the resources for all the presentations for the Sutton Trust Summer School 2026. These links will be populated throughout the week.

## Resources

#### (Monday) The hidden sequences of Pascal's triangle

- [Full notes including interactive figures](./explorations/e-pascalstriangleandgrowth.qmd)

- [Slides used in the presentation](./explorations/exploration-slides/e-s-pascalstriangleandgrowth.qmd)

- [Interactive Pascal's triangle investigator](./apps/interactive/i-pascalstriangle.qmd)

#### (Tuesday) How to win at cards - combinations and permutations

- [Full notes including interactive figures](./explorations/e-combinationspermutations.qmd)

- [Slides used in the presentation](./explorations/exploration-slides/e-s-combinationspermutations.qmd)

- [Combinations and permutations calculator](./apps/calculators/c-ncrnpr.qmd)

#### (Wednesday) Making it count: an introduction to the theory of functions

- [Full notes including interactive figures]

- [Slides used in the presentation]

- [Interactive functions investigator](./apps/interactive/i-functions.qmd)

#### (Thursday) Tutorials

- [Tutorial questions](./explorations/e-qs-combined.qmd)

- [Tutorial answers]

#### (Friday) Hilbert's hotel: an introduction to infinity

- [Full notes including interactive figures]

- [Slides used in the presentation]

## Summaries of presentations

#### (Monday) The hidden sequences of Pascal's triangle

In the first of four linked presentations, this session looks at Pascal's triangle and the various number sequences contained within. Some of these sequences are on the surface, and some of the sequences are incredibly hidden! Once these sequences are found, they will be examined and compared against each other, where their role in one of the most famous/infamous open problems in theoretical computer science will be revealed.

#### (Tuesday) How to win at cards - combinations and permutations

In the second of four linked presentations, this session looks at counting the number of ways you can choose objects from a larger set of objects. This is achieved by looking at falling factorials (where the order of choice does matter) and binomial coefficients (where the order of choice doesn't matter). Along the way, you will double-check marketing materials for a food truck, and learn how to win at cards.

#### (Wednesday) Making it count: an introduction to the theory of functions

In the third of four linked presentations, this session takes the material covered in the previous two sessions and looks at it from a more general perspective by introducing the theory of functions. Along the way, you'll learn why and how you use functions in everyday life, how every sequence of numbers is a function in disguise, and why pigeons are so important in mathematics.

#### (Friday) Hilbert's hotel: an introduction to infinity

In the final of four linked presentations, this session takes the material covered in the previous three sessions and jumps into the infinite. Following the course of a busy day at the Hilbert Hotel, this session will look at the many roles that infinity plays in mathematics. Along the way, you'll learn how to squeeze infinitely many guests into a fully booked hotel, pour infinitely many glasses of wine without going bankrupt, and how best to decorate the lobby using infinitely-defined shapes.
