---
title: "Tom's to-do list"
format: html
---

<!-- # Complete list of broken links {-} -->

<!-- ### Folder: factsheets -->

<!-- Proof: Antiderivatives of other common functions (total 1) -->
<!-- - ./factsheets/f-commonintegrals.qmd (1) -->

<!-- Proof: Derivatives of other common functions (total 1) -->
<!-- - ./factsheets/f-commonderivatives.qmd (1) -->


<!-- ### Folder: overviews -->

<!-- Guide: Arithmetic on complex numbers (total 2) -->
<!-- - ./overviews/o-setsofnumbers.qmd (2) -->

<!-- Guide: Introduction to complex numbers (total 2) -->
<!-- - ./overviews/o-setsofnumbers.qmd (2) -->

<!-- Guide: Introduction to polar coordinates (total 1) -->
<!-- - ./overviews/o-recognizing3dsurfaces.qmd (1) -->

<!-- Guide: Introduction to quadratic equations (total 2) -->
<!-- - ./overviews/o-setsofnumbers.qmd (2) -->

<!-- Guide: Introduction to sigma notation (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->

<!-- Guide: Introduction to solving simultaneous equations (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->

<!-- Guide: PMFs, PDFs, and CDFs (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->

<!-- Guide: Rationalizing the denominator (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->

<!-- Guide: The scalar product (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->

<!-- Guide: Trigonometry (degrees) (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->

<!-- Guide: Using the quadratic formula (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->

<!-- Overview: Number sets (total 1) -->
<!-- - ./overviews/o-historyofnumbers.qmd (1) -->

<!-- Proof: Constructing the reals (total 1) -->
<!-- - ./overviews/o-setsofnumbers.qmd (1) -->



<!-- ### Folder: proofsheets -->

<!-- Guide: Changing co-ordinates in double integrals (total 2) -->
<!-- - ./proofsheets/ps-pmfspdfscdfs.qmd (2) -->

<!-- Guide: Further sigma notation (total 1) -->
<!-- - ./proofsheets/ps-propsmatrixarithmetic.qmd (1) -->

<!-- Guide: Integration by substitution (total 2) -->
<!-- - ./proofsheets/ps-pmfspdfscdfs.qmd (2) -->

<!-- Guide: Introduction to continuity (total 2) -->
<!-- - ./proofsheets/ps-rulesofdifferentiation.qmd (2) -->

<!-- Guide: Introduction to differentiability (total 1) -->
<!-- - ./proofsheets/ps-rulesofdifferentiation.qmd (1) -->

<!-- Guide: Introduction to double integration (total 1) -->
<!-- - ./proofsheets/ps-pmfspdfscdfs.qmd (1) -->


<!-- Guide: Introduction to limits (total 5) -->
<!-- - ./proofsheets/ps-introtodifferentiation.qmd (1) -->
<!-- - ./proofsheets/ps-rulesofdifferentiation.qmd (4) -->

<!-- Guide: Operations on sets (total 1) -->
<!-- - ./proofsheets/ps-bayestheorem.qmd (1) -->

<!-- Guide: Proof by induction (total 1) -->
<!-- - ./proofsheets/ps-propertiesofsigmanotation.qmd (1) -->

<!-- Guide: Properties of integration (total 3) -->
<!-- - ./proofsheets/ps-pmfspdfscdfs.qmd (3) -->

<!-- Guide: Properties of limits (total 1) -->
<!-- - ./proofsheets/ps-rulesofdifferentiation.qmd (1) -->

<!-- Guide: The binomial theorem (total 4) -->
<!-- - ./proofsheets/ps-introtodifferentiation.qmd (2) -->
<!-- - ./proofsheets/ps-pmfspdfscdfs.qmd (2) -->

<!-- Overview: Number sets (total 3) -->
<!-- - ./proofsheets/ps-irrationalityofroottwo.qmd (3) -->

<!-- Proof: Derivatives of other common functions (total 1) -->
<!-- - ./proofsheets/ps-introtodifferentiation.qmd (1) -->


<!-- ### Folder: questions -->

<!-- Guide: Integration by parts (total 1) -->
<!-- - ./questions/qs-expectedvariance.qmd (1) -->

<!-- Guide: Introduction to hyperbolic functions (total 2) -->
<!-- - ./questions/qs-introtodifferentiation.qmd (1) -->
<!-- - ./questions/qs-productrule.qmd (1) -->


<!-- # Folder: search -->

<!-- # Folder: studyguides -->

<!-- For an introduction on matrices, please see Guide: Introduction to Matrices. (total 1) -->
<!-- - ./studyguides/gaussianelimination.qmd (1) -->

<!-- For an introduction systems of linear equations, please see Guide: Solving systems of linear equations. (total 1) -->
<!-- - ./studyguides/gaussianelimination.qmd (1) -->

<!-- For examples of using Gaussian elimination, please see Guide: Applications of Gaussian elimination (total 1) -->
<!-- - ./studyguides/gaussianelimination.qmd (1) -->

<!-- For more information on how to perform a -test, please see Guide: -testing. (total 1) -->
<!-- - ./studyguides/hypothesistesting.qmd (1) -->

<!-- For more information on other types of testing, see Guide: More on statistical testing (total 1) -->
<!-- - ./studyguides/introtottesting.qmd (1) -->

<!-- For more information on type I and type II errors please see Guide: Errors in hypothesis testing. (total 1) -->
<!-- - ./studyguides/hypothesistesting.qmd (1) -->

<!-- For more questions on the subject, please go to Questions: Introduction to integration. (total 1) -->
<!-- - ./studyguides/propsofintegration.qmd (1) -->

<!-- Guide: Biased and unbiased estimators (total 2) -->
<!-- - ./studyguides/linearregression.qmd (1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Guide: Binomial theorem (total 1) -->
<!-- - ./studyguides/chainrule.qmd (1) -->

<!-- Guide: Definite integrals (total 2) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->
<!-- - ./studyguides/propsofintegration.qmd (1) -->

<!-- Guide: Discrete random variables versus continuous random variables (total 2) -->
<!-- - ./studyguides/pmfspdfscdfs.qmd (2) -->

<!-- Guide: Errors in hypothesis testing (total 1) -->
<!-- - ./studyguides/hypothesistesting.qmd (1) -->

<!-- Guide: Even and odd functions (total 2) -->
<!-- - ./studyguides/trigonometricidentities-degrees.qmd (1) -->
<!-- - ./studyguides/trigonometricidentities-radians.qmd (1) -->

<!-- Guide: Expanding brackets (total 4) -->
<!-- - ./studyguides/completingthesquare.qmd (1) -->
<!-- - ./studyguides/introtosimeqs.qmd (1) -->
<!-- - ./studyguides/rationalizingthedenominator.qmd (1) -->
<!-- - ./studyguides/arithmeticoncomplexnumbers.qmd (1) -->


<!-- Guide: Hyperbolics (total 2) -->
<!-- - ./studyguides/polarcoordinates2D-degrees.qmd (1) -->
<!-- - ./studyguides/polarcoordinates2D-radians.qmd (1) -->

<!-- Guide: Integration by parts (total 3) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->
<!-- - ./studyguides/propsofintegration.qmd (2) -->

<!-- Guide: Integration by substitution (total 3) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->
<!-- - ./studyguides/propsofintegration.qmd (2) -->

<!-- Guide: Introduction to complex numbers (total 1) -->
<!-- - ./studyguides/matrixmultiplication.qmd (1) -->

<!-- Guide: Introduction to continuity (total 1) -->
<!-- - ./studyguides/introtopartialdifferentiation.qmd (1) -->

<!-- Guide: Introduction to differentiability (total 1) -->
<!-- - ./studyguides/introtopartialdifferentiation.qmd (1) -->

<!-- Guide: Introduction to Gaussian elimination (total 2) -->
<!-- - ./studyguides/matrixmultiplication.qmd (2) -->

<!-- Guide: Introduction to linear equations (total 1) -->
<!-- - ./studyguides/introtosimeqs.qmd (1) -->

<!-- Guide: Introduction to multiple linear regression (total 4) -->
<!-- - ./studyguides/linearregression.qmd (2) -->
<!-- - ./studyguides/normallinearregression.qmd (2) -->

<!-- Guide: Introduction to sigma notation (total 1) -->
<!-- - ./studyguides/matrixmultiplication.qmd (1) -->

<!-- Guide: Introduction to solving simultaneous equations (total 2) -->
<!-- - ./studyguides/matrixmultiplication.qmd (2) -->

<!-- Guide: Introduction to straight lines (total 5) -->
<!-- - ./studyguides/introtosimeqs.qmd (1) -->
<!-- - ./studyguides/linearregression.qmd (2) -->
<!-- - ./studyguides/normallinearregression.qmd (2) -->

<!-- Guide: Inverse trigonometric functions (total 1) -->
<!-- - ./studyguides/scalarproduct.qmd (1) -->

<!-- Guide: Likelihood functions (total 2) -->
<!-- - ./studyguides/normallinearregression.qmd (2) -->

<!-- Guide: Maximum likelihood estimation (total 2) -->
<!-- - ./studyguides/linearregression.qmd (1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Guide: Modulus-argument form for complex numbers (total 2) -->
<!-- - ./studyguides/arithmeticoncomplexnumbers.qmd (2) -->

<!-- Guide: Multiple linear regression. (total 1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Guide: Multiple revolutions and negative angles (total 2) -->
<!-- - ./studyguides/trigonometricidentities-degrees.qmd (1) -->
<!-- - ./studyguides/trigonometricidentities-radians.qmd (1) -->

<!-- Guide: Multiple revolutions and negative values (total 2) -->
<!-- - ./studyguides/trigonometricidentities-degrees.qmd (1) -->
<!-- - ./studyguides/trigonometricidentities-radians.qmd (1) -->

<!-- Guide: Normal linear regression (total 2) -->
<!-- - ./studyguides/linearregression.qmd (1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Guide: Normal linear regression. (total 2) -->
<!-- - ./studyguides/linearregression.qmd (1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Guide: Operations on sets (total 1) -->
<!-- - ./studyguides/conditionalprobability.qmd (1) -->

<!-- Guide: Overview of numbers (total 1) -->
<!-- - ./studyguides/rationalizingthedenominator.qmd (1) -->

<!-- Guide: Properties of functions (total 1) -->
<!-- - ./studyguides/introtodifferentiation.qmd (1) -->

<!-- Guide: Properties of integration (total 3) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->
<!-- - ./studyguides/pmfspdfscdfs.qmd (1) -->
<!-- - ./studyguides/propsofintegration.qmd (1) -->

<!-- Guide: Tangents (total 2) -->
<!-- - ./studyguides/introtodifferentiation.qmd (2) -->

<!-- Guide: The differential operator and higher derivatives (total 4) -->
<!-- - ./studyguides/implicitdifferentiation.qmd (1) -->
<!-- - ./studyguides/introtodifferentiation.qmd (3) -->

<!-- Guide: The scalar product (total 1) -->
<!-- - ./studyguides/matrixmultiplication.qmd (1) -->

<!-- Guide: Transforming data in linear regression (total 1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Guide: Transposing matrices (total 1) -->
<!-- - ./studyguides/introtomatrices.qmd (1) -->

<!-- Guide: Trigonometry and integration (total 4) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->
<!-- - ./studyguides/propsofintegration.qmd (1) -->
<!-- - ./studyguides/trigonometricidentities-degrees.qmd (1) -->
<!-- - ./studyguides/trigonometricidentities-radians.qmd (1) -->

<!-- Guide: Vector equation of a line (total 1) -->
<!-- - ./studyguides/addandsm.qmd (1) -->

<!-- Overview: Number sets (total 1) -->
<!-- - ./studyguides/matrixmultiplication.qmd (1) -->

<!-- Overview: Probability distributions. (total 1) -->
<!-- - ./studyguides/pmfspdfscdfs.qmd (1) -->

<!-- Proof sheet: Definite integrals (total 1) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->

<!-- Proof sheet: Derivatives of other common functions (total 1) -->
<!-- - ./studyguides/introtodifferentiation.qmd (1) -->

<!-- Proof sheet: Deriving estimates for regression parameters (total 1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Proof sheet: Estimating regression parameters in normal linear regression (total 1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Proof sheet: Estimating Regression Parameters in Normal Linear Regression (total 1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Proof sheet: Fundamental Theorem of Calculus (total 2) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->
<!-- - ./studyguides/propsofintegration.qmd (1) -->

<!-- Proof sheet: Rules of differentiation. (total 1) -->
<!-- - ./studyguides/implicitdifferentiation.qmd (1) -->

<!-- Proof sheet: The Fundamental Theorem of Calculus (total 1) -->
<!-- - ./studyguides/introtointegration.qmd (1) -->

<!-- Proof: Properties of matrix arithmetic (total 1) -->
<!-- - ./studyguides/matrixmultiplication.qmd (1) -->

<!-- Proof: Simple linear regression (total 3) -->
<!-- - ./studyguides/linearregression.qmd (3) -->

<!-- Proof: variances of regression parameters in normal linear regression (total 1) -->
<!-- - ./studyguides/normallinearregression.qmd (1) -->

<!-- Questions: Determinants (total 1) -->
<!-- - ./studyguides/determinants.qmd (1) -->

<!-- Questions: Introduction to matrices (total 1) -->
<!-- - ./studyguides/matrixmultiplication.qmd (1) -->

<!-- Worked examples: Integration (total 1) -->
<!-- - ./studyguides/propsofintegration.qmd (1) -->


<!-- # Folder: VIP2425 -->

<!-- also other resources such as **fact** and **proof** sheets (total 3) -->
<!-- - ./VIP2425/SMNpresentationApr2025.qmd (1) -->
<!-- - ./VIP2425/SMSNPERpresentationJul2025.qmd (1) -->
<!-- - ./VIP2425/VIPpresentation.qmd (1) -->

<!-- next Thu (total 1) -->
<!-- - ./VIP2425/VIPpresentation.qmd (1) -->

# List of topics alluded to in an existing guide, but no files exist yet

- Multiple revolutions and negative angles
- Even and odd functions
- Trigonometry and integration 
- Rearranging with factorization and reciprocals
- Finding lines and angles using trigonometry
- Inverse trigonometric functions
- Discrete and continuous random variables
- Straight lines
- Errors in hypothesis testing
- Modulus-argument form for complex numbers
- Integration by parts
- Integration by substitution
- Introduction to limits
- Introduction to continuity
- Introduction to differentiability
- Introduction to double integrals
- Operations on sets
- Introduction to hyperbolic functions
- Solving systems of linear equations
- Z-testing
- More on statistical testing
- Errors in hypothesis testing
- Biased and unbiased estimators
- Binomial theorem
- Definite integrals
- Expanding brackets
- Introduction to linear equations
- Introduction to straight lines
- Likelihood functions
- Maximum likelihood estimation
- Multiple linear regression
- Normal linear regression
- Tangents
- The differential operator and higher derivatives
- Transforming data in linear regression
- Transposing matrices
- Vector equation of a line


<!-- # Guides wanted {-} -->

<!-- ## Maths {-} -->

<!-- - The Fundamental Theorem of Calculus -->
<!-- - Integration by substitution -->
<!-- - Integration by parts -->
<!-- - Introduction to limits -->
<!-- - Injective and surjective functions -->
<!-- - Manipulation of fractions -->
<!-- - Manipulation of algebraic fractions -->
<!-- - Identifying common curves -->
<!-- - Changing co-ordinates in double integrals -->
<!-- - Further sigma notation -->

<!-- ## Stats {-} -->

<!-- - Fact sheet: Differentiation for statisticians  -->
<!-- - Fact sheet: Integration for statisticians -->
<!-- - Intro to random variables -->
<!-- - Central limit theorem -->
<!-- - The normal distribution/(guides on distributions) -->
<!-- - Fact sheet: Discrete random variables versus continuous random variables -->
<!-- - What is a p-value? (AL) -->
<!-- - Introduction to regression -->
