---
title: "VIP details"
subtitle: Semester 1, 2024/25
author: tdhc
format: 
  revealjs:
    theme: default
---

## Introduction

Hello, and welcome to the VIP on 'Creating accessible online mathematics and statstics resources'!

My name is Tom and here are my contact details:

- Office location: Room 220, Mathematical Institute
- Email: tdhc@st-andrews.ac.uk

My office policy is open-door: if my door is open, please feel free to drop in!

# VIP administration

## Events

- **VIP welcome event** on **Tuesday 17 September (Week 1)** from **1100-1300**

- Online **Reflective writing workshop** on **Friday 27th September (Week 2)** from **1300-1430** (sign-up link to follow)

- **VIP conference** in **Week 9 or 10**.

## Resources

[Link to download reflective log template](VIPReflectiveLogTemplate.docx)

[Link to University Moodle pages](https://moody.st-andrews.ac.uk/moodle/course/view.php?id=9517)

The VIP has £400 budget, and students (that's you) can apply for more. All ideas for spend should come through me.

## Assessment pattern

This VIP has the following assessment pattern. 

- **Fortnightly reflective logs** in Weeks 3, 5, 7, 9, 11 (20%)
- **Group presentations** in the meeting in Week 9 (30%)
- **Portfolio of work and final report**, due **Saturday 7 December** (50%)

You will be assessed on the **20-point scale** for each of these components relative to your year. 

Your final grade will be the weighted average of all of these components. 

## Assessment: Fortnightly logs (20%)

The deadline for each fortnightly log is **Friday 12 noon** in **odd numbered weeks**. Please **email these to me** before then. 

I will be providing **formative feedback** after the **Week 3** and **Week 7** reflective logs, which will consist of comments about your reflective logs.

Each fortnightly log will be rated on the **20-point scale**, with an average mark over the five fortnightly logs reported as your final mark for the 20%. **Only** the final grade (at the end of the semester) is needed to be made public. 

VIP event: Online **Reflective writing workshop** on **Friday 27th September (Week 2)** from **1300-1430** (sign-up link to follow from central VIP team)

## Assessment: Group presentation (30%)

The group presentation will consist of a **printed or interactive poster** and a **10-minute oral presentation** on that poster. It will take place in the Week 9 meeting. 

## Assessment: Portfolio and final report (50%)

The deadline for submission of the portfolio of works and final reflective report is **Saturday 7 December**, which is the first day of the revision diet. 

# The project

## The website

STARMAST (St Andrews Resources in Mathematics and Statistics)

[https://tdhc153.github.io/starmast](https://tdhc153.github.io/starmast)

## The tasks

**Create content**: study guides, questions, answers, proof sheets, fact sheets, general interest articles, interactive web content (flash cards, posters, etc), video and audio guides...

**Develop impact**: website management, workflow optimization, development and management of accessibility tools, social media strategies, outreach to the public, search engine optimization...

## Creating content

(aka the bit I know how to do)

- **Quality, not quantity.** Materials are going to be publicly available. *Only the best goes up.*

- **Follow the style guide to the letter.** The website *must* be written in a consistent style with the guides that are already there.

- The amount of work will vary on a sliding scale depending on your credits and year. You will write at least *one guide*, *one question set*, *one answer set*.

- Other than that, you can let your mind run free!

## Develop impact

(aka the bit I don't know how to do)

- Website management (workflow, hosting, domain name)

- Accessibility research and development

- Social media management

  - Instagram/X accounts already made

- Analytics data, search engine optimisation

## How?

The website is written using Quarto (a markup language using R as a base), with version control using Github. You can use whichever code editor you so desire, but I strongly recommend using RStudio. Please make sure you download RStudio, R, and set up a github account.

The repository can be found at [https://github.com/tdhc153/starmast](https://github.com/tdhc153/starmast).

[This is a link to the README file.](https://github.com/tdhc153/starmast/blob/master/README.md)

## Any questions?

Come and see me in room 220 or email me :)

