---
title: "More big website updates!"
format: html
author: Tom Coleman
date: 2025-08-14
abstract-title: Summary
abstract: Three new guides, factsheets on distributions, and much more!
---

## Update {-}

Another bumper summer update at STARMAST today, with no fewer than **24** new written resources and the addition of 2D and 3D graphical calculators! 💫 

Lots to say, so let's get straight into it...

### Three new study guides! {-}

#### Introduction to partial differentiation {-}

The first topic is on an introduction to partial differentiation and is written by Donald Campbell, a fourth-year participant in the University of St Andrews VIP project in Semester 2 2024/25. This guide covers aspects of partial differentiation including initial concepts, how to find partial derivatives and higher partial derivatives. This guide contains our first ever 3D Desmos interactive figures.

The links to the guide, questions and answers can be found here:

- [Guide: Introduction to partial differentiation](../studyguides/introtopartialdifferentiation.qmd)
- [Questions: Introduction to partial differentiation](../questions/qs-introtopartialdifferentiation.qmd)
- [Answers: Introduction to partial differentiation](../answers/as-introtopartialdifferentiation.qmd)

A big thank you to Donald for writing these guides and resources!

#### Introduction to integration {-}

Donald has also been busy writing literally hundreds of integration questions. A selection of these can be found in our new introduction to integration guide, written by editor-in-chief Tom. This guide introduces the ideas of both definite and indefinite integration, and explains the role of the Fundamental Theorem of Calculus in connecting the two. All of the relevant links can be found here:

- [Guide: Introduction to integration](../studyguides/introtointegration.qmd)
- [Questions: Introduction to integration](../questions/qs-introtointegration.qmd)
- [Answers: Introduction to integration](../answers/as-introtointegration.qmd)

#### Expected value, variance, standard deviation {-}

Finally, editor-in-chief Tom has written a guide providing an introduction to expected value, variance and standard deviations for random variables. All of the relevant links can be found here:

- [Guide: Expected value, variance, standard deviation](../studyguides/expectedvariance.qmd)
- [Questions: Expected value, variance, standard deviation](../questions/qs-expectedvariance.qmd)
- [Answers: Expected value, variance, standard deviation](../answers/as-expectedvariance.qmd)

### Factsheets and overview on probability distributions {-}

Our next guide expands our statistics provision and covers main aspects of probability distributions. This includes overviews of *fourteen* of the most common probability distributions, including interactive calculators for each of them written in R Shiny. This (online-only) overview has been written by Michelle Arnetta, a first-year participant in the University of St Andrews VIP project in Semester 2 2024/25.

- [Overview: Probability distributions](../overviews/o-distributions.qmd)

For your convenience however, we here at STARMAST have split up this document and created factsheets for every one of the fourteen distributions. These factsheets contain an interactive calculator for that distribution, as well as all of the information from the overview and an example of where you could use the distribution. These factsheets replace the calculators for the probability distributions added in May ([click to see the news article from May 2025 here](update020525.qmd)) and can be found here:

- [Factsheet: Beta distribution](../factsheets/f-betadist.qmd)
- [Factsheet: Binomial distribution](../factsheets/f-binomialdist.qmd)
- [Factsheet: Chi-squared distribution](../factsheets/f-chisquareddist.qmd)
- [Factsheet: Continuous uniform distribution](../factsheets/f-contunifdist.qmd)
- [Factsheet: Discrete uniform distribution](../factsheets/f-dunifdist.qmd)
- [Factsheet: Exponential distribution](../factsheets/f-expdist.qmd)
- [Factsheet: $F$-distribution](../factsheets/f-fdist.qmd)
- [Factsheet: Gamma distribution](../factsheets/f-gammadist.qmd)
- [Factsheet: Geometric distribution](../factsheets/f-geomdist.qmd) 
- [Factsheet: Lognormal distribution](../factsheets/f-lognormaldist.qmd)
- [Factsheet: Negative binomial distribution](../factsheets/f-negbinomialdist.qmd)
- [Factsheet: Normal distribution](../factsheets/f-normaldist.qmd)
- [Factsheet: Poisson distribution](../factsheets/f-poissondist.qmd)
- [Factsheet: $t$-distribution](../factsheets/f-tdist.qmd)


### Graphical calculators {-}

Following the introduction of the new 3D Desmos capability in [Guide: Introduction to partial differentiation](../studyguides/introtopartialdifferentiation.qmd), we have provided both a 2D and 3D graphical calculator on the site for your endless amusement. You can find the calculators here:

- [Calculator: 2D graphical calculator](../apps/calculators/c-blank2dgraphcalc.qmd)
- [Calculator: 3D graphical calculator](../apps/calculators/c-blank3dgraphcalc.qmd)

### What's to come... {-}

Thanks to the fantastic work by our VIP students, coming soon are guides (and questions and answers) on:

- introduction to matrices (written by Jessica Taberner)
- Gaussian elimination, applications of Gaussian elimination (written by Sara Delgado Garcia)
- multivariate rules of differentiation (written by Donald Campbell)
- implicit differentiation (tdhc)
- a set of guides on integration (tdhc)
- likelihoods (tdhc)

as well overviews on sets of numbers and a history of number representation (Jessica Taberner).

These guides will be released as soon as they are all ready; stay tuned for more updates.

Finally, a **huge** thank you to the entire student team who produced these materials. You are all always welcome at STARMAST. 

#### Version history {-}

- v1.0 initial version written by tdhc 14/08/25.

---