---
title: "Huge website updates!"
format: html
author: Tom Coleman
date: 2025-07-02
abstract-title: Summary
abstract: Five new guides, narrations on all guides, and much more!
---

## Update {-}

A huge update at STARMAST today, with no fewer than 21 new pages added to the site!! 💫 

Lots to say, so let's get straight into it...

### Five new study guides! {-}

Not one, not two, but FIVE new study guides on STARMAST!

#### Factorization {-}

The first topic is on factorization and is written by Millie Pike, a fourth-year participant in the University of St Andrews VIP project in Semester 2 2024/25. This guide covers aspects of factorization including common factors, single bracket factorization and factorizing quadratic expression, and includes Desmos interactive elements.

The links to the guide, questions and answers can be found here:

- [Guide: Factorization](../studyguides/factorization.qmd)
- [Questions: Factorization](../questions/qs-factorization.qmd)
- [Answers: Factorization](../answers/as-factorization.qmd)

and the interactive element found in this guide, for calculating roots of quadratic equations using Desmos, can be found here:

- [Calculator: Solving quadratic equations](../apps/calculators/c-solvingquadratics.qmd.)

A big thank you to Millie for writing these guides and resources!

#### Introduction to probability {-}

Our next guide expands our statistics provision and is on an introduction to probability. This guide is written by Michelle Arnetta, a first-year participant in the University of St Andrews VIP project in Semester 2 2024/25. This guide covers an introduction to probability theory, including sample spaces, experimental and theoretical probability, and dependent and indepedent events. The guide also contains three interactive elements simulating coin flips and die rolls, written in R Shiny. 

The links to the guide, questions and answers can be found here:

- [Guide: Introduction to probability](../studyguides/introtoprobability.qmd)
- [Questions: Factorization](../questions/qs-introtoprobability.qmd)
- [Answers: Factorization](../answers/as-introtoprobability.qmd)

and the interactive elements found in these guides, for flipping coins and rolling dice, can be found here:

- [Interactive: Coin flip](../apps/interactive/i-coinflip.qmd)
- [Interactive: Six-sided die roll](../apps/interactive/i-sixsideddieroll.qmd)
- [Interactive: Coin flip with statistics](../apps/interactive/i-coinfliptracking.qmd)
- [Interactive: n-sided die roll](../apps/interactive/i-nsideddieroll.qmd)

A big thank you to Michelle for writing these guides and resources!

#### Rules of differentiation {-}

Editor-in-chief Tom has also been busy contributing guides to the site, with no fewer than three guides covering rules of differentiation: the product rule, the quotient rule, and the chain rule. There is also a proof sheet that shows where these rules come from (along with rules from [Guide: Introduction to differentiation and the derivative](../studyguides/introtodifferentiation.qmd).

Questions and answers to these have been written by one of our students, Sara Delgado Garcia, a fourth-year participant in the University of St Andrews VIP project in Semester 2 2024/25. A big thank you to Sara for writing all of these questions!

The links to the guide, questions and answers can be found here:

- [Guide: The product rule](../studyguides/productrule.qmd)
- [Questions: The product rule](../questions/qs-productrule.qmd)
- [Answers: The product rule](../answers/as-productrule.qmd)

 

- [Guide: The quotient rule](../studyguides/quotientrule.qmd)
- [Questions: The quotient rule](../questions/qs-quotientrule.qmd)
- [Answers: The quotient rule](../answers/as-quotientrule.qmd)

 

- [Guide: The chain rule](../studyguides/chainrule.qmd)
- [Questions: The chain rule](../questions/qs-chainrule.qmd)
- [Answers: The chain rule](../answers/as-chainrule.qmd)

 

- [Proof: Rules of differentiation](../proofsheets/ps-rulesofdifferentiation.qmd)

### Audio guides {-}

We have managed to roll out our automatically generated mp3 narration of our resources, which are now available for download on **every** one of our 28 study guides. 

This development has been led by Sophie Chowgule, a fourth-year student in both Semester 1 and 2 of the University of St Andrews VIP project. Availability of these resources represents a big step forward in our drive to make mathematics and statistics resources accessible to all. A huge thank you to Sophie for all this hard work. 

### What's to come... {-}

Thanks to the fantastic work by our VIP students, coming soon are guides (and questions and answers) on:

- conditional probability, Bayes' theorem (written by Sophie Chowgule)
- introduction to matrices (written by Jessica Taberner)
- Gaussian elimination, applications of Gaussian elimination (written by Sara Delgado Garcia)
- introduction to partial differentiation and multivariate rules of differentiation (written by Donald Campbell)
- implicit differentiation (tdhc)
- a set of guides on integration (tdhc)
- mean and expected value, standard deviation and variance, likelihoods (tdhc)

as well as a new type of resource, known as an **overview**, on: probability distributions (Michelle Arnetta), sets of numbers (Jessica Taberner) and a history of number representation (Jessica Taberner)

These guides will be released as soon as they are all ready; stay tuned for more updates.

Finally, a **huge** thank you to the entire student team who produced these materials. You are all always welcome at STARMAST. 

#### Version history {-}

- v1.0 initial version written by tdhc 02/07/25.

---