---
title: "Website refresh!"
format: html
author: Tom Coleman
date: 2025-10-31
abstract-title: Summary
abstract: Website refresh, two new guides, new interactive elements, and more!
---

## Update {-}

A spooky update today from STARMAST HQ! 💫 

Lots to say, so let's get straight into it...

### Website refresh {-}

As we move into a place where more and more people are using our resources, the current VIP team have been focusing on making sure the website looks clean and is as accessible as possible. So in anticipation of further content, we have made the following changes:

- The front page and study guide list have been cleaned up with a more accessible contents grid for easier navigation and visibility of resources.
- A new [contact page](../contact.qmd) has been written.
- The background colour is changed to a light blue for ease of reading.
- Google Translate widget added to all pages.
- The full index has been reordered to a more logical list of topics.

Please let us know any feedback you may have about the new look of the website!

### New resources! {-}

#### Solving equations involving logarithms {-}

Some history of STARMAST here; the project started as a University of St Andrews Summer Teams Enterprise Project in 2023 in order to get the initial guides written and the website off the ground. At that time, students Krish Chaudhary, Ellie Gurini, and Mark Toner begun a guide on rearranging trigonometric and logarithmic expressions. This guide ballooned in size and was not published as it was too long. Finally, after two years, Tom has adapted the first half of this guide on solving equations involving logarithms and it is now ready for consumption; please see the links below!

- [Guide: Solving equations involving logarithms](../studyguides/solvingeqslogarithms.qmd)
- [Questions: Solving equations involving logarithms](../questions/qs-solvingeqslogarithms.qmd)
- [Answers: Solving equations involving logarithms](../answers/as-solvingeqslogarithms.qmd)

A huge thank you to Krish, Ellie, and Mark for their contributions to these resources, and very sorry that it took so long!

#### Multivariate chain rule {-}

The second topic is on the chain rule in multivariate calculus and is written by Donald Campbell, a fourth-year participant in the University of St Andrews VIP project in Semester 2 2024/25 (and a current final-year participant!). This guide covers the multivariate chain rule with many many practice questions on the topic.

The links to the guide, questions and answers can be found here:

- [Guide: Multivariate chain rule](../studyguides/multivariatechainrule.qmd)
- [Questions: Multivariate chain rule](../questions/qs-multivariatechainrule.qmd)
- [Answers: Multivariate chain rule](../answers/as-multivariatechainrule.qmd)

A big thank you to Donald for writing these guides and resources!

#### $Z$-score calculator

In anticipation of her upcoming guide on confidence intervals, Millie Harris (a fourth-year participant in the University of St Andrews VIP project in Semester 1 2025/26) has developed an R Shiny app for working out $Z$-scores; you can find this at the link below:

- [Calculator: $Z$-scores](../apps/calculators/c-zscore.qmd)

A big thank you to Millie for writing this!

### What's still to come... {-}

Our new VIP team ([meet them over at our Instagram!](https://www.instagram.com/p/DP1RQvLjOO7/)) are hard at work on their projects. Following discussions with students and academics at the University of St Andrews, we are focusing on producing guides that users really need. So coming soon in the near future are guides on:

- Fractions, both numerical and algebraic
- 2D and 3D polar co-ordinates
- Overviews on recognising 2D and 3D surfaces
- Unit conversion
- Conic sections
- Linear regression
- Confidence intervals
- Ordinary differential equations
- Determinants

In addition to this, our students are working on two fantastic new ventures:

- a **course-checker** that takes a student's course as input and suggests guides for them to use to help them study their course
- our first **video content** explaining examples from our existing guides

In addition to this, thanks to the fantastic work by our VIP students in 2024/25, (still) coming soon are guides on: introduction to matrices, Gaussian elimination, applications of Gaussian elimination, implicit and multivariate implicit differentiation, more guides on integration, likelihoods, as well overviews on sets of numbers and a history of number representation.

These resources will be released as soon as they are all ready; stay tuned for more updates.

Finally, a **huge** thank you to all the students who produced these materials.

#### Version history {-}

- v1.0 initial version written by tdhc 31/10/25.

---