---
title: "New guide!"
format: html
author: Tom Coleman
date: 2025-04-25
abstract-title: Summary
abstract: Guide on introduction to hypothesis testing available now!
---

#### Update {-}

It's new guide here at STARMAST, and it has come with some new toys to play with! 💫

The topic is on introduction to hypothesis testing and is written by Ellie Trace, a participant in the University of St Andrews VIP project in Semester 1 2024/25. Included in the guide, and new to STARMAST, is the addition of **interactive flowcharts** and **statistical calculators**, written in R Shiny. Keep an eye out for more of these fantastic interactive elements on the site!

The links to the guide, questions and answers can be found here:

- [Guide: Introduction to hypothesis testing](../studyguides/hypothesistesting.qmd)
- [Questions: Introduction to hypothesis testing](../questions/qs-hypothesistesting.qmd)
- [Answers: Introduction to hypothesis testing](../answers/as-hypothesistesting.qmd)

and here are the links to the standalone interactive elements used in the guide:

- [Calculator: $Z$-testing](../apps/calculators/c-ztesting.qmd)
- [Interactive: Hypothesis testing flowchart](../apps/interactive/i-hypothesistesting.qmd)

A big thank you to Ellie for writing these materials.

Stay tuned for more content coming soon, as we roll out our audio narration for the rest of our study guides, *and* keep adding to our ever-growing bank of resources!

#### Version history {-}

- v1.0 initial version written by tdhc 25/04/25.

---