---
title: "New guide!"
format: html
author: Tom Coleman
date: 2025-04-14
abstract-title: Summary
abstract: Guide on PMFs, PDFs, CDFs available now!
---

#### Update {-}

It's the moment you've all been waiting for... it's time to put the second ST into STARMAST with our very first guide on statistics! 

The topic is on PMFs, PDFs, CDFs and is written by Sophie Chowgule, a participant in the University of St Andrews VIP project in Semester 1 (and 2) 2024/25. The online versions of the guide are equipped with interactive figures powered by Desmos. 

The links to the guide, questions and answers, as well as a proof sheet, can be found here:

- [Guide: PMFs, PDFs, CDFs](../studyguides/pmfspdfscdfs.qmd)
- [Questions: PMFs, PDFs, CDFs](../questions/qs-pmfspdfscdfs.qmd)
- [Answers: PMFs, PDFs, CDFs](../answers/as-pmfspdfscdfs.qmd)
- [Proof sheet: PMFs, PDFs, CDFs](../answers/as-pmfspdfscdfs.qmd)

A big thank you to Sophie for writing these materials.

Stay tuned for more content coming soon, as we roll out our audio narration for the rest of our study guides, *and* keep adding to our ever-growing bank of resources!

<!-- In addition to this, Millie Pike (one of our new VIP students) has produced a fact-sheet containing all the laws of logarithms in [Guide: Introduction to logarithms](../studyguides/logarithms.qmd). This material can be found here: -->

<!-- - [Factsheet: Laws of logarithms](../factsheets/f-lawsoflogarithms.qmd) -->



#### Version history {-}

- v1.0 initial version written by tdhc 14/04/25.

---