---
title: "New guide!"
author: Tom Coleman
date: 2025-03-12
abstract-title: Summary
abstract: Guide on arithmetic on complex numbers available now!
---

#### Update {-}

It's new guide time here at STARMAST! The topic is on arithmetic on complex numbers, written by Charlotte McCarthy, a participant in the University of St Andrews VIP project in Semester 1 2024/25. The online versions of the guides are equipped with interactive figures powered by Desmos. 

The links to the guide, questions and answers can be found here:

- [Guide: Arithmetic on complex numbers](../studyguides/arithmeticoncomplexnumbers.qmd)
- [Questions: Arithmetic on complex numbers](../questions/qs-arithmeticoncomplexnumbers.qmd)
- [Answers: Arithmetic on complex numbers](../answers/as-arithmeticoncomplexnumbers.qmd)

A big thank you to Charlotte for writing these materials.

Stay tuned for more content coming soon, including our first guide on calculus and our (long-awaited) first guides on statistics -- finally putting the last ST in STARMAST!

<!-- In addition to this, Millie Pike (one of our new VIP students) has produced a fact-sheet containing all the laws of logarithms in [Guide: Introduction to logarithms](../studyguides/logarithms.qmd). This material can be found here: -->

<!-- - [Factsheet: Laws of logarithms](../factsheets/f-lawsoflogarithms.qmd) -->



#### Version history {-}

- v1.0 initial version written by tdhc 12/03/25.

---