---
title: "New guide!"
author: Tom Coleman
date: last-modified
abstract-title: Summary
abstract: Guide on rationalizing the denominator available now!
---

#### Update {-}

The first guide written by the team of University of St Andrews students to have completed their Vertically Integrated Project is available now! The topic is on rationalizing the denominator, written by Maximilian Volmar. The links to the guide, questions and answers can be found here:

- [Guide: Rationalizing the denominator](../studyguides/rationalizingthedenominator.qmd)
- [Questions: Rationalizing the denominator](../questions/qs-rationalizingthedenominator.qmd)
- [Answers: Rationalizing the denominator](../answers/as-rationalizingthedenominator.qmd)

A big thank you to Max for writing these materials.

In other news, interactive figures powered by Desmos can now be found in [Guide: Trigonometry (degrees)](../studyguides/trigonometry-degrees.qmd) and [Guide: Trigonometry (radians)](../studyguides/trigonometry-radians.qmd)

#### Version history {-}

- v1.0 initial version written by tdhc 28/01/25.

---