---
title: "New guide and factsheet!"
format: html
author: Tom Coleman
date: 2025-02-13
abstract-title: Summary
abstract: Guide on solving simultaneous equations available now!
---

#### Update {-}

It's new guide time here at STARMAST! The topic is on an introduction to solving simultaneous equations, written by Ollie Brooke, a participant in the University of St Andrews VIP project in Semester 1 2024/25. The online versions of the guides are equipped with interactive figures powered by Desmos. 

The links to the guide, questions and answers can be found here:

- [Guide: Introduction to solving simultaneous equations](../studyguides/introtosimeqs.qmd)
- [Questions: Introduction to solving simultaneous equations](../questions/qs-introtosimeqs.qmd)
- [Answers: Introduction to solving simultaneous equations](../answers/as-introtosimeqs.qmd)

A big thank you to Ollie for writing these materials.

In addition to this, Millie Pike (one of our new VIP students) has produced a fact-sheet containing all the laws of logarithms in [Guide: Introduction to logarithms](../studyguides/logarithms.qmd). This material can be found here:

- [Factsheet: Laws of logarithms](../factsheets/f-lawsoflogarithms.qmd)

Stay tuned for more content coming soon, including our first guides on statistics -- finally putting the last ST in STARMAST!

#### Version history {-}

- v1.0 initial version written by tdhc 13/02/25.

---