---
title: "New guides!"
format: html
author: Tom Coleman
date: 2025-07-11
abstract-title: Summary
abstract: Guides on conditional probability and Bayes' theorem available now!
---

#### Update {-}

It's heating up here at STARMAST with two new guides today!! 💫

The topics are on conditional probability and the law of total probability and Bayes' Theorem and are written by Sophie Chowgule, a participant in the University of St Andrews VIP project in Semester 1 and 2 2024/25.

The links to the guides, questions and answers can be found here:

- [Guide: Conditional probability](../studyguides/conditionalprobability.qmd)
- [Questions: Conditional probability](../questions/qs-conditionalprobability.qmd)
- [Answers: Conditional probability](../answers/as-conditionalprobability.qmd)

 

- [Guide: Law of total probability and Bayes' theorem](../studyguides/bayestheorem.qmd)
- [Questions: Law of total probability and Bayes' theorem](../questions/qs-bayestheorem.qmd)
- [Answers: Law of total probability and Bayes' theorem](../answers/as-bayestheorem.qmd)

and here is the link to the accompanying proof sheet for the guide on law of total probability and Bayes' theorem:

- [Proof: Law of total probability and Bayes' theorem](../proofsheets/ps-bayestheorem.qmd)

A big thank you to Sophie for writing these materials!

Stay tuned for more content coming soon, as we keep adding to our ever-growing bank of resources!

#### Version history {-}

- v1.0 initial version written by tdhc 11/07/25.

---