---
title: "Website updates!"
format: html
author: Tom Coleman
date: 2025-05-02
abstract-title: Summary
abstract: New website features and statistical calculators available now!
---

#### Update {-}

It's come to the end of another VIP semester here at STARMAST! 💫

This project would not be possible without student involvement, so a HUGE thank you to all of our Semester 2 VIP team!

As a sneak preview of all of the hard work done by our VIP team at the University of St Andrews, our web developer (and human ray of sunshine) Tristin Doherty has been working hard on:

- progress trackers for the site, to see if you have completed quick-check questions for each of our guides, 
- a mailing list so anyone can subscribe and keep up with all outputs of the website. 

These features are now live on the website, so a big thank you to Tristin for implementing these!

We are also pleased to unveil our new suite of interactive statistical calculators covering a wide range of probability distributions; you can find all of these in [our applications list](../applist.qmd).

Stay tuned for more content coming soon, as we roll out the other fantastic outputs from the rest of our S2 VIP team! You can keep up to date by [following us on Instagram](https://www.instagram.com/starmast_/) or signing up to our new mailing list below!

#### Version history {-}

- v1.0 initial version written by tdhc 02/05/25.

---