---
title: "First VIP student team outputs"
author: Tom Coleman
date: last-modified
abstract-title: Summary
abstract: Materials from our first VIP student teams are available now, with many more guides to follow!
---

#### Update {-}

We here at STARMAST have been busy over the past few months. The first team of University of St Andrews students have completed their Vertically Integrated Project module working on the site. Here's a list of materials that they have produced:

- On the website there is a custom CSS style and feedback box, written by Mohit Agarwal.

- Led by Ideja Bajra, STARMAST now has marketing and social media strategies. You can see these in full swing in the [STARMAST Instagram account: click here to see the profile 

- Posters explaining the website and what we do, produced by the whole VIP team and presented at the St Andrews VIP conference on November 14 2024. You can find all the materials they produced in the following list:

    - [Main STARMAST poster](../VIP2425/PostersS1/MainPoster.pdf)
    - [Annotated website poster](../VIP2425/PostersS1/AnnotatedWeb!.pdf)
    - [Marketing strategy poster](../VIP2425/PostersS1/MarketingPoster.pdf)
    - [Outreach strategy poster](../VIP2425/PostersS1/OutreachPoster.pdf)
    - [Presentation slides at VIP conference](..//VIP2425/PostersS1/CreatingAccessibleMS-slides.pdf)
    
And, of course, most of the VIP team have been writing guides for the website! Coming soon are guides (and questions and answers) on:

- rationalizing the denominator (written by Max Volmar)
- introduction to simultaneous equations (written by Ollie Brooke)
- arithmetic on complex numbers (written by Charlotte McCarthy)
- PMFs and PDFs (probability mass functions and probability density functions, written by Sophie Chowgule)
- Hypothesis testing (written by Ellie Trace)

These guides will be released as soon as they are all ready; stay tuned for more updates.

Finally, a **huge** thank you to the entire student team who produced these materials. You are all always welcome back at STARMAST!

#### Version history {-}

- v1.0 initial version written by tdhc 04/12/24.

---