---
title: "Overview: History of numbers"
author: "Jessica Taberner"
abstract-title: Summary
abstract: An overview of the history of numbers and the decimal number system.
categories:
  - Key skills
draft: true
---

# What are numbers 

Numbers are used to count, measure, order, and perform calculations. In this overview you will see a brief history of numbers, how the commonly used number system came about and how it works, as well as a few important different types of numbers.

## Representations

Numbers have a place even in very early history. Bones and other artifacts carved with lines that many believe to be tally marks provide evidence of the very earliest humans making use of counting, perhaps for counting quantities of things like crops and livestock, or for tracking passing time (Barrow-Green, Gray and Wilson, 2019, pp.6-8).

Numbers can be represented in many ways. Tally marks are one way of representing numbers, they can be useful for some purposes, but as you have more and more marks it will become easier to lose track and miscalculate.

You are perhaps familiar with Roman numerals as another way of representing numbers. Roman numerals are surprisingly efficient for some calculations, but the lack of a place value system can complicate things.

::: callout-note
## Definition of Roman numerals 

Roman numerals are a numeral system that uses letters to represent numbers. The seven basic letters are:
$$I=1, \quad V=5,\quad X=10,\quad L=50, \quad C=100, \quad D=500, \quad M=1000$$
:::

Now you can see an example of addition using Roman numerals.

::: {.callout-note appearance="simple"}
## Example 1
You can break down $1352$ in the following way:
$$1352 =1 \cdot 1000 + 3 \cdot 100 + 1 \cdot 50 + 2 \cdot 1.$$ 

So you would write $1352$ as $MCCCLII$ in Roman numerals.

Similarly, you can break down $735$ as:

$$735 =1 \cdot 500 + 2 \cdot 100 + 3 \cdot 10 + 1 \cdot 5.$$

So you would write $735$ as $DCCXXXV$ in Roman numerals.

To compute $1352+735$, begin by combining the Roman numeral expressions: $MCCCLIIDCCXXXVII$.

Then collect letters to get: $MDCCCCCLXXXVII$.

Since there are $5$ $C$'s, you combine those and write $D$. Giving $MDDLXXXVII$.

Since there are $2$ $D$'s, you combine those and write $M$. Giving $MMLXXXVII$, or $2082$ in decimal notation. 
:::

Lots of different cultures evolved different ways of representing numbers based on different number systems. The kind you most commonly use today are Hindu–Arabic numerals, using the digits $0,1,2,3,4,5,6,7,8,9$. The common number symbols you use today originate in the Middle East, but $0$, and the place value system originate in India, from the Brahmi numeral system (Barrow-Green, Gray and Wilson, 2019, p.201).

## Place value

Place value systems assign value to a digit based on its position within a number. Having a place value system can make writing numbers and performing calculations with them more efficient. Number systems using place value have roots in ancient civilizations, but the present decimal system was perfected by Indian mathematicians before spreading to the rest of the world (Barrow-Green, Gray and Wilson, 2019, pp.200-201). Zero plays an important role in the number system as it allows us to denote the position of a digit in the number.

::: {.callout-note appearance="simple"}
## Example 2

Place value allows you to distinguish the different values of the digits. For example, you can express $3582.5$ in the following way:

$3582.5= 3\cdot1000+5\cdot100+8\cdot10+2\cdot1+5\cdot0.1$
:::

## Bases

The base of a number system is the number of unique digits within the number system. The decimal system, a base-$10$ system, uses digits $0-9$.  Ancient Egyptians were the first to use a base-$10$ system, around $3000$BCE (Ritter, J. (2000), pp.116-127). The most common theory is that the base-10 system came about because humans have ten fingers, making it a natural way to count and represent numbers. 

You might be familiar with the binary system, a base-$2$ system using only $0$ and $1$. Binary code is often used in computing. While computers primarily use binary, humans often use hexadecimal (base-$16$) as a shorthand for representing binary data, each hexadecimal digit corresponds to four binary digits.  

Many of the earliest number systems, like those used by the Sumerians and Babylonians, favored sexagesimal systems, (base-$60$) (Barrow-Green, Gray and Wilson, 2019, p.24). Remnants of this still exist in how you measure time, angles, and geographic coordinates. At first glance, $60$ may seem an odd choice, but $60$ is a highly composite number, it has factors $1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30,$ and $60$, making it easy to divide with.

The Mayans used a vigesimal (base-$20$) system (Aveni, 2011, p.189), as did the Basque region. Remnants of this exist in the French language, $80$ is quatre-vingts, meaning four-twenties. (Barrow-Green, Gray and Wilson, 2019, p.8)

You're able to change bases using the following algorithm.

::: {.callout-note}
## Algorithm for changing bases.

Let $a$ and $b > 1$ be integers. To find the representation of $a$ in base $b$:

**Step 1**: Divide $a$ by $b$: $a = qb+r$

**Step 2**: Set $r$ to be the last digit of the expansion.

**Step 3**: Rename: $a := q$

**Step 4:** Repeat the above steps until $a = 0$
:::

Now you can see this algorithm used.
 
::: {.callout-note appearance="simple"}
## Example 3

Let's convert $152$ from the usual base $10$, to hexadecimal (base-$16$):

Let $a=152$ and $b=16$:

Divide $a$ by $b$: $152 = 9\cdot16+8$

Set $8$ to be the last digit of the expansion.

Rename: $a := 9$

Divide $a$ by $b$: $9 = 0\cdot16+9$

Set $9$ to be the second to last digit of the expansion.

Rename: $a := 0$

**STOP**

So, $152$ is $98$ in base-$16$.
:::

# Categories of numbers

## Cardinal and ordinal numbers

Cardinal numbers are used to count or represent a quantity of something.

::: callout-note
## Definition of a cardinal number

Cardinal numbers are numbers such as:
$$1, 2, 3, 4...$$
:::

Ordinal numbers, on the other hand, represent the position or order within a list.

::: callout-note
## Definition of a ordinal number

Ordinal numbers are numbers such as:
$$1st, 2nd, 3rd, 4th...$$
:::

## Positive and negative numbers

Positive numbers are numbers such as:
$$1, 2, 3...$$
Negative numbers are numbers such as:
$$-1, -2, -3...$$

::: callout-note
## Definition of positive and negative numbers 
A positive number is a number greater than $0$, conversely, a negative number is a number less than $0$. 
:::

Negative numbers were first introduced in Chinese mathematics around $200$BCE, as a way of representing debts and deficits (Barrow-Green, Gray and Wilson, 2019, pp.214-220). Indian mathematics began incorporating negatives as well, Brahmagupta laid out sets of rules for working with negative numbers in the $7$th century (Barrow-Green, Gray and Wilson, 2019, pp.206-207), but it took until the $19$th century for negative numbers to be fully accepted in western mathematics (Mumford, 2010, p.114).

From tally marks on bones to the place value systems used today, the history of numbers reflects the evolving needs and ingenuity of human societies. Understanding this history will not only enrich your appreciation for mathematics but also highlight how cultural exchange and practical necessity have shaped the way you count, calculate, and make sense of the world.

# Bibliography

Barrow-Green, J., Gray, J. and Wilson, R.J. (2019). The history of mathematics : a source-based approach. Volume 1. Providence, Rhode Island: Maa Press, An Imprint Of The American Mathematical Society

Ritter, J. (2000). Egyptian Mathematics. In: Selin, H. (eds) Mathematics Across Cultures. Science Across Cultures: The History of Non-Western Science, vol 2. Springer, Dordrecht. 

Aveni, A.F. (2011) ‘Maya Numerology’, Cambridge Archaeological Journal, 21(2), pp. 187–216. doi:10.1017/S0959774311000230.

Mumford, D. (2010). What’s so Baffling About Negative Numbers? — a Cross-Cultural Comparison. In: Seshadri, C.S. (eds) Studies in the History of Indian Mathematics. Culture and History of Mathematics. Hindustan Book Agency, Gurgaon.F


# Further reading

For more reading on types of numbers, please go to [Overview: Number sets].


## Version history {-}

v1.0: initial version created 04/25 by Jessica Taberner as part of a University of St Andrews VIP project.
  
[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)