---
title: "Overview: Number sets"
author: "Jessica Taberner"
abstract-title: Summary
abstract: An overview of what numbers and sets are, and some key number sets you can use. 
categories:
  - Key skills
draft: true
---

# What are numbers?

Numbers are used to count, measure, order, and perform calculations. In this overview, you will see some common sets of numbers, what defines them, and how they all fit together.

# What are sets?

In mathematics, a set is a collection of things. In this overview, the sets you'll look at will be sets of numbers. The elements of a set are usually called members. Curly brackets are commonly used for set notation. Sets can be empty, they can contain a finite number of elements or an infinite number of elements. The sets you'll see discussed in detail in this guide are all infinitely large sets.

::: {.callout-note appearance="simple"}
## Example 1

This is how you might write a set containing the first 8 letters in the alphabet. You can call this set $'A8'$.
$$A8=\{a,b,c,d,e,f,g,h\}$$
:::

There are some symbols you can use to describe containment within sets. 

::: callout-note
## Definition of a member

If you want to say an element is a member of a set, you can use $\in$.

So $a \in A$ means $a$ is a member of $A$.
Similarly, if you want to say an element is not a member of a set, you can use $\notin$.
So $b \notin A$ means $b$ is not a member of $A$.
:::

::: {.callout-note appearance="simple"}
## Example 2

Using the set containing the first 8 letters in the alphabet from above:
$$A8=\{a,b,c,d,e,f,g,h\}$$
Since $a$ is in $A8$, you can write $a \in A8$.

Since $z$ is not in $A8$, you can write $z \notin A8$.
:::

::: callout-note
## Definition of subset
Sets can contain other sets. If $A$ and $B$ are two sets, then you can say that $B$ is a **subset** of $A$ if every member of $B$ is also a member of $A$. If this happens, you can write that $B \subseteq A$.

Similarly, you can use $\nsubseteq$ to say something isn't a subset. If all the members of $D$ aren't also members of $C$, you can say $D \nsubseteq C$.
:::

::: {.callout-note appearance="simple"}
## Example 3
The set containing the first 4 letters of the alphabet is a subset of $A8$.

$\{a,b,c,d\} \subseteq A8$.

But the set containing $\{g,h,i,j\}$ isn't a subset of $A8$, since $i$ and $j$ aren't members of $A8$. 

So $\{g,h,i,j\} \nsubseteq A8$.
:::

# Types of number sets

Now you can look at some different sets of numbers. 

## Natural numbers

::: callout-note
## Definition of the natural numbers

$\mathbb{N} = \{0, 1, 2, 3, 4, 5,\ldots\}$

The natural numbers are used for counting things, ordering, and for representing quantities. You will see them used across a large range of topics, including [Guide: Introduction to sigma notation]. **Important sets often have standard notation**, the symbol **commonly used for the natural numbers is $\mathbb{N}$**.
:::

Opinions vary on whether or not zero should be considered a natural number or not. For this overview, you can assume zero is a natural number.

**number line diagram**

## Integers

Natural numbers allow you to count and measure positive values, but what about measuring negative quantities like debts or deficits? For those you have the **integers**. 

Integers are essential for counting, measuring, and expressing concepts that can be positive, negative, or zero. You may see them used in [Guide: Using the quadratic formula] as coefficients in quadratic equations.

The integers are the natural numbers as well as the negatives of each natural number. The symbol commonly used for the integers is $\mathbb{Z}$. The 'Z' from the German word, Zahlen, meaning numbers.

::: callout-note
## Definition of the integers

$\mathbb{Z} = \{... -3, -2, -1, 0, 1, 2, 3 ...\}$
:::

**number line diagram**

Since the integers contain the natural numbers as a subset you can say $\mathbb{N} \subseteq \mathbb{Z}$.

## Rational numbers

The natural numbers and the integers let you count in whole numbers, but what if you need to split a whole number? Imagine you have a cake you want to split between three people, for this, you need the rationals. 

The rational numbers are all numbers that can be described as fractions of integers. They are used for many purposes, you can see them in [Guide: Introduction to solving simultaneous equations], as both solutions to equations and as coefficients. The symbol used for the rational numbers is $\mathbb{Q}$, the 'Q' coming from quotient.

::: callout-note
## Definition of the rational numbers

$\mathbb{Q} = \{ a/b : a,b \in \mathbb{Z} \quad \textsf{and} \quad b \neq 0\}$
:::

It's **very important** here that you don't allow $b$ to be $0$, as you can't divide by $0$.

::: {.callout-note appearance="simple"}
## Example 4

Here are some examples of rational numbers,
$$-3/7 \in \mathbb{Q}, \quad -0.5 \in \mathbb{Q}, \quad 2 \in \mathbb{Q}.$$
:::

If you consider the rational numbers where $b$ is $1$, that is $\mathbb{Q} = \{ a/b : a \in \mathbb{Z} \quad \textsf{and} \quad b = 1\}$, you can see that the rationals necessarily contain the integers, and, by extension, the natural numbers.

$\mathbb{N} \subseteq \mathbb{Z} \subseteq \mathbb{Q}$.


**number line diagram**

## Irrational numbers

The numbers you have so far are sufficient for counting positively and negatively, and dividing, but what about measuring? How would you measure the diagonal of a square of side length 1? For this, you need the irrationals.

The irrational numbers are all numbers that can't be expressed as a fraction of integers. A group of ancient Greek mathematicians, the Pythagoreans, believed all numbers were rational. Legend has it that when a member of their order, Hippasus of Metapontum, proved that $\sqrt{2}$ is not rational, his brothers left him to drown in the Mediterranean as punishment. 

Hippasus was correct. $\sqrt{2}$ cannot be described as a fraction of integers, you can read a proof of this here, [Proof: The square root of 2 is irrational]. In fact, there are lots more irrational numbers. **There are actually more irrational numbers than rational ones.**

:::{.callout-note appearance="simple"}
## Example 5

Here are some more examples of irrational numbers: $\pi$, $-\sqrt{3}$, $e$.
:::

Irrational numbers are very useful. You can see them used in [Guide: Rationalizing the denominator] in the form of square roots, and you can see them used in the context of vectors in [Guide: The scalar product].

## Real numbers

Together, the rational numbers and the irrational numbers describe what you call the real numbers. The symbol used for the real numbers is $\mathbb{R}$.

The real numbers then, necessarily contain all of the above number types: the natural numbers, the integers, the rationals, and the irrationals. 

$\mathbb{N} \subseteq \mathbb{Z} \subseteq \mathbb{Q} \subseteq \mathbb{R}$.

**number line diagram**

You can define the real numbers formally. A **Cauchy sequence** is a sequence where the terms become arbitrarily close to each other. By taking Cauchy sequences of rational numbers, you can define the real numbers as the limits of these sequences. You can read a detailed explanation and proof of this in [Proof: Constructing the reals].

The name, real numbers, is attributed to René Descartes and serves to distinguish them from another set of numbers you can read about below.

Real numbers are used extensively in various applications, particularly when dealing with continuous measurements like length, volume, and other physical quantities. They are fundamental in mathematics for defining limits, continuity, and derivatives, they form the basis for real analysis. You can see them used in tables of common angles in [Guide: Trigonometry (degrees)]. You can see how they are needed in statistics in [Guide: PMFs, PDFs, and CDFs].

## Complex numbers

The numbers you have so far will let you count, measure, order, and perform some calculations. But how would you solve a problem like $x^2+1=0$? For more on this type of equation please read [Guide: Introduction to quadratic equations].

The complex numbers came about while 16th-century Italian mathematician, Girolamo Cardano, wrestled with solutions to cubic equations, that is, equations of the form $ax^{3}+bx^{2}+cx+d$. He ran into the problem of having to square root a negative number. He defined the $\sqrt{-1}$ to be $i$, the imaginary number, its name evidencing some of the mocking this faced at the time.

Complex numbers are numbers of the form $a+bi$, where $a$ and $b$ are real numbers. You can think of complex numbers as having a real part and an imaginary part, though either or both of these can be zero. The symbol used for the complex numbers is $\mathbb{C}$.

::: callout-note
## Definition of the complex numbers
$\mathbb{C} = \{a+bi:a,b \in \mathbb{R}\}$
:::

::: {.callout-note appearance="simple"}
## Example 6

The following are examples of complex numbers: 
$$1+i\in \mathbb{C}, \quad
5-7i\in \mathbb{C}, \quad
4/5\in \mathbb{C}, \quad
\sqrt{3}i\in \mathbb{C}, \quad 
0\in \mathbb{C}, \quad
-17/3+7/8i\in \mathbb{C}.$$
:::

The complex numbers contain all of the above number sets.
$\mathbb{N} \subseteq \mathbb{Z} \subseteq \mathbb{Q} \subseteq \mathbb{R} \subseteq \mathbb{C}$.

Complex numbers are very important. They form the basis for the study of complex analysis and much more. You can read more about complex numbers in [Guide: Introduction to complex numbers], and you can see how to perform arithmetic on complex numbers in [Guide: Arithmetic on complex numbers]. In [Guide: Introduction to quadratic equations], you'll see complex numbers as the solutions to quadratic equations.

**insert here Argan diagram, plots of examples?**

**then have here a demonstration of the nesting of these sets**

## Algebraic and transcendental numbers

Algebraic vs transcendental is an important way of distinguishing complex numbers. Before defining algebraic and transcendental numbers, you need to define a polynomial.

::: callout-note
## Definition of a polynomial
A **polynomial** is an expression of the form:
$$a_{n}x^n+a_{n-1}x^{n-1}+...a_1x+a_0$$
The $a_n$ here are the **coefficients**.
The solutions to the equation, $a_{n}x^n+a_{n-1}x^{n-1}+...a_1x+a_0=0$, are the **roots** of the polynomial.
:::

You can now define an algebraic number.

::: callout-note
## Definition of an algebraic number
An algebraic number is a number that is a root to some non-zero polynomial with rational coefficients. 
:::

::: callout-note
## Definition of a transcendental number
A transcendental number is a number that's not algebraic.
:::

It is very difficult to prove that a number is transcendental. It was first assumed that all numbers were algebraic, but in 1844 Joseph Liouville proved that his number, the Liouville constant, $0.1100010000000001...$, was transcendental. Other mathematicians followed suit and proved that both $\pi$ and $e$ are also transcendental. Fascinatingly, **there are actually more transcendental numbers than algebraic numbers**. 

# Further reading

For more on this topic, please go to [Guide: Introduction to complex numbers] and [Guide: Arithmetic on complex numbers].

## Version history {-}

v1.0: initial version created 04/25 by Jessica Taberner as part of a University of St Andrews VIP project.
  
[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)