---
title: "Proof: The quadratic formula"
author: "Tom Coleman"
abstract-title: Summary
abstract: An explanation as to why the quadratic formula is true.

---

*Before reading this proof sheet, it is recommended that you read [Guide: Completing the square](../studyguides/completingthesquare.qmd).*

# Proof of the quadratic formula {-}

Remember from [Guide: Using the quadratic formula](../studyguides/quadraticformula.qmd) that the **quadratic formula** is used to find roots of any quadratic equation:

::: {.callout-note}

## The quadratic formula

Let $ax^2 + bx + c = 0$ be a quadratic equation (where $a\neq 0$). The roots to this quadratic equation are given by
$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$
where one of the roots is given by the term $(-b+\sqrt{b^2 - 4ac})/2a$ and the other given by the term $(-b-\sqrt{b^2 - 4ac})/2a$.

:::


In order to prove that these really are the solutions to the quadratic, you can **complete the square** on $ax^2 + bx + c$ using the fact that $a\neq 0$. See [Guide: Completing the square](../studyguides/completingthesquare.qmd) for why this works. 

## Proof of the quadratic formula

First of all, as $a\neq 0$ you can divide $ax^2 + bx + c = 0$ through by $a$ to get 
$$x^2 + \frac{b}{a} x + \frac{c}{a} = 0$$
Taking the $c/a$ term over to the other side gives
$$x^2 + \frac{b}{a} x = -\frac{c}{a}$$
Completing the square (see [Guide: Completing the square](../studyguides/completingthesquare.qmd)) gives
$$\left(x + \frac{b}{2a}\right)^2 - \frac{b^2}{4a^2} = -\frac{c}{a}$$
You can rearrange to get $$\left(x + \frac{b}{2a}\right)^2 = \frac{b^2}{4a^2} - \frac{c}{a} = \frac{b^2 - 4ac}{4a^2}$$ Now the result is starting to come together. Taking square roots of both sides (not forgetting that it could be positive or negative) gives
$$x + \frac{b}{2a} = \pm\frac{\sqrt{b^2 - 4ac}}{2a}$$
and rearranging gives
$$x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}$$
as required.

# Further reading {-}

[Guide: Using the quadratic formula](../studyguides/quadraticformula.qmd)

[Questions: Using the quadratic formula](../questions/qs-quadraticformula.qmd)

## Version history and licensing {-}

v1.0: created in 04/24 by tdhc. 

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)



