---
title: "Proof: Trigonometric identities"
author: "Shanelle Advani, Krish Chaudhary, Tom Coleman, Dzhemma Ruseva"
abstract-title: Summary
abstract: Explanations as to why certain trigonometric identities are true.
draft: true

---

*Before reading this proof sheet, it is recommended that you read [Guide: Trigonometric identities (degrees)](../studyguides/trigonometricidentities-degrees.qmd) or [Guide: Trigonometric identities (radians)](../studyguides/trigonometricidentities-radians.qmd).*

# Proof of Pythagorean identities {-}

Remember from [Guide: Trigonometric identities (degrees)](../studyguides/trigonometricidentities-degrees.qmd) or [Guide: Trigonometric identities (radians)](../studyguides/trigonometricidentities-radians.qmd) that the **Pythagorean identities** are:

\begin{align*}
\cos^2(\theta) + \sin^2(\theta)  &= 1\\[1em]
1 + \tan^2(\theta) &= \sec^2(\theta)\\[1em] 
\cot^2(\theta) + 1 &= \csc^2(\theta)
\end{align*}

::: {.callout-note appearance="simple"}

## Proof of $\sin^2(\theta) + \cos^2(\theta) = 1$

You know from [Guide: Trigonometry (degrees)](../studyguides/trigonometry-degrees.qmd) or [Guide: Trigonometry (radians)](../studyguides/trigonometry-radians.qmd) that $$\sin(\theta) = \frac{\textsf{opposite}}{\textsf{hypotenuse}}\quad\textsf{ and }\quad\cos(\theta) = \frac{\textsf{adjacent}}{\textsf{hypotenuse}}.$$ You can shorten these to $O$ for opposite, $A$ for adjacent and $H$ for hypotenuse. Rearranging gives $A = H\cos(\theta)$ and $O = H\sin(\theta)$.

From Pythagoras' Theorem, you also know that $A^2 + O^2 = H^2$.

Replacing $A$ and $O$ with the expressions above, you get

$${(H\cos(\theta))}^2 + {(H\sin(\theta))}^2 = H^2$$

Using the laws of indices (see [Guide: Laws of indices](../studyguides/lawsofindices.qmd)), and using the standard notation $(\cos(\theta))^2 = \cos^2(\theta)$ and $(\sin(\theta))^2 = \sin^2(\theta)$ you can write

$$H^2\cos^2(\theta) + H^2\sin^2(\theta) = H^2$$

Divide everything by the non-zero $H^2$ to get:

$$\frac{H^2\cos^2(\theta)}{H^2} + \frac{H^2\sin^2(\theta)}{H^2} = \frac{H^2}{H^2}$$

Therefore $\cos^2(\theta) + \sin^2(\theta) = 1$.

:::

<!-- ::: callout-note -->
<!-- ## Proof -->

<!-- If you rearrange the double angle identity $\cos(2\theta)$ = $1 - 2sin^2(\theta)$ to make $\sin(\theta)$ the subject of the formula, it results in $\sin(\theta)$ = $±\sqrt{\frac{(1 - \cos(2\theta))}{2}}$ -->

<!-- You can now replace $\theta$ with the variable $\frac{\theta}{2}$ to get the half angle identity. -->

<!-- You can use the remaining double angle identities to derive similar proofs for the other two half angle identities. -->
<!-- ::: -->

# Proof of sum identities {-}

# Further reading {-}

[Guide: Trigonometric identities (degrees)](../studyguides/trigonometricidentities-degrees.qmd)

[Questions: Trigonometric identities (degrees)](../questions/qs-trigonometricidentities-degrees.qmd)

## Version history {-}

v1.0: created in 04/24 by tdhc. 

