---
title: "Questions: Arithmetic on complex numbers"
author: "Charlotte McCarthy"
abstract-title: Summary
abstract: A selection of questions for the study guide on arithmetic on complex numbers.
---

*Before attempting these questions, it is highly recommended that you read [Guide: Arithmetic on complex numbers](../studyguides/arithmeticoncomplexnumbers.qmd).*

## Q1 {-}

Work out each of the following expressions, expressing your answer in the form $a+bi$ where $a$ is the real part and $b$ is the imaginary part. 

1.1. $\quad (5+7i)-(2+3i)$

1.2. $\quad (8+6i)+(2-4i)$

1.3. $\quad (4-i\sqrt{2})-(3+i\sqrt{7})$

1.4. $\quad (\sqrt{8}+4i)-(\sqrt{5}+2i)$

1.5. $\quad (\sqrt{7}+3i)+(2-i)$ 

1.6. $\quad (5 + i\sqrt{2}) - (7 - i) + (\sqrt{3} + 4i)$


## Q2 {-}

Work out each of the following expressions, expressing your answer in the form $a+bi$ where $a$ is the real part and $b$ is the imaginary part. 

2.1. $\quad (2+3i)(4+5i)$

2.2. $\quad (3+i)(2-i)$

2.3. $\quad 4(6+3i)$

2.4. $\quad (1+i)^2$

2.5. $\quad (3+2i)^3$ 

2.6. $\quad (7-4i)^2(i-2)$

2.7. $\quad (1 - i\sqrt{3})^3$

2.8. $\quad (5-2i)(5+2i)$

2.9. $\quad (\sqrt{2} + i\sqrt{3})(\sqrt{8} - i\sqrt{3})$


## Q3 {-}

Work out each of the following expressions, expressing your answer in the form $a+bi$ where $a$ is the real part and $b$ is the imaginary part.  

3.1. $\quad \dfrac{7-6i}{1+2i}$

3.2. $\quad \dfrac{4-i}{1+4i}$

3.3. $\quad \dfrac{3}{5i}$

3.4. $\quad \dfrac{4+2i}{3-i}$

3.5. $\quad \dfrac{9+i}{i}$

3.6. $\quad \dfrac{-2-2i}{-2+2i}$

3.7. $\quad \dfrac{1+5i}{-3i}$

3.8. $\quad \dfrac{-4}{1-i}$

3.9. $\quad \dfrac{1-3i}{1+2i}$

## Q4 {-}

Work out each of the following expressions, expressing your answer in the form $a+bi$ where $a$ is the real part and $b$ is the imaginary part. 

4.1. $\quad \dfrac{(6+4i)(3-i)}{2i}$

4.2. $\quad 3i(5-4i)+(6+2i)$

4.3. $\quad (2+3i)(1-i)-(5-4i)$

4.4. $\quad \dfrac{(5+2i)+(4-i)}{1+i}$

4.5. $\quad \dfrac{(2+i)^3}{(3+i)-(1+i)}$

4.6. $\quad (\dfrac{6-3i}{2(1-i)})^2$


---

[After attempting the questions above, please click this link to find the answers.](../answers/as-arithmeticoncomplexnumbers.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 11/24 by Charlotte McCarthy as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)