---
title: "Questions: Vector addition and scalar multiplication"
author: "Renee Knapp, Kin Wang Pang"
abstract-title: Summary
abstract: A selection of questions for the study guide on vector addition and scalar multiplication.

---

*Before attempting these questions, it is highly recommended that you read [Guide: Vector addition and scalar multiplication](../studyguides/addandsm.qmd).*
<!--2 hyperlinks: line9, 70-->

## Q1 {-}

Answer the following questions.

1.1. If $\mathbf{a} = 4\mathbf{i} + 5\mathbf{j} + 7\mathbf{k}$ and $\mathbf{b} = 8\mathbf{i} + 2\mathbf{j} + 4\mathbf{k}$, find $\mathbf{a} + \mathbf{b}$.

1.2. If $\mathbf{a} = 3\mathbf{j} + 4\mathbf{k}$ and $\mathbf{b} = 2\mathbf{i} + 5\mathbf{k}$, find $\mathbf{a} + \mathbf{b}$.

1.3. If $\mathbf{a} = -2\mathbf{i}  + 6\mathbf{k}$ and $\mathbf{b} = -4\mathbf{i} + 11\mathbf{j} -8\mathbf{k}$, find $\mathbf{a} - \mathbf{b}$.

1.4. If $\mathbf{a} = 4\mathbf{i} + 12\mathbf{j} -7\mathbf{k}$, $\mathbf{b} = 3\mathbf{i} -3\mathbf{j} -2\mathbf{k}$ and $\mathbf{c} = 11\mathbf{i} -4\mathbf{j} +9\mathbf{k}$, find $\mathbf{a} - (\mathbf{b} + \mathbf{c})$.

## Q2 {-}

Solve the following, expressing your answers in terms of the unknown scalars $x,y,z$.

2.1. If $\mathbf{a} = \begin{bmatrix}x \\2y\\0\end{bmatrix}$ and $\mathbf{b} = \begin{bmatrix}3x \\5y\\0\end{bmatrix}$, find $\mathbf{a} + \mathbf{b}$.

2.2. If $\mathbf{a} = \begin{bmatrix}5 \\3y\\5z\end{bmatrix}$ and $\mathbf{b} = \begin{bmatrix}-2\\2x\\6z\end{bmatrix}$, find $\mathbf{a} - \mathbf{b}$.

2.3. If $\mathbf{a} = \begin{bmatrix}2x \\3y\\4z\end{bmatrix}$, $\mathbf{b} = \begin{bmatrix}-2x\\y\\0\end{bmatrix}$ and  $\mathbf{c} = \begin{bmatrix}0\\4y\\4z\end{bmatrix}$, find $\mathbf{a} + \mathbf{b} - \mathbf{c}$.

2.4. If $\mathbf{a} = \begin{bmatrix}2x\\3y\\5z\end{bmatrix}$, what is $\mathbf{a} + \mathbf{0}$?

## Q3 {-}

Answer the following questions.

3.1. If $\mathbf{u} = 5\mathbf{j} + 6\mathbf{k}$, find $3\mathbf{u}$.

3.2. If $\mathbf{v} = \begin{bmatrix}0\\-3\\7\end{bmatrix}$, find $-6\mathbf{v}$.

3.3. If $\mathbf{u} = \begin{bmatrix}0\\5\\6\end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix}0\\-3\\7\end{bmatrix}$, find $4\mathbf{v} - 3\mathbf{u}$.

3.4. If $\mathbf{u} = \begin{bmatrix}0\\5\\6\end{bmatrix}$, $\mathbf{v} = \begin{bmatrix}0\\-3\\7\end{bmatrix}$ and $\mathbf{w} = \begin{bmatrix}2\\3\\-4\end{bmatrix}$, find $-2\mathbf{w} - (4\mathbf{u} -2\mathbf{v})$.

## Q4 {-}

Answer the following questions.

4.1. If $A = (3,4,5)$. $B = (-2,5,7)$, find $\overrightarrow{AB}$.

4.2. If $A = (2,5,7)$, $B = (6,11,7)$ and $C = (0,1,2)$, find $\overrightarrow{AB} - \overrightarrow{AC}$.

<!-- 4.3. If $A = (2,9)$, $B = (12,4)$, $C = (4k,3k)$ and $\overrightarrow{AB}$ and $\overrightarrow{BC}$ are parallel, find $k$. -->

4.3. If $\overrightarrow{AB} = \begin{bmatrix}6\\7\\-2\end{bmatrix}$ and $B = (1,5,9)$, find the coordinates of $A$.

4.4. If $\mathbf{a} = 2\mathbf{i} + 3\mathbf{j}$ and $\mathbf{b} = 3\mathbf{i} -5\mathbf{j}$, find $13\mathbf{i} -9\mathbf{j}$ in terms of $\mathbf{a}$ and $\mathbf{b}$.

4.5. If $\mathbf{a} = \begin{bmatrix}3\\5\\z\end{bmatrix}$, $\mathbf{b} = \begin{bmatrix}-1\\-3\\4\end{bmatrix}$ and $2\mathbf{a} + 3\mathbf{b} = \begin{bmatrix}x\\y\\0\end{bmatrix}$, solve for the unknown scalars $x,y,z$. 

4.6. Given that $\mathbf{a}$ and $\mathbf{b}$ are parallel, if $\mathbf{a} = (x-7)\mathbf{i} + (5x+1)\mathbf{k}$ and $\mathbf{b} = -2\mathbf{i} + 8\mathbf{k}$, find $x$. 

<!-- 4.8. If $5\begin{bmatrix}\alpha\\3\\7\\1\end{bmatrix} - \begin{bmatrix}-5\\\beta\\2\\-5\end{bmatrix} = \begin{bmatrix}2\alpha\\3\beta\\\gamma\\2\delta\end{bmatrix} + 2\begin{bmatrix}-1\\4\\6\\\delta\end{bmatrix}$, solve for the unknowns. -->

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-addandsm.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Renee Knapp, Kin Wang Pang as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)