---
title: "Questions: Area between two curves"
author: "Donald Campbell"
abstract-title: Summary
abstract: A selection of questions for the study guide on the area between two curves.
draft: true
---

*Before attempting these questions, it is highly recommended that you read \[Guide: Area between two curves\].*

## Q1 {.unnumbered}

Calculate the area of the shaded region between the following graphs and the $x$-axis.

1.1. *Insert figure of the graph of* $y = x^3$ *with shaded region between* $x=0$ *and* $x=2$ *bounded by the graph and the* $x$-*axis.*

1.2. *Insert figure of the graph of* $y = \sqrt{4-x}$ *with shaded region between* $x=0$ *and* $x=4$ *bounded by the graph and the* $x$-*axis.*

1.3. *Insert figure of the graph of* $y = \sqrt{2x}$ *with shaded region between* $x=0$ *and* $x=2$ *bounded by the graph and the* $x$-*axis.*

1.4. *Insert figure of the graph of* $y = 2-x$ *with shaded region between* $x=0$ *and* $x=2$ *bounded by the graph and the* $x$-*axis.*

1.5. *Insert figure of the graph of* $y = \dfrac{1}{x}$ *with shaded region between* $x=1$ *and* $x=2$ *bounded by the graph and the* $x$-*axis.*

1.6. *Insert figure of the graph of* $y = x^2-2$ *with shaded region between* $x=-\sqrt{2}$ *and* $x=\sqrt{2}$ *bounded by the* $x$-*axis and the graph.*

1.7. *Insert figure of the graph of* $y = 2x-x^2$ *with shaded region between* $x=0$ *and* $x=2$ *bounded by the graph and the* $x$-*axis.*

1.8. *Insert figure of the graph of* $y = x(x-1)$ *with shaded region between* $x=0$ *and* $x=1$ *bounded by the* $x$-*axis and the graph.*

1.9. *Insert figure of the graph of* $y = x^3-x$ *with shaded region between* $x=0$ *and* $x=1$ *bounded by the graph and the* $x$-*axis.*

1.10. *Insert figure of the graph of* $y = 1-\dfrac{x^2}{4}$ *with shaded region between* $x=-2$ *and* $x=2$ *bounded by the graph and the* $x$-*axis.*

## Q2 {.unnumbered}

Calculate the area of the shaded region between the following trigonometric graphs and the $x$-axis.

2.1. *Insert figure of the graph of* $y = \sin ( x )$ *with shaded region between* $x=0$ *and* $x=\pi$ *bounded by the graph and the* $x$*-axis.*

2.2. *Insert figure of the graph of* $y = \cos ( x )$ *with shaded region between* $x=\dfrac{\pi}{2}$ *and* $x=\dfrac{3\pi}{2}$ *bounded by the graph and the* $x$*-axis.*

2.3. *Insert figure of the graph of* $y = \cos ( 2x )$ *with shaded region between* $x=0$ *and* $x=\dfrac{\pi}{2}$ *bounded by the graph and the* $x$*-axis.*

2.4. *Insert figure of the graph of* $y = \sin ( 2x )$ *with shaded region between* $x=0$ *and* $x=\pi$ *bounded by the graph and the* $x$*-axis.*

2.5. *Insert figure of the graph of* $y = \sin ( 3x )$ *with shaded region between* $x=0$ *and* $x=\dfrac{\pi}{3}$ *bounded by the graph and the* $x$*-axis.*

2.6. *Insert figure of the graph of* $y = \sin ( 3x )$ *with shaded region between* $x=0$ *and* $x=\dfrac{\pi}{2}$ *bounded by the graph and the* $x$*-axis.*

2.7. *Insert figure of the graph of* $y = \cos ( 2x )$ *with shaded region between* $x=\dfrac{\pi}{4}$ *and* $x=\dfrac{5\pi}{4}$ *bounded by the graph and the* $x$*-axis.*

2.8. *Insert figure of the graph of* $y = \sin ( 2x )$ *with shaded region between* $x=\dfrac{\pi}{4}$ *and* $x=\dfrac{3\pi}{4}$ *bounded by the graph and the* $x$*-axis.*

2.9. *Insert figure of the graph of* $y = \sin ( 2x )$ *with shaded region between* $x=\dfrac{\pi}{8}$ *and* $x=\dfrac{3\pi}{4}$ *bounded by the graph and the* $x$*-axis.*

## Q3 {.unnumbered}

Calculate the area of the region enclosed by the following lines and curves.

3.1. *Insert figure of the graph of* $y = 5x-2x^2$ *and* $y = \dfrac{1}{2}x^2$ *with shaded region between* $x=0$ *and* $x=2$ *bounded above by* $y = 5x-2x^2$ *and below by* $y = \dfrac{1}{2}x^2$*.*

3.2. *Insert figure of the graph of* $y = \sqrt{x}-1$ *and* $y = \left( \dfrac{1}{3}x - 1 \right) ^2 -2$ *with shaded region between* $x=0$ *and* $x=9$ *bounded above by* $y = \sqrt{x}-1$ *and below by* $y = \left( \dfrac{1}{3}x - 1 \right) ^2 -2$*.*

3.3. $\quad y = x^2$ and $y = 2x+3$.

3.4. $\quad y = 2x+3$ and $y = 3-\dfrac{1}{2}x^2$.

3.5. $\quad y = 4x^2-3$ and $y = 3-2x$.

3.6. $\quad y = 4\sqrt{x}$ and $y = \dfrac{1}{2}x^2$.

3.7. $\quad y = 4- ( x-4 ) ^2$ and $y = x-2$.

3.8. $\quad y = 5-3x^2$ and $y = -3x-1$.

------------------------------------------------------------------------

[After attempting the questions above, please click this link to find the answers.](../answers/as-areabetweencurves.qmd)

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
