---
title: "Addition and scalar multiplication: questions"
author: "Kin Wang Pang, Renee Knapp"
abstract-title: Summary
abstract: A selection of questions for the study guide on addition and scalar multiplication.

---

*Before attempting these questions, it is highly recommended that you read [Guide: Addition and scalar multiplication](additionandscalarmultiplication.qmd).*
<!--2 hyperlinks: line9, 70-->

## Q1 {-}

Answer the following questions.

1.1. If $\mathbf{a} = 4\mathbf{i} + 5\mathbf{j} + 7\mathbf{k}$ and $\mathbf{b} = 8\mathbf{i} + 2\mathbf{j} + 4\mathbf{k}$, find $\mathbf{a} + \mathbf{b}$.

1.2. If $\mathbf{a} = 0\mathbf{i} + 3\mathbf{j} + 4\mathbf{k}$ and $\mathbf{b} = 2\mathbf{i} + 0\mathbf{j} + 5\mathbf{k}$, find $\mathbf{a} + \mathbf{b}$.

1.3. If $\mathbf{a} = -2\mathbf{i}  + 6\mathbf{k}$ and $\mathbf{b} = -4\mathbf{i} + 11\mathbf{j} -8\mathbf{k}$, find $\mathbf{a} - \mathbf{b}$.

1.4. If $\mathbf{a} = 4\mathbf{i} + 12\mathbf{j} -7\mathbf{k}$, $\mathbf{b} = 3\mathbf{i} -3\mathbf{j} -2\mathbf{k}$ and $\mathbf{c} = 11\mathbf{i} -4\mathbf{j} +9\mathbf{k}$, find $\mathbf{a} - (\mathbf{b} + \mathbf{c})$.

## Q2 {-}

Solve the following in terms of $\alpha$, $\beta$ and $\gamma$.

2.1. If $\mathbf{a} = \begin{pmatrix}\alpha \\2\beta\end{pmatrix}$ and $\mathbf{b} = \begin{pmatrix}3\alpha \\5\beta\end{pmatrix}$, find $\mathbf{a} + \mathbf{b}$.

2.2. If $\mathbf{a} = \begin{pmatrix}5 \\3\beta\\5\gamma\end{pmatrix}$ and $\mathbf{b} = \begin{pmatrix}-2\\2\alpha\\6\gamma\end{pmatrix}$, find $\mathbf{a} - \mathbf{b}$.

2.3. If $\mathbf{a} = \begin{pmatrix}2\alpha \\3\beta\\4\gamma\end{pmatrix}$, $\mathbf{b} = \begin{pmatrix}-2\alpha\\\beta\\0\end{pmatrix}$ and  $\mathbf{c} = \begin{pmatrix}0\\4\beta\\4\gamma\end{pmatrix}$, find $\mathbf{a} + \mathbf{b} - \mathbf{c}$.

2.4. If $\mathbf{a} = \begin{pmatrix}2\alpha\end{pmatrix}$, What is $\mathbf{a} + 0$?

## Q3 {-}

Answer the following questions.

3.1. If $\mathbf{u} = 5\mathbf{j} + 6\mathbf{k}$. find $3\mathbf{u}$.

3.2. If $\mathbf{v} = \begin{pmatrix}0\\-3\\7\end{pmatrix}$, find $-6\mathbf{v}$.

3.3. If $\mathbf{u} = \begin{pmatrix}0\\5\\6\end{pmatrix}$ and $\mathbf{v} = \begin{pmatrix}0\\-3\\7\end{pmatrix}$, find $4\mathbf{v} - 3\mathbf{u}$.

3.4. If $\mathbf{u} = \begin{pmatrix}0\\5\\6\end{pmatrix}$, $\mathbf{v} = \begin{pmatrix}0\\-3\\7\end{pmatrix}$ and $\mathbf{w} = \begin{pmatrix}2\\3\\-4\end{pmatrix}$, find $-2\mathbf{w} - (4\mathbf{u} -2\mathbf{v})$.

## Q4 {-}

Answer the following questions.

4.1. If $A = (3,4,5)$. $B = (-2,5,7)$, find $\overrightarrow{AB}$.

4.2. If $A = (2,5,7)$, $B = (6,11,7)$ and $C = (0,1,2)$, find $\overrightarrow{AB} - \overrightarrow{AC}$.

4.3. If $A = (2,9)$, $B = (12,4)$, $C = (4k,3k)$ and $\overrightarrow{AB}$ and $\overrightarrow{BC}$ are parallel, find $k$.

4.4. If $\overrightarrow{AB} = \begin{pmatrix}6,7,-2\end{pmatrix}$ and $B = (1,5,9)$, find the coordinates of $A$.


4.5. If $\mathbf{a} = 2\mathbf{i} + 3\mathbf{j}$ and $\mathbf{b} = 3\mathbf{i} -5\mathbf{j}$, find $13\mathbf{i} + -9\mathbf{j}$ in terms of $\mathbf{a}$ and $\mathbf{b}$.

4.6. If $\mathbf{a} = \begin{pmatrix}3\\5\\\gamma\end{pmatrix}$, $\mathbf{b} = \begin{pmatrix}-1\\-3\\4\end{pmatrix}$ and $2\mathbf{a} + 3\mathbf{b} = \begin{pmatrix}\alpha\\\beta\\0\end{pmatrix}$, solve for the unknowns. 

4.7.Given that $\mathbf{a}$ and $\mathbf{b}$ are parallel. If $\mathbf{a} = (k-7)\mathbf{i} + (5k+1)\mathbf{j}$ and $\mathbf{b} = -2\mathbf{i} + 8\mathbf{j}$, find $k$. 

4.8. If $5\begin{pmatrix}\alpha\\3\\7\\1\end{pmatrix} - \begin{pmatrix}-5\\\beta\\2\\-5\end{pmatrix} = \begin{pmatrix}2\alpha\\3\beta\\\gamma\\2\delta\end{pmatrix} + 2\begin{pmatrix}-1\\4\\6\\\delta\end{pmatrix}$, solve for the unknowns.
---

[Please click this link to find the answers.](as-additionandscalarmultiplication.qmd)

---