---
title: "Questions: Introduction to confidence intervals"
author: "Millie Harris"
abstract-title: Summary
abstract: A selection of questions to test your understanding of confidence intervals, using the normal distribution.
format: html
draft: true
---

*Before attempting these questions it is highly recommended that you read* [Guide: Introduction to confidence intervals](../studyguides/confidenceinterval.qmd)*.*

## Q1

Identify the confidence level from these alpha values.

1.1. $\alpha = 0.05$

1.2. $\alpha = 0.1$

1.3. $\alpha = 0.01$

## Q2

Using the normal distribution, what are the Z Values for these alpha values? You may find [Calculator: Z-score](.../calculators/c-zscore.qmd) helpful.

2.1. $\alpha = 0.05$

2.2. $\alpha = 0.1$

2.3. $\alpha = 0.01$

## Q3

Cantor's Confectionery want to calculate a $90\%$ confidence interval for the weight of $178$ chocolate swirls. The average weight of this sample is $14g$ and the standard deviation is $0.75g$.

identify the following:

3.1. $n =$ sample size

3.2. $\bar{x} =$ sample mean

3.3. $\sigma =$ sample standard deviation

3.4. $\alpha =$ alpha value

3.5. $Z_\frac{\alpha}{2} =$ Z value using the normal distribution

## Q4

4.1. Use the information in **Q3** to construct a $90\%$ confidence interval for the weight of Cantor's Confectionery's chocolate swirls.

4.2 Explain what the confidence interval tells you in context of Cantor's Confectionery.
