---
title: "Questions: Introduction to confidence intervals"
author: "Millie Harris"
abstract-title: Summary
abstract: A selection of questions to test your understanding of confidence intervals using the normal distribution.
---

*Before attempting these questions it is highly recommended that you read [Guide: Introduction to confidence intervals](../studyguides/confidenceintervals.qmd).*

## Q1

Identify the confidence level from these $\alpha$ values.

1.1. $\alpha = 0.05$

1.2. $\alpha = 0.1$

1.3. $\alpha = 0.07$

## Q2

Using the normal distribution, what are the $Z$-values for these alpha values? You may find [Calculator: Z-score](../apps/calculators/c-zscore.qmd) helpful.

2.1. $\alpha = 0.05$

2.2. $\alpha = 0.1$

2.3. $\alpha = 0.07$

## Q3

Cantor's Confectionery want to calculate a $99\%$ confidence interval for the weight of $178$ chocolate swirls. The average weight of this sample is $14\,\textrm{g}$ and the standard deviation is $0.75\,\textrm{g}$.

3.1. Identify the following:

- sample size $n$

- sample mean $\bar{x}$

- sample standard deviation $s$

- alpha value $\alpha$

- $Z$-value $Z_{\alpha/2}$

3.2. Use the information in 3.1 to construct a $99\%$ confidence interval for the weight of Cantor's Confectionery's chocolate swirls. Give your answers to 3 decimal places.

3.3. Explain what the confidence interval tells you.

## Q4

You are given the following data.

| Quantity    |    Value          |
|:-----------:|:-----------------:|
| $s$         | $4$               |
| $\bar{x}$   | $31$              |
| $n$         | $59$              |

Use the summary table below to construct the following:

4.1. a 90% CI.

4.2. a 95% CI.

4.3. a 99% CI.

You should give you answers to 2 decimal places.

## Q5

You are given a $90\%$ CI as $[98.1,102.5]$ with a sample size of $121$. Work out an estimate of the sample mean $\bar{x}$ and sample standard deviation $s$ associated to this confidence interval. Explain why this can only be an estimate.

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-confidenceintervals.qmd)

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 12/25 by Millie Harris as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
