---
title: "Questions: Expected value, variance, standard deviation"
author: Tom Coleman
abstract-title: Summary
abstract: A selection of questions to test your understanding of expected values, variance, and standard deviation.
---

*Before attempting these questions it is highly recommended that you read [Guide: Expected value, variance, standard deviation](../studyguides/expectedvariance.qmd).*

## Q1 {-}

For each of the following valid random variables with associated probability mass function, work out the expected value and variance.

#### 1.1. {-}

Let $X$ be the random variable representing the result of rolling a biased four sided-die. The PMF of $X$ is given by:

| $x$      | $1$               | $2$              | $3$              | $4$              |
|--------|----|----|----|----|
| $P(X=x)$ | $\dfrac{1}{10}$ | $\dfrac{1}{5}$ | $\dfrac{1}{2}$ | $\dfrac{1}{5}$ |


#### 1.2. {-}

A discrete random variable $X$ has five possible outcomes ($1, 2, 3, 4,$ or $5$), and the PMF is given by:

| $x$      | $1$    | $2$    | $3$    | $4$   | $5$   |
|--------|----|----|----|----|----|
| $P(X=x)$ | $0.25$ | $0.35$ | $0.05$ | $0.2$ | $0.1$ |

#### 1.3. {-}

A coin is tossed, where the probability of tails is $70%$ and heads is $30%$. Let $X$ represent the result of the coin toss. Complete the table below:

| $x$      | Heads | Tails |
|--------|----|----|
| $P(X=x)$ |  $0.7$   |  $0.3$     |

#### 1.4. {-}

The PMF for a random variable $X$ is given as:

| $x$      | 1   | 2    | 3    | 4    |
|--------|----|----|----|----|
| $P(X=x)$ | $1/10$ | $2/10$ | $3/10$ | $4/10$ |


## Q2 {-}

For each of the following valid random variables with associated probability density function, work out the expected value and variance.

#### 2.1. {-}

Let $X$ be a continuous random variable on the interval $[0, 2]$ with the PDF: $$f(x) =\begin{cases} \dfrac{1}{2} & \textsf{if } 0 \leq x \leq 2 \\[0.5em] 0 & \textsf{otherwise} \end{cases}$$

#### 2.2. {-}

Let $X$ be a continuous random variable with the PDF:
$$f(x) = \begin{cases} 2x & \textsf{if } 0 \leq x \leq 1, \\[0.5em] 0 & \textsf{otherwise}.\end{cases}$$

## Q3 {-}

Give the expected value and variance for rolling seven fair $6$-sided dice. You may assume that each roll is independent of every other roll. 

## Q4 {-}

This question refers to the exponential distribution for a continuous random variable. You can find more information about this and [Factsheet: Exponential distribution](../factsheets/f-expdist.qmd).

The PDF of the exponential distribution is $\mathbb{P}(X=x)=\lambda e^{-\lambda x}$. Using integration by parts (see [Guide: Integration by parts]) and the fact that $$\lim_{x\to\infty}x^n e^{-\lambda x} = 0$$ for any natural number $n$ and real $\lambda > 0$, show that

(a) the mean $\mu$ of the exponential distribution is $\dfrac{1}{\lambda}$;

(b) the variance $\sigma^2$ of the exponential distribution is $\dfrac{1}{\lambda^2}$.


--- 

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-expectedvariance.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 08/25 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)


