---
title: "Questions: Factorization"
author: "Millie Pike"
abstract-title: Summary
abstract: A selection of questions for the study guide on factorization.
---

*Before attempting these questions, it is highly recommended that you read [Guide: Factorization](../studyguides/factorization.qmd).*

## Q1 {-}

Express each of the following expressions in their simplest factorized form. 

1.1. $\quad 7x+35$

1.2. $\quad 3x-51$

1.3. $\quad 6m+3n$

1.4. $\quad 5f+10+15k$

1.5. $\quad 10x-2+3y^2+3y$

1.6. $\quad 9xy-3x$

1.7. $\quad a^2+ab$

1.8. $\quad 4m^2-8nm+12m$

1.9. $\quad 12wx^2+16wx$

1.10. $\quad a^3b+ab^2+ ab^3$

1.11. $\quad x(x-6)+3(6-x)$

1.12. $\quad 3w+3z+xw+xz$

1.13. $\quad 2ab+ b^2-b-2a$

1.14. $\quad a^2 b+3a^2+ab+3a-2b-6$

## Q2 {-}

Express each of the following expressions in their simplest factorized form.

2.1. $\quad x^2+6x+5$

2.2. $\quad x^2-3x-4$

2.3. $\quad x^2-4x+3$

2.4. $\quad 2x^2-13x+21$

2.5. $\quad 5x^2-10x+5$

2.6. $\quad x^2-xy-6y^2$

2.7. $\quad 12x^2 y^2+8xy^2-4y^2$

2.8. $\quad x^2-4yx-x+4y$

2.9. $\quad x^2+y^2-2xy$

2.10. $\quad x^2-y^2$

2.11. $\quad 9x^2 +3x -2$


## Q3 {-}

Using your workings from Q1 and Q2, solve the following expressions for $x$ only.

3.1. $\quad 7x+35 = 0$

3.2. $\quad x(x-6)+3(6-x)=0$

3.3. $\quad x^2-4x+3=0$

3.4. $\quad 12x^2 y^2+8xy^2-4y^2=0$

3.5. $\quad x^2-4yx-x+4y=0$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-factorization.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 04/25 by Millie Pike, as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
