---
title: "Questions: Hypothesis Testing"
author: "Ellie Trace"
abstract-title: Summary
abstract: A selection of questions for the study guide on Hypothesis Testing.
draft: true
---

*Before attempting these questions, it is highly recommended that you read [Guide: Hypothesis Testing](../studyguides/hypothesistesting.qmd).*

# Defining hypotheses

1. A library claims that its books are 350 pages long on average. However, you suspect that their books are shorter than 350 pages on average. Define the null and alternative hypotheses you would use to test this.

2. A factory aims to make sure no more than 10% of their products are defective. Define the null and alternative hypotheses you would use to show if the factory is meeting its production target.

3. A food chain wants to test whether mean wait times differ in differ in two of their branches. Define the null and alternative hypotheses you would use to test this.

4. A train company wants to compare the mean travel time of its express trains versus regular trains on a specific route. Define the null and alternative hypotheses if you want to determine if the express trains are significantly faster.

# Significance levels

5. What $\alpha$ value corresponds to a 15% level of significance?

6. What significance level would you choose if you want a 1% chance of incorrectly rejecting $H_0$

# Test selection

7. What test would you use if you had one sample with 15 observations and paired data?

# Critical values and conclusions

8. Cantor's Confectionery is testing whether their average daily sales of Boole Bars differ from the expected mean of 150 bars. They are conducting a two-tailed hypothesis test at a significance level of $\alpha=0.01$ The critical values are $2.58$ and $-2.58$. Their test statistic is $3.12$. What conclusion do you draw?

9. Cantor's Confectionery is now testing if the proportion of customers who buy Lagrangian Lollipops exceeds $40\%$. They conduct a one-tailed hypothesis test at a significance level of $\alpha=0.05$, with a critical value of $1.645$. Their test statistic is $2.01$. What conclusion do you draw?

10. The shop is now testing a new recipe for their Gauss Gummies and wants to compare the sweetness scores of the original recipe and the new recipe. They conduct a paired $t$-test with $\alpha=0.05$ to determine if there is a significant difference between the two recipes. The critical values for their test are $2.306$ and $-2.306$, and the calculated test statistic is $2.45$. What conclusion does the shop reach about the sweetness scores?

[After attempting the questions above, please click this link to find the answers.](../as-hypothesistests.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 10/24 by ect6 (as part of a University of St Andrews VIP project)

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
