---
title: "Questions: Introduction to complex numbers"
author: "Tom Coleman"
abstract-title: Summary
abstract: A selection of questions for the study guide on introduction to complex numbers.
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to complex numbers](../studyguides/introtocomplexnumbers.qmd).*

## Q1 {-}

Using complex numbers, find solutions to the following equations.

1.1. $\quad x^2 = -1$

1.2. $\quad x^2 + 9 = 0$

1.3. $\quad y^2 + 160 = 16$

1.4. $\quad x^2 - 1 = 0$

## Q2 {-}

For each of the complex numbers below, give their real and imaginary parts. (In this question, $a,b$ are real numbers.)

2.1. $\quad z_1 = 2 + 3i$.

2.2. $\quad z_2 = -23 + 32i$.

2.3. $\quad z_3 = 3 - 3i$.

2.4. $\quad z_4 = 3i$.

2.5. $\quad z_5 = - 3 - 2i$.

2.6. $\quad z_6 = a + 2bi$.

2.7. $\quad z_7 = 2$.

2.8. $\quad z_8 = 3/2 + 2i/3$.

2.9. $\quad z_9 = 22 - 33i$.

2.10. $\quad z_{10} = 333 + 22i$.

2.11. $\quad z_{11} = 2i - 2$.

2.12. $\quad z_{12} = -3i - 2$.

## Q3 {-}

Find the complex conjugate for every complex number in Q2.

## Q4 {-}

Draw $z_1, z_4, z_5, z_7$ and their conjugates on the same Argand diagram, making sure to label both your axes and each complex number on the diagram. Can you spot a relationship between a complex number and its conjugate, with respect to the Argand diagram?

<!-- ## Q5 {-} -->

<!-- Show that for every complex number $z = a + bi$: -->

<!-- 5.1. $z + \bar{z} = 2\textsf{Re}(z)$ -->

<!-- 5.2. $z - \bar{z} = 2\textsf{Im}(z)$. -->

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtocomplexnumbers.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 10/24 by tdhc. 

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)