---
title: "Questions: Introduction to vectors"
author: "Zheng Chen"
abstract-title: Summary
abstract: A selection of questions for the study guide on introduction to vectors.
---

*Before attempting these questions, it is recommended that you read [Guide: Introduction to vectors](../studyguides/introductiontovectors.qmd).*

<!-- ## Q1 {.unnumbered} -->

<!-- Are these vectors parallel? -->

<!-- 1.1. $\overrightarrow{AB}=\begin{bmatrix}3\\1\end{bmatrix}$ and $\overrightarrow{CD}=\begin{bmatrix}6\\2\end{bmatrix}$ -->

<!-- 1.2. $\overrightarrow{EF}=\begin{bmatrix}2x\\-y\end{bmatrix}$ and $\overrightarrow{MN}=\begin{bmatrix}6x\\-3y\end{bmatrix}$ -->

<!-- 1.3. $\overrightarrow{PQ}=\begin{bmatrix}2\\-1\end{bmatrix}$ and $\overrightarrow{BC}=\begin{bmatrix}8\\-4\end{bmatrix}$ -->

<!-- 1.4. $\overrightarrow{DE}=\begin{bmatrix}4\\2\\0\end{bmatrix}$ and $\overrightarrow{BC}=\begin{bmatrix}8\\-4\\0\end{bmatrix}$ -->

<!-- 1.5. $\overrightarrow{MO}=\begin{bmatrix}6\\8\\10\end{bmatrix}$ and $\overrightarrow{AC}=\begin{bmatrix}-3\\-4\\-5\end{bmatrix}$ -->


## Q1 {-}

Find the magnitude of the following vectors.

1.1. $\quad \mathbf{a} = -\mathbf{i} + 3\mathbf{j}$

1.2. $\quad \mathbf{b} = 2\mathbf{i}+4\mathbf{j}+6\mathbf{k}$

1.3. $\quad \mathbf{c} = \mathbf{i}-\mathbf{j}+4\mathbf{k}$

1.4. $\quad \mathbf{d} = 5\mathbf{i}-2\mathbf{j}+\mathbf{k}$

1.5. $\quad \mathbf{e} = \begin{bmatrix}2\\-1\\4\end{bmatrix}$

1.6. $\quad \mathbf{f} = \begin{bmatrix}-3\\6\\2\end{bmatrix}$

1.7. $\quad \mathbf{g} = \begin{bmatrix}5\\1\\\sqrt{2}\end{bmatrix}$

1.8. $\quad \mathbf{h} = 6\mathbf{i}+2\mathbf{j}+2\mathbf{k}$

1.9. $\quad \mathbf{m} = -3\mathbf{i}+3\mathbf{j}-3\mathbf{k}$

1.10. $\quad \mathbf{n} = 2\mathbf{i}+4\mathbf{j}+4\mathbf{k}$

1.11. $\quad \mathbf{p} = 8\mathbf{i}-2\mathbf{j}+16\mathbf{k}$

1.12. $\quad \mathbf{q} = \begin{bmatrix}5\\-2\\14\end{bmatrix}$

1.13. $\quad \mathbf{u} = \begin{bmatrix}7\\2\\-1\end{bmatrix}$

1.14. $\quad \mathbf{v} = \begin{bmatrix}12\\9\\8\end{bmatrix}$


## Q2 {-}

Find the unit vectors in the directions of the following vectors.

2.1. $\quad \mathbf{a} = -2\mathbf{i} + 3\mathbf{j}$

2.2. $\quad \mathbf{b} = -2\mathbf{i}+4\mathbf{j}-6\mathbf{k}$

2.3. $\quad \mathbf{c} = \mathbf{i}+2\mathbf{j}+4\mathbf{k}$

2.4. $\quad \mathbf{d} = 4\mathbf{i}-2\mathbf{j}+3\mathbf{k}$

2.5. $\quad \mathbf{e} = \begin{bmatrix}3\\0\\2\end{bmatrix}$

2.6. $\quad \mathbf{f} = \begin{bmatrix}-3\\1\\7\end{bmatrix}$

2.7. $\quad \mathbf{g} = \begin{bmatrix}-5\\0\\\sqrt{2}\end{bmatrix}$

2.8. $\quad \mathbf{h} = -3\mathbf{i}+1\mathbf{j}+1\mathbf{k}$

2.9. $\quad \mathbf{m} = -3\mathbf{i}+3\mathbf{j}-3\mathbf{k}$

2.10. $\quad \mathbf{n} = 3\mathbf{i}+6\mathbf{j}+9\mathbf{k}$

2.11. $\quad \mathbf{p} = 3\mathbf{i}-4\mathbf{j}-5\mathbf{k}$

2.12. $\quad \mathbf{q} = \begin{bmatrix}4\\-3\\12\end{bmatrix}$

2.13. $\quad \mathbf{u} = \begin{bmatrix}6\\5\\4\end{bmatrix}$

2.14. $\quad \mathbf{v} = \begin{bmatrix}2\\4\\8\end{bmatrix}$


---

[After attempting the questions above, please click this link to find the answers.](../answers/as-introductiontovectors.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Zheng Chen as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
