---
title: "Questions: Introduction to logic"
author: "Jessica Taberner"
abstract-title: Summary
abstract: A selection of questions for the study guide introducing propositional logic.
draft: true
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to logic](../studyguides/introtologic.qmd).*


## Q1 Propositions{-}

Boole's Burgers has recently opened. To help Mary and George with their advertising strategy, determine which of the following sentences are propositions.

**1.1.** "Boole's Burgers is a burger restaurant."

**1.2.** "Our burgers taste amazing!"

**1.3.** “All burgers in the restaurant cost more than $£2$.”

**1.4.** “Please give me a cheeseburger.”

**1.5.** “What are your burger toppings?”

**1.6.** “Some customers prefer vegan burgers.”

**1.7.** “Are the fries sold out?”

**1.8.** “The fries are sold out.”

## Q2 Connectives{-}

What is the logical structure for the following statements?

**2.1.** "If you get two burgers, you'll get a discount."

**2.2.** "I'll get one cheeseburger and one vegan burger."

**2.3.** "I won't get cheese on my burger."

**2.4.** "I'll get a hamburger, or I'll get a milkshake."

**2.5.** "I'll only get a cheeseburger if you get one too."

**2.6.** "If you go to Boole's Burgers, I'll go too, and I'll get a vegan burger."

## Q3 Truth tables{-}

Give the truth tables for the following logical statements:

**3.1.** $P \rightarrow Q$

**3.2.** $\neg P$

**3.3.** $(P \vee Q) \wedge \neg Q$

**3.4.** $\neg (P \leftrightarrow Q)$
 
**3.5.** $\neg (P\wedge Q)$

**3.6.** $(P \rightarrow Q) \rightarrow R$

**3.7.** $\neg (P \vee (Q \vee R))$

**3.8.** $(P \leftrightarrow Q) \vee (\neg R)$

## Q4 Equivalence{-}

Using truth tables or otherwise, are the following pairs of statements logically equivalent? 

**4.1.** $\neg (P \wedge Q)$ and $(\neg P) \vee (\neg Q)$

**4.2.** $P \rightarrow Q$ and $Q \rightarrow P$

**4.3.** $P \rightarrow Q$ and $(\neg P) \vee Q$ 

**4.4.** $P \rightarrow Q$ and $\neg (P \vee Q)$ 

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtologic.qmd)

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 03/26 by Jessica Taberner as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
