---
title: "Questions: Introduction to factorials, permutations, and combinations"
author: "Jessica Taberner"
abstract-title: Summary
abstract: A selection of questions for the study guide introducing factorials, permutations, and combinations.
draft: true
---

Before attempting these questions, it is highly recommended that you read [Guide: Introduction to factorials, permutations, and combinations](../studyguides/introtofactorials.qmd).

The questions below will be based on the sweet shops, Cantor’s Confectionery and Lovelace's Lollies.

## Q1 Factorials {-}

**1.1.** In the sweet shop, Cantor's Confectionery, how many ways can you list the different types of sweets? 

(a) There are $5$ types of bonbons, how many ways can you list them?

(b) There are $7$ types of jelly sweets, how many ways can you list them?

(c) There are $4$ types of fudge, how many ways can you list them?

**1.2.** How many ways can you list all $16$ types of these sweets?

**1.3.** How many ways can you list all $16$ of these sweets, if you want to keep all sweets of a certain type together?

## Q2 Permutations{.unnumbered}


**2.1.**

(a) If there are $6$ types of gumdrops sold at Lovelace's Lollies, but only $3$ spots on the shelf for these, how many ways could you fill these $3$ spots?

(b) If there are $7$ types of liquorice, but only $2$ spots on the shelf for these, how many ways could you fill these $2$ spots?

(c) If there are $10$ types of fizzy sweets, but only $6$ spots on the shelf for these, how many ways could you fill these $6$ spots?

**2.2.** Combining all $3$ of these types of sweets, how many ways could you organize the $21$ different kinds of sweets into the $11$ available spots?

**2.3.** How many ways can you do this, if you want to include at least $2$ of each type?

## Q3 Combinations {.unnumbered}

**3.1.**

(a) If there are $8$ types of lollies sold at Cantor's Confectionery, how many ways could you pick $2$?

(b) If there are $4$ types of chocolate, how many ways could you pick $3$?

(c) If there are $12$ types of marshmallow, how many ways could you pick $4$?

**3.2.** Combining all $3$ of these different types of sweets, how many ways could you pick $7$ sweets from the $24$ different kinds?

**3.3.** Assuming you don't want all $7$ to be marshmallows or lollies, how many ways could you pick $7$ sweets from the $24$ different kinds?

## Q4 Counting Strategies {.unnumbered}

**4.1.** Lovelace's Lollies sells $3$ red sweets, $3$ yellow sweets, and $2$ blue sweets, all different from each other. How many ways could you organize these if you don't want all $3$ red sweets together?   

**4.2.** For a display in Cantor's Confectionery, you want to arrange the $8$ bonbons in a circle. How many ways are there to do this?

**4.3.** At Lovelace's Lollies, you want to stock $3$ kinds of lollies and $4$ kinds of jelly sweets. How many ways can you do this, making sure no $2$ lollies are next to each other?

**4.4.** Say you're stocking the shelves at Cantor's Confectionery. There are $10$ different types of sweets, including $5$ kinds of fizzy sweets. You want to arrange these sweets on the shelf, but you want to keep all the fizzy sweets together. How many ways can you do this?

**4.5.** Say you're getting a bag of sweets at Lovelace's Lollies. There are $12$ different types of sweets, $4$ of which are fudge. You want to pick $6$ sweets, but you want this to include at least $2$ different types of fudge. How many ways can you do this?

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtofactorials.qmd)

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 02/26 by Jessica Taberner as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
