---
title: "Questions: Introduction to partial differentiation"
author: "Donald Campbell"
abstract-title: Summary
abstract: A selection of questions for the study guide on the introduction to partial differentiation.
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to partial differentiation](../studyguides/introtopartialdifferentiation.qmd).*

## Q1 {.unnumbered}

Find all possible first-order partial derivatives for each function $f$.

1.1. $\displaystyle \quad f(x,y) = x^2y + y^3$

1.2. $\displaystyle \quad f(x,y) = 3x^3 - 2y^4 + xy$

1.3. $\displaystyle \quad f(x,y) = y\sin(2x) + 3$

1.4. $\displaystyle \quad f(x,y) = e^{xy} + 2x^2y^3$

1.5. $\displaystyle \quad f(x,y) = \ln(x) + x\ln(y) + 3x$

1.6. $\displaystyle \quad f(x,y) = \dfrac{y}{x} - \dfrac{x}{y}$

1.7. $\displaystyle \quad f(x,y) = x \exp(y^2)$

1.8. $\displaystyle \quad f(x,y) = \sqrt{x^2+y^2}$

1.9. $\displaystyle \quad f(x,y) = (3x+2y)^4$

1.10. $\displaystyle \quad f(x,y) = y \sin(xy)$

1.11. $\displaystyle \quad f(x,y) = \sin(x^2+y^2)$

1.12. $\displaystyle \quad f(x,y) = \ln(1+x^2y^2)$

1.13. $\displaystyle \quad f(x,y,z) = x^2y \sin(z)$

1.14. $\displaystyle \quad f(x,y,z) = (x+y)(y+z)(z+x)$

1.15. $\displaystyle \quad f(x,y,z) = \dfrac{xyz}{x+y+z}$

## Q2 {.unnumbered}

A function $f(x,y)$ is called harmonic if it satisfies the equation

$$\dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$$

Show that each of these functions is harmonic by calculating the pure second-order partial derivatives and checking that their sum is zero.

2.1. $\displaystyle \quad f(x,y) = x^2 - y^2$

2.2. $\displaystyle \quad f(x,y) = xy$

2.3. $\displaystyle \quad f(x,y) = x^3-3xy^2$

2.4. $\displaystyle \quad f(x,y) = \cos(x) \sinh(y)$

2.5. $\displaystyle \quad f(x,y) = e^x \sin(y)$

2.6. $\displaystyle \quad f(x,y) = \tan^{-1} \left( \dfrac{y}{x} \right)$

2.7. $\displaystyle \quad f(x,y) = \ln(x^2+y^2)$

## Q3 {.unnumbered}

For each function $f(x,y)$, calculate the mixed second-order partial derivatives and confirm that they satisfy the equation

$$\dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$$

3.1. $\displaystyle \quad f(x,y) = x^2y + xy^2$

3.2. $\displaystyle \quad f(x,y) = 2x^2 \cos(y)$

3.3. $\displaystyle \quad f(x,y) = (x+y)^5$

3.4. $\displaystyle \quad f(x,y) = \dfrac{x}{1+y}$

3.5. $\displaystyle \quad f(x,y) = \sqrt{x^2+y^2}$

3.6. $\displaystyle \quad f(x,y) = x^2\sin(y) + y^2\cos(x)$

3.7. $\displaystyle \quad f(x,y) = \tan^{-1}(xy)$

------------------------------------------------------------------------

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtopartialdifferentiation.qmd)

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
