---
title: "Questions: Solving first-order linear ODEs using integrating factors"
author: "Maddi Koenig"
abstract-title: Summary
abstract: A selection of questions for the study guide on solving first-order linear ODEs using integrating factors.
draft: true
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to solving first-order linear ODEs using integrating factors](../answers/as-integratingfactors.qmd).*

<!-- ## Q1 {-} -->

<!-- For each of the ODEs below, identify the order of the equation. -->

<!-- 1.1. $\frac {dy}{dx} = 4y + \frac {d^2y}{dx^2}$. -->

<!-- 1.2. $\frac {d^2y}{dx^2}  + 3y  = -\frac {d^5y}{dx^5}$. -->

<!-- 1.3. $4x^5 = \frac {d^3x}{dt^3} - \frac {d^2x}{dt^2}$. -->

<!-- 1.4. $6e^y + 5x^3 = \frac {d^9y}{dx^9} + 12 \frac {d^4y}{dx^4)$  -->

## Q1 {-}

Rearrange each first-order linear ODE below to be in the form, $\frac{dy}{dx} + P(x)y = Q(x)$ with respect to the variables in each equation. 

1.1. $- \frac {\mathrm{d}y}{\mathrm{d}x} = y + 8$.

1.2. $\frac {1}{2x} = \frac {\frac {\mathrm{d}y}{\mathrm{d}x} + 5x}{y}$.

1.3. $\frac {\mathrm{d}x}{\mathrm{d}t} - \cos(t) = -x\cos(t)$.

1.4. $x\frac {\mathrm{d}y}{\mathrm{d}x} - x^2 = y$.

## Q2 {-}

Find the integrating factor of every question in question 2. 

## Q3 {-}

Solve each equation in question 2 for the general solution.

## Q4 {-}

4.1. Find the exact solution to question 1.1. given the initial condition $y(0) = 0$.

4.2. Find the exact solution to question 1.2. given the initial condition $y(1) = 6$.

4.3. Find the exact solution to question 1.3. given the initial condition $x(0) = \pi$.

4.4. Find the exact solution to question 1.4. given the initial condition $y(2) = 3$.

## Q5 {-}

5.1 Find the general solution to $\frac {\mathrm{d}y}{\mathrm{d}x} - \frac{5}{x} y = 3x + 2$.

5.2 Find the general solution to $\frac {\mathrm{d}y}{\mathrm{d}x} - \frac{-4y}{4x + 1} = 5x^4$.

5.3 Find the exact solution to $\frac {\mathrm{d}y}{\mathrm{d}x} - \cos(x) = -4y\cot(x)$ when $y(\frac{\pi}{2}) = 1$.

5.4 Find the exact solution to $e^{4x}\frac{\mathrm{d}y}{\mathrm{d}x} + 4e^{4x}y = 4x\sin(x)$ when $y(0) = 4$.


---

[After attempting the questions above, please click this link to find the answers.](../answers/testA.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 04/06 by mak.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)