---
title: "Questions: Introduction to logic (maths)"
author: "Jessica Taberner"
abstract-title: Summary
abstract: A selection of questions for the study guide introducing propositional logic (maths).
draft: true
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to logic (maths)](../studyguides/introtologicmaths.qmd).*


## Q1 Propositions{-}

Which of the following statements are propositions?

**1.1.** "$3 < 5$"

**1.2.** "$5 < 3$"

**1.3.** “$x < 5$”

**1.4.** “$5$ is even.”

**1.5.** “$y$ is odd.”

**1.6.** “$2 \cdot 3 =6$”

**1.7.** “$4 \cdot 3 =10$”

**1.8.** “$2 \cdot 3 < 5x$”

## Q2 Connectives{-}

What is the logical structure for the following statements?

**2.1.** "If $x < 3$, then $y$ is even."

**2.2.** "$x$ is odd and positive."

**2.3.** "$z$ is not $-1$."

**2.4.** "$y$ is even or odd."

**2.5.** "$z$ is positive if and only if $y$ is negative."

**2.6.** "If $x<0$, then $y$ and $z$ are even."

## Q3 Truth tables{-}

Give the truth tables for the following logical statements:

**3.1.** $P \rightarrow Q$

**3.2.** $\neg P$

**3.3.** $(P \vee Q) \wedge \neg Q$

**3.4.** $\neg (P \leftrightarrow Q)$
 
**3.5.** $\neg (P\wedge Q)$

**3.6.** $(P \rightarrow Q) \rightarrow R$

**3.7.** $\neg (P \vee (Q \vee R))$

**3.8.** $(P \leftrightarrow Q) \vee (\neg R)$

## Q4 Equivalence{-}

Using truth tables or otherwise, are the following pairs of statements logically equivalent? 

**4.1.** $\neg (P \wedge Q)$ and $(\neg P) \vee (\neg Q)$

**4.2.** $P \rightarrow Q$ and $Q \rightarrow P$

**4.3.** $P \rightarrow Q$ and $(\neg P) \vee Q$ 

**4.4.** $P \rightarrow Q$ and $\neg (P \vee Q)$ 

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtologicmaths.qmd)

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 03/26 by Jessica Taberner as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
