---
title: "Questions: Introduction to differentiation and the derivative"
author: "Sara Delgado Garcia"
abstract-title: Summary
abstract: A selection of questions for the study guide on introduction to differentiation and the derivative.
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to differentiation and the derivative](../studyguides/introtodifferentiation.qmd).*

In this guide, the following definitions are used:

$$\cosh(x) = \frac{e^{x} + e^{-x}}{2} \quad\textsf{ and }\quad \sinh(x) = \frac{e^{x} - e^{-x}}{2}$$
These are **hyperbolic trigonometric functions**; for more about these, see [Guide: Introduction to hyperbolic functions].

Using the differentiation rules seen in [Guide: Introduction to differentiation and the derivative](../studyguides/introtodifferentiation.qmd), differentiate the following functions:

1.1. $\quad x^3+5x - 3$

1.2. $\quad 5x$

1.3. $\quad -5\sqrt{x}$

1.4. $\quad -\sin(x)$

1.5. $\quad \cos(x) + 5$

1.6. $\quad 2\sqrt{x}$

1.7. $\quad 2\ln(2x) + x^5$

1.8. $\quad \ln(5x)$

1.9. $\quad e^{-x}$

1.10. $\quad 23x + 5$

1.11. $\quad 4x + 100$

1.12. $\quad \sinh(5x)$

1.13 $\quad \cos(3x) - \sin(2x)$

1.14 $\quad \ln(x) +\cos(x) + 3x$

1.15. $\displaystyle\quad \frac{2}{5}\sinh(x) + \frac{2}{13}\cosh(x)$

1.16. $\quad e^{5x} + x^2 + 3$

1.17. $\quad \ln(x) + x^2$

1.18. $\quad \ln(5x) - \ln(x)$

1.19. $\quad \cosh(x) -5x^7$

1.20. $\quad \sqrt{3x^2}$

1.21. $\quad x^3 + 3x - \sqrt{2x}$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtodifferentiation.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 03/25 by Sara Delgado Garcia as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)