---
title: "Questions: Introduction to rearranging equations"
author: "Shanelle Advani, Tom Coleman"
abstract-title: Summary
abstract: A selection of questions for the study guide on introduction to rearranging equations.

---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to rearranging equations](../studyguides/introtorearrange.qmd).*

## Q1 {-}

For each of the following equations, rearrange the equation for the variable given. 

1.1. Rearrange $x = a + 2b$ for $a$.

1.2. Rearrange $x = a + 2b$ for $b$.

1.3. Rearrange $x - 2y + 4z = 4$ for $z$. 

1.4. Rearrange $5x - 3y + 8z = -2$ for $x$. 

1.5. Rearrange $5x - 3y + 8z = -2$ for $y$. 

1.6. Rearrange $5x - 3y + 8z = -2$ for $z$. 

1.7. Rearrange $x^2 + y^2 = 4$ for $x$. 

1.8. Rearrange $\dfrac{x^2}{4} + \dfrac{y^2}{16} = a$ for $x$. 

1.9. Rearrange $\dfrac{x^2}{4} + \dfrac{y^2}{16} = a$ for $y$. 

1.10. Rearrange $\sqrt{x^2 - a^2} = y + 1$ for $x$. 

1.11. Rearrange $\sqrt[3]{x^3 - a^3} = y + 1$ for $a$. 

1.12. Rearrange $\sqrt[3]{x^3 - a^3} = y + 1$ for $x$. 

1.13. Rearrange $x^4y^2 = a^3 + 2bcd$ for $d$. 

1.14. Rearrange $x^4y^2 = a^3 + 2bcd$ for $a$. 

1.15. Rearrange $x^4y^2 = a^3 + 2bcd$ for $x$. 

1.16. Rearrange $\dfrac{1}{x} + 45 = ly^2$ for $x$. 

## Q2 {-}

In [Guide: Introduction to rearranging equations](../studyguides/introtorearrange.qmd), you saw the expression $$5x^3y^3 + \frac{6z}{w^4} = 4abc^2$$ where you rearranged this equation for $x$.

Rearrange this expression for every other variable $a,b,c,y,z,w$.

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtorearrange.qmd)

---