---
title: "Questions: Introduction to $t$-testing"
author: "Millie Harris"
abstract-title: Summary
abstract: A selection of questions for the study guide on introduction to $t$-testing.
draft: True
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to](../studyguides/introtottesting.qmd)* [$t$-testing](../studyguides/introtottesting.qmd).

## Q1

**1.1.** What is the rule of thumb for sample size in $t$-testing?

**1.2.** What is the definition of a t test?

**1.3.** What is the definition of a Student’s t test?

**1.4.** What is the definition of a Welch’s t test?

## Q2

Fill in the tables below and identify what each symbol stands for in these test statistics.

**2.1.** A one-sample test statistic

| Symbol     | Meaning |
|------------|---------|
| $$         
  \bar{x}    
  $$         |         |
| $$         
  \mu_0      
  $$         |         |
| $$         
  s          
  $$         |         |
| $$         
  n          
  $$         |         |

**2.2.** A two-sample test statistic

| Symbol    | Meaning |
|-----------|---------|
| $$        
  \mu_1     
  $$        |         |
| $$        
  \mu_2     
  $$        |         |
| $$        
  s_1       
  $$        |         |
| $$        
  s_2       
  $$        |         |
| $$        
  n_1       
  $$        |         |
| $$        
  n_2       
  $$        |         |

**2.3.** What is the relationship between $s_1$ and $s_2$ for:

a\) A Student's $t$-test?

b\) A Welch's $t$-test?

## Q3 {.unnumbered}

The following examples will follow sweet shops named Cantor's Confectionery and Lovelace's Lollies. For the examples, construct a null and alternative hypothesis.

**3.1.** A one-sample, one-tailed $t$-test where the sample mean is $\bar{x}$. Cantor’s Confectionery want to test if their mean daily earnings are greater than the market average $\mu_0$.

**3.2.** A two-sample, one-tailed $t$-test where Cantor’s Confectionery compare the mean daily earnings, $(\mu_1)$ to Lovelace’s Lollies’ $(\mu_2)$. They want to test if they earns more than Lovelace’s Lollies do.

**3.3.** A two-sample, two-tailed $t$-test where Cantor’s Confectionery compare the mean earnings from weekday sales $(\mu_1)$ and weekend sales $(\mu_2)$ to test if there is a difference.

## Q4 {.unnumbered}

**4.1.** Use the information below to calculate a test statistic.

| Symbol    | Value |
|-----------|-------|
| $\bar{x}$ | $10$  |
| $\mu_0$   | $7$   |
| $s$       | $0.5$ |
| $n$       | $19$  |

**4.1.1** Is this a Students t test or a Welch’s t test?

**4.1.2** Why?

**4.2.** Use the information below to calculate a test statistic.

| Symbol      | Value |
|-------------|-------|
| $\mu_1$     | $12$  |
| $\mu_2$     | $13$  |
| $s_1 = s_2$ | $2$   |
| $n_1$       | $15$  |
| $n_2$       | $16$  |

**4.2.1** Is this a Students t test or a Welch’s t test?

**4.2.2** Why?

**4.3.** Use the information below to calculate a test statistic.

| Symbol  | Value |
|---------|-------|
| $\mu_1$ | $45$  |
| $\mu_2$ | $51$  |
| $s_1$   | $3$   |
| $s_2$   | $3.5$ |
| $n_1$   | $19$  |
| $n_2$   | $18$  |

**4.3.1** Is this a Students t test or a Welch’s t test?

**4.3.2** Why?

## Q5

**5.1.** Perform a $t$-test on the following scenario:

Cantor’s Confectionery want to perform a $t$-test at the $5\%$ significance level. They want to test if their average daily earnings are more than the average for sweet shops in the area. They record the earnings for one week ($7$ days) and calculate the sample mean daily earnings as £$905$, with sample standard deviation £$4$. The market average is £$901.20$.

**5.1.** Perform a $t$-test on the following scenario:

Cantor’s Confectionery want to test whether weekday sales and weekend sales are different. They record daily earnings over several weeks and calculate the following statistics. The test is conducted at the $5\%$ significance level.

**5.2.** Cantor’s Confectionery introduce a new shop window display and want to test if it increases average daily earnings compared to the old display. They collect data on daily earnings before and after the change. The test is conducted at the $5\%$ significance level.

------------------------------------------------------------------------

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtottesting.qmd)

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 03/26 by Millie Harris as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
