---
title: "Questions: Introduction to integration"
author: "Donald Campbell"
abstract-title: Summary
abstract: A selection of questions for the study guide on introduction to integration.
draft: true
---

*Before attempting these questions, it is highly recommended that you read \[Guide: Introduction to integration\].*

## Q1 {.unnumbered}

Use the power rule to integrate the following expressions with respect to $x$.

1.1. $\displaystyle \quad \int x^4 \, \mathrm{d}x$

1.2. $\displaystyle \quad \int 2x \, \mathrm{d}x$

1.3. $\displaystyle \quad \int 7x^5 \, \mathrm{d}x$

1.4. $\displaystyle \quad \int 3x \, \mathrm{d}x$

1.5. $\displaystyle \quad \int -5 \, \mathrm{d}x$

1.6. $\displaystyle \quad \int (2x-5x^2) \, \mathrm{d}x$

1.7. $\displaystyle \quad \int (4x^2+2) \, \mathrm{d}x$

1.8. $\displaystyle \quad \int (10x^{-2}-2x) \, \mathrm{d}x$

1.9. $\displaystyle \quad \int (3x^8+4x^{-4}-2x) \, \mathrm{d}x$

1.10. $\displaystyle \quad \int (5x-2x^{-3}-3x^4) \, \mathrm{d}x$

## Q2 {.unnumbered}

Use the power rule to integrate the following expressions with respect to $x$, using the laws of indices where necessary.

2.1. $\displaystyle \quad \int \dfrac{3}{x^3} \, \mathrm{d}x$

2.2. $\displaystyle \quad \int \dfrac{6}{x^4} \, \mathrm{d}x$

2.3. $\displaystyle \quad \int -\dfrac{2}{x^5} \, \mathrm{d}x$

2.4. $\displaystyle \quad \int \dfrac{8}{3x^6} \, \mathrm{d}x$

2.5. $\displaystyle \quad \int -\dfrac{7}{2x^7} \, \mathrm{d}x$

2.6. $\displaystyle \quad \int \left( \dfrac{5}{x^4} + \dfrac{3}{x^5} \right) \, \mathrm{d}x$

2.7. $\displaystyle \quad \int \left( \dfrac{4}{3x^3} - \dfrac{6}{5x^7} \right) \, \mathrm{d}x$

2.8. $\displaystyle \quad \int \left( \dfrac{7}{x^4} + x^3 -\dfrac{2}{x^6} \right) \, \mathrm{d}x$

2.9. $\displaystyle \quad \int \left( \dfrac{3}{x^5} + \dfrac{4}{x^6} - 1 \right) \, \mathrm{d}x$

2.10. $\displaystyle \quad \int \left( \dfrac{9}{x^9} + \dfrac{4}{7x^6} - \dfrac{7}{3x^8} \right) \, \mathrm{d}x$

## Q3 {.unnumbered}

The following expressions contain fractional indices of $x$. Use the power rule to integrate these expressions with respect to $x$, using the laws of indices where necessary.

3.1. $\displaystyle \quad \int x^{1/3} \, \mathrm{d}x$

3.2. $\displaystyle \quad \int 3x^{-2/3} \, \mathrm{d}x$

3.3. $\displaystyle \quad \int \dfrac{4x^{1/4}}{3} \, \mathrm{d}x$

3.4. $\displaystyle \quad \int \dfrac{2}{5x^{1/3}} \, \mathrm{d}x$

3.5. $\displaystyle \quad \int \dfrac{5}{6x^{-4/3}} \, \mathrm{d}x$

3.6. $\displaystyle \quad \int 2 \sqrt[3]{x} \, \mathrm{d}x$

3.7. $\displaystyle \quad \int \dfrac{6}{\sqrt[4]{x}} \, \mathrm{d}x$

3.8. $\displaystyle \quad \int \Big( x^3 - \dfrac{3}{4\sqrt[3]{x}} + \sqrt[4]{x} \Big) \, \mathrm{d}x$

3.9. $\displaystyle \quad \int \Big( \sqrt[5]{x} - \dfrac{4}{\sqrt[3]{x}} \Big) \, \mathrm{d}x$

3.10. $\displaystyle \quad \int \sqrt[4]{x^5} \, \mathrm{d}x$

3.11. $\displaystyle \quad \int x ( 2-\sqrt[3]{x} ) \, \mathrm{d}x$

3.12. $\displaystyle \quad \int \dfrac{x}{3}\left( \sqrt{x^4} - 2x^{1/3} \right) \, \mathrm{d}x$

3.13. $\displaystyle \quad \int \dfrac{5}{\sqrt[3]{x}} ( 3x^2 + 2 )^2 \, \mathrm{d}x$

3.14. $\displaystyle \quad \int ( 3x^2 + 4x ) ( x^3 + 1 )^2 \, \mathrm{d}x$

3.15. $\displaystyle \quad \int \dfrac{2}{\sqrt[4]{x}} ( 2x^2 + 3 )^2 \, \mathrm{d}x$

## Q4 {.unnumbered}

Integrate the following expressions with respect to $x$ by simplifying the fractions first.

4.1. $\displaystyle \quad \int \dfrac{x^3-2x}{x} \, \mathrm{d}x$

4.2. $\displaystyle \quad \int \dfrac{x^4-3x}{x^3} \, \mathrm{d}x$

4.3. $\displaystyle \quad \int \dfrac{x^2-1}{\sqrt{x}} \, \mathrm{d}x$

4.4. $\displaystyle \quad \int \dfrac{x^3+5x}{\sqrt[3]{x}} \, \mathrm{d}x$

4.5. $\displaystyle \quad \int \dfrac{(x^2-1)(2x^3-3)}{x^2} \, \mathrm{d}x$

4.6. $\displaystyle \quad \int \dfrac{4(3x-1)^2}{x^5} \, \mathrm{d}x$

4.7. $\displaystyle \quad \int \dfrac{5-8x^2}{x\sqrt{x}} \, \mathrm{d}x$

------------------------------------------------------------------------

[After attempting the questions above, please click this link to find the answers.](../answers/as-introtointegration.qmd)

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
