---
title: "Questions: Integration by substitution"
author: "Donald Campbell"
abstract-title: Summary
abstract: A selection of questions for the study guide on integration by substitution.
draft: true
---

*Before attempting these questions, it is highly recommended that you read \[Guide: Integration by substitution\].*

## Q1 {.unnumbered}

Using an appropriate substitution or the chain rule for integration, integrate the following expressions with respect to $x$.

1.1. $\displaystyle \quad \int ( 2x+5 )^3 \, \mathrm{d}x$

1.2. $\displaystyle \quad \int ( 3-4x )^5 \, \mathrm{d}x$

1.3. $\displaystyle \quad \int \left( \dfrac{x}{2} -1 \right)^4 \, \mathrm{d}x$

1.4. $\displaystyle \quad \int ( 5x-2 )^{-3} \, \mathrm{d}x$

1.5. $\displaystyle \quad \int ( 4-3x )^{-2} \, \mathrm{d}x$

1.6. $\displaystyle \quad \int ( 2x+7 )^{-3} \, \mathrm{d}x$

1.7. $\displaystyle \quad \int \left( \dfrac{x}{5} +3 \right)^{-4} \, \mathrm{d}x$

1.8. $\displaystyle \quad \int ( 1-2x )^{-1/2} \, \mathrm{d}x$

1.9. $\displaystyle \quad \int ( 3x+4 )^{-3/2} \, \mathrm{d}x$

1.10. $\displaystyle \quad \int ( 5-6x )^{-2/3} \, \mathrm{d}x$

## Q2 {.unnumbered}

Using an appropriate substitution or the chain rule for integration, integrate the following trigonometric functions with respect to $x$.

2.1. $\displaystyle \quad \int \cos (x) \, \mathrm{d}x$

2.2. $\displaystyle \quad \int \sin ( 2x ) \, \mathrm{d}x$

2.3. $\displaystyle \quad \int \dfrac{5}{6} \cos ( x ) \, \mathrm{d}x$

2.4. $\displaystyle \quad \int \cos ( 3x ) \, \mathrm{d}x$

2.5. $\displaystyle \quad \int \sin \left( \dfrac{x}{3} \right) \, \mathrm{d}x$

2.6. $\displaystyle \quad \int \dfrac{4}{5} \cos \left( 3x-\dfrac{\pi}{4} \right) \, \mathrm{d}x$

2.7. $\displaystyle \quad \int \sin \left( \dfrac{\pi}{3} - \dfrac{4x}{9} \right) \, \mathrm{d}x$

2.8. $\displaystyle \quad \int -\dfrac{1}{2} \cos \left( 3x + \dfrac{\pi}{2} \right) \, \mathrm{d}x$

2.9. $\displaystyle \quad \int 4\sin \left( \dfrac{x}{4} - \dfrac{\pi}{2} \right) \, \mathrm{d}x$

2.10. $\displaystyle \quad \int \dfrac{3}{5} \cos \left( \dfrac{\pi}{6} - 5x \right) \, \mathrm{d}x$

## Q3 {.unnumbered}

Using an appropriate substitution or the chain rule for integration, integrate the following exponential and reciprocal linear functions with respect to $x$.

3.1. $\displaystyle \quad \int 5\mathrm{e}^{2x+1} \, \mathrm{d}x$

3.2. $\displaystyle \quad \int 7\mathrm{e}^{-3x+4} \, \mathrm{d}x$

3.3. $\displaystyle \quad \int -\mathrm{e}^{-3(x-2)} \, \mathrm{d}x$

3.4. $\displaystyle \quad \int 2\exp \Big(\dfrac{x}{3}-5\Big) \, \mathrm{d}x$

3.5. $\displaystyle \quad \int \dfrac{6}{3x-7} \, \mathrm{d}x$

3.6. $\displaystyle \quad \int \dfrac{4}{5-2x} \, \mathrm{d}x$

3.7. $\displaystyle \quad \int \dfrac{3}{2x+5} \, \mathrm{d}x$

3.8. $\displaystyle \quad \int -\dfrac{3}{5(x-2)+1} \, \mathrm{d}x$

## Q4 {.unnumbered}

Using an appropriate substitution, integrate the following functions with respect to $x$. Express your answers in terms of $x$ only.

4.1. $\displaystyle \quad \int 6x(3x^2+2)^4 \, \mathrm{d}x$

4.2. $\displaystyle \quad \int 5(5x-7)^3 \, \mathrm{d}x$

4.3. $\displaystyle \quad \int 8x \exp(4x^2-1) \, \mathrm{d}x$

4.4. $\displaystyle \quad \int \dfrac{2x+1}{(x^2+x+5)^2} \, \mathrm{d}x$

4.5. $\displaystyle \quad \int 6x\cos(3x^2+2) \, \mathrm{d}x$

4.6. $\displaystyle \quad \int (2x+3) \exp(x^2+3x) \, \mathrm{d}x$

4.7. $\displaystyle \quad \int \dfrac{x}{(x^2+1)^{3/2}} \, \mathrm{d}x$

4.8. $\displaystyle \quad \int \dfrac{\mathrm{e}^{5x}}{2\mathrm{e}^{5x}+3} \, \mathrm{d}x$

4.9. $\displaystyle \quad \int -4x\sin(4-2x^2) \, \mathrm{d}x$

4.10. $\displaystyle \quad \int \dfrac{3x^2}{(x^3+1)^2} \, \mathrm{d}x$

------------------------------------------------------------------------

[After attempting the questions above, please click this link to find the answers.](../answers/as-integrationbysubstitution.qmd)

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
