---
title: "Questions: Introduction to Matrices"
author: "Jessica Taberner"
abstract-title: Summary
abstract: A selection of questions on matrices.
categories:
  - Key skills
  - Algebra
draft: true
---

Before attempting these questions, it is highly recommended that you read Guide: Introduction to matrices.

# Q1 {-}

$$A = \begin{bmatrix} 
2 & -1 & \sqrt{3} \\
0 & 4 & -\pi 
\end{bmatrix} \textsf{ , }\quad B = \begin{bmatrix} 
1+i & -2i \\
3 & -4 
\end{bmatrix} \textsf{ , }\quad C = \begin{bmatrix} 
0 & -1 & 2 & 3\\
4 & -\sqrt{2} & i & -5 \\
6 & \pi & -7 & 0
\end{bmatrix} \textsf{ , }\quad D = \begin{bmatrix} 
3 & -i\\
\sqrt{5} & x\\
y & 1/2
\end{bmatrix},$$

$$E = \begin{bmatrix} 
1 & -2 & \sqrt{7}\\
i & 3 & -4\\
5 & -6 & 7 
\end{bmatrix} \textsf{ , }\quad F = \begin{bmatrix} 
-2 & 3/4 & -i\\
\pi & -\sqrt{3} & x^2 \\
7 & 0 & -5
\end{bmatrix} \textsf{ , }\quad G = \begin{bmatrix} 
-1 \\
5 \\
i \\
8 \\
3
\end{bmatrix} \textsf{ , }\quad H = \begin{bmatrix} 
\sqrt{2} & -3 & 4\\
5 & -i & 2/3\\
x & \pi & -7 \\
8 & 9 & -10
\end{bmatrix}.$$

## Q1.1

Give the dimensions of the following matrices:

1.1.1. $\quad A$\

1.1.2. $\quad B$\

1.1.3. $\quad C$\

1.1.4. $\quad D$\

1.1.5. $\quad E$\

1.1.6. $\quad F$\

1.1.7. $\quad G$\

1.1.8. $\quad H$

## Q1.2

Give the values of the following entries:

1.2.1. $\quad a_{1,1}$\

1.2.2. $\quad g_{4,1}$\

1.2.3. $\quad d_{1,2}$\

1.2.4. $\quad f_{3,2}$\

1.2.5. $\quad b_{2,1}$\

1.2.6. $\quad a_{1,2}$\

1.2.7. $\quad c_{2,3}$\

1.2.8. $\quad e_{2,3}$\

1.2.9. $\quad h_{3,1}$\

1.2.10. $\quad h_{1,3}$\

1.2.11. $\quad e_{3,2}$\

1.2.12. $\quad g_{1,1}$

## Q1.3

Give the main diagonals of the following matrices:

1.3.1. $\quad A$\

1.3.2. $\quad C$\

1.3.3. $\quad E$\

1.3.4. $\quad G$\

# Q2

$$ I = \begin{bmatrix} 
3 \\
-\sqrt{5} \\
2i \\
\pi 
\end{bmatrix} \textsf{ , }\quad J = \begin{bmatrix} 
-1 \\
4+i \\
2/3 \\
-\sqrt{7} 
\end{bmatrix} \textsf{ , }\quad K = \begin{bmatrix} 
1 & -2 & 3 \\
4 & i & -5 \\
6 & -7 & \pi 
\end{bmatrix} \textsf{ , }\quad L = \begin{bmatrix} 
\sqrt{3} & -4 & 5/2 \\
-6 & 7 & -8 \\
9 & -i & 10 
\end{bmatrix},$$

$$M = \begin{bmatrix} 
1 & -2 & 3 & 4\\
5 & -i & \sqrt{2} & -6
\end{bmatrix} \textsf{ , }\quad N = \begin{bmatrix} 
-\pi & 3/4 & -1 & 2i \\
0 & -\sqrt{5} & x & 7 
\end{bmatrix} \textsf{ , }\quad O = \begin{bmatrix} 
1 & -2 \\
3 & 4 \\
-5 & i
\end{bmatrix} \textsf{ , }\quad P = \begin{bmatrix} 
\sqrt{3} & -4 \\
\pi & 5 \\
-6 & 7i 
\end{bmatrix}.$$


Calculate the following questions using matrix addition, subtraction and scalar multiplication: 


## Q2.1

2.1.1. $\quad I+J$

2.1.2. $\quad L-K$

2.1.3. $\quad N+M$

2.1.4. $\quad O-P$

2.1.5. $\quad 3I$

2.1.6. $\quad -2J$

2.1.7. $\quad xK$

2.1.8. $\quad -4L$

2.1.9. $\quad yM$

2.1.10. $\quad 7N$

2.1.11. $\quad (1/2)O$

2.1.12. $\quad -4P$

2.1.13. $\quad 3I+J$

2.1.14. $\quad -2(K+L)$

2.1.15. $\quad N-4M$

2.1.16. $\quad 5O-iP$


# Q3

$$Q = \begin{bmatrix} 2 & 3 & 1 & 4 \end{bmatrix} \textsf{ , }\quad R = \begin{bmatrix} -1 \\ 3 \\ \pi \\ 5 \end{bmatrix} \textsf{ , }\quad S = \begin{bmatrix} 1 & -2 & 5 \\ -3 & 4 & -1 \end{bmatrix} \textsf{ , }\quad T = \begin{bmatrix} 5 & -6 \\ 7 & 2 \\ 0 & 8 \end{bmatrix},$$
$$ U = \begin{bmatrix} -1 & 2 \\ 3 & -4 \end{bmatrix} \textsf{ , }\quad V = \begin{bmatrix} \sqrt{2} & -1/2 \\ 3 & 7 \end{bmatrix} \textsf{ , }\quad W = \begin{bmatrix} 0 & -1 & 2 & \pi \\ 3 & -4 & 5 & -6 \\ 1 & \sqrt{7} & -8 & 9 \end{bmatrix} \textsf{ , }\quad X = \begin{bmatrix} 4 \\ 1/2 \end{bmatrix}.$$
Calculate the following using matrix multiplication: 

## Q3.1

3.1.1. $\quad Q   R$

3.1.2. $\quad R   Q$

3.1.3. $\quad S   T$

3.1.4. $\quad T   S$

3.1.5. $\quad U   V$

3.1.6. $\quad V   U$

3.1.7. $\quad W   R$

3.1.8. $\quad S   W$

3.1.9. $\quad T   U$

3.1.10. $\quad T   V$

3.1.11. $\quad T   X$

3.1.12. $\quad U   X$

3.1.13. $\quad V   X$

3.1.14. $\quad X   Q$

3.1.15. $\quad V   V$

3.1.16. $\quad U   U$

## Q3.2

3.2.1. $\quad U   X   Q$

3.2.2. $\quad U^3$

3.2.3. $\quad S   T   V$

3.2.4. $\quad T   X   Q   R$

## Q3.3

3.3.1. $\quad 3U   X$

3.3.2. $\quad (S   T)-2U$

3.3.3. $\quad W   R + T   X$

3.3.4. $\quad -R   Q   R$

3.3.5. $\quad (V+U)   X$

3.3.6. $\quad 4U^2 + V^2$


After attempting the questions above, please click this link to find the answers.

## Version history {-}

v1.0: initial version created 04/25 by ect6 (as part of a University of St Andrews VIP project)
  


