---
title: "Questions: Logarithms"
author: "Zoe Gemmell"
abstract-title: Summary
abstract: A selection of questions for the study guide on logarithms.

---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to Logarithms](../studyguides/logarithms.qmd).*

## Q1 {-}

For the following, find the value of $x$, representing your answer exactly (not decimals).

1.1. $\quad \log_{7}(x) = 1$
 

1.2. $\quad \log_{8}(x) = 3$
 

1.3. $\quad \log_{12}(x) = 0$
 

1.4. $\quad \log_{10}(100) = x$
 

1.5. $\quad \log_{2}(64) = x$
 

1.6. $\quad \log_{4}(2) = x$
 

1.7. $\quad \log_{3}(27) = x$
 

1.8. $\quad \log_{10}(1) = x$
 

1.9. $\quad \log_{x}(16) = 4$
 

1.10. $\quad \log_{x}(49) = 2$
 

1.11. $\quad \log_{x}(13) = 4$
 

1.12. $\quad \log_{2x}(12) = -1$
 

## Q2 {-}

Before attempting this question, write out the five laws of logarithms next to their names: the product rule, the quotient rule, the power rule, the zero rule, the identity rule.

Using the five laws of logarithms, find the value of $x$:

2.1. $\quad \log_{3}\left(\dfrac{1}{27}\right) = x$
 

2.2. $\quad 4\log_{4}(2) = x$
 

2.3. $\quad \log_{5}(10) + \log_{5}\left(\dfrac{5}{2}\right)=x$
 

2.4. $\quad 3\log_{7}\left(a^{1/3}\right) - \frac{1}{2}\log_{7}(a^2) = x$
 

2.5. $\quad \log_{x}(YZ) = M$
 

2.6. $\quad \log_{a}\left(y\right) - \log_a(x) = 11$
 

## Q3 {-}

Using the change of base rule and other laws of logs if required, express the following logarithms as expressions involving a logarithm to the specified base. Give your answer as simply as possible, evaluating if you can. 

3.1. $\quad \log_3(25)$ to base $5$
 

3.2. $\quad \log_{8}(3)$ to base $16$
 

3.3. $\quad \log_{e}(10)$ to base $1000$
 

3.4. $\quad \ln(27)$ to base $3$
 

3.5. $\quad \log_{4}(8x)$ to base $2$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-logarithms.qmd)

---