---
title: "Questions: Laws of indices"
author: "Isabella Lewis, Akshat Srivastava"
abstract-title: Summary
abstract: A selection of questions for the study guide on laws of indices.
---

*Before attempting these questions, it is highly recommended that you read [Guide: Laws of indices](../studyguides/lawsofindices.qmd).*

## Q1 {-}

Express each of the following as a single real number.

1.1. $\quad 3^4$
 

1.2. $\quad 125^{\frac{2}{3}}$
 

1.3. $\quad 32^{\frac{2}{5}}$
 

1.4. $\quad 729^{-\frac{2}{3}}$
 

1.5. $\quad 4^3\cdot2^5$
 

1.6. $\quad 2^2\cdot3^2$
 

1.7. $\quad 8^5\cdot6^5$
 

1.8. $\quad 12^{6}\cdot3^{6}$
 

1.9. $\displaystyle\quad \frac{9^2}{27^2}$
 

1.10. $\quad (5^2)^2$
 

1.11. $\quad (35^0)^9$
 

1.12. $\quad (35^9)^0$
 

1.13. $\quad (729^9)^{\frac{1}{9}}$
 

1.14. $\quad 7^{-3}$
 

1.15. $\quad \dfrac{4^5}{2^5}$
 

1.16. $\quad \dfrac{2^{-2}}{13^{-2}}$
 

1.17. $\quad 64^{\frac{4}{3}}$
 

1.18. $\displaystyle\quad \left(\frac{4^3\cdot{3^3}}{6^3}\right)$
 

1.19. $\quad \left(\dfrac{4^2\cdot{8^2}}{2^2}\right)\cdot{\left(\dfrac{1}{2}\right)^2}$
 

1.20. $\quad \dfrac{\left[\left(\frac{-2}{3}\right)^{-3}\cdot\left(\frac{-3}{5}\right)^{-3}\right]}{\left({\frac{2}{3}}\right)^{-3}}$
 

1.21. $\quad \dfrac{\left(\frac{1}{2}\right)^4\left(\frac{3}{5}\right)^4}{\left(\frac{8}{3}\right)^{4}}$
 

1.22. $\displaystyle\quad \left(\frac{2}{3}\right)^{14}\cdot\left(\frac{9}{12}\right)^{14}$


## Q2 {-}
Evaluate the following expressions, writing your answer in the simplest possible form.

2.1. $\quad (b^{7})^{4}$
 

2.2. $\quad y^{13}\cdot{y^{5}}$
 

2.3. $\quad a^2\cdot b^2$
 

2.4. $\quad \dfrac{x^{13}}{x^5}$
 

2.5. $\quad (y^{-2})^5$
 

2.6. $\quad a^{-4}\cdot b^{-4}$
 

2.7. $\quad (7z^{-5})^3$
 

2.8. $\quad \dfrac{8x^5}{4x^{-5}}$
 

2.9. $\quad (x^{2})^3\cdot{x^{5}}$
 

2.10. $\quad \dfrac{2a^{-4}}{3a^{-2}}$
 

2.11. $\quad \dfrac{x^5}{y^5}$
 

2.12. $\quad \dfrac{2y^3}{2y^5}$
 

2.13. $\displaystyle\quad \left(\frac{2}{a}\right)^{4}\cdot\left(\frac{a}{12}\right)^{3}$
 

2.14. $\quad \dfrac{25t^{-4}}{60t^{5}}$
 

2.15. $\displaystyle\quad \left(\frac{a}{b}\right)^{-4}\cdot\left(\frac{c}{d}\right)^4\cdot\left(\frac{e}{f}\right)^4$
 

2.16. $\quad \dfrac{5^{x+1}\cdot6^{x+1}}{3^{x+1}}$
 

2.17. $\quad \left(a^{\frac{1}{2}}\right)\cdot\left(b^{-\frac{1}{2}}\right)$
 

2.18. $\displaystyle\quad \left(\frac{a}{b}\right)^n\cdot\left(\frac{c}{d}\right)^{-n}$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-lawsofindices.qmd).

---
