---
title: "Questions: Introduction to matrices"
author: "Jessica Taberner"
abstract-title: Summary
abstract: A selection of questions on matrices.
draft: true
---

Before attempting these questions, it is highly recommended that you read [Guide: Introduction to matrices].

# Q1 {-}

You are given the following matrices:

$$A = \begin{bmatrix} 
2 & -1 & \sqrt{3} \\
0 & 4 & -\pi 
\end{bmatrix} \textsf{ , }\quad B = \begin{bmatrix} 
2 & -2 \\
3 & -4 
\end{bmatrix} \textsf{ , }\quad C = \begin{bmatrix} 
0 & -1 & 2 & 3\\
4 & -\sqrt{2} & 1 & -5 \\
6 & \pi & -7 & 0
\end{bmatrix} \textsf{ , }\quad D = \begin{bmatrix} 
3 & -1\\
\sqrt{5} & x\\
y & 1/2
\end{bmatrix},$$

$$E = \begin{bmatrix} 
1 & -2 & \sqrt{7}\\
1 & 3 & -4\\
5 & -6 & 7 
\end{bmatrix} \textsf{ , }\quad F = \begin{bmatrix} 
-2 & 3/4 & -1\\
\pi & -\sqrt{3} & x^2 \\
7 & 0 & -5
\end{bmatrix} \textsf{ , }\quad G = \begin{bmatrix} 
-1 \\
5 \\
1 \\
8 \\
3
\end{bmatrix} \textsf{ , }\quad H = \begin{bmatrix} 
\sqrt{2} & -3 & 4\\
5 & -1 & 2/3\\
x & \pi & -7 \\
8 & 9 & -10
\end{bmatrix}.$$

## Q1.1

Give the dimensions of all matrices $A-H$.

## Q1.2

Give the values of the following entries:

a. $\quad [A]_{11}$

b. $\quad [G]_{41}$

c. $\quad [D]_{12}$\

d. $\quad [F]_{32}$\

e. $\quad [B]_{21}$\

f. $\quad [A]_{12}$\

g. $\quad [C]_{23}$\

h. $\quad [E]_{23}$\

i. $\quad [H]_{31}$\

j. $\quad [H]_{13}$\

k. $\quad [E]_{32}$\

l. $\quad [G]_{11}$

## Q1.3

Give the main diagonals of the matrices $A$, $C$, $E$, and $G$.

# Q2

You are given the following matrices:

$$ X = \begin{bmatrix} 
3 \\
-\sqrt{5} \\
2 \\
\pi 
\end{bmatrix} \textsf{ , }\quad Y = \begin{bmatrix} 
-1 \\
5 \\
2/3 \\
-\sqrt{7} 
\end{bmatrix} \textsf{ , }\quad Z = \begin{bmatrix} 
1 & -2 & 3 \\
4 & 1 & -5 \\
6 & -7 & \pi 
\end{bmatrix} \textsf{ , }\quad W = \begin{bmatrix} 
\sqrt{3} & -4 & 5/2 \\
-6 & 7 & -8 \\
9 & -1 & 10 
\end{bmatrix},$$

$$M = \begin{bmatrix} 
1 & -2 & 3 & 4\\
5 & -1 & \sqrt{2} & -6
\end{bmatrix} \textsf{ , }\quad N = \begin{bmatrix} 
-\pi & 3/4 & -1 & 2 \\
0 & -\sqrt{5} & x & 7 
\end{bmatrix} \textsf{ , }\quad O = \begin{bmatrix} 
1 & -2 \\
3 & 4 \\
-5 & 1
\end{bmatrix} \textsf{ , }\quad P = \begin{bmatrix} 
\sqrt{3} & -4 \\
\pi & 5 \\
-6 & 7 
\end{bmatrix}.$$


Calculate the following questions using matrix addition, subtraction, and scalar multiplication: 

a. $\quad X+Y$

b. $\quad Z-W$

c. $\quad N+M$

d. $\quad O-P$

e. $\quad 3X$

f. $\quad -2Y$

g. $\quad xZ$

h. $\quad -4W$

i. $\quad yM$

j. $\quad 7N$

k. $\quad (1/2)O$

l. $\quad -4P$

m. $\quad 3X+Y$

n. $\quad -2(Z+W)$

o. $\quad N-4M$


# Q3

You are given the following matrices:

$$Q = \begin{bmatrix} 2 & 3 & 1 & 4 \end{bmatrix} \textsf{ , }\quad R = \begin{bmatrix} -1 \\ 3 \\ \pi \\ 5 \end{bmatrix} \textsf{ , }\quad S = \begin{bmatrix} 1 & -2 & 5 \\ -3 & 4 & -1 \end{bmatrix} \textsf{ , }\quad T = \begin{bmatrix} 5 & -6 \\ 7 & 2 \\ 0 & 8 \end{bmatrix},$$
$$ U = \begin{bmatrix} -1 & 2 \\ 3 & -4 \end{bmatrix} \textsf{ , }\quad V = \begin{bmatrix} \sqrt{2} & -1/2 \\ 3 & 7 \end{bmatrix} \textsf{ , }\quad W = \begin{bmatrix} 0 & -1 & 2 & \pi \\ 3 & -4 & 5 & -6 \\ 1 & \sqrt{7} & -8 & 9 \end{bmatrix} \textsf{ , }\quad X = \begin{bmatrix} 4 \\ 1/2 \end{bmatrix}.$$
Calculate the following using matrix multiplication: 

a. $\quad Q   R$

b. $\quad R   Q$

c. $\quad S   T$

d. $\quad T   S$

e. $\quad U   V$

f. $\quad V   U$

g. $\quad W   R$

h. $\quad S   W$

i. $\quad T   U$

j. $\quad T   V$

k. $\quad T   X$

l. $\quad U   X$

m. $\quad V   X$

n. $\quad X   Q$

o. $\quad V   V$

p. $\quad U   U$

q. $\quad U   X   Q$

r. $\quad U^3$

s. $\quad S   T   V$

t. $\quad T   X   Q   R$

u. $\quad 3U   X$

v. $\quad (S   T)-2U$

w. $\quad W   R + T   X$

x. $\quad -R   Q   R$

y. $\quad (V+U)   X$

z. $\quad 4U^2 + V^2$

---

After attempting the questions above, please click this link to find the answers.

---

## Version history {-}

v1.0: initial version created 04/25 by Jessica Taberner as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
