---
title: "Questions: Matrix multiplication with special matrices"
author: "Tom Coleman"
abstract-title: Summary
abstract: A selection of questions on matrix multiplication with special matrices.
---

Before attempting these questions, it is highly recommended that you read [Guide: Matrix multiplication with special matrices](../studyguides/matrixmultiplication.qmd).

## Q1 {-}

You are given the following matrix multiplications. Express each of these as a system of simultaneous equations.

1.1. $\displaystyle\quad \begin{bmatrix}3&3\\1&-1\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix} = \begin{bmatrix}4\\5\end{bmatrix}$

1.2. $\displaystyle\quad \begin{bmatrix}3&3\\1&-1\\-4&3\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix} = \begin{bmatrix}4\\5\\0\end{bmatrix}$

1.3. $\displaystyle\quad \begin{bmatrix}3&3&3\\0&1&-1\\-4&3&-1\end{bmatrix}\begin{bmatrix}x\\y\\z\end{bmatrix} = \begin{bmatrix}4\\5\\0\end{bmatrix}$

1.4. $\displaystyle\quad \begin{bmatrix}3&3&3\end{bmatrix}\begin{bmatrix}x\\y\\z\end{bmatrix} = \begin{bmatrix}4\end{bmatrix}$

1.5. $\displaystyle\quad \begin{bmatrix}3&3&3&3\\1&-1&0&1\end{bmatrix}\begin{bmatrix}x\\y\\z\\t\end{bmatrix} = \begin{bmatrix}4\\5\end{bmatrix}$

## Q2 {-}

You are given the following systems of simultaneous equations. Express each of these as a matrix multiplication.

2.1. $$\begin{aligned} 9x - y &= -4 \\[0.2em] x + y &= 1\end{aligned}$$

2.2. $$\begin{aligned} x + 3y + z &= 8 \\[0.2em] -x - y + 9z &= -1 \end{aligned}$$

2.3. $$\begin{aligned} 3x + y &= 4 \\[0.2em] x - y  &= 5\\[0.2em] 8x - 9y &= 1\end{aligned}$$

2.4. $$\begin{aligned} 3x + 3y + 3z &= 4\\ z &= 1\\-4x - 4y + 8z &= 1\end{aligned}$$

2.5. $$\begin{aligned} 2x + 2y + 2z + 9t &= 4 \\[0.2em] -x - y - z - t &= -10\end{aligned}$$

## Q3 {-}

Let $\;\;S = \begin{bmatrix} 1 & -2 & 5 \\ -3 & 4 & -1 \end{bmatrix},$ $\;\;T = \begin{bmatrix} 5 & -6 \\ 7 & 2 \\ 0 & 8 \end{bmatrix}$. Work out the following matrix products.

3.1. $\quad S0_{3\times 9}$

3.2. $\quad 0_{9\times 3}T$

3.3. $\quad SI_3$

3.4. $\quad I_2S$

3.5. $\quad I_2T$

## Q4 {-}

For each of the following statements, give an example of an upper triangular $2\times 2$ matrix $A$ and a lower triangular $2\times 2$ matrix $B$ such that:

4.1. $\quad AB$ is upper triangular.

4.2. $\quad AB$ is lower triangular.

4.3. $\quad AB$ is diagonal.

4.4. $\quad AB$ is the $2\times 2$ identity matrix.

4.5. $\quad AB$ is neither upper nor lower triangular. 






---

[After attempting the questions above, please click this link to find the answers.](../answers/as-matrixmultiplication.qmd)

---

## Version history {-}

v1.0: initial version created 05/26 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
