---
title: "Powers and nth roots: questions"
author: "Isabella Lewis"
abstract-title: Summary
abstract: A selection of questions for the study guide on powers and nth roots.

---

*Before attempting these questions, it is highly recommended that you read [Guide: powers and nth roots].*

## Q1 {-}
Simplify the following expressions, leaving your answer as a singular power:\

1.1. $(a)^2\cdot(b)^2$\

1.2. $(a)^{-4}\cdot(b)^{-4}$\

1.3. $2^2\cdot3^2$\

1.4. $8^5\cdot6^5$\

1.5. $12^{11}\cdot3^{11}$\

1.6. $(\frac{x^5}{y^5})$\

1.7. $(\frac{4^5}{2^5})$\

1.8. $(\frac{2^{-2}}{13^{-2}})$\

1.9. $(\frac{a}{b})^n\cdot(\frac{c}{d})^n$\

1.10. $(\frac{2}{3})^{14}\cdot(\frac{9}{12})^{14}$\

1.11. $(a^{\frac{1}{2}})\cdot(b^{\frac{1}{2}})$\


## Q2 {-}
Evaluate the following:\

2.1. $(\frac{4^3\cdot{3^3}}{6^3})$\

2.2. $(\frac{4^2\cdot{8^2}}{2^2})\cdot{(\frac{1}{2})^2}$\

2.3. ${(\frac{a}{b})^4}\cdot{(\frac{c}{d})^4}\cdot{(\frac{e}{f})^4}$\

2.4. $\frac{[({\frac{-2}{3}})^{-3}\cdot({\frac{-3}{5}})^{-3}]}{(({\frac{2}{3}})^{-3})}$\

2.5. ${\frac{5^{x+1}\cdot6^{x+1}}{3^{x+1}}}$\

2.6. $\frac{(\frac{1}{2})^4(\frac{3}{5})^4}{(\frac{8}{3})^{4}}$\


## Q3 {-}
For the following, find the value of $x$:\

3.1. $(4^x)\cdot(2^x)=64$\

3.2.  ${\frac{5^{x+1}\cdot6^{x+1}}{3^{x+1}}}=100$\

3.3. $\frac{[(\frac{1}{2})^x\cdot(\frac{-1}{4})^x]}{(\frac{2}{3})^x}=\frac{-27}{4096}$\


## Q4 {-}
Simplify the following expressions:\

4.1. $\sqrt{8}$\

4.2. $\sqrt{3}\cdot\sqrt{7}$\

4.3. $(\frac{\sqrt{24}}{\sqrt{6}})$\

4.4. $(\sqrt{5})^2$\

4.5. $(\sqrt{2})^4$\

4.6. $\sqrt{75}$\

4.7. $\sqrt{4^3}\cdot\sqrt[3]{8}$\

4.8. $\sqrt{6}\cdot\sqrt{15}$\

4.9. $\sqrt{75}-\sqrt{27}$\

4.10. $(8+\sqrt{2})\cdot(3-\sqrt{2})$\

4.11. $(3\sqrt{7})^2(8\sqrt{3})^2$\

4.12. $(3-\sqrt{8})^2$\

4.13. $(7+\sqrt{5})\cdot(1+\sqrt{5})$\

4.14. $\sqrt{45}+\sqrt{125}$\

4.15. $\sqrt{108}$


## Q5 {-}
Simplify the following:\

5.1. $\frac{8}{\sqrt{3}}$\

5.2. $\frac{7+\sqrt{5}}{3+\sqrt{5}}$\

5.3. $(\frac{2-\sqrt{3}}{3+\sqrt{3}})$\

5.4. $\frac{21}{2+\sqrt{3}}$\

5.5. $\frac{1}{4-\sqrt{8}}$\

---

[Please click this link to find the answers.](as-powersandnthroots.qmd)

---
