---
title: "Questions: The product rule"
author: "Sara Delgado Garcia"
abstract-title: Summary
abstract: A selection of questions for the study guide on the product rule. 
---

*Before attempting these questions, it is highly recommended that you read [Guide: The product rule.](../studyguides/productrule.qmd).*

In this question set, the following definitions are used:

$$\cosh(x) = \frac{e^{x} + e^{-x}}{2} \quad\textsf{ and }\quad \sinh(x) = \frac{e^{x} - e^{-x}}{2}$$
These are **hyperbolic trigonometric functions**; for more about these, see [Guide: Introduction to hyperbolic functions].

Differentiate the following functions using the product rule.

1.1. $\quad xe^x$

1.2. $\quad x^2e^{2x}$

1.3. $\quad 5x^3\tan(x)\cos(x)$

1.4. $\quad x \ln(x)$

1.5. $\quad (x^3 + x^2 -5)(x +1)$

1.6. $\quad (13x^2 + 5x +2)(x^3 + 2)$

1.7. $\quad x(5x^2 + 3x + 2)(x^2 +x +1)$

1.8. $\quad (10x^2 + 21)\cos(x)$

1.9. $\quad \cosh(2x)\sinh (3x)$

1.10 $\quad (x^2 +3)\ln(x)$

1.11 $\quad \sin(x)\sqrt{x}$

1.12 $\quad \cosh(x)\ln(x)$

1.13. $\quad x^2\sqrt{x}+x^2\cos(x)$

1.14. $\quad e^{-5x}(x^3+5)$

1.15. $\quad \cos(x)\ln(x)$

1.16. $\quad \ln(x) \ln (3x) \ln (100x)$

1.17. $\quad (x^2 + 5x + 2)\sin(x)$

1.18. $\quad -\ln(x)\ln(3x)$

1.19. $\quad (x^5 + 3)(x^2+ 3x)(x^7 + x^4)$

1.20. $\quad (\sin(x) + 3x)e^{-x}$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-productrule.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 05/25 by Sara Delgado Garcia as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)