---
title: "Questions: PMFs, PDFs, and CDFs"
author: Sophie Chowgule
abstract-title: Summary
abstract: A selection of questions to test your understanding of probability mass functions (PMFs), probability density functions (PDFs), and cumulative distribution functions (CDFs).
---

*Before attempting these questions it is highly recommended that you read [Guide: PMFs, PDFs, and CDFs](../studyguides/pmfspdfscdfs.qmd).*

## Q1 {-}

For each of the scenarios below, determine if the given distribution is a valid PMF and answer the following questions.

#### 1.1. {-}

Let $X$ be the random variable representing the result of rolling a biased four sided-die. The PMF of $X$ is given by:

| $x$      | $1$               | $2$              | $3$              | $4$              |
|--------|----|----|----|----|
| $P(X=x)$ | $\dfrac{1}{10}$ | $\dfrac{1}{5}$ | $\dfrac{1}{2}$ | $\dfrac{1}{5}$ |

What is $P(X = 4)$?

#### 1.2. {-}

A discrete random variable $X$ has five possible outcomes ($1, 2, 3, 4,$ or $5$), and the PMF is given by:

| $x$      | $1$    | $2$    | $3$    | $4$   | $5$   |
|--------|----|----|----|----|----|
| $P(X=x)$ | $0.25$ | $0.35$ | $0.05$ | $0.2$ | $0.1$ |

What is the probability of $X = 3$ or $X = 4$?

#### 1.3. {-}

A coin is tossed, where the probability of tails is $70%$ and heads is $30%$. Let $X$ represent the result of the coin toss. Complete the table below:

| $x$      | Heads | Tails |
|--------|----|----|
| $P(X=x)$ |       |       |

#### 1.4. {-}

A discrete random variable $X$ has the possible outcomes $1, 2, 3, 4, 5, 6,$ or  $7$, with the following PMF:

| $x$      | $1$   | $2$    | $3$ | $4$   | $5$    | $6$    | $7$    |
|--------|----|----|----|----|----|----|----|
| $P(X=x)$ | $0.1$ | $0.05$ | $0.05$ | $0.3$ | $0.25$ | $0.75$ | $0.35$ |

Is this a valid PMF? Justify your answer either way. 

#### 1.5. {-}

A bag contains $5$ red, $3$ blue, and $2$ green sweets from a sweet shop. Let $X$ represent the color of a randomly picked sweet:

(a) What is the probability of picking a blue sweet?

(b) Construct the PMF for this scenario by completing the table:

| $x$      | Red | Blue | Green |
|--------|----|----|----|
| $P(X=x)$ |     |      |       |

#### 1.6. {-}

The PMF for a random variable $X$ is given as:

| $x$      | 1   | 2    | 3    | 4    |
|--------|----|----|----|----|
| $P(X=x)$ | $p$ | $2p$ | $3p$ | $4p$ |

(a) For what value of $p$ is this a valid PMF?

(b) For this value of $p$, what is $P(X = 3)$?

## Q2 {-}

For each of the scenarios below, determine if the given distribution is a valid PDF and answer the following questions.

#### 2.1. {-}

Let $X$ be a continuous random variable on the interval $[0, 2]$ with the PDF:$$f(x) =\begin{cases} \dfrac{1}{2} & \textsf{if } 0 \leq x \leq 2 \\[0.5em] 0 & \textsf{otherwise} \end{cases}$$

What is the probability that $X$ lies between 1 and 2?

#### 2.2. {-}

Let $X$ be a continuous random variable with the PDF:
$$f(x) = \begin{cases} 2x & \textsf{if } 0 \leq x \leq 1, \\[0.5em] 0 & \textsf{otherwise}.\end{cases}$$

(a) What is the probability that $X$ lies between $0.5$ and $1$?

(b) What is $P(0.25 \leq X \leq 0.75)$?

#### 2.3. {-}

Let $X$ be a continuous random variable uniformly distributed between $3$ and $7$. The PDF is: $$f(x) =\begin{cases}\dfrac{1}{4} & \textsf{if } 3 \leq x \leq 7 \\[0.5em] 0 & \textsf{otherwise}\end{cases}$$

What is the probability that $X$ lies between $3$ and $6$?

#### 2.4. {-} 

The PDF of a random variable $X$ is given by: $$f(x) =\begin{cases}\dfrac{1}{9} & \textsf{if } 1 \leq x \leq 4 \\[0.5em]\dfrac{1}{4} & \textsf{if } 5 \leq x \leq 7 \\[0.5em] 0 & \textsf{otherwise}\end{cases}$$

Is this a valid PDF? Justify your answer either way. 

#### 2.5. {-}

Consider the PDF:

$$
f(x) =
\begin{cases}
k x^2 & \textsf{if } 0 \leq x \leq 1 \\[0.5em]
0 & \textsf{otherwise}
\end{cases}
$$

(a) For what value of $k$ is this a valid PDF?

(b) For this value of $k$, what is $P(0.2 \leq x \leq 0.3)$?

#### 2.6. {-}

The PDF of $X$ is given by:

$$
f(x) =
\begin{cases}
4x & \textsf{if } 0 \leq x < 0.5, \\[0.5em]
4 - 4x & \textsf{if } 0.5 \leq x < 0.75, \\[0.5em]
0.5 & \textsf{if } 0.75 \leq x \leq 1, \\[0.5em]
0 & \textsf{otherwise}.
\end{cases}
$$

Is this a valid PDF? Justify your answer either way.

## Q3 {-}

For each of the scenarios below, answer the following questions.

#### 3.1. {-}

In a scenario involving a discrete random variable, the following CDF is given:

| $x$      | $1$   | $2$   | $3$   | $4$   |
|--------|----|----|----|----|
| $P(X=x)$ | $0.1$ | $0.3$ | $0.5$ | $1$   |

(a) What is $F(3)$?

(b) What is $P(X > 2)$?

#### 3.2. {-}

For the random variable uniformly distributed on $[0, 2]$ as seen in Q2.2:

(a) Calculate the CDF at values $0.5$, $1$, and $2$.

(b) What is $F(3)$?

#### 3.3. {-}

For the PDF given in Q2.3:

(a) Calculate the CDF at points $x=4$, $x=5$, and $x=6$.

(b) What is $P(X > 5)$?

#### 3.4. {-}

The CDF of $X$ for a scenario is given by:

| $x$      | $1$   | $2$   | $3$   | $4$   | $5$   | $6$   |
|--------|----|----|----|----|----|----|
| $P(X=x)$ | $0.1$ | $0.2$ | $0.5$ | $0.4$ | $0.8$ | $1$   |

Is this a valid CDF? Justify your answer either way.

--- 

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-pmfspdfscdfs.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 12/24 by Sophie Chowgule as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)


