---
title: "Questions: Using the quadratic formula"
author: "Tom Coleman"
abstract-title: Summary
abstract: A selection of questions on using the quadratic formula.

---

*Before attempting these questions, it is recommended that you read [Guide: Using the quadratic formula](../studyguides/quadraticformula.qmd).*

## Q1 {-}

Using the quadratic formula or otherwise, solve the following quadratic equations.

1.1. $\quad x^2 - 7x + 6 = 0$.

1.2. $\quad x^2 + 14x + 45 = 0$.

1.3. $\quad x^2 - 4x + 13 = 0$.

1.4. $\quad x^2 - x - 56 = 0$.

1.5. $\quad s^2 + 4s + 4 = 0$.

1.6. $\quad t^2 + 4t - 4 = 0$.

1.7. $\quad m^2 - 144 = 0$. 

1.8. $\quad 5c^2 - 25 + 30 = 0$. 

1.9. $\quad 2n^2 + n + 1 = 0$.

1.10. $\quad -3c^2 + 9c - 1 = 0$.

1.11. $\quad \frac{x^2}{2} - \frac{7x}{2} + 3 = 0$.

1.12. $\quad e^{2x} - 4e^x + 4 = 0$

1.13. $\quad -9s^2 + 3s - 1 = 0$

1.14. $\quad 2e^{6x} + e^{3x} + 1 = 0$.

1.15. $\quad \cos^2(x) + 4\cos(x) - 4 = 0$. 

1.16. $\quad 8m^2 - 4m - 1 = 0$.

## Q2 {-}

In [Questions: Introduction to quadratic equations](qs-introtoquadratics.qmd), you saw that the following expressions are all quadratic equations in disguise. Solve these for the variable indicated. 

2.1. $\quad x = 1/x - 1$; solve for $x$.

2.2. $\quad (y-1)(y-4) = -(y+2)(y+3)$; solve for $y$.

2.3. $\quad 4m(m+1) + 6 = 5$; solve for $m$. 

2.4. $\quad (t-1)(t+1) = -2$; solve for $t$. 

2.5. $\quad \displaystyle \frac{x-1}{x-2} = 5x$; solve for $x$.

2.6. $\quad \displaystyle \frac{e^{x} - e^{-x}}{2} = 1$; solve for $x$ (you may need [Guide: Introduction to logarithms](../studyguides/logarithms.qmd) to express your answers.)

---

[Please click this link to find the answers.](../answers/as-quadraticformula.qmd)




