---
title: "Questions: Introduction to radians"
author: "Mark Toner, Ifan Howell-Baines"
abstract-title: Summary
abstract: Questions relating to the introduction to radians study guide.

---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to radians](../studyguides/radians.qmd).*

## Q1 {-}

Convert the following angle measures in degrees into radians, giving your answer as both a fraction of $\pi$ and a real number to three decimal places.

1.1. $\quad 30^\circ$
 

1.2. $\quad 105^\circ$
 

1.3. $\quad 298^\circ$
 

1.4. $\quad 61^\circ$
 

1.5. $\quad 353^\circ$
 

1.6. $\quad 197^\circ$
 

## Q2 {-}

Convert the following angle measures in radians into degrees. If your answer is a decimal, you should give your answer to three decimal places.

2.1. $\quad \dfrac{\pi}{3}$
 

2.2. $\quad \dfrac{2\pi}{3}$
 

2.3. $\quad \dfrac{\pi}{7}$
 

2.4. $\quad \dfrac{5\pi}{7}$
 

2.5. $\quad 5$
 

2.6. $\quad \dfrac{3}{4}$
 

## Q3 {-}

Find the length of arc and the area of the sector of the following specified objects, giving your answer as either a fraction of $\pi$ or expressing your answer to three decimal places.

3.1. circle with radius $7$ over an angle of $\dfrac{\pi}{8}$
 

3.2. circle with radius $\dfrac{1}{3}$ over an angle of $\dfrac{3\pi}{2}$
 

3.3. circle with radius $30$ over an angle of $\dfrac{7\pi}{15}$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-radians.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Mark Toner, Ifan Howells-Baines as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)


