---
title: "Questions: Rationalizing the denominator"
author: "Maximilian Volmar"
abstract-title: Summary
abstract: A selection of questions for the study guide on rationalizing the denominator.
draft: true
---

*Before attempting these questions, it is highly recommended that you read [Guide: Rationalizing the denominator](../studyguides/rationalizingthedenominator.qmd).*


## Q1 {-}

Rationalize the denominator for each of the following expressions. Provide your answers in their simplest form and with a positive denominator.

1.1. $\quad \dfrac{5}{\sqrt{3}}$

1.2. $\quad \dfrac{7}{2\sqrt{5}}$

1.3. $\quad \dfrac{11}{4\sqrt{7}}$

1.4. $\quad \dfrac{8}{5\sqrt{6}}$

1.5. $\quad \dfrac{3\sqrt{2}}{\sqrt{5}}$

1.6. $\quad \dfrac{9}{\sqrt{10}}$

1.7. $\quad \dfrac{\sqrt{7}}{\sqrt{3}}$

1.8. $\quad \dfrac{\sqrt{2}}{\sqrt{6}}$

1.9. $\quad \dfrac{12}{\sqrt{11}}$

1.10. $\quad \dfrac{\sqrt{8}}{\sqrt{2}}$

1.11. $\quad \dfrac{15}{3\sqrt{7}}$

1.12. $\quad \dfrac{6\sqrt{3}}{\sqrt{10}}$

1.13. $\quad \dfrac{\sqrt{18}}{\sqrt{9}}$

1.14. $\quad \dfrac{2\sqrt{5}}{\sqrt{12}}$

1.15. $\quad \dfrac{4}{\sqrt{2}}$

1.16. $\quad \dfrac{10}{5\sqrt{13}}$

---

## Q2 {-}

Rationalize the denominator for each of the following expressions. Provide your answers in their simplest form and with a positive denominator.

2.1. $\quad \dfrac{5}{2 + \sqrt{3}}$

2.2. $\quad \dfrac{7}{4 - \sqrt{2}}$

2.3. $\quad \dfrac{3}{\sqrt{5} + 1}$

2.4. $\quad \dfrac{\sqrt{7}}{\sqrt{3} - 1}$

2.5. $\quad \dfrac{2 + \sqrt{5}}{1 - \sqrt{2}}$

2.6. $\quad \dfrac{3\sqrt{2} + 5}{4 + \sqrt{6}}$

2.7. $\quad \dfrac{8}{3 - \sqrt{7}}$

2.8. $\quad \dfrac{6}{2 + \sqrt{5}}$

2.9. $\quad \dfrac{\sqrt{10}}{\sqrt{2} + 3}$

2.10. $\quad \dfrac{2\sqrt{3} + 5}{\sqrt{7} - 1}$

2.11. $\quad \dfrac{\sqrt{6} - \sqrt{2}}{2 + \sqrt{5}}$

2.12. $\quad \dfrac{4 + \sqrt{3}}{5 - \sqrt{7}}$

2.13. $\quad \dfrac{2}{4 - \sqrt{11}}$

2.14. $\quad \dfrac{\sqrt{8} + \sqrt{3}}{\sqrt{7} - 2}$

---

## Q3{-}

3.1. $\quad$ The denominator of the expression $\dfrac{\sqrt{11}}{2\sqrt{3}+\sqrt{5}}$ is not of the form $b + c\sqrt{d}$, where $b$ and $c$ are integers and $d$ is an integer that is not a perfect square but you can still rationalize the denominator.

Prove that

$$
\dfrac{\sqrt{11}}{2\sqrt{3}+\sqrt{5}} = \dfrac{2\sqrt{33}-\sqrt{55}}{7}
$$

3.2. $\quad$ Rationalize the denominator of this expression:
$\dfrac{5-\sqrt{2}}{\sqrt{10}-\sqrt{3}}$

Provide your answer in its simplest form and with a positive denominator.



---

[After attempting the questions above, please click this link to find the answers.](../answers/as-rationalizingthedenominator.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 12/24 by Maximilian Volmar.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
