---
title: "Questions: Introduction to sigma notation"
author: "Ifan Howells-Baines, Mark Toner"
abstract-title: Summary
abstract: Questions relating to the guide on introduction to sigma notation.
categories:
  - Arithmetic
  - A-level
  - Advanced Higher
---

*Before attempting these questions, it is highly recommended that you read [Guide: Introduction to sigma notation](../studyguides/sigmanotation.qmd).*

## Q1 {-}

Calculate the value of the following sums in sigma notation. You may use the properties of sums but they should not be necessary.

1.1. $\displaystyle\quad \sum_{i = 1}^{10} 2i$

1.2. $\displaystyle\quad \sum_{i = 2}^{11} i$

1.3. $\displaystyle\quad \sum_{i = 3}^{6} 3i$

1.4. $\displaystyle\quad \sum_{i = 1}^{5} i^3$

1.5. $\displaystyle\quad \sum_{i = 2}^{6} 5i^2$

1.6. $\displaystyle\quad \sum_{i = 3}^{6} 2$

1.7. $\displaystyle\quad \sum_{i = 1}^{6} j$

## Q2 {-}

Express the following using sigma notation. Note that there are multiple correct answers for some of the questions. It is recommended to use $i$ as your variable so that your answers will align with those provided.

2.1. $\quad 3 + 6 + 9 + 12$

2.2. $\quad - 1 - 2 - 3 - 4$

2.3. $\quad 0 + 3 + 9 + 27 + 81$

2.4. $\quad 1 + 1 + 1 + 1 + 1$

2.5. $\quad 6 - 12 + 18 - 24$

2.6. $\quad 8 + 16 + 12 + 4$

2.7. $\quad 25 + 20 + 15 + 10 + 5$

## Q3 {-}

Using the properties listed in the guide write the following sums in their simplest form; that is, with as little information as possible within the summation.

3.1. $\displaystyle\quad \sum_{i = 1}^{n} 2i$

3.2. $\displaystyle\quad \sum_{i = 1}^{n} 2i + \sum_{j = 1}^{n} 2i$

3.3. $\displaystyle\quad \sum_{i = 0}^{n} 4i + \sum_{i = 1}^{n} 2i$

3.4. $\displaystyle\quad \sum_{i = 2}^{n} 2i - \sum_{i = 1}^{n} i$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-sigmanotation.qmd)

---
