---
title: "Questions: The scalar product"
author: "Ritwik Anand"
abstract-title: Summary
abstract: A selection of questions for the study guide on the scalar product
---

*Before attempting these questions, it is highly recommended that you read [Guide: The scalar product](../studyguides/scalarproduct.qmd), as well as [Guide: Introduction to quadratic equations](../studyguides/introtoquadratics.qmd).*

## Q1 {-}

Find the scalar product of $\mathbf{a}$ and $\mathbf{b}$.

1.1. $\mathbf{a}= \begin{bmatrix}6\\3\\4\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}1\\4\\2\end{bmatrix}$

1.2. $\mathbf{a}= \begin{bmatrix}10\\-7\\4\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}3\\-5\\13\end{bmatrix}$

1.3. $\mathbf{a}= \begin{bmatrix}-44\\-12\\3\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}61\\-25\\93\end{bmatrix}$
 
1.4. $\mathbf{a}= \begin{bmatrix}54\\38\\0\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}32\\-55\\13\end{bmatrix}$

1.5. $\mathbf{a}= 2\mathbf{i} + 7\mathbf{j} + \mathbf{k}$ and $\mathbf{b}= 6\mathbf{i} + 4\mathbf{j} + 8\mathbf{k}$

1.6. $\mathbf{a}= -3\mathbf{i} + 10\mathbf{j} - 8\mathbf{k}$ and $\mathbf{b}= \mathbf{i} - 12\mathbf{j} + 9\mathbf{k}$

1.7. $\mathbf{a}= 17\mathbf{j} + 23\mathbf{k}$ and $\mathbf{b}= 6\mathbf{i} - 23\mathbf{j} - 8\mathbf{k}$

1.8. $\mathbf{a}= \mathbf{i}$ and $\mathbf{b}= \mathbf{j}$. 

What can you say about the result of 1.8.? Can you deduce similar conclusions for the scalar product of different combinations of the vectors $\mathbf{i}$, $\mathbf{j}$, $\mathbf{k}$?

## Q2 {-}

Using the geometric definition of the scalar products, find the smallest angle $\theta$ in between $\mathbf{a}$ and $\mathbf{b}$ in degrees. If your answer is not a whole number, give your answer to an accuracy of one decimal place.

2.1. $\mathbf{a}= \begin{bmatrix}-5\\2\\-3\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}2\\-2\\11\end{bmatrix}$

2.2. $\mathbf{a}= \begin{bmatrix}1\\1\\1\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}1\\-1\\1\end{bmatrix}$

2.3. $\mathbf{a}= \begin{bmatrix}-8\\1\\-4\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}-1\\-5\\7\end{bmatrix}$

2.4. $\mathbf{a}= \begin{bmatrix}1.2\\-1.4\\-3.1\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}-5.4\\9.7\\-7.5\end{bmatrix}$

2.5. $\mathbf{a}= \begin{bmatrix}45\\65\\54\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}-19\\-58\\71\end{bmatrix}$

2.6. $\mathbf{a}= \begin{bmatrix}1\\0\\0\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}0\\0\\1\end{bmatrix}$

2.7. $\mathbf{a}= \begin{bmatrix}-1\\-2\\3\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}4\\-5\\6\end{bmatrix}$

2.8. $\mathbf{a}= \begin{bmatrix}-17\\3\\8\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}12\\-19\\-16\end{bmatrix}$

## Q3 {-}

Find the value(s) of $\lambda$ for which $\mathbf{a}$ and $\mathbf{b}$ are perpendicular.

3.1. $\mathbf{a}= \begin{bmatrix}2\\4\\7\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}1\\\lambda\\-2\end{bmatrix}$

3.2. $\mathbf{a}= \begin{bmatrix}0\\1\\\lambda\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}1\\2\\3\end{bmatrix}$

3.3. $\mathbf{a}= \begin{bmatrix}9\\-2\\11\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}\lambda\\-\lambda\\3\end{bmatrix}$ 

3.4. $\mathbf{a}= \begin{bmatrix}\lambda\\6\\1\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}\lambda\\\lambda\\8\end{bmatrix}$ 

3.5. $\mathbf{a}= \begin{bmatrix}-2\lambda^2\\4\\14\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}3\\2\lambda\\1\end{bmatrix}$ 

3.6. $\mathbf{a}= \begin{bmatrix}-5\\9\\2\lambda\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}\lambda\\-2\\\lambda\end{bmatrix}$

3.7. $\mathbf{a}= \begin{bmatrix}-7\\4\\2\lambda\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}2\lambda\\1\\6\lambda\end{bmatrix}$

3.8. $\mathbf{a}= \begin{bmatrix}-25\\-\lambda^2\\-2\end{bmatrix}$ and $\mathbf{b}= \begin{bmatrix}3\lambda\\-11\\7\end{bmatrix}$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-scalarproduct.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Ritwik Anand as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
