---
title: "Questions: Solving equations involving logarithms"
author: "Tom Coleman, Ellie Gurini"
abstract-title: Summary
abstract: A selection of questions for the study guide on solving equations involving logarithms.
---

*Before attempting these questions, it is highly recommended that you read [Guide: Solving equations involving logarithms](../studyguides/solvingeqslogarithms.qmd).*

## Q1 {-}

1.1. Rearrange $\log_{16}(x)=\log_2(y)$ for both $x$ and $y$.

1.2. Rearrange $\log_{3}(x^2)=\log_{27}(y)$ for both $x$ and $y$.

1.3. Rearrange $\log_{3}(x^2) - \log_{9}(y) = 3\log_{3}(z)$ for $x,y$ and $z$.

## Q2 {-}

Solve each of the logarithmic equations below for the variable in the equation. If an equation has more than one variable, solve for the variable stated. You should check the validity of all your potential solutions.

2.1. $6\log_3(x)+\log_3(5)=9$

2.2. $\log_2{16x}=6$

2.3. $\log_{12}e^{2t} = 4$

2.4. $log_9(x)+log_3(3x)=6$

2.5. $4\ln\sqrt{x} - \ln(1-2x) = 0$

2.6. $\ln(x+1) - \ln(x) = e$

2.7. $\log_{10}(2y + 10) = \log_{10}(y-2)$

2.8. $\log_3\sqrt{x} - \log_9 \sqrt{4x - 3} = 0$

2.9. $\log_3(2-3x) = \log_9(6x^2 - 19x + 2)$

2.10. $\log_3(x) - 2\log_x(3) = 1$

## Q3 {-}

Solve the simultaneous equations

$$
\begin{aligned}
\log_{10}(x) - \log_{10}(y+1) &= 1\\[0.5em]
\log_2(x - 14y) &= 3.
\end{aligned}
$$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-solvingeqslogarithms.qmd)

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Ellie Gurini as part of a University of St Andrews STEP project, and updated 10/25 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

