---
title: "Questions: Trigonometric identities (radians)"
author: "Dzhemma Ruseva"
abstract-title: Summary
abstract: A selection of questions on trigonometric identities, where angles are measured in radians.

---

*Before attempting these questions, it is recommended that you read [Guide: Trigonometric identities (radians)](../studyguides/trigonometricidentities-radians.qmd).*


## Q1 {-}

Using trigonometric identities, find the values of the following expressions:

1.1.  $\quad2(6\sin^2(\theta))+3(4\cos^2(\theta))$.

1.2.  $\quad10(7\sin^2(\theta))+14(5\cos^2(\theta))$.

1.3.  $\quad5\left(\dfrac{6}{\csc^2(\theta)}\right)+15\left(\dfrac{2}{\sec^2(\theta)}\right)$.

1.4.  $\quad(\cos^2(\theta)-\sin^2(\theta))^2 + 4sin^2(\theta)\cos^2(\theta)$

<!-- 1.5.  $\quad7\cos(90^\circ-\theta)\sin(\theta)+7\sin(90^\circ-\theta)\cos(\theta)$ -->

<!-- 1.6.  $\quad6\sin(\theta+2\pi)\sin(\theta+4\pi)+6\cos(\theta-2\pi)\cos(\theta-4\pi)$ -->

1.5.  $\quad2\sin(\pi/6)\cos(\pi/12)+2\cos(\pi/6)\sin(\pi/12)$

1.6.  $\quad3\cos(\pi/4)\cos(\pi/12)-3\sin(\pi/4)\sin(\pi/12)$

1.7.  $\quad\sin(5\pi/6)+\sin(\pi/6)$

1.8. $\quad\cos(5\pi/6)+\cos(\pi/6)$


## Q2 {-}

Simplify the following expressions:

2.1. $\quad\tan(\theta)\cos(-\theta)$

2.2  $\quad\tan(-\theta)\csc(-\theta)\sec(-\theta)$

2.3. $\quad\tan^2(\theta)+\sin^2(\theta)+\cos^2(\theta)$

2.4. $\quad\displaystyle\frac{2\sin(\theta)}{\cos(\theta)(1-\tan^2(\theta))}$

<!-- 2.5. $\quad\sin(90+\theta)-\sin(90-\theta)$ -->

2.5. $\quad\displaystyle\frac{\sin(7\theta)+\sin(3\theta)}{\cos(7\theta)-\cos(3\theta)}$

2.6. $\quad\displaystyle\frac{\sin(5\theta)-\sin(\theta)}{\cos(5\theta)+\cos(\theta)}$

## Q3 {-}

Using trigonometric identities, answer the following questions:

3.1. What is the value of $\cos(-7\pi/6)$?

3.2. What are the values of $\sin(3\pi/4)$ and $\sin(5\pi/4)$?

3.3. If $\sin(5\pi/18)$ has the value $0.766$ (to $3$ decimal places), what is the value of $\cos(13\pi/18)$ to three decimal places?

## Q4 {-}

Using trigonometric identities find **exact** values of the following:

3.1. $\quad\sin(\pi/12)$

3.2. $\quad\cos(\pi/12)$

3.3. $\quad\tan(\pi/12)$

3.4. $\quad\sin(5\pi/12)$

3.5. $\quad\cos(5\pi/12)$

3.6. $\quad\tan(5\pi/12)$

---

[After attempting the questions above, please click this link to find the answers.](../answers/as-trigonometricidentities-radians.qmd)

---


## Version history and licensing {-}

v1.0: initial version created 08/23 by Dzhemma Ruseva as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc, and split into versions for both degrees and radians.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)



