---
title: "Questions: Trigonometric identities (degrees)"
author: "Dzhemma Ruseva"
abstract-title: Summary
abstract: A selection of questions on trigonometric identities, where angles are measured in degrees.

---

*Before attempting these questions, it is recommended that you read [Guide: Trigonometric identities (degrees)](../studyguides/trigonometricidentities-degrees.qmd).*


## Q1 {-}

Using trigonometric identities, find the values of the following expressions:

1.1.  $\quad2(6\sin^2(\theta))+3(4\cos^2(\theta))$.

1.2.  $\quad10(7\sin^2(\theta))+14(5\cos^2(\theta))$.

1.3.  $\quad5\left(\dfrac{6}{\csc^2(\theta)}\right)+15\left(\dfrac{2}{\sec^2(\theta)}\right)$.

1.4.  $\quad(\cos^2(\theta)-\sin^2(\theta))^2 + 4sin^2(\theta)\cos^2(\theta)$

<!-- 1.5.  $\quad7\cos(90-\theta)\sin(\theta)+7\sin(90-\theta)\cos(\theta)$ -->

<!-- 1.6.  $\quad6\sin(\theta+2\pi)\sin(\theta+4\pi)+6\cos(\theta-2\pi)\cos(\theta-4\pi)$ -->

1.5.  $\quad2\sin(30)\cos(15)+2\cos(30)\sin(15)$

1.6.  $\quad3\cos(45)\cos(15)-3\sin(45)\sin(15)$

1.7.  $\quad\sin(150)+\sin(30)$

1.8. $\quad\cos(150)+\cos(30)$


## Q2 {-}

Simplify the following expressions:

2.1. $\quad\tan(\theta)\cos(-\theta)$

2.2  $\quad\tan(-\theta)\csc(-\theta)\sec(-\theta)$

2.3. $\quad\tan^2(\theta)+\sin^2(\theta)+\cos^2(\theta)$

2.4. $\quad\displaystyle\frac{2\sin(\theta)}{\cos(\theta)(1-\tan^2(\theta))}$

<!-- 2.5. $\quad\sin(90+\theta)-\sin(90-\theta)$ -->

2.5. $\quad\displaystyle\frac{\sin(7\theta)+\sin(3\theta)}{\cos(7\theta)-\cos(3\theta)}$

2.6. $\quad\displaystyle\frac{\sin(5\theta)-\sin(\theta)}{\cos(5\theta)+\cos(\theta)}$
 
## Q3 {-}

Using trigonometric identities, answer the following questions:

3.1. What is the value of $\cos(210^\circ)$?

3.2. What are the values of $\sin(135^\circ)$ and $\sin(225^\circ)$?

3.3. If $\sin(50^\circ)$ has the value $0.766$ (to $3$ decimal places), what is the value of $\cos(130^\circ)$ to three decimal places?

## Q4 {-}

Using trigonometric identities, find **exact** values of the following:

4.1. $\quad\sin(15)$

4.2. $\quad\cos(15)$

4.3. $\quad\tan(15)$

4.4. $\quad\sin(75)$

4.5. $\quad\cos(75)$

4.6. $\quad\tan(75)$




