---
title: "Exploration questions"
author: "Tom Coleman"
abstract-title: Summary
abstract: A selection of questions for the explorations/presentations on the hidden sequences of Pascal's triangle, how to win at cards - combinations and permutations, and making it count - an introduction to the theory of functions.
---

## Q1: The hidden sequences of Pascal's triangle {-}

*Before attempting these questions, you should read [Exploration: The hidden sequences of Pascal's triangle](e-pascalstriangleandgrowth.qmd).*

**1.1.** The 2026 FIFA World Cup is taking place in the USA/Canada/Mexico right now. It has 48 teams, split into 12 groups/leagues of 4, where each team plays each other team in the group once. From there, 32 teams qualify for the knockout stages, leading to the round of 32, round of 16, quarter-finals, semi-finals, third-place play-off and the final.

Work out how many football matches will be played in total at the 2026 FIFA World Cup. 

**1.2.** Fill out the following table investigating growth of the following sequences. 

|  $n$ | $Te_n$ | $n^3$ |  $3^n$ |    $n!$   |     $n^n$     |
|:----:|:-----:|:-----:|:------:|:---------:|:-------------:|
|  $0$ |  0  |    |   |    |     undef     |
|  $1$ |     | | | |  |
|  $2$ |     | | | |  |
|  $3$ |     | | | |  |
|  $4$ |     | | | |  |
|  $5$ |    | | | |  |
|  $6$ |    | | | |  |
|  $7$ |    | | | |  |
|  $8$ |    | | | |  |
|  $9$ |    | | | |  |
| $10$ |    | | | |  |

**1.3.** Modifying the proof that $2^n > n^2$ for $n\geq 4$, prove that $3^n > n^3$ for $n \geq 8$.

## Q2: How to win at cards - combinations and permutations {-}

*Before attempting these questions, you should read [Exploration: How to win at cards - combinations and permutations](e-combinationspermutations.qmd).*

**2.1.** Using the formula from [Exploration: The hidden sequences of Pascal's triangle](e-pascalstriangleandgrowth.qmd), show that the $n$th triangular number is equal to $\displaystyle\binom{n}{2}$.

**2.2.** Using the formula from [Exploration: The hidden sequences of Pascal's triangle](e-pascalstriangleandgrowth.qmd), show that the $n$th tetrahedral number is equal to $\displaystyle\binom{n}{3}$.

**2.3.** Show the following identity for binomial coefficients: $$k\binom{n}{k} = n\binom{n-1}{k-1}$$  (Hint: Think of picking a team of $k$ students from a class of $n$ students in two different ways: one where you pick the team first, then a captain; and one where you pick a captain first, then the rest of the team.)

**2.4.** Work out the probability of getting a straight flush in Texas hold 'em poker. An ace-low straight flush 5 4 3 2 A is permitted, so you should include this in your calculations. You should also remember that an A K Q J 10 straight flush is a royal flush, and so should be excluded from your calculations. 

**2.5.** The UK National Lottery is a twice-weekly draw of 6 numbers out of a possible 59. To win the jackpot, you will need to match all 6 numbers on a single ticket. Work out the odds of winning the UK National Lottery by matching all 6 numbers.

## Q3: Making it count - an introduction to the theory of functions {-}

**3.1.** *Before attempting these questions, you should read [Exploration: Making it count - an introduction to the theory of funcions](e-functionsandcounting.qmd).*

(a) Let $A$, $B$ be sets and let $f: A \to B$ be some function. Suppose there is a function $g : B \to A$ with the property that  $f(g(b)) = b$ for all $b \in B$. Show that $f$ has to be surjective. 

(b) Let $A$, $B$ be sets and let $p: A \to B$ be a function. Suppose there is a function $q : B \to A$ with the property that $q(p(a)) = a$ for all $a \in A$. Show that $p$ has to be injective.

(c) Find an example of functions $f,g$ as in (a) where $f$ is not a bijection.

(d) Find an example of functions $p,q$ as in (b) where $p$ is not a bijection.

(e) Now suppose that $f:A\to B$ is a bijection. Show that there is a function $g:B\to A$ such that $g(f(a)) = a$ for all $a\in A$ and $f(g(b)) = b$ for all $b\in B$.

(f) Finally, suppose that $f:A\to B$ and $g:B\to A$ are functions such that $g(f(a)) = a$ for all $a\in A$ and $f(g(b)) = b$ for all $b\in B$. Prove that $f$ is bijective. 


---

## Version history and licensing {-}

v1.0: initial version created 07/26 by tdhc, originally for the Sutton Trust Summer School 2026.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)