---
title: "Factsheet: Correlation"
author: Jakub Brzozowski
abstract-title: Summary
abstract: An introduction to Correlation.
filters: 
  - shinylive
embed-resources: false
categories:
  - Statistics
  - Probability
draft: true
---

```{r, setup, include = FALSE}
library("webexercises")
```

# What is correlation?

Correlation is a measure that quantifies the strength and the direction (positive / negative) of a relationship between the two random variables (for example: $X$ and $Y$).

## Mathematical definition of correlation

To define Correlation of $X$ and $Y$, you need to first define the **covariance** of these two variables. It is a measure of how these variables change together with one another:

::: callout-note
## Definition of covariance
The covariance between two random variables $X$ and $Y$ is defined to be:

$$Cov(X, Y) = \mathbb{E}((X - \mu_X) (Y - \mu_Y)) = \mathbb{E}(XY) - \mathbb{E}(X)\mathbb{E}(Y)$$

where:

- $X$ is a random variable
- $\mu_X$ is the mean of $X$
- $Y$ is a random variable
- $\mu_Y$ is the mean of $Y$
:::

::::callout-tip
Useful properties of covariance include:

1. Covariance of the variable with itself is equal to that variable's variance: $Cov(X, X) = Var(X)$
2. If two random variables are independent, then their covariance is equal to $0$: Should $X$ and $Y$ be independent, then $Cov(X, Y) = 0$
3. Covariance is linear (?), that is when a random variable is multiplied by a constant, then the covariance is too: $Cov(aX, bY) = ab Cov(X, Y)$, where $a$ and $b$ are some constant numbers. 
::: 

Now, having defined the covariance, which allows us to quantify how these variables change with one another, you can formalize this measure into the correlation.

::: callout-note
## Definition of correlation
The correlation between two random variables $X$ and $Y$ is defined by:

$$\rho(X, Y) = \frac{Cov(X, Y)}{\sqrt{Var(X)Var(Y)}} = \frac{Cov(X, Y)}{\sigma_X\sigma_Y}$$

where:

- $X$ and $Y$ are random variables
- $Cov(X, Y)$ is the covariance between these random variables
- $Var(X)$ is the variance of the random variable $X$
- $Var(Y)$ is the variance of the random variable $Y$
- $\sigma_X$ is the standard deviation of the random variable $X$: ($\sqrt{Var(X)} = \sigma_X$)
- $\sigma_Y$ is the standard deviation of the random variable $Y$: ($\sqrt{Var(Y)} = \sigma_Y$)
:::

::::callout-tip
The main advantage of correlation (in linear applications) over covariance is that it is unit-free, that is: 
$$-1 \leq \rho(X, Y) \leq 1$$
**Properties:**

1. If $\rho(X, Y) > 0$, then $X$ and $Y$ are positively correlated (they both increase at the same time).
2. If $\rho(X, Y) < 0$, then $X$ and $Y$ are negatively correlated (as one of the increases, the other - decreases).
3.If $\rho(X, Y) = 0$, then $X$ and $Y$ are uncorrelated.
:::

:::callout-important
Remember, uncorrelated does not imply that these variables are independent. 
If you know that the variables are independent, then their correlation ($\rho$) is indeed equal to $0$. 
However, if you only know that the two variables' correlation is equal to $0$, you can only infer that there is no linear relationship between them.
In other words correlation only checks for linear relationships between the variables.
:::

::::{.callout-note appearance="simple"}
## Example
Cantor's Confectionery wants to check if the total amount of sunshine on a day ($X$) is correlated with the average amount of customers in the confectionery per minute ($Y$). The Confectionery's statistician after obtaining the raw data finds the following:

$$Var(X) = 0.978$$

$$Var(Y) = 1.43$$
$$Cov(X, Y) = 0.96789$$
they calculate the covariance using the formula provided above:

$$\rho(X, Y) = \frac{Cov(X, Y)}{\sqrt{Var(X)Var(Y)}} = \frac{4.789}{\sqrt{1.43 \cdot 0.978}} = 0.818$$
Therefore, they conclude that the two variables are highly correlated and so the Confectionery may expect high numbers of customers on sunny days.  

:::

:::callout-important
## Correlation does not imply causation
Even if you find out that two variables are highly correlated, it **does not** imply that one of these causes the other to behave this way. For example, customer visits per minute increasing in Cantor's Confectionery on sunny days might not be caused by sunlight itself, but rather higher likelihood of family days out, more tourists in town, or more generally a higher collective mood - all contributing to more customer visits per hour in the confectionery.
:::

# Further reading {-}


[For more information on hypothesis test, please go to Guide: Hypothesis testing](../studyguides/hypothesistesting.qmd)
[For more information on t-test, please go to Guide: Introduction to t-testing](../studyguides/t-testing.qmd)
[For more information on ANOVA, please go to Guide: ANOVA](../studyguides/anova.qmd)
[For more information on linear regression, please go to Guide: Linear regression](../studyguides/linearregression.qmd)

## Version history {-}

v1.0: initial version created 04/26 by Jakub Brzozowski as a part of a University of St Andrews VIP project.

  
[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)



