---
title: "Factsheet: Confidence intervals"
author: "Millie Harris"
abstract-title: Summary
abstract: This factsheet summarises key information on constructing and understanding confidence intervals using the normal distribution.
draft: true
---

*Before reading this factsheet, it is recommended that you read* [Guide: Introduction to confidence intervals](confidenceintervals.qmd)

## What is a confidence interval?

A confidence interval is a **range of values** which contains the true estimate with certain confidence, in repeated sampling.

::: callout-note
## How to construct

$$ [\bar{x} \pm Z_{\frac{\alpha}{2}} \frac{\sigma}{n}] $$

-   $\bar{x} =$ the sample mean

-   $Z_{\frac{\alpha}{2}} =$ the Z value

-   $\sigma =$ the standard deviation

-   $n =$ population total
:::

# Confidence levels

Every CI has a confidence level (CL).

A confidence level (CL) suggests that if you were to repeat the study many times, you would expect the true estimate to fall within CL$\%$ of the results.

::: callout-caution
## Caution!

This does not mean there is a $95\%$ chance the range of values contains the true estimate. Instead, if you were to **repeat the study** many times, with a CL of $95\%$ - you would **expect** $95\%$ of the CIs to contain the true estimate.
:::

# $Z$ values for commonly used confidence levels

This is a summary table of commonly used CL and their $Z$ values, following a normal distribution.

| Confidence level (CL) | $\frac{\alpha}{2}$ | $Z_{\frac{\alpha}{2}}$ |
|-----------------------|--------------------|------------------------|
| 0.80 = 80%            | 0.10               | 1.282                  |
| 0.85 = 85%            | 0.075              | 1.440                  |
| 0.90 = 90%            | 0.05               | 1.645                  |
| 0.95 = 95%            | 0.025              | 1.960                  |
| 0.99 = 99%            | 0.005              | 2.576                  |

# Further reading

[For more questions on the subject, please go to Questions: Confidence Intervals.](../questions/qs-confidenceintervals.qmd)

# Version history

v1.0: initial version created 12/06 by Millie Harris as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
