---
title: "Factsheet: List of integrals"
author: "Tom Coleman"
abstract-title: Summary
abstract: A list of common (and some uncommon) integrals of functions.
categories:
  - Mathematics
---

Throughout, $a,k$ are real numbers and $C$ is the constant of integration.

## Antiderivatives of polynomial, rational, exponential, logarithmic functions {-}

::: {.content-hidden when-format="pdf"}

| function | antiderivative w.r.t $x$ | notes |
|:-----------:|:---------------------------:|:-------------:|
| $a$ | $ax + C$ |  |
| $ax^n$ | $\dfrac{ax^{n+1}}{n+1} + C$ | $n \in\mathbb{R},\, n \neq -1$ |
| $ax^{-1}$ | $a\ln|x| + C$ |  |
| $\dfrac{a}{bx + c}$ | $\dfrac{a}{b}\ln|bx + c| + C$ | $b,c\in \mathbb{R}$ |
| $\dfrac{a}{(bx + c)^n}$ | $\dfrac{a(bx + c)^{1-n}}{b(1-n)} + C$ | $b,c\in \mathbb{R}$ |
| $ae^{kx}$ | $\dfrac{a}{k}e^{kx} + C$ |  | 
| $a\ln(kx)$ | $ax\ln|kx| - ax + C$ | | 

:::

::: {.content-visible when-format="pdf"}

| function | antiderivative w.r.t $x$ | notes |
|:-----------:|:---------------------------|:-------------:|
| $a$ | $ax + C$ |  |
|   |   |   |
| $ax^n$ | $\dfrac{ax^{n+1}}{n+1} + C$ | $n \in\mathbb{R},\, n \neq -1$ |
|   |   |   |
| $ax^{-1}$ | $a\ln|x| + C$ |  |
|   |   |   |
| $\frac{a}{bx + c}$ | $\dfrac{a}{b}\ln|bx + c| + C$ | $b,c\in \mathbb{R}$ |
|   |   |   |
| $\frac{a}{(bx + c)^n}$ | $\dfrac{a(bx + c)^{1-n}}{b(1-n)} + C$ | $b,c\in \mathbb{R}$ |
|   |   |   |
| $ae^{kx}$ | $\dfrac{a}{k}e^{kx} + C$ |  | 
| $a\ln(kx)$ | $ax\ln|kx| - ax + C$ | | 

:::

## Antiderivatives of trigonometric functions {-}

::: {.content-hidden when-format="pdf"}

| function | antiderivative w.r.t $x$ | 
|:-----------:|:---------------------------|
| $a\sin(kx)$ | $-\dfrac{a}{k}\cos(kx) + C$ | 
| $a\cos(kx)$ | $\dfrac{a}{k}\sin(kx) + C$ | 
| $a\tan(kx)$ | $\dfrac{a}{k}\ln|\sec(kx)| + C$ | 
| $a\cot(kx)$ | $\dfrac{a}{k}\ln|\sin(kx)| + C$ | 
| $a\sec(kx)$ | $\dfrac{a}{k}\ln\left|\tan(kx) + \sec(kx)\right| + C$ | 
| $a\csc(kx)$ | $\dfrac{a}{k}\left(\ln\left|\sin\left(\frac{kx}{2}\right)\right| -\ln\left|\cos\left(\frac{kx}{2}\right)\right|\right) + C$ | 

:::

::: {.content-visible when-format="pdf"}

| function | antiderivative w.r.t $x$ | 
|:-----------:|:---------------------------|
| $a\sin(kx)$ | $-\dfrac{a}{k}\cos(kx) + C$ | $a,k\in\mb{R}$ 
|   |   |
| $a\cos(kx)$ | $\dfrac{a}{k}\sin(kx) + C$ | $a,k\in\mb{R}$ 
|   |   |
| $a\tan(kx)$ | $\dfrac{a}{k}\ln|\sec(kx)| + C$ | 
|   |   |
| $a\cot(kx)$ | $\dfrac{a}{k}\ln|\sin(kx)| + C$ | 
|   |   | 
| $a\sec(kx)$ | $\dfrac{a}{k}\ln\left|\tan(kx) + \sec(kx)\right| + C$ | 
|   |   | 
| $a\csc(kx)$ | $\dfrac{a}{k}\left(\ln\left|\sin\left(\frac{kx}{2}\right)\right| -\ln\left|\cos\left(\frac{kx}{2}\right)\right|\right) + C$ | 

:::

## Antiderivatives of some hyperbolic functions {-}

::: {.content-hidden when-format="pdf"}

| function | antiderivative w.r.t $x$ |
|:-----------:|:---------------------------|
| $a\sinh(kx)$ | $\dfrac{a}{k}\cosh(kx) + C$ |  
| $a\cosh(kx)$ | $\dfrac{a}{k}\sinh(kx) + C$ |
| $a\tanh(kx)$ | $\dfrac{a}{k}\ln|\cosh(kx)| + C$ | 
| $a\coth(kx)$ | $\dfrac{a}{k}\ln|\sinh(kx)| + C$ | 

:::

::: {.content-visible when-format="pdf"}

| function | antiderivative w.r.t $x$ |
|:-----------:|:---------------------------|
| $a\sinh(kx)$ | $\dfrac{a}{k}\cosh(kx) + C$ |  
|   |   | 
| $a\cosh(kx)$ | $\dfrac{a}{k}\sinh(kx) + C$ | 
|   |   |
| $a\tanh(kx)$ | $\dfrac{a}{k}\ln|\cosh(kx)| + C$ | 
|   |   | 
| $a\coth(kx)$ | $\dfrac{a}{k}\ln|\sinh(kx)| + C$ | 

:::

## Standard forms that integrate to inverse trigonometric/hyperbolic functions {-}

::: {.content-visible when-format="pdf"}

| function | antiderivative w.r.t $x$ |
|:------------:|:--------------------|
| $\dfrac{a}{\sqrt{1-k^2x^2}}$ | $\dfrac{a}{k}\sin^{-1}(kx) + C$ |  
|   |   |
| $-\dfrac{a}{\sqrt{1-k^2x^2}}$ | $\dfrac{a}{k}\cos^{-1}(kx) + C$ | 
|   |   | 
| $\dfrac{a}{1+k^2x^2}$ | $\dfrac{a}{k}\tan^{-1}(kx) + C$ | 
|   |   | 
| $\dfrac{a}{\sqrt{1+k^2x^2}}$ | $\dfrac{a}{k}\sinh^{-1}(kx) + C$ |
|   |   | 
| $\dfrac{a}{\sqrt{k^2x^2 - 1}}$ | $\dfrac{a}{k}\cosh^{-1}(kx) + C$ | 
|   |   |
| $\dfrac{a}{\sqrt{1-k^2x^2}}$ | $\dfrac{a}{k}\tanh^{-1}(kx) + C$ |  

:::

::: {.content-hidden when-format="pdf"}

| function | antiderivative w.r.t $x$ | 
|:------------:|:--------------------|
| $\dfrac{a}{\sqrt{1-k^2x^2}}$ | $\dfrac{a}{k}\sin^{-1}(kx) + C$ |  
| $-\dfrac{a}{\sqrt{1-k^2x^2}}$ | $\dfrac{a}{k}\cos^{-1}(kx) + C$ |  
| $\dfrac{a}{1+k^2x^2}$ | $\dfrac{a}{k}\tan^{-1}(kx) + C$ |  
| $\dfrac{a}{\sqrt{1+k^2x^2}}$ | $\dfrac{a}{k}\sinh^{-1}(kx) + C$ |  
| $\dfrac{a}{\sqrt{k^2x^2 - 1}}$ | $\dfrac{a}{k}\cosh^{-1}(kx) + C$ |  
| $\dfrac{a}{\sqrt{1-k^2x^2}}$ | $\dfrac{a}{k}\tanh^{-1}(kx) + C$ |  

:::

 


---

---

# Further reading {-}

For more about where these came from, please see [Guide: Introduction to integration](../studyguides/introtointegration.qmd) and [Proof sheet: Antiderivatives of other common functions].

## Version history {-}

v1.0: created in 08/25 by tdhc. 

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
