---
title: "Factsheet: List of derivatives"
author: "Tom Coleman"
abstract-title: Summary
abstract: A list of common (and some uncommon) derivatives of functions.
categories:
  - Mathematics
---

Throughout, $a,k$ are real numbers.

## Derivatives of polynomial, exponential and logarithmic functions {-}

::: {.content-hidden when-format="pdf"}

| function | derivative w.r.t $x$ | notes |
|:------------:|:--------------------:|:---------------------:|
| $c$ | $0$ | $c\in\mathbb{R}$ |
| $mx + c$ | $m$ | $m,c\in\mathbb{R}$ |
| $x^\alpha$ | $\alpha x^{\alpha-1}$ | $\alpha \in\mathbb{R}, \alpha \neq 0$ |
| $ae^{kx}$ | $ake^{kx}$ | |
| $a\ln(kx)$ | $\dfrac{a}{x}$ |   | 
| $ac^{kx}$ | $akc^{kx}\ln(c)$ | $c \in\mathbb{R}, c > 0$ constant |
| $a\log_c(kx)$ | $\dfrac{a}{x\ln(c)}$ | $c \in\mathbb{R}, c > 1$ constant |

:::

::: {.content-visible when-format="pdf"}

| function | derivative w.r.t $x$ | notes |
|:------------:|:--------------------:|:---------------------:|
| $c$ | $0$ | $c\in\mathbb{R}$ |
| $mx + c$ | $m$ | $m,c\in\mathbb{R}$ |
| $x^\alpha$ | $\alpha x^{\alpha-1}$ | $\alpha \in\mathbb{R}, \alpha \neq 0$ |
| $ae^{kx}$ | $ake^{kx}$ | |
|   |   |   |
| $a\ln(kx)$ | $\dfrac{a}{x}$ |   | 
|   |   |   |
| $ac^{kx}$ | $akc^{kx}\ln(b)$ | $c \in\mathbb{R}, c > 0$ constant |
|   |   |   |
| $a\log_c(kx)$ | $\dfrac{a}{x\ln(c)}$ | $c \in\mathbb{R}, c > 1$ constant |

:::

## Derivatives of trigonometric functions {-}

| function | derivative w.r.t $x$ |
|:------------:|:--------------------|
| $a\sin(kx)$ | $ak\cos(kx)$ | 
| $a\cos(kx)$ | $-ak\sin(kx)$ |  
| $a\tan(kx)$ | $ak\sec^2(kx)$ | 
| $a\cot(kx)$ | $-ak\csc^2(kx)$ | 
| $a\sec(kx)$ | $ak\sec(kx)\tan(kx)$ | 
| $a\csc(kx)$ |  $-ak\csc(kx)\cot(kx)$ | 

## Derivatives of inverse trigonometric functions {-}

::: {.content-hidden when-format="pdf"}

| function | derivative w.r.t $x$ | notes |
|:------------:|:--------------------:|:---------------------:|
| $a\sin^{-1}(kx)$ | $\displaystyle\frac{ak}{\sqrt{1-k^2x^2}}$ | valid for $x\in\left(-\frac{1}{k},\frac{1}{k}\right)$ |
| $a\cos^{-1}(kx)$ | $\displaystyle\frac{-ak}{\sqrt{1-k^2x^2}}$ | valid for $x\in\left(-\frac{1}{k},\frac{1}{k}\right)$ |
| $a\tan^{-1}(kx)$ | $\displaystyle\frac{ak}{1+k^2x^2}$ | valid for $x\in\mathbb{R}$ |
| $a\cot^{-1}(kx)$ | $\displaystyle\frac{-ak}{1+k^2x^2}$ | valid for $x\in\mathbb{R}$ | 
| $a\sec^{-1}(kx)$ | $\displaystyle\frac{a}{|x|\sqrt{k^2x^2 - 1}}$ | valid for  $x\in\mathbb{R}\smallsetminus\left(-\frac{1}{k},\frac{1}{k}\right)$ |
| $a\csc^{-1}(kx)$ |  $\displaystyle\frac{-a}{|x|\sqrt{k^2x^2 - 1}}$ | valid for  $x\in\mathbb{R}\smallsetminus\left(-\frac{1}{k},\frac{1}{k}\right)$ |

:::

::: {.content-visible when-format="pdf"}

| function | derivative w.r.t $x$ | notes |
|:------------:|:--------------------:|:---------------------:|
| $a\sin^{-1}(kx)$ | $\displaystyle\frac{ak}{\sqrt{1-k^2x^2}}$ | valid for $x\in\left(-\frac{1}{k},\frac{1}{k}\right)$ |
|   |   |   |
| $a\cos^{-1}(kx)$ | $\displaystyle\frac{-ak}{\sqrt{1-k^2x^2}}$ | valid for $x\in\left(-\frac{1}{k},\frac{1}{k}\right)$ |
|   |   |   |
| $a\tan^{-1}(kx)$ | $\displaystyle\frac{ak}{1+k^2x^2}$ | valid for $x\in\mathbb{R}$ |
|   |   |   |
| $a\cot^{-1}(kx)$ | $\displaystyle\frac{-ak}{1+k^2x^2}$ | valid for $x\in\mathbb{R}$ | 
|   |   |   |
| $a\sec^{-1}(kx)$ | $\displaystyle\frac{a}{|x|\sqrt{k^2x^2 - 1}}$ | valid for  $x\in\mathbb{R}\smallsetminus\left(-\frac{1}{k},\frac{1}{k}\right)$ |
|   |   |   |
| $a\csc^{-1}(kx)$ |  $\displaystyle\frac{-a}{|x|\sqrt{k^2x^2 - 1}}$ | valid for  $x\in\mathbb{R}\smallsetminus\left(-\frac{1}{k},\frac{1}{k}\right)$ |

:::

## Derivatives of hyperbolic functions {-}


| function | derivative w.r.t $x$ |
|:------------:|:--------------------|
| $a\sinh(kx)$ | $ak\cosh(kx)$ |  
| $a\cosh(kx)$ | $ak\sinh(kx)$ | 
| $a\tanh(kx)$ | $ak\,\textrm{sech}^2(kx)$ | 
| $a\,\textrm{coth}(kx)$ | $-ak\,\textrm{csch}^2(kx)$ | 
| $a\,\textrm{sech}(kx)$ | $-ak\,\textrm{sech}(kx)\,\textrm{tanh}(kx)$ | 
| $a\,\textrm{csch}(kx)$ |  $-ak\,\textrm{csch}(kx)\,\textrm{coth}(kx)$ | 

## Derivatives of inverse hyperbolic functions {-}

Throughout, $a,k$ are real numbers.

::: {.content-hidden when-format="pdf"}

| function | derivative w.r.t $x$ | notes |
|:----------:|:----------------------------------:|:------------:|
| $a\sinh^{-1}(kx)$ | $\dfrac{ak}{\sqrt{1+k^2x^2}}$ |  |
| $a\cosh^{-1}(kx)$ | $\dfrac{ak}{\sqrt{k^2x^2 - 1}}$ | $a,k,x$ positive |
| $a\tanh^{-1}(kx)$ | $\dfrac{ak}{1-k^2x^2}$ | |
| $a\,\textrm{coth}^{-1}(kx)$ | $\dfrac{ak}{1-k^2x^2}$ | | 
| $a\,\textrm{sech}^{-1}(kx)$ | $-\dfrac{ak}{x\sqrt{1-k^2x^2}}$ | $a,k,x$ positive | 
| $a\,\textrm{csch}^{-1}(kx)$ |  $-\dfrac{ak}{|x|\sqrt{k^2x^2+1}}$ | | 

:::

::: {.content-visible when-format="pdf"}

| function | derivative w.r.t $x$ | notes |
|:-------------:|:----------------------------------:|:------------:|
| $a\sinh^{-1}(kx)$ | $\dfrac{ak}{\sqrt{1+k^2x^2}}$ |  |
|   |   |   |
| $a\cosh^{-1}(kx)$ | $\dfrac{ak}{\sqrt{k^2x^2 - 1}}$ | $a,k,x$ positive |
|   |   |   |
| $a\tanh^{-1}(kx)$ | $\dfrac{ak}{1-k^2x^2}$ | |
|   |   |   |
| $a\,\textrm{coth}^{-1}(kx)$ | $\dfrac{ak}{1-k^2x^2}$ | | 
|   |   |   |
| $a\,\textrm{sech}^{-1}(kx)$ | $-\dfrac{ak}{x\sqrt{1-k^2x^2}}$ | $a,k,x$ positive | 
|   |   |   |
| $a\,\textrm{csch}^{-1}(kx)$ |  $-\dfrac{ak}{|x|\sqrt{k^2x^2+1}}$ | | 

:::

---

---

# Further reading {-}

For more about where these came from, please see [Guide: Introduction to differentiation and the derivative](../studyguides/introtodifferentiation.qmd) and [Proof sheet: Derivatives of other common functions].

## Version history {-}

v1.0: created in 08/25 by tdhc. 

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
