---
title: "Factsheet: Hyperbolic identities"
author: "Tom Coleman"
abstract-title: Summary
abstract: A list of hyperbolic trig identities. 
categories:
  - Mathematics
---

*These are common definitions and identities for hyperbolic functions. For derivatives and antiderivatives, please see [Factsheet: List of derivatives](f-commonderivatives.qmd) and [Factsheet: List of integrals](f-commonintegrals.qmd) respectively.*

## Definitions of hyperbolic functions {-}

For all real numbers $x$:

$$\begin{aligned} 
\cosh(x) &= \frac{e^x + e^{-x}}{2} \\[0.5em] 
\sinh(x) &= \frac{e^x - e^{-x}}{2} \\[0.5em] 
\tanh(x) &= \frac{\sinh(x)}{\cosh(x)} = \frac{e^x - e^{-x}}{e^x + e^{-x}} \\[0.5em] 
\textrm{coth}(x) &= \frac{1}{\tanh(x)} = \frac{\cosh(x)}{\sinh(x)} = \frac{e^x + e^{-x}}{e^x - e^{-x}} \\[0.5em] 
\textrm{sech}(x) &= \frac{1}{\cosh(x)} = \frac{2}{e^x + e^{-x}} \\[0.5em] 
\textrm{csch}(x) &= \frac{1}{\sinh(x)} = \frac{2}{e^x - e^{-x}}
\end{aligned}$$

## Hyperbolic identities {-}

**Pythagorean formulas**

For all real numbers $x$:

$$\begin{aligned}
\cosh^2(x) - \sinh^2(x) &= 1 \\[0.5em]
1 - \tanh^2(x) &= \textrm{sech}^2(x) \\[0.5em]
\coth^2(x) - 1 &= \textrm{csch}^2(x)
\end{aligned}$$


**Sum and difference formulas**

For all real numbers $x,y$:

$$\begin{aligned}
\cosh(x + y) &= \cosh(x)\cosh(y) + \sinh(x)\sinh(y) \\[0.5em]
\cosh(x - y) &= \cosh(x)\cosh(y) - \sinh(x)\sinh(y) \\[0.5em]
\sinh(x + y) &= \sinh(x)\cosh(y) + \cosh(x)\sinh(y) \\[0.5em]
\sinh(x - y) &= \sinh(x)\cosh(y) - \cosh(x)\sinh(y) \\[0.5em]
\tanh(x + y) &= \frac{\tanh(x) + \tanh(y)}{1 + \tanh(x)\tanh(y)}\\[0.5em]
\tanh(x - y) &= \frac{\tanh(x) - \tanh(y)}{1 - \tanh(x)\tanh(y)}
\end{aligned}$$
 

**Double angle formulas**

For all real numbers $x$:

$$\begin{aligned}
\cosh(2x) &= \cosh^2(x) + \sinh^2(x) \\[0.5em]
\sinh(2x) &= 2\sinh(x)\cosh(x) \\[0.5em]
\tanh(2x) &= \frac{2\tanh(x)}{1 + \tanh^2(x)} 
\end{aligned}$$

## Definitions of inverse hyperbolic functions {-}

::: {.content-hidden when-format="pdf"}

| function | logarithmic definition | validity |
|:------------:|:--------------------:|:---------------------:|
| $\sinh^{-1}(x)$ | $\ln\left(x + \sqrt{x^2 + 1}\right)$ |  |
| $\cosh^{-1}(x)$ | $\ln\left(x + \sqrt{x^2 - 1}\right)$ | $x\geq 1$ |
| $\tanh^{-1}(x)$ | $\dfrac{1}{2}\ln\left(\dfrac{1+x}{1-x}\right)$ | $|x| < 1$ |
| $\textrm{coth}^{-1}(x)$ | $\dfrac{1}{2}\ln\left(\dfrac{x+1}{x-1}\right)$ | $|x| > 1$ | 
| $\textrm{sech}^{-1}(x)$ | $\ln\left(\dfrac{1}{x} + \sqrt{\dfrac{1}{x^2}-1}\right)$ | $0< x \leq 1$ | 
| $\textrm{csch}^{-1}(x)$ |  $\ln\left(\dfrac{1}{x} + \sqrt{\dfrac{1}{x^2} +1}\right)$ | $x\neq 0$ | 

:::

::: {.content-visible when-format="pdf"}

| function | logarithmic definition | validity |
|:------------:|:--------------------:|:---------------------:|
| $\sinh^{-1}(x)$ | $\ln\left(x + \sqrt{x^2 + 1}\right)$ |  |
|   |   |   |
| $\cosh^{-1}(x)$ | $\ln\left(x + \sqrt{x^2 - 1}\right)$ | $x\geq 1$ |
|   |   |   |
| $\tanh^{-1}(x)$ | $\dfrac{1}{2}\ln\left(\dfrac{1+x}{1-x}\right)$ | $|x| < 1$ |
|   |   |   |
| $\textrm{coth}^{-1}(x)$ | $\dfrac{1}{2}\ln\left(\dfrac{x+1}{x-1}\right)$ | $|x| > 1$ | 
|   |   |   |
| $\textrm{sech}^{-1}(x)$ | $\ln\left(\dfrac{1}{x} + \sqrt{\dfrac{1}{x^2}-1}\right)$ | $0< x \leq 1$ | 
|   |   |   |
| $\textrm{csch}^{-1}(x)$ |  $\ln\left(\dfrac{1}{x} + \sqrt{\dfrac{1}{x^2} +1}\right)$ | $x\neq 0$ | 

:::

---

---

## Version history {-}

v1.0: created in 08/25 by tdhc. 

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
