---
title: "Factsheet: Simple random sampling"
author: "Millie Harris"
abstract-title: Summary
abstract: This factsheet summarises simple random sampling {srs} and defines its expectation and variance.
draft: true
---

*Before reading this factsheet, it is recommended that you read* \[Guide: Introduction to sampling\]

## Simple random sampling {srs; $\bar{y}$}

In simple random sampling, everything in the population has **equal probability** of being chosen. Also, every possible sample has **equal probability** of being chosen.

::: callout-note
## Definition: Probability of selecting a particular sample under srs

If a population has $N$ individuals and you take a sample size of $n$, then:

$P$(Selecting a particular sample) is

$$\frac{1}{\binom{N}{n}}$$ or

$$\binom{n}{N}$$

where:

$$\binom{n}{N} = \frac{n!}{N!(n - N)!}$$
:::

In srs, $\bar{y}$ is the sample mean of $y$, such that $\bar{y}$ = $\frac{1}{n} \sum_{i = 1}^{n} y_i$ and it is an unbiased estimator for the population mean $\mu$.

This table contains key properties of $\bar{y}$ for srs:

|  |  |
|------------------------------------|------------------------------------|
| Expectation = E\[$\bar{y}$\] | $\mu$ |
| Variance = Var\[$\bar{y}$\] | $(1 - f) \frac{S^2}{n}$ |
| Confidence interval (CI) | $\bar{y} \pm Z_{\frac{\alpha}{2}} \frac{s}{\sqrt{n}}\sqrt{(1 - f)}$ |

where,

-   $S^2$ = Finite population variance of y = $\frac{1}{(N - 1)}\sum_{i = 1}^{n} (y_i - \mu)^2$

-   $f$ = Sampling fraction = $\frac{n}{N}$

# Further reading

# Version history

v1.0: initial version created 12/06 by Millie Harris as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
