---
title: "Factsheet: Trigonometric identities (degrees)"
author: "Tom Coleman"
abstract-title: Summary
abstract: A list of trigonometric identities with angles measured in degrees. 
categories:
  - Mathematics
---

*The main study guide for this factsheet is [Guide: Trigonometric identities (degrees)](../studyguides/trigonometricidentities-degrees.qmd). If you would like to know more about these, please read the guide.*

*This factsheet measures angles in degrees. For the associated factsheet measuring angles in radians, please go to [Factsheet: Trigonometric identities (radians)](f-trigonometricidentities-radians.qmd).*

## Trigonometric identities {-}

**Periodicity and parity**

For all angles $\theta$ and for all whole numbers $k\in\mathbb{Z}$:

$$\begin{aligned} \cos(-\theta) &= \cos(\theta) \\[0.25em] \sin(-\theta) &= -\sin(\theta) \\[0.25em] \tan(-\theta) &= -\tan(\theta) \\[0.25em] \cos(\theta + 360k) &= \cos(\theta) \\[0.25em] \sin(\theta + 360k) &= \sin(\theta) \\[0.25em] \tan(\theta + 180k) &= \tan(\theta) \end{aligned}$$

 

**Pythagorean formulas**

For all angles $\theta$
$$\begin{aligned}
\cos^2(\theta) + \sin^2(\theta) &= 1 \\[0.5em]
1 + \tan^2(\theta) &= \sec^2(\theta) \\[0.5em]
\cot^2(\theta) + 1 &= \csc^2(\theta)
\end{aligned}$$


**Sum and difference formulas**

For all angles $\alpha,\beta$:

$$\begin{aligned}
\cos(\alpha + \beta) &= \cos(\alpha)\cos(\beta) - \sin(\alpha)\sin(\beta) \\[0.5em]
\cos(\alpha - \beta) &= \cos(\alpha)\cos(\beta) + \sin(\alpha)\sin(\beta) \\[0.5em]
\sin(\alpha + \beta) &= \sin(\alpha)\cos(\beta) + \cos(\alpha)\sin(\beta) \\[0.5em]
\sin(\alpha - \beta) &= \sin(\alpha)\cos(\beta) - \cos(\alpha)\sin(\beta) \\[0.5em]
\tan(\alpha + \beta) &= \frac{\tan(\alpha) + \tan(\beta)}{1 - \tan(\alpha)\tan(\beta)}\\[0.5em]
\tan(\alpha - \beta) &= \frac{\tan(\alpha) - \tan(\beta)}{1 + \tan(\alpha)\tan(\beta)}
\end{aligned}$$
 

**Double angle formulas**

For all angles $\theta$:

$$\begin{aligned}
\cos(2\theta) &= \cos^2(\theta) - \sin^2(\theta) \\[0.5em]
\sin(2\theta) &= 2\sin(\theta)\cos(\theta) \\[0.5em]
\tan(2\theta) &= \frac{2\tan(\theta)}{1 - \tan^2(\theta)} 
\end{aligned}$$

 

**Shift formulas**

For all angles $\theta$:

$$\begin{aligned}
\cos\left(\theta + 90\right) &= -\sin(\theta) \\[0.5em]
\cos\left(\theta - 90\right) &= \sin(\theta) \\[0.5em]
\sin\left(\theta + 90\right) &= \cos(\theta) \\[0.5em]
\sin\left(\theta - 90\right) &= -\cos(\theta) \\[0.5em]
\cos\left(\theta \pm 180\right) &= -\cos(\theta) \\[0.5em]
\sin\left(\theta \pm 180\right) &= -\sin(\theta) \\[0.5em]
\sin\left(180 - \theta\right) &= \sin(\theta) \\[0.5em]
\cos\left(180 - \theta\right) &= -\cos(\theta)
\end{aligned}$$

**Sine and cosine rules**

For a triangle with corners $A,B,C$, angles $\alpha$, $\beta$, $\gamma$ respectively at those corners, and sides $a,b,c$ opposite their respective corners, the **sine rule** is

$$\frac{\sin(\alpha)}{a} = \frac{\sin(\beta)}{b} = \frac{\sin(\gamma)}{c}$$

and the **cosine rule** is $$a^2 = b^2 + c^2 - 2bc\cos(\alpha).$$

**Common values of trigonometric functions**

::: {.content-hidden when-format="pdf"}

| Angle $\theta$ | $0$ | $30$ | $45$ | $60$ | $90$ | $120$ | $135$ | $150$ | $180$ |
|:--------------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| $\sin(\theta)$ | $0$ | $\dfrac{1}{2}$ | $\dfrac{\sqrt{2}}{2}$ | $\dfrac{\sqrt{3}}{2}$ | $1$ | $\dfrac{\sqrt{3}}{2}$ | $\dfrac{\sqrt{2}}{2}$ | $\dfrac{1}{2}$ | $0$ |
| $\cos(\theta)$ | $1$ | $\dfrac{\sqrt{3}}{2}$ | $\dfrac{\sqrt{2}}{2}$ | $\dfrac{1}{2}$ | $0$ | $-\dfrac{1}{2}$ | $-\dfrac{\sqrt{2}}{2}$ | $-\dfrac{\sqrt{3}}{2}$ | $-1$ |
| $\tan(\theta)$ | $0$ | $\dfrac{1}{\sqrt{3}}$ | $1$ | $\sqrt{3}$ | undef. | $-\sqrt{3}$ | $-1$ | $-\dfrac{1}{\sqrt{3}}$ | $0$ |

:::

::: {.content-visible when-format="pdf"}

| Angle $\theta$ | $0$ | $30$ | $45$ | $60$ | $90$ | $120$ | $135$ | $150$ | $180$ |
|:--------------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| $\sin(\theta)$ | $0$ | $\dfrac{1}{2}$ | $\dfrac{\sqrt{2}}{2}$ | $\dfrac{\sqrt{3}}{2}$ | $1$ | $\dfrac{\sqrt{3}}{2}$ | $\dfrac{\sqrt{2}}{2}$ | $\dfrac{1}{2}$ | $0$ |
|   |   |   |   |   |   |   |   |   |   |
| $\cos(\theta)$ | $1$ | $\dfrac{\sqrt{3}}{2}$ | $\dfrac{\sqrt{2}}{2}$ | $\dfrac{1}{2}$ | $0$ | $-\dfrac{1}{2}$ | $-\dfrac{\sqrt{2}}{2}$ | $-\dfrac{\sqrt{3}}{2}$ | $-1$ |
|   |   |   |   |   |   |   |   |   |   |
| $\tan(\theta)$ | $0$ | $\dfrac{1}{\sqrt{3}}$ | $1$ | $\sqrt{3}$ | undef. | $-\sqrt{3}$ | $-1$ | $-\dfrac{1}{\sqrt{3}}$ | $0$ |

:::

<!-- | Angle $\theta$ | $0$ | $-\dfrac{\pi}{6}$ | $-\dfrac{\pi}{4}$ | $-\dfrac{\pi}{3}$ | $-\dfrac{\pi}{2}$ | $-\dfrac{2\pi}{3}$ | $-\dfrac{3\pi}{4}$ | $-\dfrac{5\pi}{6}$ | $-\pi$ | -->
<!-- |:--------------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:| -->
<!-- | $\sin\theta$ | $0$ | $-\dfrac{1}{2}$ | $-\dfrac{\sqrt{2}}{2}$ | $-\dfrac{\sqrt{3}}{2}$ | $-1$ | $-\dfrac{\sqrt{3}}{2}$ | $-\dfrac{\sqrt{2}}{2}$ | $-\dfrac{1}{2}$ | $0$ | -->
<!-- | $\cos\theta$ | $1$ | $\dfrac{\sqrt{3}}{2}$ | $\dfrac{\sqrt{2}}{2}$ | $\dfrac{1}{2}$ | $0$ | $-\dfrac{1}{2}$ | $-\dfrac{\sqrt{2}}{2}$ | $-\dfrac{\sqrt{3}}{2}$ | $-1$ | -->
<!-- | $\tan\theta$ | $0$ | $-\dfrac{1}{\sqrt{3}}$ | $-1$ | $-\sqrt{3}$ | undef. | $\sqrt{3}$ | $1$ | $\dfrac{1}{\sqrt{3}}$ | $0$ | -->

---

---

## Version history {-}

v1.0: created in 08/25 by tdhc. 

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
