---
title: "Answers: Arithmetic on numerical fractions"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on arithmetic on numerical fractions.
draft: true
---

*These are the answers to [Questions: Arithmetic on numerical fractions](../questions/qs-arithmeticonnumericalfractions.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {.unnumbered}

1.1. $\displaystyle \quad \dfrac{1}{2}$

1.2. $\displaystyle \quad \dfrac{3}{7}$

1.3. $\displaystyle \quad -\dfrac{1}{5}$

1.4. $\displaystyle \quad \dfrac{1}{2}$

1.5. $\displaystyle \quad \dfrac{1}{4}$

1.6. $\displaystyle \quad \dfrac{1}{2}$

1.7. $\displaystyle \quad \dfrac{1}{2}$

1.8. $\displaystyle \quad \dfrac{4}{5}$

1.9. $\displaystyle \quad \dfrac{5}{6}$

1.10. $\displaystyle \quad \dfrac{7}{8}$

1.11. $\displaystyle \quad \dfrac{7}{20}$

1.12. $\displaystyle \quad \dfrac{1}{12}$

1.13. $\displaystyle \quad \dfrac{5}{6}$

1.14. $\displaystyle \quad -\dfrac{13}{20}$

1.15. $\displaystyle \quad \dfrac{25}{14}$

## Q2 {.unnumbered}

2.1. $\displaystyle \quad \dfrac{1}{12}$

2.2. $\displaystyle \quad \dfrac{6}{35}$

2.3. $\displaystyle \quad 6$

2.4. $\displaystyle \quad \dfrac{1}{6}$

2.5. $\displaystyle \quad \dfrac{3}{5}$

2.6. $\displaystyle \quad -\dfrac{3}{28}$

2.7. $\displaystyle \quad 4$

2.8. $\displaystyle \quad \dfrac{10}{3}$

2.9. $\displaystyle \quad -\dfrac{14}{15}$

2.10. $\displaystyle \quad -\dfrac{3}{4}$

2.11. $\displaystyle \quad \dfrac{2}{13}$

2.12. $\displaystyle \quad \dfrac{3}{8}$

## Q3 {.unnumbered}

3.1. $\displaystyle \quad 2$

3.2. $\displaystyle \quad \dfrac{8}{15}$

3.3. $\displaystyle \quad \dfrac{3}{16}$

3.4. $\displaystyle \quad \dfrac{1}{6}$

3.5. $\displaystyle \quad 20$

3.6. $\displaystyle \quad \dfrac{3}{2}$

3.7. $\displaystyle \quad -\dfrac{5}{6}$

3.8. $\displaystyle \quad \dfrac{2}{11}$

3.9. $\displaystyle \quad -\dfrac{3}{4}$

3.10. $\displaystyle \quad -\dfrac{4}{3}$

3.11. $\displaystyle \quad \dfrac{3}{8}$

3.12. $\displaystyle \quad \dfrac{1}{14}$

## Q4 {.unnumbered}

4.1. $\displaystyle \quad \dfrac{7}{2}$

4.2. $\displaystyle \quad \dfrac{9}{4}$

4.3. $\displaystyle \quad 3$

4.4. $\displaystyle \quad 4$

4.5. $\displaystyle \quad \dfrac{49}{12}$

4.6. $\displaystyle \quad \dfrac{19}{8}$

4.7. $\displaystyle \quad -\dfrac{3}{5}$

4.8. $\displaystyle \quad -2$

4.9. $\displaystyle \quad -\dfrac{59}{15}$

4.10. $\displaystyle \quad 4$

4.11. $\displaystyle \quad 2$

4.12. $\displaystyle \quad \dfrac{89}{18}$

------------------------------------------------------------------------

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 12/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
