---
title: "Answers: Vector addition and scalar multiplication"
author: "Renee Knapp, Kin Wang Pang"
abstract-title: Summary
abstract: Answers to questions relating to the guide on vector addition and scalar multiplication.
---

*These are the answers to [Questions: Addition and scalar multiplication](../questions/qs-addandsm.qmd).* 

**Please attempt the questions before reading these answers!**

<!--1 hyperlink: line 9-->

## Q1 {-}

1.1. For the $\mathbf{i}$ component, $4 + 8 = 12$.For the $\mathbf{j}$ component, $5 + 2 = 7$.For the $\mathbf{k}$ component, $7 + 4 = 11$. So the answer is $\mathbf{a} + \mathbf{b} = 12\mathbf{i} + 7\mathbf{j} + 11\mathbf{k}$.

1.2. $\mathbf{a} + \mathbf{b} = 2\mathbf{i} + 3\mathbf{j} + 9\mathbf{k}$.

1.3. $\mathbf{a} - \mathbf{b} = 2\mathbf{i} - 11\mathbf{j} + 14\mathbf{k}$.

1.4. You can solve this by doing addition componentwise. $\mathbf{i}$ component: $4- (3+11) = -10$, $\mathbf{j}$ component: $12- (-3-4) = 19$, $\mathbf{k}$ component: $-7-(-2+9) = -14$. So the answer is $-10\mathbf{i} + 19\mathbf{j} -14\mathbf{k}$.

## Q2 {-}

2.1. $\mathbf{a} + \mathbf{b} = \begin{pmatrix}4x \\7y\\0\end{pmatrix}$

2.2. $\mathbf{a} - \mathbf{b} = \begin{pmatrix}7 \\ 3y - 2x \\ -z\end{pmatrix}$

2.3. $\mathbf{a} + \mathbf{b} - \mathbf{c} = \mathbf{0}$ or $\begin{pmatrix}0\\0\\0\end{pmatrix}$.

2.4. $\mathbf{a}$.

## Q3 {-}

3.1. $3\mathbf{u} = (3)5\mathbf{j} + (3)6\mathbf{k} = 15\mathbf{j} + 18\mathbf{k}$.

3.2. $-6\mathbf{v} = \begin{pmatrix}0\\18\\-42\end{pmatrix}$.

3.3. $4\mathbf{v} - 3\mathbf{u} = \begin{pmatrix}0\\-27\\10\end{pmatrix}$

3.4. $-2\mathbf{w} - (4\mathbf{u} -2\mathbf{v}) = \begin{pmatrix}-4\\-32\\-2\end{pmatrix}$

## Q4 {-}

4.1. By the laws of vector addition, $\overrightarrow{AB} = \overrightarrow{AO} + \overrightarrow{OB} = -\overrightarrow{OA} + \overrightarrow{OB}$, where $\overrightarrow{OA}$ and $\overrightarrow{OB}$ are the respective coordinates of $A$ and $B$ written in vector form. You can find $\overrightarrow{AB}$ by solving the above equation. $\overrightarrow{AB} = \begin{pmatrix}-2-3\\5-4\\7-5\end{pmatrix} = \begin{pmatrix}-5\\1\\2\end{pmatrix}$

4.2.$\overrightarrow{AB} = \begin{pmatrix}4\\6\\0\end{pmatrix}$, $\overrightarrow{AC} = \begin{pmatrix}-2\\-4\\-5\end{pmatrix}$. $\overrightarrow{AB} - \overrightarrow{AC} = \begin{pmatrix}6\\10\\5\end{pmatrix}$. You can also calculate this by noticing $\overrightarrow{AB} - \overrightarrow{AC} = \overrightarrow{CA} + \overrightarrow{AB} = \overrightarrow{CB}$. Then $\overrightarrow{CB} = \begin{pmatrix}6-0\\11-1\\7-2\end{pmatrix} = \begin{pmatrix}6\\10\\5\end{pmatrix}$ as required.

<!-- 4.3. Let $\lambda$ be a real scalar. $\overrightarrow{AB} = \lambda\overrightarrow{BC}$. $\overrightarrow{AB} = \begin{pmatrix}10\\-5\end{pmatrix}$, $\overrightarrow{BC} = \begin{pmatrix}4k-12\\3k-4\end{pmatrix}$. This gives you the simultaneous equations $\begin{cases} 10 = \lambda(4k-12)\\-5 = \lambda(3k-4) \end{cases}$. Solving this gives $k = 2$. -->

4.3. $\overrightarrow{AB} = \overrightarrow{OB} - \overrightarrow{OA}$. $\begin{pmatrix}1\\5\\9\end{pmatrix} - \begin{pmatrix}a_1\\a_2\\a_3\end{pmatrix} = \begin{pmatrix}6\\7\\-2\end{pmatrix}$. Solving this gives $A = (-5,-2,11)$.

4.4. Let $\lambda$ and $\mu$ be scalars. $\lambda \mathbf{a} + \mu \mathbf{b} = 13\mathbf{i} -9\mathbf{j}$. This gives you the simultaneous equations 
\begin{align*} 
2\lambda + 3\mu &= 13 \tag{\textsf{$\mathbf{i}$ component}}\\
3\lambda -5\mu &= -9 \tag{\textsf{$\mathbf{j}$ component}}
\end{align*}
Solving this gives $\mu = 3$, $\lambda = 2$, which gives the answer $2\mathbf{a} + 3\mathbf{b}$.

4.5. $2\begin{pmatrix}2\\5\\z\end{pmatrix} + 3\begin{pmatrix}-1\\-3\\4\end{pmatrix} = \begin{pmatrix}x\\y\\0\end{pmatrix}$. Solving this gives $x = 3$, $y = 1$ and $z = -6$.

4.6. As they are parallel $\mathbf{a} = \lambda \mathbf{b}$ for some real scalar $\lambda$. This gives the simultaneous equations 
\begin{align*} 
x - 7 &= -2\lambda \tag{\textsf{$\mathbf{i}$ component}}\\
5x+1 &= 8\lambda \tag{\textsf{$\mathbf{k}$ component}}
\end{align*} 
Eliminating $\lambda$ and solving gives $x = 3$.

<!-- 4.8. This gives the simultaneous equations $\begin{cases} 5\alpha + 5 = 2\alpha -2\\3-\beta = 3\beta + 8\\7-2 = \gamma + 12\\1+5 = 2\delta + 2\delta\end{cases}$. Solving this gives $\alpha = -\frac{7}{3}$,$\beta = -\frac{5}{4}$,$\gamma = -7$ and $\delta = \frac{3}{2}$. -->

---

---

