---
title: "Answers: Arithmetic on algebraic fractions"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on arithmetic on algebraic fractions.
draft: true
---

*These are the answers to [Questions: Arithmetic on algebraic fractions](../questions/qs-arithmeticonalgebraicfractions.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {.unnumbered}

1.1. $\displaystyle \quad \dfrac{7}{x}$

1.2. $\displaystyle \quad \dfrac{2x-1}{3}$

1.3. $\displaystyle \quad \dfrac{3}{y}$

1.4. $\displaystyle \quad \dfrac{1}{x}$

1.5. $\displaystyle \quad -1$

1.6. $\displaystyle \quad \dfrac{3}{2x}$

1.7. $\displaystyle \quad \dfrac{7}{15y}$

1.8. $\displaystyle \quad \dfrac{x}{2}$

1.9. $\displaystyle \quad \dfrac{5x+2}{x(x+1)}$

1.10. $\displaystyle \quad \dfrac{6}{x-1}$

1.11. $\displaystyle \quad \dfrac{6}{x-3}$

1.12. $\displaystyle \quad \dfrac{x-6}{(x+2)(x-2)}$

1.13. $\displaystyle \quad \dfrac{3x+1}{x^2}$

1.14. $\displaystyle \quad \dfrac{x(2x-3)}{(x-3)(x+3)}$

1.15. $\displaystyle \quad \dfrac{x^2 - x - 5}{(x+2)^2}$

## Q2 {.unnumbered}

2.1. $\displaystyle \quad \dfrac{2x}{15}$

2.2. $\displaystyle \quad 6$

2.3. $\displaystyle \quad \dfrac{x(x+1)}{6}$

2.4. $\displaystyle \quad \dfrac{3}{4}$

2.5. $\displaystyle \quad \dfrac{x-3}{4}$

2.6. $\displaystyle \quad -\dfrac{6}{x}$

2.7. $\displaystyle \quad \dfrac{x}{2}$

2.8. $\displaystyle \quad \dfrac{x+2}{x+3}$

2.9. $\displaystyle \quad \dfrac{3}{4}$

2.10. $\displaystyle \quad \dfrac{x+3}{x+1}$

2.11. $\displaystyle \quad -\dfrac{3}{2}$

2.12. $\displaystyle \quad \dfrac{2x}{3(x-2)}$

## Q3 {.unnumbered}

3.1. $\displaystyle \quad \dfrac{5}{2}$

3.2. $\displaystyle \quad 6$

3.3. $\displaystyle \quad \dfrac{1}{2}$

3.4. $\displaystyle \quad \dfrac{3x}{2}$

3.5. $\displaystyle \quad \dfrac{4(x-2)}{3x}$

3.6. $\displaystyle \quad \dfrac{x-1}{x}$

3.7. $\displaystyle \quad -6$

3.8. $\displaystyle \quad 2$

3.9. $\displaystyle \quad \dfrac{1}{2}$

3.10. $\displaystyle \quad \dfrac{x+3}{x-3}$

3.11. $\displaystyle \quad 2$

3.12. $\displaystyle \quad \dfrac{3(x+2)}{2x}$

## Q4 {.unnumbered}

4.1. $\displaystyle \quad \dfrac{x+y}{y}$

4.2. $\displaystyle \quad -\dfrac{6x}{x+2}$

4.3. $\displaystyle \quad \dfrac{1}{2}$

4.4. $\displaystyle \quad \dfrac{x+2}{3x}$

4.5. $\displaystyle \quad -\dfrac{2x(x+1)}{x-1}$

---

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 12/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
