---
title: "Answers: Completing the square"
author: "Tom Coleman"
abstract-title: Summary
abstract: Answers to questions relating to the guide on completing the square.

---

*These are the answers to [Questions: Completing the square](../questions/qs-completingthesquare.qmd).* 

**Please attempt the questions before reading these answers!**

## Q1 {-}

1.1. Here, $x^2 - 2x + 15 = (x-1)^2 + 14$, so in this question $p = -1$ and $q = 14$. 

1.2. Here, $y^2 - 6y + 8 = (y-3)^2 - 1$, so in this question $p = -3$ and $q = -1$. 

1.3. Here, $x^2 + 8x + 20 = (x+4)^2 + 4$, so in this question $p = 4$ and $q = 4$. 

1.4. Here, $m^2 - 26m + 25 = (m-13)^2 - 144$, so in this question $p = -13$ and $q = -144$. 

1.5. Here, $n^2  + 6n + 50 = (m+3)^2 + 41$, so in this question $p = 3$ and $q = 41$. 

1.6. Here, $x^2 + 2x + 144 = (x+1)^2 + 143$, so in this question $p = 1$ and $q = 143$. 

1.7. Here, $\displaystyle h^2 - 3h - 3 = \left(h- \frac{3}{2}\right)^2 + \frac{3}{4}$, so in this question $p = -3/2$ and $q = 3/4$. 

1.8. Here, $\displaystyle x^2 + x - 3 = \left(x+ \frac{1}{2}\right)^2 - \frac{13}{4}$, so in this question $p = 1/2$ and $q = -13/4$. 

1.9. Here, $\displaystyle x^2 - 13x + 43 = \left(x- \frac{13}{2}\right)^2 + \frac{3}{4}$, so in this question $p = -13/2$ and $q = 3/4$. 

1.10. Here, $\displaystyle y^2 - 8y + 16 = \left(y- 4\right)^2$, so in this question $p = -4$ and $q = 0$.

1.11. Here, $\displaystyle x^2 + 13x + 9 = \left(x+ \frac{13}{2}\right)^2 - \frac{133}{4}$, so in this question $p = 13/2$ and $q = -133/4$.

1.12. Here, $\displaystyle m^2 + 3m + 33 = \left(m+ \frac{3}{2}\right)^2 - \frac{143}{4}$, so in this question $p = 3/2$ and $q = -143/4$.


## Q2 {-}

2.1. Here, $2x^2 - 12x + 14 = 2(x-3)^2 - 4$, so in this question $a = 2$, $p = -3$ and $q = -4$. 

2.2. Here, $5y^2 - 10y + 4 = 5(x-1)^2 - 1$, so in this question $a = 5$, $p = -1$ and $q = -1$. 

2.3. Here, $4x^2 + 32x + 68 = 4(x+4)^2 + 4$, so in this question $a = p = q = 4$. (Or, if you prefer, $(2x+8)^2 + 4$.)

2.4. Here, $\displaystyle 2m^2 + 2m + 2 = 2\left(m + \frac{1}{2}\right)^2 + \frac{3}{2}$, so in this question $a = 2$, $p = 1/2$ and $q = 3/2$. 

2.5. Here, $\displaystyle 3x^2 - 2x + 5 = 3\left(x - \frac{1}{3}\right)^2 + \frac{14}{3}$, so in this question $a = 3$, $p = -1/3$ and $q = 14/3$. 

2.6. Here, $\displaystyle 4x^2 - 4x + 1 = 4\left(x - \frac{1}{2}\right)^2$, so in this question $a = 4$, $p = -1/2$ and $q = 0$. (Or, if you prefer, $(2x-1)^2$.) 

2.7. Here, $\displaystyle 2h^2 - 3h + 1 = 2\left(h- \frac{3}{4}\right)^2 - \frac{1}{8}$, so in this question $a = 2$, $p = -3/4$ and $q = -1/8$. 

2.8. Here, $\displaystyle 3x^2 + 5x + 2 = 3\left(x+ \frac{5}{6}\right)^2 - \frac{3}{36}$, so in this question $a = 3$, $p = 5/6$ and $q = -3/36$. 

## Q3 {-}

Using your working from Q1 and Q2, solve the following quadratic equations.

3.1. You worked out in 1.2 that $y^2 - 6y + 8 = (y-3)^2 - 1$. Rearranging $(y-3)^2 - 1 = 0$ for $y$ gives $y = 3 \pm 1$, so $y = 2$ or $y = 4$.

3.2. You worked out in 1.4 that $m^2 - 26m + 25 = (m-13)^2 - 144$. Rearranging $(y-3)^2 - 144 = 0$ for $y$ gives $y = 13 \pm 12$, so $y = 1$ or $y = 25$.

3.3. You worked out in 1.3 that $x^2 + 8x + 20 = (x+4)^2 + 4$. Using the fact that $(\pm 2i)^2 = -4$ (see [Guide: Introduction to complex numbers]), rearranging $(x+4)^2 + 4 = 0$ for $y$ gives $y = -4 \pm 2i$, so $y = -4 - 2i$ or $y = -4 + 2i$.

3.4. You worked out in 2.6 that $\displaystyle 4x^2 - 4x + 1 = 4\left(x - \frac{1}{2}\right)^2$. Rearranging $4\left(x - \frac{1}{2}\right)^2 = 0$ for $x$ gives $\displaystyle x = \frac{1}{2}$ (twice, see [Guide: Introduction to quadratic equations](../studyguides/introtoquadratics.qmd)).

3.5. You worked out in 2.3 that $4x^2 + 32x + 68 = 4(x+4)^2 + 4$. Using the fact that $(\pm i)^2 = -1$ (see [Guide: Introduction to complex numbers]), rearranging $4(x+4)^2 + 4 = 0$ for $x$ gives $x = -4 \pm i$, so $x = -4 - i$ or $x = -4 + i$.

3.6. You worked out in 2.8 that $\displaystyle 3x^2 + 5x + 2 = 3\left(x+ \frac{5}{6}\right)^2 - \frac{3}{36}$. Rearranging $\displaystyle 3\left(x+ \frac{5}{6}\right)^2 - \frac{3}{36} = 0$ for $x$ gives $\displaystyle y = -\frac{5}{6} \pm \frac{1}{6}$, so $y = -1$ or $y = -2/3$.

---

---

## Version history and licensing {-}

v1.0: initial version created 09/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

