---
title: "Answers: Introduction to confidence intervals"
author: "Millie Harris"
abstract-title: Summary
abstract: Answers to questions on introduction to confidence intervals.
draft: true
---

*These are the answers to [Questions: Introduction to confidence intervals](../questions/qs-confidenceintervals.qmd).*

**Please attempt the questions before reading these answers.**

## Q1

1.1. $95\%$ or $0.95$

1.2. $90\%$ or $0.90$

1.3. $99\%$ or $0.99$

## Q2

2.1. $Z_\frac{\alpha}{2} = 1.960$

2.2. $Z_\frac{\alpha}{2} = 1.645$

2.3. $Z_\frac{\alpha}{2} = 2.576$

## Q3

3.1. $n = 178$

3.2. $\bar{x} = 14$

3.3. $\sigma = 0.75$

3.4. $\alpha = 0.1$

3.5. $Z_\frac{\alpha}{2} = 2.576$

## Q4

4.1.

From **Q3**:

-   $\bar{x} = 14$

-   $Z_\frac{\alpha}{2} = 2.576$

-   $\sigma = 0.75$

-   $n = 178$

$= [14 - 2.576(\frac{0.75}{\sqrt{178}}),14 + 2.576(\frac{0.75}{\sqrt{178}})]$

$= [13.855, 14.145]$

4.2 If Cantor's Confectionery were to repeat the study several times, they would expect the true mean of the weights of their chocolate swirls to lie between $13.855$ grams and $14.145$ grams.

## Q5

5.1

-   $\bar{x} = 31$

-   $\sigma = 4$

-   $n = 59$

-   $Z_\frac{\alpha}{2} = 1.645$

$= [31 - 1.645(\frac{4}{\sqrt{59}}), 31 + 1.645(\frac{4}{\sqrt{59}})]$

$= [30.14, 31.86]$

5.2

-   $\bar{x} = 31$

-   $\sigma = 4$

-   $n = 59$

-   $Z_\frac{\alpha}{2} = 1.960$

$= [31 - 1.960(\frac{4}{\sqrt{59}}), 31 + 1.960(\frac{4}{\sqrt{59}})]$

$= [29.98, 32.02]$

5.3

-   $\bar{x} = 31$

-   $\sigma = 4$

-   $n = 59$

-   $Z_\frac{\alpha}{2} = 2.576$

$= [31 - 2.576(\frac{4}{\sqrt{59}}), 31 + 2.576(\frac{4}{\sqrt{59}})]$

$=[29.66, 32.34]$

## Version history and licensing {.unnumbered}

v1.0: initial version created 12/04 by mh392 (as part of a University of St Andrews VIP project)

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
