---
title: "Answers: 2D Conic Sections"
author: "Abigail Carpenter"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to 2D conic sections.
draft: true
---

*These are the answers to [Questions: 2D Conic Sections](../questions/qs-conicsections.qmd).* 

**Please attempt the questions before reading these answers!**

## Q1 {-}

1.1. Ellipse

1.2. Circle

1.3. Hyperbola

1.4. Parabola

1.5. Ellipse

1.6. Hyperbola

1.7. Ellipse

1.8. Parabola

1.9. Ellipse

1.10. Hyperbola


## Q2 {-}

2.1. 

Centre: $(2,-1)$

Radius: $4$

2.2. 

Centre: $(2,-3)$

Radius: $5$

2.3. 

Centre: $(-4,5)$

Radius: $4 \sqrt{2}$

2.4.

Centre: $(3,-2)$

Foci: $(3 \pm \sqrt{5}, -2)$

2.5.

Centre: $(-1,4)$

Foci: $(-1, \pm \sqrt{7}, 4)$

2.6. 

Centre: $(1,-2)$ 

Foci: $(1, -2 \pm \sqrt{5})$

2.7. 

Centre: $(1,-3)$

Foci: $(1, -3 \pm \sqrt{7})$

2.8.

Centre: $(3,-1)$

Foci: $(3 \pm \sqrt{3}, -1)$

2.9.

Centre: $(1,3)$

Foci: $(1 \pm \sqrt{3}, 3)$

2.10.

Centre: $(2,-2)$

Foci: $(2 \pm \sqrt{7}, -2)$

2.11. 

Vertex: $(2,3)$

Focus: $(2, \frac{13}{4})$

Directrix: $y = 3 - \frac{1}{4}$

2.12.

Vertex: $(-1,2)$

Focus: $(-1, 4)$

Directrix: $y = 0$

2.13.

Vertex: $(2,-3)$

Focus: $(1,-3)$

Directrix: $x=3$

2.14.

Vertex: $(3,1)$

Focus: $(3,2)$

Directrix: $y = 0$

2.15.

Vertex: $(4,-4)$

Focus: $(3, -4)$

Directrix: $x=5$

2.16. 

Centre: $(2,1)$

Foci: $(2 \pm \sqrt 13, -1)$

Vertices: $(2 \pm 3, -1)$

2.17.

Centre: $(-1,3)$

Foci: $(-1, 3 \pm 5)$

Vertices: $(-1, 3 \pm 4)$

2.18.

Centre: $(1,2)$

Foci: $(1 \pm 5,2)$

Vertices: $(1 \pm 4, 2)$

2.19.

Centre: $(2,-3)$

Foci: $(2 \pm \sqrt 8,-3)$

Vertices: $(2 \pm 2, 2)$

2.20.

Centre: $(-3,2)$

Foci: $(-3, 2 \pm 3)$

Vertices: $(-3, 2 \pm \sqrt {13})$

---

## Version history and licensing {-}

v1.0: initial version created 11/25 by Abigail Carpenter as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
