---
title: "Answers: The chain rule"
author: "Sara Delgado Garcia"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the chain rule.
---

*These are the answers to [Questions: The chain rule](../questions/qs-chainrule.qmd).* 

**Please attempt the questions before reading these answers!**

---

1.1. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left( \dfrac{1}{7}\cos(5+4x)\right)=-\frac{4}{7}\sin(5+4x).$

---

1.2. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(4\cos(x^2)\right)= -8x \sin(x^2).$

---

1.3. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(e^{x^2 + 5}\right) = 2xe^{x^2+5}$

---

1.4. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(2(\sin(2x))^2\right)= 8\sin(2x)\cos(2x).$

---

1.5. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(e^{\sin(3x)}\right)=3\cos(3x)e^{\sin(3x)}.$

---

1.6. Using laws of logarithms, write $\ln((2+4x^{-2})^{-1})=-\ln(2+4x^{-2})$. Then $$\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln({{2+ 4x^{-2}})^{-1}}\right)=\frac{8x^{-3}}{2+4x^{-2}} =\frac{4}{x^3+2x}.$$

---

1.7. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(e^{5x^4}\right)= 20x^3e^{5x^4}$

---

1.8. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(e^{2x^{-3}}\right)= -6x^{-4}e^{2x^{-3}}$

---

1.9. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(-5\sqrt{x-2}\right)=-\frac{5}{2\sqrt{x-2}}$

---

1.10. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\sqrt{(x+3)^2}\right)= 1$ (for $x\geq 3$.)

---

1.11. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln (x^2 +1)\right)=\frac{2x}{x^2+1}$

---

1.12. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln(\cos(x))\right)=-\tan(x)$.

---

1.13. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(2\cos^2(x)\right)=-4\cos(x)\sin(x)=-2\sin(2x).$

---

1.14. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(2(x^3 + 5x^2 + 13x -1)^3\right)= 6(3x^2+10x+13)(x^3 + 5x^2 + 13x -1)^2.$

---

1.15. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\sqrt{\dfrac{1}{2x}}\right)=-\frac{1}{4x^2}\left(\frac{1}{2x}\right)^{-1/2}$

---

1.16. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\cos(5x^{-1/2})\right)=\frac{5}{2}x^{-3/2}\sin(5x^{-1/2}).$

---

1.17. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\sin\left(\sqrt{x^2+1}\right)\right)= \frac{x\cos(\sqrt{x^2 +1})}{\sqrt{x^2+1}}$

---

1.18. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\sin(e^x)\right)= e^x\cos(e^x).$

---

1.19. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\cos(e^{-2x} + 5)\right)= 2e^{-2x}\sin(e^{-2x}+5).$

---

1.20. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln(3x^3 + \sin(x))\right)= \frac{9x^2+\cos(x)}{3x^3+\sin(x)}.$

---

---

## Version history and licensing {-}

v1.0: initial version created 05/25 by Sara Delgado Garcia as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

