---
title: "Answers: Expected value, variance, standard deviation"
author: Tom Coleman
abstract-title: Summary
abstract: Answers to questions relating to the guide on expected value, variance, and standard deviation.
---

*These are the answers to [Questions: PMFs, PDFs, and CDFs.](../questions/qs-expectedvariance.qmd)*

**Please attempt the questions before reading these answers!**

## Q1 {-}

For each of the following valid random variables with associated probability mass function, work out the expected value and variance.

#### 1.1. {-}

Here, $\mathbb{E}(X) = 2.8$ and $\mathbb{V}(X) = 0.76$.

#### 1.2. {-}

Here, $\mathbb{E}(X) = 2.4$ and $\mathbb{V}(X) = 2.04$.

#### 1.3. {-}

This is a Bernoulli trial, with probability of success $p = 0.7$. From Example 2 of [Guide: Expected value, variance, standard deviation](../studyguides/expectedvariance.qmd), you can say that $\mathbb{E}(X) = p = 0.3$. The variance can be worked out to be $$\mathbb{V}(X) = 0.3 - (0.3)^2 = 0.21 = (0.3)(0.7) = p(1-p).$$

#### 1.4. {-}

Here, $\mathbb{E}(X) = 3$ and $\mathbb{V}(X) = 1$.


## Q2 {-}

For each of the following valid random variables with associated probability density function, work out the expected value andvariance.

#### 2.1. {-}

This is the continuous uniform distribution with $a = 0$ and $b = 2$. From Example 2 of [Guide: Expected value, variance, standard deviation](../studyguides/expectedvariance.qmd), you can say that $\mathbb{E}(X) = (a+b)/2 = (0+2)/2 = 1$ and $$\mathbb{V}(X) = \frac{1}{12}(b-a)^2 = \frac{1}{12}(2-0)^2 = \frac{4}{12} = \frac{1}{3}.$$

#### 2.2. {-}

Here, $\mathbb{E}(X) = \dfrac{2}{3}$ and $\mathbb{V}(X) = \dfrac{1}{6}$.

## Q3 {-}

You know that the expected value and variance of rolling one fair die are $\mathbb{E}(X) = \dfrac{7}{2}$ and $\mathbb{V}(X) = \dfrac{35}{12}$.

Because the roll of each die is an independent event, the random variable $Y$ of rolling seven dice is the same as $$Y = X + X + X + X + X + X + X$$ which is seven lots of $X$. 

You can use the properties of expected values and variance to get 

$$\begin{aligned} \mathbb{E}(Y) &= \mathbb{E}(X + X + X + X + X + X + X)\\ &= 7\cdot \frac{7}{2} = \frac{49}{2} = 24.5\end{aligned}$$

and

$$\begin{aligned} \mathbb{V}(Y) &= \mathbb{V}(X + X + X + X + X + X + X)\\ &= 7\cdot \frac{35}{12} = \frac{245}{12}\end{aligned}$$

## Q4 {-}

When doing this question, you need to find the two integrals $$\mathbb{E}(X) = \int_0^\infty \lambda xe^{-\lambda x}\,\textrm{d}x\quad \textsf{ and }\quad \mathbb{V}(X) =\int_0^\infty \lambda x^2e^{-\lambda x}\,\textrm{d}x.$$ You will need to use integration by parts; you should always differentiate the power of $x$ to reduce the size of the power. Use the given result to evaluate the integral when $x\to\infty$; the antiderivative should always be $0$ in this case.


--- 

---

## Version history and licensing {-}

v1.0: initial version created 08/25 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
