---
title: "Answers: Factorization"
author: "Millie Pike"
abstract-title: Summary
abstract: Answers to questions relating to the guide on factorization.
---

*These are the answers to [Questions: Factorization](../questions/qs-factorization.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {-}

Note that you can rearrange the factorized brackets — the answer stays the same because the order of multiplication doesn't matter.

1.1. $7x+35 = 7(x+5)$.

1.2. $3x-51 = 3(x-17)$.

1.3. $6m+3n = 3(2m+n)$.

1.4. $5f+10+15k = 5(f+2+3k)$.

1.5. $10x-2+3y^2+3y = 2(5x-1)+y(3y+3)$.

1.6. $9xy-3x = 3x(3y-1)$.

1.7. $a^2+ab = a(a+b)$.

1.8. $4m^2-8nm+12m = 4m(m-2n+3)$.

1.9. $12wx^2+16wx = 4wx(3x+4)$.

1.10. $a^3b+ab^2+ ab^3 = ab(a^2+b(1+b))$.

1.11. $x(x-6)+3(6-x) = (x-6)(x-3)$.

1.12. $3w+3z+xw+xz = (w+z)(3+x)$.

1.13. $2ab+ b^2-b-2a = (2a+b)(b-1)$.

1.14. $a^2 b+3a^2+ab+3a-2b-6 = (b+3)(a-1)(a+2)$.

## Q2 {-}

Note that you can rearrange the factorized brackets — the answer stays the same because the order of multiplication doesn't matter.

2.1. $x^2+6x+5 = (x+5)(x+1)$.

2.2. $x^2-3x-4 = (x-4)(x+1)$.

2.3. $x^2-4x+3 = (x-3)(x-1)$.

2.4. $2x^2-13x+21 = (2x-7)(x-3)$.

2.5. $5x^2-10x+5 = 5(x-1)(x-1)$.

2.6. $x^2-xy-6y^2 = (x-3y)(x+2y)$.

2.7. $12x^2 y^2+8xy^2-4y^2 = 4y^2(3x-1)(x+1)$.

2.8. $x^2-4yx-x+4y = (x-4y)(x-1)$.

2.9. $x^2+y^2-2xy = (x-y)^2$ or $(y-x)^2$.

2.10. $x^2-y^2 = (x-y)(x+y)$.

2.11. $9x^2 +3x -2 = (3x-1)(3x+2)$.

## Q3 {-}

3.1. You worked out in 1.1 that $7x+35 = 7(x+5)$. Solving for $x$ gives $x =-5$.

3.2. You worked out in 1.11 that $x(x-6)+3(6-x)=(x-6)(x-3)$. Solving for $x$ gives $x =3$ and $x=6$.

3.3. You worked out in 2.3 that $x^2-4x+3=(x-3)(x-1)$. Solving for $x$ gives $x =3$ and $x=1$.

3.4. You worked out in 2.7 that $12x^2 y^2+8xy^2-4y^2=4y^2(3x-1)(x+1)$. Solving for $x$ gives $x = 1/3$ and $x=-1$.

3.5. You worked out in 2.8 that $x^2-4yx-x+4y=(x-4y)(x-1)$. Solving for $x$ gives $x =4y$ and $x=1$.

---

---

## Version history and licensing {-}

v1.0: initial version created 04/25 by Millie Pike, as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
