---
title: "Answers: Introduction to hypothesis testing"
author: "Ellie Trace"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to hypothesis testing.
---

*These are the answers to [Questions: Introduction to hypothesis testing](../questions/qs-hypothesistesting.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {-}

The following questions are on defining hypotheses.

1.1. Set the average number of pages (mean) to $\mu$. Here, $H_0: \mu=350$ and $H_1: \mu<350$, and you would need a lower one-tailed test.

1.2. Set the percentage of defective products to be equal to $D$. Here, $H_0: D=0.1$ and $H_1: D>0.1$, and you would need an upper one-tailed test.

1.3. Set $\mu_a,\mu_b$ to be the average wait time in the two different branches. Here, $H_0: \mu_a=\mu_b$ and $H_1: \mu_a\neq\mu_b$, and you would need a two-tailed test.

1.4. Set $\mu_x$ to be the average time of the express trains, and $\mu_r$ to be the average time of the regular trains. Here, $H_0: \mu_r=\mu_x$ and $H_1: \mu_x>\mu_r$, and you would need a lower one-tailed test.

## Q2 {-}

2.1. $\alpha=0.15$

2.2. $\alpha=0.01$

2.3. A paired t-test.

## Q3 {-}

3.1. I reject $H_0$ as the test statistic of $3.12$ is greater than the critical value of $2.58$. Therefore there is significant evidence to suggest the average daily sales of Boole Bars differ from 150.

3.2. I reject $H_0$ as the test statistic of $2.01$ is greater than the critical value of $1.645$. Therefore there is significant evidence to suggest the proportion of customers who buy Lagrangian Lollipops exceeds $40\%$.

3.3. I do not reject $H_0$ as the test statistic of $2.102$ is between the critical values of $2.306$ and $-2.306$. Therefore there is no significant evidence to suggest there is a difference in sweetness scores between the two recipes.

---

---

## Version history and licensing {-}

v1.0: initial version created 12/24 by Ellie Trace as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
