---
title: "Answers: Solving first-order linear ODEs using integrating factors"
author: "Maddi Koenig"
abstract-title: Summary
abstract: Answers to questions relating to the guide on solving first-order linear ODEs using integrating factors.
draft: true
---

*These are the answers to [Questions: Introduction to solving first-order linear ODEs using integrating factors](../questions/qs-integratingfactors.qmd).* 

**Please attempt the questions before reading these answers!**

<!-- For the Differential Equations Sheet -->

<!-- ## Q1 {-} -->

<!-- For each of the ODEs below, identify the order of the equation. -->

<!-- 1.1. For $\frac {dy}{dx} = 4y + \frac {d^2y}{dx^2}$, the order is $2$. -->

<!-- 1.2. For $\frac {d^2y}{dx^2}  + 3y  = -\frac {d^5y}{dx^5}$, the order is $5$. -->

<!-- 1.3. For $4x^5 = \frac {d^3x}{dt^3} - \frac {d^2x}{dt^2}$, the order is $3$. -->

<!-- 1.4. For $6e^y + 5x^3 = \frac {d^9y}{dx^9} + 12 \frac {d^4y}{dx^4)$, the order is $9$. -->



## Q1 {-}

1.1. The equation rearranged into the form $\frac{\mathrm{d}y}{\mathrm{d}x} + P(x)y = Q(x)$ is $\frac {\mathrm{d}y}{\mathrm{d}x} + y = -8$.

1.2. The equation rearranged into the form $\frac{\mathrm{d}y}{\mathrm{d}x} + P(x)y = Q(x)$ is $\frac {\mathrm{d}y}{\mathrm{d}x} - \frac {1}{2x} \cdot y = -5x$.

1.3. The equation rearranged into the form $\frac{\mathrm{d}x}{\mathrm{d}t} + P(t)x = Q(t)$ is $\frac {\mathrm{d}x}{\mathrm{d}t} + \cos(t)x = \cos(t)$.

1.4. The equation rearranged into the form $\frac{\mathrm{d}y}{\mathrm{d}x} + P(x)y = Q(x)$ is $\frac {\mathrm{d}y}{\mathrm{d}x} - \frac {1}{x} \cdot y = x$.

## Q2 {-}

2.1. The integrating factor for $- \frac {\mathrm{d}y}{\mathrm{d}x} = y + 8$ is $\mu = e^x$.

2.2. The integrating factor for $\frac {1}{2x} = \frac {\frac {\mathrm{d}y}{\mathrm{d}x} + 5x}{y}$ is $\mu = x^{-\frac {1}{2}}$.

2.3. The integrating factor for $\frac {\mathrm{d}x}{\mathrm{d}t} - \cos(t) = -x\cos(t)$ is $\mu = e^{\sin(t)}$.

2.4. The integrating factor for $x\frac {\mathrm{d}y}{\mathrm{d}x} - x^2 = y$ is $\mu = x^{-1}$.

## Q3 {-}

3.1. The general solution is $y = -8 + Ce^{-x}$.

3.2. The general solution is $y = -\frac {10}{3}x^2 + Cx^{\frac {1}{2}}$.

3.3. The general solution is $x = 1 + Ce^{-\sin(t)}$.

3.4. The general solution is $y = x^2 + Cx$.

## Q4 {-}

4.1. The exact solution, given the initial condition $y(0) = 0$, is $y = -8 + 8e^{-x}$.

4.2. The exact solution, given the initial condition $y(1) = 6$, is $y = -\frac {10}{3}x^2 + \frac {28}{3} x^{\frac {1}{2}}$.

4.3. The exact solution, given the initial condition $x(0) = \pi$, is $x = 1 + (\pi - 1)e^{-\sin(t)}$.

4.4. The exact solution, given the initial condition $y(2) = 3$, is $y = x^2 - \frac {1}{2}x$.

## Q5 {-}

5.1. The general solution is $y = -x^2 - \frac{1}{2} x + Cx^5$

5.2 The general solution is $y = \frac{\frac{10}{3}x^6 + x^5 + C}{4x+1}$

5.3 The exact solution, given the initial condition $y(\frac{\pi}{2}) = 1$, is $y(x) = \frac{1}{5}\sin(x) + \frac{4}{5}\csc^4(x)$

5.4 The exact solution, given the initial condition $y(0) = 4$, is $y(x) = -4xe^{-4x}\cos(x) + 4e^{-4x}\sin(x) + 4e^{-4x}$ 

---

---

## Version history and licensing {-}

v1.0: initial version created 04/06 by mak.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
