---
title: "Answers: Introduction to numerical fractions"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the introduction to numerical fractions.
---

*These are the answers to [Questions: Introduction to numerical fractions](../questions/qs-introtonumericalfractions.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {.unnumbered}

1.1. $\displaystyle \quad \dfrac{2}{5}$

1.2. $\displaystyle \quad \dfrac{7}{8}$

1.3. $\displaystyle \quad \dfrac{3}{4}$

1.4. $\displaystyle \quad \dfrac{1}{6}$

1.5. $\displaystyle \quad 1\dfrac{1}{4} \textsf{ or } \dfrac{5}{4}$

1.6. $\displaystyle \quad \dfrac{6}{10} \textsf{ or } \dfrac{3}{5}$

1.7. $\displaystyle \quad 1\dfrac{1}{3} \textsf{ or } \dfrac{4}{3}$

1.8. $\displaystyle \quad \dfrac{9}{16}$

1.9. $\displaystyle \quad 2\dfrac{3}{4} \textsf{ or } \dfrac{11}{4}$

1.10. $\displaystyle \quad \dfrac{11}{20}$

## Q2 {.unnumbered}

2.1. $\displaystyle \quad \dfrac{3}{2}$

2.2. $\displaystyle \quad -\dfrac{8}{3}$

2.3. $\displaystyle \quad \dfrac{13}{4}$

2.4. $\displaystyle \quad -\dfrac{27}{5}$

2.5. $\displaystyle \quad \dfrac{31}{7}$

2.6. $\displaystyle \quad \dfrac{37}{6}$

2.7. $\displaystyle \quad -\dfrac{43}{5}$

2.8. $\displaystyle \quad \dfrac{92}{9}$

2.9. $\displaystyle \quad -\dfrac{82}{11}$

2.10. $\displaystyle \quad \dfrac{51}{4}$

## Q3 {.unnumbered}

3.1. $\displaystyle \quad 2\dfrac{1}{2}$

3.2. $\displaystyle \quad -1\dfrac{3}{4}$

3.3. $\displaystyle \quad 3\dfrac{1}{3}$

3.4. $\displaystyle \quad -1\dfrac{4}{7}$

3.5. $\displaystyle \quad 2$

3.6. $\displaystyle \quad -4\dfrac{1}{6}$

3.7. $\displaystyle \quad 3\dfrac{4}{9}$

3.8. $\displaystyle \quad 4\dfrac{6}{11}$

3.9. $\displaystyle \quad -8$

3.10. $\displaystyle \quad -7\dfrac{9}{13}$

## Q4 {.unnumbered}

4.1. $\displaystyle \quad 3$

4.2. $\displaystyle \quad 9$

4.3. $\displaystyle \quad 15$

4.4. $\displaystyle \quad 10$

4.5. $\displaystyle \quad -15$

4.6. $\displaystyle \quad -4$

4.7. $\displaystyle \quad 32$

4.8. $\displaystyle \quad 24$

4.9. $\displaystyle \quad -9$

4.10. $\displaystyle \quad 100$

4.11. $\displaystyle \quad -24$

4.12. $\displaystyle \quad 55$

4.13. $\displaystyle \quad -9$

4.14. $\displaystyle \quad 36$

4.15. $\displaystyle \quad 42$

## Q5 {.unnumbered}

5.1. $\displaystyle \quad \dfrac{1}{2}$

5.2. $\displaystyle \quad \dfrac{1}{3}$

5.3. $\displaystyle \quad \dfrac{3}{5}$

5.4. $\displaystyle \quad \dfrac{3}{4}$

5.5. $\displaystyle \quad \dfrac{3}{5}$

5.6. $\displaystyle \quad \dfrac{1}{3}$

5.7. $\displaystyle \quad \dfrac{2}{3}$

5.8. $\displaystyle \quad \dfrac{5}{7}$

5.9. $\displaystyle \quad \dfrac{2}{3}$

5.10. $\displaystyle \quad \dfrac{5}{6}$

## Q6 {.unnumbered}

6.1. $\displaystyle \quad \dfrac{6}{4} = 1\dfrac{2}{4} = 1\dfrac{1}{2}$

6.2. $\displaystyle \quad 2\dfrac{2}{8} = \dfrac{18}{8} = \dfrac{9}{4}$

6.3. $\displaystyle \quad \dfrac{12}{10} = 1\dfrac{2}{10} = 1\dfrac{1}{5}$

6.4. $\displaystyle \quad -\dfrac{15}{9} = -1\dfrac{6}{9} = -1\dfrac{2}{3}$

6.5. $\displaystyle \quad 3\dfrac{4}{6} = \dfrac{22}{6} = \dfrac{11}{3}$

6.6. $\displaystyle \quad -1\dfrac{6}{8} = -\dfrac{14}{8} = -\dfrac{7}{4}$

6.7. $\displaystyle \quad \dfrac{20}{12} = 1\dfrac{8}{12} = 1\dfrac{2}{3}$

6.8. $\displaystyle \quad \dfrac{30}{25} = 1\dfrac{5}{25} = 1\dfrac{1}{5}$

6.9. $\displaystyle \quad 5\dfrac{10}{15} = \dfrac{85}{15} = \dfrac{17}{3}$

6.10. $\displaystyle \quad -\dfrac{45}{20} = -2\dfrac{5}{20} = -2\dfrac{1}{4}$

6.11. $\displaystyle \quad 4\dfrac{8}{10} = \dfrac{48}{10} = \dfrac{24}{5}$

6.12. $\displaystyle \quad \dfrac{50}{30} = 1\dfrac{20}{30} = 1\dfrac{2}{3}$

6.13. $\displaystyle \quad \dfrac{75}{-50} = -\dfrac{75}{50} = -1\dfrac{25}{50} = -1\dfrac{1}{2}$

6.14. $\displaystyle \quad 6\dfrac{12}{16} = \dfrac{108}{16} = \dfrac{27}{4}$

6.15. $\displaystyle \quad -2\dfrac{14}{21} = -\dfrac{56}{21} = -\dfrac{8}{3}$

---

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 12/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
