---
title: "Answers: Integration by substitution"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on integration by substitution.
draft: true
---

*These are the answers to [Questions: Integration by substitution](../questions/qs-integrationbysubstitution.qmd).*

**Please attempt the questions before reading these answers!**

## Answers {.unnumbered}

### Q1 {.unnumbered}

In these questions, you can either use an appropriate $u=ax+b$ substitution or use the chain rule for integration

$$\displaystyle \int (ax+b)^n \, \mathrm{d}x = \dfrac{(ax+b)^{n+1}}{a(n+1)} + C$$

1.1. $\displaystyle \quad \dfrac{1}{8}(2x+5)^4 + C \:$ using the substitution $\: u = 2x+5 \:$ or the chain rule with $\: a=2$.

1.2. $\displaystyle \quad -\dfrac{1}{24}(3-4x)^6 + C \:$ using the substitution $\: u = 3-4x \:$ or the chain rule with $\: a=-4$.

1.3. $\displaystyle \quad \dfrac{2}{5} \left( \dfrac{x}{2}-1 \right)^5 + C \:$ using the substitution $\: u = \dfrac{x}{2}-1 \:$ or the chain rule with $\: a=\dfrac{1}{2}$.

1.4. $\displaystyle \quad -\dfrac{1}{10}(5x-2)^{-2} + C \:$ using the substitution $\: u = 5x-2 \:$ or the chain rule with $\: a=5$.

1.5. $\displaystyle \quad \dfrac{1}{3}(4-3x)^{-1} + C \:$ using the substitution $\: u = 4-3x \:$ or the chain rule with $\: a=-3$.

1.6. $\displaystyle \quad -\dfrac{1}{4}(2x+7)^{-2} + C \:$ using the substitution $\: u = 2x+7 \:$ or the chain rule with $\: a=2$.

1.7. $\displaystyle \quad -\dfrac{5}{3} \left( \dfrac{x}{5}+3 \right)^{-3} + C \:$ using the substitution $\: u = \dfrac{x}{5}+3 \:$ or the chain rule with $\: a=\dfrac{1}{5}$.

1.8. $\displaystyle \quad -(1-2x)^{1/2} + C \:$ using the substitution $\: u = 1-2x \:$ or the chain rule with $\: a=-2$.

1.9. $\displaystyle \quad -\dfrac{2}{3}(3x+4)^{-1/2} + C \:$ using the substitution $\: u = 3x+4 \:$ or the chain rule with $\: a=3$.

1.10. $\displaystyle \quad -\dfrac{1}{2}(5-6x)^{1/3} + C \:$ using the substitution $\: u = 5-6x \:$ or the chain rule with $\: a=-6$.

### Q2 {.unnumbered}

In these questions, you can either use an appropriate $u=ax+b$ substitution or use the chain rule for integration

$$
\begin{aligned}
\displaystyle \int \sin(ax+b) \, \mathrm{d}x &= -\dfrac{1}{a}\cos(ax+b) + C \\
\displaystyle \int \cos(ax+b) \, \mathrm{d}x &= \dfrac{1}{a}\sin(ax+b) + C \\
\end{aligned}
$$

2.1. $\displaystyle \quad \sin \left( x \right) +C \:$ using the substitution $\: u = x \:$ or the chain rule with $\: a=1$.

2.2. $\displaystyle \quad -\dfrac{1}{2} \cos \left( 2x \right) +C \:$ using the substitution $\: u = 2x \:$ or the chain rule with $\: a=2$.

2.3. $\displaystyle \quad \dfrac{5}{6} \sin \left( x \right) +C \:$ using the substitution $\: u = x \:$ or the chain rule with $\: a=1$.

2.4. $\displaystyle \quad \dfrac{1}{3} \sin \left( 3x \right) +C \:$ using the substitution $\: u = 3x \:$ or the chain rule with $\: a=3$.

2.5. $\displaystyle \quad -3 \cos \left( \dfrac{x}{3} \right) +C \:$ using the substitution $\: u = \dfrac{x}{3} \:$ or the chain rule with $\: a=\dfrac{1}{3}$.

2.6. $\displaystyle \quad \dfrac{4}{15} \sin \left( 3x-\dfrac{\pi}{4} \right) +C \:$ using the substitution $\: u = 3x-\dfrac{\pi}{4} \:$ or the chain rule with $\: a=3$.

2.7. $\displaystyle \quad -\dfrac{9}{4} \cos \left( \dfrac{\pi}{3} - \dfrac{4x}{9} \right) +C \:$ using the substitution $\: u = \dfrac{\pi}{3} - \dfrac{4x}{9} \:$ or the chain rule with $\: a=-\dfrac{4}{9}$.

2.8. $\displaystyle \quad -\dfrac{1}{6} \sin \left( 3x + \dfrac{\pi}{2} \right) +C \:$ using the substitution $\: u = 3x + \dfrac{\pi}{2} \:$ or the chain rule with $\: a=3$.

2.9. $\displaystyle \quad -16 \cos \left( \dfrac{x}{4} - \dfrac{\pi}{2} \right) +C \:$ using the substitution $\: u = \dfrac{x}{4} - \dfrac{\pi}{2} \:$ or the chain rule with $\: a=\dfrac{1}{4}$.

2.10. $\displaystyle \quad -\dfrac{3}{25} \sin \left( \dfrac{\pi}{6} - 5x \right) +C \:$ using the substitution $\: u = \dfrac{\pi}{6} - 5x \:$ or the chain rule with $\: a=-5$.

### Q3 {.unnumbered}

In these questions, you can either use an appropriate $u=ax+b$ substitution or use the chain rule for integration

$$
\begin{aligned}
\displaystyle \int \mathrm{e}^{ax+b} \, \mathrm{d}x &= \dfrac{1}{a} \mathrm{e}^{ax+b} + C \\
\displaystyle \int \dfrac{1}{ax+b} \, \mathrm{d}x &= \dfrac{1}{a} \ln|ax+b| + C \\
\end{aligned}
$$

3.1. $\displaystyle \quad \dfrac{5}{2} \mathrm{e}^{2x+1} + C \:$ using the substitution $\: u = 2x+1 \:$ or the chain rule with $\: a=2$.

3.2. $\displaystyle \quad -\dfrac{7}{3} \mathrm{e}^{-3x+4} + C \:$ using the substitution $\: u = -3x+4 \:$ or the chain rule with $\: a=-3$.

3.3. $\displaystyle \quad \dfrac{1}{3} \mathrm{e}^{-3(x-2)} + C \:$ using the substitution $\: u = -3(x-2) \:$ or the chain rule with $\: a=-3$.

3.4. $\displaystyle \quad 6 \exp\left( \dfrac{x}{3} - 5 \right) + C \:$ using the substitution $\: u = \dfrac{x}{3} - 5 \:$ or the chain rule with $\: a=\dfrac{1}{3}$.

3.5. $\displaystyle \quad 2 \ln|3x-7| + C \:$ using the substitution $\: u = 3x-7 \:$ or the chain rule with $\: a=3$.

3.6. $\displaystyle \quad -2 \ln|5-2x| + C \:$ using the substitution $\: u = 5-2x \:$ or the chain rule with $\: a=-2$.

3.7. $\displaystyle \quad \dfrac{3}{2} \ln|2x+5| + C \:$ using the substitution $\: u = 2x+5 \:$ or the chain rule with $\: a=2$.

3.8. $\displaystyle \quad -\dfrac{3}{5} \ln|5(x-2)+1| + C \:$ using the substitution $\: u = 5(x-2)+1 \:$ or the chain rule with $\: a=5$.

### Q4 {.unnumbered}

4.1. $\displaystyle \quad \dfrac{1}{5}(3x^{2}+2)^{5}+C \:$ using the substitution $\: u = 3x^{2}+2 \:$.

4.2. $\displaystyle \quad \dfrac{1}{4}(5x-7)^{4}+C \:$ using the substitution $\: u = 5x-7 \:$.

4.3. $\displaystyle \quad \exp(4x^{2}-1)+C \:$ using the substitution $\: u = 4x^{2}-1 \:$.

4.4. $\displaystyle \quad -\dfrac{1}{x^{2}+x+5}+C \:$ using the substitution $\: u = x^{2}+x+5 \:$.

4.5. $\displaystyle \quad \sin(3x^{2}+2)+C \:$ using the substitution $\: u = 3x^{2}+2 \:$.

4.6. $\displaystyle \quad \exp(x^{2}+3x)+C \:$ using the substitution $\: u = x^{2}+3x \:$.

4.7. $\displaystyle \quad -\dfrac{1}{\sqrt{x^{2}+1}}+C \:$ using the substitution $\: u = x^{2}+1 \:$.

4.8. $\displaystyle \quad \dfrac{1}{10} \ln | 2\mathrm{e}^{5x}+3 | +C \:$ using the substitution $\: u = 2\mathrm{e}^{5x}+3 \:$.

4.9. $\displaystyle \quad -\cos(4-2x^{2})+C \:$ using the substitution $\: u = 4-2x^{2} \:$.

4.10. $\displaystyle \quad -\dfrac{1}{x^{3}+1}+C \:$ using the substitution $\: u = x^{3}+1 \:$.

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
