---
title: "Answers: Introduction to algebraic fractions"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the introduction to algebraic fractions.
---

*These are the answers to [Questions: Introduction to algebraic fractions](../questions/qs-introtoalgebraicfractions.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {.unnumbered}

1.1. $\displaystyle \quad x \neq 0$

1.2. $\displaystyle \quad x \neq 4$

1.3. $\displaystyle \quad x \neq -\dfrac{1}{2}$

1.4. $\displaystyle \quad y \neq -5$

1.5. $\displaystyle \quad x \neq 0$ and $x \neq \dfrac{2}{3}$

1.6. $\displaystyle \quad t \neq -2$ and $t \neq 3$

1.7. $\displaystyle \quad x \neq -4$ and $x \neq 4$

1.8. $\displaystyle \quad x \neq 1$

1.9. $\displaystyle \quad b \neq -4$ and $b \neq 0$

1.10. $\displaystyle \quad x \neq -3$ and $x \neq \dfrac{5}{2}$

1.11. $\displaystyle \quad x \neq 2$ and $x \neq 3$

1.12. $\displaystyle \quad z \neq -4$ and $z \neq 2$

## Q2 {.unnumbered}

2.1. $\displaystyle \quad 3x$

2.2. $\displaystyle \quad 5t$

2.3. $\displaystyle \quad 3a + 3$

2.4. $\displaystyle \quad 12x$

2.5. $\displaystyle \quad 10$

2.6. $\displaystyle \quad 2t - 6$

2.7. $\displaystyle \quad 3y - 3$

2.8. $\displaystyle \quad 3x$

2.9. $\displaystyle \quad 6x$

2.10. $\displaystyle \quad 6z - 3$

2.11. $\displaystyle \quad x(x+1)$

2.12. $\displaystyle \quad r^2 + r - 6$

2.13. $\displaystyle \quad 4x(x+1)$

2.14. $\displaystyle \quad 3x - 15$

2.15. $\displaystyle \quad 2z - 10$

## Q3 {.unnumbered}

3.1. $\displaystyle \quad \dfrac{2}{3}$ if $y\neq 0$

3.2. $\displaystyle \quad \dfrac{x}{3}$ if $x\neq 0$

3.3. $\displaystyle \quad n + 4$ if $n\neq 0$

3.4. $\displaystyle \quad \dfrac{x-3}{2}$ if $x\neq 0$

3.5. $\displaystyle \quad -\dfrac{2}{5}$ if $x\neq 0$

3.6. $\displaystyle \quad m + 4$ if $m\neq 4$

3.7. $\displaystyle \quad x - 1$ if $x\neq -1$

3.8. $\displaystyle \quad x + 3$ if $x\neq -2$

3.9. $\displaystyle \quad z + 5$ if $z\neq 2$

3.10. $\displaystyle \quad 2x + 1$ if $x\neq -3$

3.11. $\displaystyle \quad y - 5$ if $y\neq 5$

3.12. $\displaystyle \quad -1$ if $x\neq 4$

3.13. $\displaystyle \quad 2$ if $x\neq -2$ and $x \neq 2$

3.14. $\displaystyle \quad c$ if $c\neq -2$ and $c \neq 2$

3.15. $\displaystyle \quad \dfrac{A+2}{A+5}$ if $A\neq -5$ and $A \neq 5$

---

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 12/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
