---
title: "Answers: Introduction to integration"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to integration.
---

*These are the answers to [Questions: Introduction to integration](../questions/qs-introtointegration.qmd).*

**Please attempt the questions before reading these answers!**

<!-- ANSWERS TO INTRO TO INTEGRATION -->

## Q1 {.unnumbered}

1.1. $\displaystyle \quad \int x^4 \, \mathrm{d}x = \dfrac{1}{5}x^5 + C$.

1.2. $\displaystyle \quad \int 2x \, \mathrm{d}x = x^2 + C$.

1.3. $\displaystyle \quad \int 7x^5 \, \mathrm{d}x = \dfrac{7}{6}x^6 + C$.

1.4. $\displaystyle \quad \int -5 \, \mathrm{d}t = -5t + C$.

1.5. $\displaystyle \quad \int \dfrac{3}{y^3} \, \mathrm{d}y = -\dfrac{3}{2}y^{-2} + C$.

1.6. $\displaystyle \quad \int 6x^{-4} \, \mathrm{d}x = -2x^{-3} + C$.

1.7. $\displaystyle \quad \int -\dfrac{2}{x^5} \, \mathrm{d}x = \dfrac{1}{2}x^{-4} + C$.

1.8. $\displaystyle \quad \int \dfrac{8}{3x^6} \, \mathrm{d}x = -\dfrac{8}{15}x^{-5} + C$.

1.9. $\displaystyle \quad \int -\dfrac{7}{2z^7} \, \mathrm{d}z = \dfrac{7}{12}z^{-6} + C$.

1.10. $\displaystyle \quad \int x^{1/3} \, \mathrm{d}x = \dfrac{3}{4} x^{4/3} + C$.

1.11. $\displaystyle \quad \int 3t^{-2/3} \, \mathrm{d}t = 9t^{1/3} + C$.

1.12. $\displaystyle \quad \int \dfrac{4x^{1/4}}{3} \, \mathrm{d}x = \dfrac{16}{15} x^{5/4} + C$.

1.13. $\displaystyle \quad \int \dfrac{2}{5x^{1/3}} \, \mathrm{d}x = \dfrac{3}{5} x^{2/3} + C$.

1.14. $\displaystyle \quad \int \dfrac{5}{6y^{-4/3}} \, \mathrm{d}y = \dfrac{5}{14} y^{7/3} + C$.

## Q5 {.unnumbered}

2.1. $\displaystyle \quad \int e^{2x} \, \mathrm{d}x =  \frac{1}{2}e^{2x} + C$

2.2. $\displaystyle \quad \int -3e^{-3x} \, \mathrm{d}x = e^{-3x} + C$

2.3. $\displaystyle \quad \int 2e^{11x} \, \mathrm{d}x = \frac{2}{11}e^{11x} + C$

2.4. $\displaystyle \quad \int \frac{4}{x} \, \mathrm{d}x = 4\ln|x| + C$

2.5. $\displaystyle \quad \int -\frac{5}{3x} \, \mathrm{d}x = -\frac{5}{3}\ln|x| + C$

2.6. $\displaystyle \quad \int \cos (x) \, \mathrm{d}x = \sin ( x ) + C$.

2.7. $\displaystyle \quad \int \sin ( 2x ) \, \mathrm{d}x = -\dfrac{1}{2} \cos ( 2x ) + C$.

2.8. $\displaystyle \quad \int \dfrac{5}{6} \cos ( x ) \, \mathrm{d}x = \dfrac{5}{6} \sin ( x ) + C$.

2.9. $\displaystyle \quad \int \cos ( 3x ) \, \mathrm{d}x = \dfrac{1}{3} \sin ( 3x ) + C$.

2.10. $\displaystyle \quad \int \sin \left( \dfrac{x}{3} \right) \, \mathrm{d}x = -3 \cos \left( \dfrac{x}{3} \right) + C$.

## Q3 {.unnumbered}

3.1. $\displaystyle \quad \int_{1}^{4} 2 \, \mathrm{d}x = 6$

3.2. $\displaystyle \quad \int_{-2}^{2} 3x \, \mathrm{d}x = 0$

3.3. $\displaystyle \quad \int_{2}^{4} 2x^3 \, \mathrm{d}x = 120$

3.4. $\displaystyle \quad \int_{1}^{27} \dfrac{4}{\sqrt[3]{x}} \, \mathrm{d}x = 48$

3.5. $\displaystyle \quad \int_{0}^{\ln(3)} 4e^x \, \mathrm{d}x = 8$

3.6. $\displaystyle \quad \int_{0}^{5} e^{-3x} \, \mathrm{d}x = \frac{1}{3}\left(1 - e^{-15}\right)$

3.7. $\displaystyle \quad \int_{1}^{2} -4e^{4x} \, \mathrm{d}x = e^4(1-e^4)$

3.8. $\displaystyle \quad \int_{1}^{2} \frac{2}{x} \, \mathrm{d}x = 2\ln(2)$

3.9. $\displaystyle \quad \int_{1}^{e^3} -\frac{4}{x} \, \mathrm{d}x = -12$

3.10. $\displaystyle \quad \int_{e^3}^{e^9} \frac{9}{5x} \, \mathrm{d}x = \frac{54}{5}$

3.11. $\displaystyle \quad \int_{0}^{\pi/2} \sin ( x ) \, \mathrm{d}x = 1$

3.12. $\displaystyle \quad \int_{0}^{\pi} \cos ( x ) \, \mathrm{d}x = 0$

3.13. $\displaystyle \quad \int_{0}^{\pi/4} \sin ( 2x ) \, \mathrm{d}x = \dfrac{1}{2}$

3.14. $\displaystyle \quad \int_{0}^{\pi/6} \cos(2x) \, \mathrm{d}x = \dfrac{\sqrt{3}}{4}$

3.15. $\displaystyle \quad \int_{-\pi/4}^{0} \sin(3x) \, \mathrm{d}x = -\dfrac{1}{3} - \dfrac{1}{3\sqrt{2}}$

---

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
