---
title: "Answers: Introduction to set theory"
author: "Holly Goldsmith"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to set theory.
draft: true
---

*These are the answers to [Questions: Introduction to set theory](../questions/qs-introtosettheory.qmd).* 

**Please attempt the questions before reading these answers!**

## Q1 {-}

1.1. This set is finite.

1.2. This set is countably infinite.

1.3. This set is finite.

1.4. This set is uncountable.

1.5. This set is uncountable.

1.6. This set is countably infinite.


## Q2 {-}

2.1. This is TRUE.

2.2. This is FALSE, as $2 \notin \{1, 3, 5, 6, 7, 16, 18, 20\}$.

2.3. This is FALSE, as $\frac{1}{3}, \frac{41}{2} \notin \mathbb{Z}$.

2.4. This is TRUE.

2.5. This is FALSE, as $(1.6, 5]$ is open on the left, so $1.6 \notin (1.6, 5]$.

2.6. This is TRUE.

2.7. This is FALSE, as $15$ is not even, so $15 \notin \{x: \frac{x}{2} \in \mathbb{Z}\}$.

2.8. This is TRUE, as $6, 18, 24$ and $27$ are all multiples of $3$.


## Q3 {-}

3.1.
$$
\mathcal{P}(A) =
\begin{aligned}
\{&\phantom{\,\ } \emptyset, \\
&\{1\},\ \{2\},\ \{3\}, \\
&\{1,2\},\ \{1,3\},\ \{2,3\}, \\
&\{1,2,3\}\}
\end{aligned}
$$
3.2.
$$
\mathcal{P}(B) =
\begin{aligned}
\{&\phantom{\,\ } \emptyset, \\
&\{\frac{1}{2}\},\ \{\frac{1}{3}\},\ \{\frac{1}{6}\}, \\
&\{\frac{1}{2},\frac{1}{3}\},\ \{\frac{1}{2},\frac{1}{6}\},\ \{\frac{1}{3},\frac{1}{6}\}, \\
&\{\frac{1}{2},\frac{1}{3},\frac{1}{6}\}\}
\end{aligned}
$$
3.3.
$$
\mathcal{P}(C) =
\begin{aligned}
\{&\phantom{\,\ } \emptyset, \\
&\{1\},\ \{3\},\ \{6\}, \{9\}, \\
&\{1,3\},\ \{1,6\},\ \{1,9\}, \{3, 6\}, \{3, 9\}, \{6, 9\}, \\
&\{1,3,6\}, \{1, 3, 9\}, \{1, 6, 9\}, \{3, 6, 9\}, \\
&\{1, 3, 6, 9\}\}
\end{aligned}
$$

3.4.
$$
\mathcal{P}(D) =
\begin{aligned}
\{&\phantom{\,\ } \emptyset, \\
&\{\emptyset\},\ \{4\}, \\
&\{\emptyset,4\}\}
\end{aligned}
$$

3.5.
$$
\mathcal{P}(E) =
\begin{aligned}
\{&\phantom{\,\ } \emptyset, \\
&\{4.5\},\ \{8\},\ \{9\}, \{10\}, \\
&\{4.5,8\},\ \{4.5,9\},\ \{4.5,10\}, \{8, 9\}, \{8, 10\}, \{9, 10\}, \\
&\{4.5,8,9\}, \{4.5, 8, 10\}, \{4.5, 9, 10\}, \{8, 9, 10\}, \\
&\{4.5, 8, 9, 10\}\}
\end{aligned}
$$

3.6.
$$
\mathcal{P}(F) =
\begin{aligned}
\{&\phantom{\,\ } \emptyset, \\
&\{\sqrt{2}\},\ \{5\},\ \{\frac{16}{3}\}, \{18.2\}, \\
&\{\sqrt{2},5\},\ \{\sqrt{2},\frac{16}{3}\},\ \{\sqrt{2},18.2\}, \{5, \frac{16}{3}\}, \{5, 18.2\}, \{\frac{16}{3}, 18.2\}, \\
&\{\sqrt{2},5,\frac{16}{3}\}, \{\sqrt{2}, 5, 18.2\}, \{\sqrt{2}, \frac{16}{3}, 18.2\}, \{5, \frac{16}{3}, 18.2\}, \\
&\{\sqrt{2}, 5, \frac{16}{3}, 18.2\}\}
\end{aligned}
$$

### Q4 {-}

4.1. $|\mathcal{P}(A)| = 2^{|\mathcal{P}(A)|} = 2^3 = 8$

4.2. $|\mathcal{P}(B)| = 2^{|\mathcal{P}(B)|} = 2^3 = 8$

4.3. $|\mathcal{P}(C)| = 2^{|\mathcal{P}(C)|} = 2^4 = 16$

4.4. $|\mathcal{P}(D)| = 2^{|\mathcal{P}(D)|} = 2^2 = 4$

4.5. $|\mathcal{P}(E)| = 2^{|\mathcal{P}(E)|} = 2^4 = 16$

4.6. $|\mathcal{P}(F)| = 2^{|\mathcal{P}(F)|} = 2^4 = 16$

---

---

## Version history and licensing {-}

v1.0: initial version created 09/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

