---
title: "Answers: Introduction to partial differentiation"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the introduction to partial differentiation.
---

*These are the answers to [Questions: Introduction to partial differentiation](../questions/qs-introtopartialdifferentiation.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {.unnumbered}

1.1. $\displaystyle \quad \dfrac{\partial f}{\partial x} = 2xy$ and $\displaystyle \dfrac{\partial f}{\partial y} = x^2 + 3y^2$.

1.2. $\displaystyle \quad \dfrac{\partial f}{\partial x} = 9x^2 + y$ and $\displaystyle \dfrac{\partial f}{\partial y} = x-8y^3$.

1.3. $\displaystyle \quad \dfrac{\partial f}{\partial x} = 2y \cos(2x)$ and $\displaystyle \dfrac{\partial f}{\partial y} = \sin(2x)$.

1.4. $\displaystyle \quad \dfrac{\partial f}{\partial x} = y e^{xy} + 4xy^3$ and $\displaystyle \dfrac{\partial f}{\partial y} = x e^{xy} + 6x^2y^2$.

1.5. $\displaystyle \quad \dfrac{\partial f}{\partial x} = \dfrac{1}{x} + \ln(y) + 3$ and $\displaystyle \dfrac{\partial f}{\partial y} = \dfrac{x}{y}$.

1.6. $\displaystyle \quad \dfrac{\partial f}{\partial x} = -\dfrac{y}{x^2} - \dfrac{1}{y}$ and $\displaystyle \dfrac{\partial f}{\partial y} = \dfrac{1}{x} + \dfrac{x}{y^2}$.

1.7. $\displaystyle \quad \dfrac{\partial f}{\partial x} = \exp(y^2)$ and $\displaystyle \dfrac{\partial f}{\partial y} = 2xy \exp(y^2)$.

1.8. $\displaystyle \quad \dfrac{\partial f}{\partial x} = \dfrac{x}{\sqrt{x^2+y^2}}$ and $\displaystyle \dfrac{\partial f}{\partial y} = \dfrac{y}{\sqrt{x^2+y^2}}$.

1.9. $\displaystyle \quad \dfrac{\partial f}{\partial x} = 12(3x+2y)^3$ and $\displaystyle \dfrac{\partial f}{\partial y} = 8(3x+2y)^3$.

1.10. $\displaystyle \quad \dfrac{\partial f}{\partial x} = y^2 \cos(xy)$ and $\displaystyle \dfrac{\partial f}{\partial y} = x \cos(xy) - x^2y \sin(xy)$.

1.11. $\displaystyle \quad \dfrac{\partial f}{\partial x} = 2x \cos(x^2+y^2)$ and $\displaystyle \dfrac{\partial f}{\partial y} = 2y \cos(x^2+y^2)$.

1.12. $\displaystyle \quad \dfrac{\partial f}{\partial x} = \dfrac{2xy^2}{1+x^2y^2}$ and $\displaystyle \dfrac{\partial f}{\partial y} = \dfrac{2x^2y}{1+x^2y^2}$.

1.13. $\displaystyle \quad \dfrac{\partial f}{\partial x} = 2xy \sin(z)$ and $\displaystyle \dfrac{\partial f}{\partial y} = x^2 \sin(z)$ and $\displaystyle \dfrac{\partial f}{\partial z} = x^2y \cos(z)$.

1.14. $\displaystyle \quad \dfrac{\partial f}{\partial x} = (y+z)(2x+y+z)$ and $\displaystyle \dfrac{\partial f}{\partial y} = (x+z)(x+2y+z)$ and $\displaystyle \dfrac{\partial f}{\partial z} = (x+y)(x+y+2z)$.

1.15. $\displaystyle \quad \dfrac{\partial f}{\partial x} = \dfrac{yz(y+z)}{(x+y+z)^2}$ and $\displaystyle \dfrac{\partial f}{\partial y} = \dfrac{xz(x+z)}{(x+y+z)^2}$ and $\displaystyle \dfrac{\partial f}{\partial z} = \dfrac{xy(x+y)}{(x+y+z)^2}$.

## Q2 {.unnumbered}

2.1. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x^2} = 2$ and $\displaystyle \dfrac{\partial^2 f}{\partial y^2} = -2$ so $\displaystyle \dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$.

2.2. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x^2} = 0$ and $\displaystyle \dfrac{\partial^2 f}{\partial y^2} = 0$ so $\displaystyle \dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$.

2.3. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x^2} = 6x$ and $\displaystyle \dfrac{\partial^2 f}{\partial y^2} = -6x$ so $\displaystyle \dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$.

2.4. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x^2} = -\cos(x)\sinh(y)$ and $\displaystyle \dfrac{\partial^2 f}{\partial y^2} = \cos(x)\sinh(y)$ so $\displaystyle \dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$.

2.5. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x^2} = e^x\sin(y)$ and $\displaystyle \dfrac{\partial^2 f}{\partial y^2} = -e^x\sin(y)$ so $\displaystyle \dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$.

2.6. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x^2} = \dfrac{2xy}{(x^2+y^2)^2}$ and $\displaystyle \dfrac{\partial^2 f}{\partial y^2} = -\dfrac{2xy}{(x^2+y^2)^2}$ so $\displaystyle \dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$.

2.7. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x^2} = \dfrac{2(y^2-x^2)}{(x^2+y^2)^2}$ and $\displaystyle \dfrac{\partial^2 f}{\partial y^2} = \dfrac{2(x^2-y^2)}{(x^2+y^2)^2}$ so $\displaystyle \dfrac{\partial^2 f}{\partial x^2} + \dfrac{\partial^2 f}{\partial y^2} = 0$.

## Q3 {.unnumbered}

3.1. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x \partial y} = 2x+2y$ and $\displaystyle \dfrac{\partial^2 f}{\partial y \partial x} = 2x+2y$ so $\displaystyle \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$.

3.2. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x \partial y} = -4x\sin(y)$ and $\displaystyle \dfrac{\partial^2 f}{\partial y \partial x} = -4x\sin(y)$ so $\displaystyle \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$.

3.3. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x \partial y} = 20(x+y)^3$ and $\displaystyle \dfrac{\partial^2 f}{\partial y \partial x} = 20(x+y)^3$ so $\displaystyle \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$.

3.4. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x \partial y} = -\dfrac{1}{(y+1)^2}$ and $\displaystyle \dfrac{\partial^2 f}{\partial y \partial x} = -\dfrac{1}{(y+1)^2}$ so $\displaystyle \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$.

3.5. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x \partial y} = -\dfrac{xy}{(x^2+y^2)^{3/2}}$ and $\displaystyle \dfrac{\partial^2 f}{\partial y \partial x} = -\dfrac{xy}{(x^2+y^2)^{3/2}}$ so $\displaystyle \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$.

3.6. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x \partial y} = 2x\cos(y) - 2y\sin(x)$ and $\displaystyle \dfrac{\partial^2 f}{\partial y \partial x} = 2x\cos(y) - 2y\sin(x)$ so $\displaystyle \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$.

3.7. $\displaystyle \quad \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{1-(xy)^2}{(1+(xy)^2)^2}$ and $\displaystyle \dfrac{\partial^2 f}{\partial y \partial x} = \dfrac{1-(xy)^2}{(1+(xy)^2)^2}$ so $\displaystyle \dfrac{\partial^2 f}{\partial x \partial y} = \dfrac{\partial^2 f}{\partial y \partial x}$.

---

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
