---
title: "Answers: Introduction to vectors"
author: "Zheng Chen"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to vectors.
---

*These are the answers to [Questions: Introduction to vectors](../questions/qs-introductiontovectors.qmd).* 

**Please attempt the questions before reading these answers!**

<!-- ## Q1 {.unnumbered} -->

<!-- Are these vectors parallel? -->

<!-- 1.1. $\overrightarrow{CD}=\begin{bmatrix}6\\2\end{bmatrix}=2\begin{bmatrix}3\\1\end{bmatrix}$ so $\overrightarrow{CD}$ is a multiple of $\overrightarrow{AB}$ so they are parallel to each other. -->

<!-- 1.2. You can use factorisation to get $\overrightarrow{EF}=\begin{bmatrix}6x\\-3y\end{bmatrix}=3\begin{bmatrix}2x\\-y\end{bmatrix}$ thus showing that it is a multiple and therefore parallel. -->

<!-- 1.3. You can show that $\overrightarrow{BC}=\begin{bmatrix}8\\-4\end{bmatrix}=4\begin{bmatrix}2\\-1\end{bmatrix}$ therefore being a multiple, so they are parallel. -->

<!-- 1.4. Since $\begin{bmatrix}4\\2\\0\end{bmatrix}$ is not a multiple of $\begin{bmatrix}8\\-4\\0\end{bmatrix}$, so $\overrightarrow{DE}$ is not parallel to $\overrightarrow{BC}$. -->

<!-- 1.5.  $\overrightarrow{MO}=\begin{bmatrix}6\\8\\10\end{bmatrix}=-2\begin{bmatrix}-3\\-4\\-5\end{bmatrix}$ so they are parallel. -->


## Q1 {-}

1.1. $|\mathbf{a}| = \sqrt{(-1)^2 + 3^2} = \sqrt{1+9} = \sqrt{10}$

1.2. $|\mathbf{b}| = \sqrt{2^2+4^2+6^2} = \sqrt{4+16+36} = \sqrt{56} = 2\sqrt{14}$

1.3. $|\mathbf{c}| = \sqrt{1^2+(-1)^2+4^2} = \sqrt{1+1+16} = \sqrt{18} = 3\sqrt{2}$

1.4. $|\mathbf{d}| = \sqrt{5^2+(-2)^2+1^2} = \sqrt{25+4+1} = \sqrt{30}$

1.5. $|\mathbf{e}| = \sqrt{2^2+(-1)^2+4^2} = \sqrt{4+1+16} = \sqrt{21}$

1.6. $|\mathbf{f}| = \sqrt{(-3)^2+6^2+2^2} = \sqrt{9+36+4} = \sqrt{49} = 7$

1.7. $|\mathbf{g}| = \sqrt{5^2+1^2+(\sqrt{2})^2} = \sqrt{25+1+2} = \sqrt{28} = 2\sqrt{7}$

1.8. $|\mathbf{h}| = \sqrt{6^2+2^2+2^2} = \sqrt{36+4+4} = \sqrt{44} = 2\sqrt{11}$

1.9. $|\mathbf{m}| = \sqrt{(-3)^2+3^2+(-3)^2} = \sqrt{9+9+9} = \sqrt{27} = 3\sqrt{3}$

1.10. $|\mathbf{n}| = \sqrt{2^2+4^2+4^2} = \sqrt{4+16+16} = \sqrt{36} = 6$

1.11. $|\mathbf{p}| = \sqrt{8^2+(-2)^2+16^2} = \sqrt{64+4+256} = \sqrt{324} = 18$

1.12. $|\mathbf{q}| = \sqrt{5^2+(-2)^2+14^2} = \sqrt{25+4+196} = \sqrt{225} = 15$

1.13. $|\mathbf{u}| = \sqrt{7^2+2^2+(-1)^2} = \sqrt{49+4+1} = \sqrt{54} = 3\sqrt{6}$

1.14. $|\mathbf{v}| = \sqrt{12^2+9^2+8^2} = \sqrt{144+81+64} = \sqrt{289} = 17$


## Q2 {-}

2.1. Find the magnitude of the vector first, so $|\mathbf{a}| =\sqrt{(-2)^2+3^2}=\sqrt{13}$. 

Then $$\hat{\mathbf{a}}=\frac{-2\mathbf{i}+3\mathbf{j}}{\sqrt{13}}=\frac{-2}{\sqrt{13}}\mathbf{i}+\frac{3}{\sqrt{13}}\mathbf{j}$$

 

2.2. Find the magnitude of the vector first, so $|\mathbf{b}| =\sqrt{(-2)^2+4^2+(-6)^2}=\sqrt{56}=2\sqrt{14}$.

Then $$\hat{\mathbf{b}}=\frac{-2\mathbf{i}+4\mathbf{j}-6\mathbf{k}}{2\sqrt{14}}=\frac{-1}{\sqrt{14}}\mathbf{i}+\frac{2}{\sqrt{14}}\mathbf{j}-\frac{3}{\sqrt{14}}\mathbf{k}$$

 

2.3. Find the magnitude of the vector first, so $|\mathbf{c}| =\sqrt{1^2+2^2+4^2}=\sqrt{21}$.

Then $$\hat{\mathbf{c}}=\frac{\mathbf{i}+2\mathbf{j}+4\mathbf{k}}{\sqrt{21}}=\frac{1}{\sqrt{21}}\mathbf{i}+\frac{2}{\sqrt{21}}\mathbf{j}+\frac{4}{\sqrt{21}}\mathbf{k}$$

 

2.4. Find the magnitude of the vector first, so $|\mathbf{d}| =\sqrt{4^2+(-2)^2+3^2}=\sqrt{29}$. 

Then $$\hat{\mathbf{d}}=\frac{4\mathbf{i}-2\mathbf{j}+3\mathbf{k}}{\sqrt{29}}=\frac{4}{\sqrt{29}}\mathbf{i}-\frac{2}{\sqrt{29}}\mathbf{j}+\frac{3}{\sqrt{29}}\mathbf{k}$$

 

2.5. Find the magnitude of the vector first, so $|\mathbf{e}| =\sqrt{3^2+2^2}=\sqrt{13}$. 

Then $$\hat{\mathbf{e}}=\frac{3\mathbf{i}+2\mathbf{k}}{\sqrt{13}}=\frac{3}{\sqrt{13}}\mathbf{i}+\frac{2}{\sqrt{13}}\mathbf{k}$$

 

2.6. Find the magnitude of the vector first, so $|\mathbf{f}| =\sqrt{(-3)^2+1^2+7^2}=\sqrt{59}$. 

Then $$\hat{\mathbf{f}}=\frac{-3\mathbf{i}+\mathbf{j}+7\mathbf{k}}{\sqrt{59}}=-\frac{3}{\sqrt{59}}\mathbf{i}+\frac{1}{\sqrt{59}}\mathbf{j}+\frac{7}{\sqrt{59}}\mathbf{k}$$

 

2.7. Find the magnitude of the vector first, so $|\mathbf{g}| =\sqrt{(-5)^2+(\sqrt{2})^2}=\sqrt{27}=3\sqrt{3}$. 

Then $$\hat{\mathbf{g}}=\frac{-5\mathbf{i}+\sqrt{2}\mathbf{k}}{3\sqrt{3}}=-\frac{5}{3\sqrt{3}}\mathbf{i}+\frac{\sqrt{2}}{3\sqrt{3}}\mathbf{k}$$

 

2.8. Find the magnitude of the vector first, so $|\mathbf{h}| =\sqrt{(-3)^2+1^2+1^2}=\sqrt{11}$. 

Then $$\hat{\mathbf{h}}=\frac{-3\mathbf{i}+\mathbf{j}+\mathbf{k}}{\sqrt{11}}=\frac{-3}{\sqrt{11}}\mathbf{i}+\frac{1}{\sqrt{11}}\mathbf{j}+\frac{1}{\sqrt{11}}\mathbf{k}$$

 

2.9. Find the magnitude of the vector first, so $|\mathbf{m}| =\sqrt{(-3)^2+3^2+(-3)^2}=\sqrt{27}=3\sqrt{3}$. 

Then $$\hat{\mathbf{m}}=\frac{-3\mathbf{i}+3\mathbf{j}-3\mathbf{k}}{3\sqrt{3}}=-\frac{1}{\sqrt{3}}\mathbf{i}+\frac{1}{\sqrt{3}}\mathbf{j}-\frac{1}{\sqrt{3}}\mathbf{k}$$

 

2.10. Find the magnitude of the vector first, so $|\mathbf{n}| =\sqrt{3^2+6^2+9^2}=\sqrt{126}=3\sqrt{14}$. 

Then $$\hat{\mathbf{n}}=\frac{3\mathbf{i}+6\mathbf{j}+9\mathbf{k}}{3\sqrt{14}}=\frac{1}{\sqrt{14}}\mathbf{i}+\frac{2}{\sqrt{14}}\mathbf{j}+\frac{3}{\sqrt{14}}\mathbf{k}$$

 

2.11. Find the magnitude of the vector first, so $|\mathbf{p}| =\sqrt{3^2+(-4)^2+(-5)^2}=\sqrt{50}=5\sqrt{2}$. 

Then $$\hat{\mathbf{p}}=\frac{3\mathbf{i}-4\mathbf{j}-5\mathbf{k}}{5\sqrt{2}}=\frac{3}{5\sqrt{2}}\mathbf{i}-\frac{4}{5\sqrt{2}}\mathbf{j}-\frac{1}{\sqrt{2}}\mathbf{k}$$

 

2.12. Find the magnitude of the vector first, so $|\mathbf{q}| =\sqrt{4^2+(-3)^2+12^2}=\sqrt{169}=13$. 

Then $$\hat{\mathbf{q}}=\frac{4\mathbf{i}-3\mathbf{j}+12\mathbf{k}}{13}=\frac{4}{13}\mathbf{i}-\frac{3}{13}\mathbf{j}+\frac{12}{13}\mathbf{k}$$

 

2.13. Find the magnitude of the vector first, so $|\mathbf{u}| =\sqrt{6^2+5^2+4^2}=\sqrt{77}=$. 

Then $$\hat{\mathbf{u}}=\frac{6\mathbf{i}+5\mathbf{j}+4\mathbf{k}}{\sqrt{77}}=\frac{6}{\sqrt{77}}\mathbf{i}+\frac{5}{\sqrt{77}}\mathbf{j}+\frac{4}{\sqrt{77}}\mathbf{k}$$

 

2.14. Find the magnitude of the vector first, so $|\mathbf{v}| =\sqrt{2^2+4^2+8^2}=\sqrt{84}=2\sqrt{21}$. 

Then $$\hat{\mathbf{v}}=\frac{2\mathbf{i}+4\mathbf{j}+8\mathbf{k}}{2\sqrt{21}}=\frac{1}{\sqrt{21}}\mathbf{i}+\frac{2}{\sqrt{21}}\mathbf{j}+\frac{4}{\sqrt{21}}\mathbf{k}$$

---

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Zheng Chen as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
