---
title: "Answers: Introduction to differentiation and the derivative"
author: "Sara Delgado Garcia"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to differentiation and the derivative.
---

*These are the answers to [Questions: Introduction to differentiation and the derivative](../questions/qs-introtodifferentiation.qmd).* 

**Please attempt the questions before reading these answers!**

1.1. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(x^3+5x-3\right)=3x^2+5.$

1.2. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(5x\right)=5.$

1.3. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(-5\sqrt{x}\right)=-5\cdot\frac{1}{2}x^{-1/2}=-\frac{5}{2\sqrt{x}}.$

1.4. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(-\sin(x)\right)=-\cos(x).$

1.5. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\cos x+5\right)=-\sin(x).$

1.6. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(2\sqrt{x}\right)=2\cdot\frac{1}{2}x^{-1/2}=\frac{1}{\sqrt{x}}.$

1.7. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(2\ln(2x)+x^5\right)=\frac{2}{x}+5x^4.$

1.8. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln(5x)\right)=\frac{1}{5x}\cdot5=\frac{1}{x}.$

1.9. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(e^{-x}\right)=e^{-x}\cdot(-1)=-e^{-x}.$

1.10. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(23x+5\right)=23.$

1.11. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(4x+100\right)=4.$

1.12. For $\displaystyle \sinh(5x)= \frac{e^{5x} - e^{-5x}}{2}$, it follows that $$\dfrac{\mathrm{d}}{\mathrm{d}x}\left(\sinh(5x)\right)=5 \frac{e^{5x} +e^{-5x}}{2} = 5\cosh(5x)$$ since $\displaystyle\cosh(x) = \frac{e^x +e^{-x}}{2}$.

1.13. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\cos(3x)-\sin(2x)\right)=-3\sin(3x)-2\cos(2x).$

1.14. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln(x)+\cos(x)+3x\right)=\frac{1}{x}-\sin(x)+3.$

1.15. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{2}{5}\sinh(x)+\frac{2}{13}\cosh(x)\right)=\frac{2}{5}\cosh(x)+\frac{2}{13}\sinh(x).$

1.16. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(e^{5x}+x^2+3\right)=5e^{5x}+2x.$

1.17. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln(x)+x^2\right)=\frac{1}{x}+2x.$

1.18. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln(5x)-\ln(x)\right)=\frac{1}{x}-\frac{1}{x}=0.$

1.19. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\cosh(x)-5x^7\right)= \sinh(x)-35x^6.$

1.20. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\sqrt{3x^2}\right)=\sqrt{3}$

1.21. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(x^3+3x-\sqrt{2x}\right)=3x^2+3-\frac{1}{\sqrt{2x}}.$

---

---

## Version history and licensing {-}

v1.0: initial version created 03/25 by Sara Delgado Garcia as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

