---
title: "Answers: Introduction to factorials, permutations, and combinations"
author: "Jessica Taberner"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to factorials, permutations, and combinations.
draft: true
---

*These are the answers to [Questions: Introduction to factorials, permutations, and combinations.](../questions/qs-introtofactorials.qmd)*

**Please attempt the questions before reading these answers!**

## Q1 Factorials{-}

**1.1.** 

(a) There are $120$ ways of listing the $5$ different types of bonbons.

(b) There are $5040$ ways of listing the $7$ different types of jelly sweets.

(c) There are $24$ ways of listing the $4$ different types of fudge.

**1.2.** There are $20922789888000$ ways of listing all $16$ different types of sweets.

**1.3.** There are $87091200$ ways of listing the $16$ different types of sweets, if you want to keep all sweets of a certain type together.

## Q2 Permutations{.unnumbered}


**2.1.**

(a) If there are $6$ types of gumdrops sold at Lovelace's Lollies, but only $3$ spots on the shelf for these, there are $120$ ways you could organize the sweets.

(b) If there are $7$ types of liquorice, but only $2$ spots on the shelf for these, there are $42$ ways you could organize the sweets.

(c) If there are $10$ types of fizzy sweets, but only $6$ spots on the shelf for these, there are $151200$ ways you could organize the sweets.

**2.2.** Combining all $3$ of these types of sweets, you can organize the $21$ different kinds of sweets into the $11$ available spots in $41508446720000$ different ways.

**2.3.** If you want to include at least $2$ of each type, there are $980755776000$ ways to organize the sweets.

## Q3 Combinations {.unnumbered}

**3.1.**

(a) If there are $8$ types of lollies sold at Cantor's Confectionery, there are $28$ ways you could pick $2$.

(b) If there are $4$ types of chocolate, there are $4$ ways you could pick $3$.

(c) If there are $12$ types of marshmallow, there are $494$ ways you could pick $4$.

**3.2.** Combining all $3$ of these different types of sweets, there are $346104$ ways you could pick $7$.

**3.3.** Assuming you don't want all $7$ to be marshmallows or lollies, there are $345304$ ways to pick.

## Q4 Counting Strategies {.unnumbered}


**4.1.** If Lovelace's Lollies sells $3$ red sweets, $3$ yellow sweets, and $2$ blue sweets, and you want to arrange them without having all $3$ red sweets together, there are $36000$ ways to do this. That is $8!-(3!\cdot 6!)$, all possible permutations, take away the permutations where the red sweets are together.

**4.2.** For a display in Cantor's Confectionery, if you want to arrange the $8$ bonbons in a circle, there are $5040$ ways to do this.

**4.3.** If you want to stock $3$ kinds of lollies and $4$ kinds of jelly sweets, making sure no $2$ lollies are next to each other, there are $1440$ ways to do this.

**4.4.** If there are $10$ different types of sweets, including $5$ kinds of fizzy sweets, and you want to arrange these sweets on the shelf, but you want to keep all the fizzy sweets together, there are $86400$ ways to do this.

**4.5.** If there are $12$ different types of sweets, $4$ of which are fudge, and you want to pick $6$ sweets, including at least $2$ different types of fudge, there are $1260$ ways to do this.

## Version history and licensing {-}

v1.0: initial version created 02/26 by Jessica Taberner as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
