---
title: "Answers: Introduction to quadratic equations"
author: "Tom Coleman"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to quadratic equations.

---

*These are the answers to [Questions: Introduction to quadratic equations](../questions/qs-introtoquadratics.qmd).* 

**Please attempt the questions before reading these answers!**

## Q1 {-}

For each of the quadratic equations below, identify the variable and the coefficients $a,b,c$.

1.1. For $x^2 - 7x + 6 = 0$, the variable is $x$, and the coefficients are $a = 1,b= -7, c=6$.

1.2. For $y^2 + 14y + 49 = 0$, the variable is $y$, and the coefficients are $a = 1,b= 14, c=49$.

1.3. For $h^2 - h - 56 = 0$, the variable is $h$, and the coefficients are $a = 1,b= -1, c= -56$.

1.4. For $7y^4 - y^2 = 0$, the variable is $y^2$, and the coefficients are $a = 7, b=-1,c=0$.

1.5. For $5n^2 - 14n + 100 = 0$, the variable is $n$, and the coefficients are $a = 5, b=-14,c=100$. 

1.6. For $A^2 - 144 = 0$, the variable is $A$, and the coefficients are $a = 1, b=0,c=-144$. 

1.7. For $25M^2= 0$, the variable is $M$, and the coefficients are $a = 25, b=0,c=0$. 

1.8. For $e^{2x} - 4e^x + 4 = 0$, the variable is $e^x$, and the coefficients are $a = 1, b=-4,c=4$. 

1.9. For $-9s^4 + 3s^2 - 1 = 0$, the variable is $s^2$, and the coefficients are $a = -9, b=3,c=-1$.

1.10. For $2e^{6x} + e^{3x} + 1 = 0$, the variable is $e^{3x}$, and the coefficients are $a = 2, b=1,c=1$.

1.11. For $\cos^2(x) + 4\cos(x) - 4 = 0$, the variable is $\cos(x)$, and the coefficients are $a = 1, b=4,c=-4$.

1.12. For $8x^8 - 4x^4 - 1 = 0$, the variable is $x^4$, and the coefficients are $a = 8, b=-4,c=-1$.


## Q2 {-}

2.1. The discriminant of the equation $x^2 - 7x + 6 = 0$ is $D = 25$, and therefore the equation has two distinct real roots. 

2.2. The discriminant of the equation $y^2 + 14y + 49 = 0$ is $D = 0$, and therefore the equation has one distinct real root.

2.3. The discriminant of the equation $h^2 - h - 56 = 0$ is $D = 217$, and therefore the equation has two distinct real roots. 

2.4. The discriminant of the equation $7y^4 - y^2 = 0$ is $D = 1$, and therefore the equation has two distinct real roots. 

2.5. The discriminant of the equation $5n^2 - 14n + 100 = 0$ is $D = -1804$, and therefore the equation has no real roots (two distinct complex roots).

2.6. The discriminant of the equation $A^2 - 144 = 0$ is $D = 576$, and therefore the equation has two distinct real roots. 

2.7. The discriminant of the equation $25M^2 = 0$ is $D = 0$, and therefore the equation has one distinct real root. 

2.8. The discriminant of the equation $e^{2x} - 4e^x + 4 = 0$ is $D = 0$, and therefore the equation has one distinct real root $r$ in $e^x$. Whether or not it has a real root in $x$ depends on whether or not $r$ is positive. If $r$ is positive, there is exactly one real root $x = \ln(r)$; if $r$ is negative, then there are no real roots.

2.9. The discriminant of the equation $-9s^4 + 3s^2 - 1 = 0$ is $D = -27$, and therefore the equation has no real roots. This is true even with $s^2$ as the variable, as if $s^2$ is complex then $s$ must also be complex. 

2.10. The discriminant of the equation $2e^{6x} + e^{3x} + 1 = 0$ is $D = -7$, and therefore the equation has no real roots. This is true even with $e^{3x}$ as the variable, as if $e^{3x}$ is complex then $x$ must also be complex.

2.11. The discriminant of the equation $\cos^2(x) + 4\cos(x) - 4 = 0$ is $D = 32$, and therefore the equation has two distinct real roots $r_1$ and $r_2$ in $\cos(x)$. Whether or not it has a real root in $x$ depends on whether or not either of the roots is between $-1$ and $1$. If both $r_1$ and $r_2$ are outside this range, then there are no real roots. If one of $r_1$ or $r_2$ is between $-1$ and $1$, then there are infinitely many solutions.

2.12. The discriminant of the equation $8x^8 - 4x^4 - 1 = 0$ is $D = 48$, and therefore the equation has two distinct real roots $r_1$ and $r_2$ in $x^4$. The amount of real roots depend on the signs of $r_1$ and $r_2$. 
  
  - If $r_1$ and $r_2$ are both positive, then there are four real roots in $x$. This is because $x^2 = \pm\sqrt{r_1}$ or $x^2 = \pm\sqrt{r_2}$; square rooting the positive terms gives the roots in $x$ as $\pm\sqrt{(\sqrt{r_1})} = \pm\sqrt[4]{r_1}$ and $\pm\sqrt{(\sqrt{r_2})} = \pm\sqrt[4]{r_2}$. Any other roots must be complex, since you are taking square roots of the negative numbers $-\sqrt{r_1}$ and $-\sqrt{r_2}$.
 
  - If exactly one of $r_1$ and $r_2$ is positive (say $r_i$), then there are two real roots in $x$ given by $\pm\sqrt[4]{r_i}$. All other roots are complex. 
  
  - If both $r_1$ and $r_2$ are negative, then then there are no real roots in $x$. 


## Q3 {-}

3.1. Rearranging gives $x^2 + x - 1 = 0$. The discriminant of this is $D = 5$, and therefore the equation has two distinct real roots. 

3.2. Rearranging gives $y^2 + 10 = 0$. The discriminant of this is $D = -40$, and therefore the equation has no real roots (two distinct complex roots).

3.3. Rearranging gives $4m^2 + 4m + 1 = 0$. The discriminant of this is $D = 0$, and therefore the equation has one distinct real root.

3.4. Rearranging gives $t^4 + 1 = 0$. The discriminant of this is $D = -4$, and therefore the equation has no real roots. This is true even with $t^2$ as the variable, as if $t^2$ is complex then $t$ must also be complex. 

3.5. Rearranging gives $5x^2 - 11x - 1 = 0$. The discriminant of this is $D = 101$, and therefore the equation has two distinct real roots. 

3.6. Rearranging gives $e^{2x} - 2e^x + 1 = 0$. The discriminant of this is $D = 0$, and therefore the equation has one distinct real root $r$ in $e^x$. Whether or not it has a real root in $x$ depends on whether or not $r$ is positive. If $r$ is positive, there is exactly one real root $x = \ln(r)$; if $r$ is negative, then there are no real roots.

---

---

## Version history and licensing {-}

v1.0: initial version created 04/23 by tdhc.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

