---
title: "Answers: Introduction to simultaneous equations"
author: "Ollie Brooke"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to simultaneous equations.
---

*These are the answers to [Questions: Introduction to simultaneous equations](../questions/qs-introtosimeqs.qmd).* 

**Please attempt the questions before reading these answers!**

<!-- ## Q1 {.unnumbered} -->

<!-- Find how many solutions exist for the following sets of simultaneous equations. -->

<!-- 1.1. The second equation is a multiple of the first. This means there are infinitely many solutions. -->

<!-- 1.2. The second equation is also a multiple of the first. Thus, there are infinitely many solutions. -->

<!-- 1.3. The two lines are not parallel and not multiples of each other, so they intersect at one point. There is one unique solution. -->


## Q1 {-}

1.1. The second equation is a multiple of the first. This means there are infinitely many solutions.

1.2. The second equation is also a multiple of the first. Thus, there are infinitely many solutions.

1.3. The two lines are not parallel and not multiples of each other, so they intersect at one point. There is one unique solution.

## Q2 {-}

2.1. $\quad x=4$ and $y=-3$. 

2.2. $\quad x=-2$ and $y=13$.

2.3. $\quad x=\dfrac{6}{13}$ and $y=\dfrac{69}{13}$. 

2.4. $\quad x=\dfrac{16}{5}$ and $y=\dfrac{12}{5}$.

2.5. $\quad x=\dfrac{73}{25}$ and $y=\dfrac{93}{25}$.

2.6. $\quad x=1$ and $y=5$.

2.7. $\quad x=\dfrac{19}{10}$ and $y=\dfrac{17}{10}$. 

## Q3 {-}

3.1. $\quad x=1$ and  $y=-2$.

3.2. $\quad x=-3$ and $y=-4$.

3.3. $\quad x=\dfrac{31}{24}$ and  $y=-\dfrac{1}{12}$.

3.4. $\quad x=3$ and $y=\dfrac{2}{3}$.

3.5. $\quad x=\dfrac{127}{44}$ and $y=\dfrac{3}{44}$.

3.6. $\quad x=-\dfrac{18}{49}$ and $y=\dfrac{39}{49}$.

3.7. $\quad x=\dfrac{32}{15}$ and $y=-\dfrac{11}{5}$.

## Q4 {-}

4.1. $\quad x=\dfrac{5}{3}$ and $y=-\dfrac{2}{3}$.

4.2. $\quad x=4$ and $y=0$.

4.3. $\quad x=\dfrac{88}{19}$ and $y=-\dfrac{1}{19}$.

4.4. $\quad x=\dfrac{47}{26}$ and $y=\dfrac{12}{13}$.

4.5. $\quad x=\dfrac{52}{11}$ and $y=-\dfrac{1}{11}$.

---

## Version history {-}

v1.0: initial version created 12/24 by Ollie Brooke as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

