---
title: "Answers: Introduction to Matrices"
author: "Jessica Taberner"
abstract-title: Summary
abstract: Answers to a selection of questions on matrices.
categories:
  - Key skills
  - Algebra
draft: true
---

These are the answers to Questions: Introduction to matrices.

**Please attempt the questions before reading these answers!**
 
# Q1 {-}

## Q1.1

1.1.1. $\quad$The matrix $A$ has dimension $2 \times  3$\

1.1.2. $\quad$The matrix $B$ has dimension $2 \times  2$\

1.1.3. $\quad$The matrix $C$ has dimension $3 \times  4$\

1.1.4. $\quad$The matrix $D$ has dimension $3 \times  2$\

1.1.5. $\quad$The matrix $E$ has dimension $3 \times  3$\

1.1.6. $\quad$The matrix $F$ has dimension $3 \times  3$\

1.1.7. $\quad$The matrix $G$ has dimension $5 \times  1$\

1.1.8. $\quad$The matrix $H$ has dimension $4 \times  3$


## Q1.2

1.2.1. $\quad a_{1,1} = 2$\

1.2.2. $\quad g_{4,1} = 8$\

1.2.3. $\quad d_{1,2} = -i$\

1.2.4. $\quad f_{3,2} = 0$\

1.2.5. $\quad b_{2,1} = 3$\

1.2.6. $\quad a_{1,2} = -1$\

1.2.7. $\quad c_{2,3} = i$\

1.2.8. $\quad e_{2,3} = -4$\

1.2.9. $\quad h_{3,1} = x$\

1.2.10. $\quad h_{1,3} = 4$\

1.2.11. $\quad e_{3,2} = -6$\

1.2.12. $\quad g_{1,1} = -1$


## Q1.3

1.3.1. $\quad diagA = (2,4)$\

1.3.2. $\quad diagC = (0, -\sqrt{2},-7)$\

1.3.3. $\quad diagE = (1,3,7)$\

1.3.4. $\quad diagG = (-1)$\

# Q2

## Q2.1

2.1.1. $\quad I + J = \begin{bmatrix} 2 \\ 4-\sqrt{5} + i \\ 2/3 + 2i \\ \pi - \sqrt{7} \end{bmatrix}$

2.1.2. $\quad L - K = \begin{bmatrix} -1 +\sqrt{3} & -2 & -1/2 \\ -10 & 7 - i & -3 \\ 3 & 7 -i & 10 - \pi \end{bmatrix}$

2.1.3. $\quad N + M = \begin{bmatrix} -\pi + 1 & -5/4 & 2 & 4+ 2i \\ 5 & -\sqrt{5} - i & x + \sqrt{2} & 1 \end{bmatrix}$

2.1.4. $\quad O - P = \begin{bmatrix} 1 - \sqrt{3} & 2 \\ 3 - \pi & -1 \\ 1 & -6i \end{bmatrix}$

2.1.5. $\quad 3I = \begin{bmatrix} 
9 \\
-3\sqrt{5} \\
6i \\
3\pi \end{bmatrix}$

2.1.6. $\quad -2J = \begin{bmatrix} 
2 \\
-8-2i \\
-4/3 \\
2\sqrt{7} 
\end{bmatrix}$

2.1.7. $\quad xK = \begin{bmatrix} 
x & -2x & 3x \\
4x & xi & -5x \\
6x & -7x & \pi x 
\end{bmatrix}$

2.1.8. $\quad -4L =\begin{bmatrix} 
\sqrt{3} & -4 & 5/2 \\
24 & -28 & 32 \\
-36 & 4i & -40 
\end{bmatrix}$

2.1.9. $\quad yM = \begin{bmatrix} 
y & -2y & 3y & 4y\\
5y & -yi & \sqrt{2}y & -6y
\end{bmatrix}$

2.1.10. $\quad 7N =\begin{bmatrix} 
-7\pi & 21/4 & -7 & 14i \\
0 & -7\sqrt{5} & 7x & 49 \end{bmatrix}$

2.1.11. $\quad (1/2) O = \begin{bmatrix} 
1/2 & -1 \\
3/2 & 2 \\
-5/2 & 1/2 i
\end{bmatrix}$

2.1.12. $\quad -4P =\begin{bmatrix} -4\sqrt{3} & 16 \\
-4\pi & -20 \\
24 & 28i \end{bmatrix}$

2.1.13. $\quad 3I+J =\begin{bmatrix} 8 \\
4 -3\sqrt{5} + i \\
2/3 + 6i \\
3\pi - \sqrt{7} \end{bmatrix}$

2.1.14. $\quad -2(K+L) = \begin{bmatrix} -2 -2\sqrt{3} & 12 & -11 \\
4 & -14 -2i & 26 \\
-30 & 14 =2i & -20-2\pi \end{bmatrix}$

2.1.15. $\quad N-4M = \begin{bmatrix} -4 -\pi & 35/4 & -13 & -16 + 2i \\
- 20 & -\sqrt{5} + 4i & x - 4\sqrt{2} & 31 \end{bmatrix}$

2.1.16. $\quad 5O-iP = \begin{bmatrix} 5 - i\sqrt{3} & -10 + 4i \\
15 - \pi i & 20 - 5i \\
-25 + 6i & 7+5i \end{bmatrix}$

# Q3

## Q3.1

3.1.1. $\quad Q   R = \begin{bmatrix} 27+\pi \end{bmatrix}$

3.1.2. $\quad R   Q = \begin{bmatrix} -2 & -3 & -1 & -4 \\
6 & 9 & 3 & 12 \\
2\pi & 3\pi & \pi & 4\pi \\
10& 15 & 5 &20 \end{bmatrix}$

3.1.3. $\quad S   T = \begin{bmatrix} -9 & 30 \\
13 & 18 \end{bmatrix}$

3.1.4. $\quad T   S = \begin{bmatrix} 23 & -34 & 31 \\
1 & -6 & 33 \\
-24 & 32 & -8 \end{bmatrix}$

3.1.5. $\quad U   V = \begin{bmatrix} 6-\sqrt{2} & 29/2 \\
-12+3\sqrt{2} & -59/2 \end{bmatrix}$

3.1.6. $\quad V   U = \begin{bmatrix} -3/2-\sqrt{2} & 2+2\sqrt{2} \\
18 & -22 \end{bmatrix}$

3.1.7. $\quad W   R =  = \begin{bmatrix} -3 + 7\pi \\
-45 + 5\pi \\
44 +3\sqrt{7} - 8\pi \end{bmatrix}$

3.1.8. $\quad S   W =  = \begin{bmatrix} -1 & 7 + 5\sqrt{7} & -48 & 57 + \pi\\
11 & -13 -\sqrt{7} & 22 & -33-3\pi \end{bmatrix}$

3.1.9. $\quad T   U = \begin{bmatrix} -23 & 34 \\
-1 & 6 \\
24 & -32 \end{bmatrix}$

3.1.10. $\quad T   V = \begin{bmatrix} 18-5\sqrt{2} & -89/2 \\
6+7\sqrt{2} & 21/2 \\
24 & 56 \end{bmatrix}$

3.1.11. $\quad T   X = \begin{bmatrix} 17 \\
29 \\
4 \end{bmatrix}$

3.1.12. $\quad U   X = \begin{bmatrix} -3 \\
10 \end{bmatrix}$

3.1.13. $\quad V   X = \begin{bmatrix} -1/4 + 4\sqrt{2} \\
31/2 \end{bmatrix}$

3.1.14. $\quad X   Q = \begin{bmatrix} -8 & 12 & 4 & 16 \\
1 & 3/2 & 1/2 & 2 \end{bmatrix}$

3.1.15. $\quad V   V = \begin{bmatrix} 1/2 & -7/2 -\sqrt{2} /2 \\
21+3\sqrt{2} & 95/2 \end{bmatrix}$

3.1.16. $\quad U   U = \begin{bmatrix} 7 & -10 \\
-15 & 22 \end{bmatrix}$

## Q3.2

3.2.1. $\quad U   X   Q = \begin{bmatrix} -6 & -9 & -3 & -12 \\
20 & 30 & 10 & 40 \end{bmatrix}$

3.2.2. $\quad U^3 = \begin{bmatrix} -37 & 54 \\
81 & -118 \end{bmatrix}$

3.2.3. $\quad S   T   U = \begin{bmatrix} 99 & -138 \\
41 & -46 \end{bmatrix}$

3.2.4. $\quad T   X   Q   R = \begin{bmatrix} 459 +17\pi \\
783 + 29\pi \\
108 +4\pi \end{bmatrix}$

## Q3.3

3.3.1. $\quad 3U   X = \begin{bmatrix} -18 \\
60 \end{bmatrix}$

3.3.2. $\quad (S   T)-2U = \begin{bmatrix} -11 & 26 \\
7 & 10 \end{bmatrix}$

3.3.3. $\quad W   R + T   X = \begin{bmatrix} 14+7\pi \\
-16 +5\pi \\
18+ 3\sqrt{7} -8\pi \end{bmatrix}$

3.3.4. $\quad -R   Q   R = \begin{bmatrix} 27+\pi \\
-81 -3\pi \\
-27\pi + \pi^2 \\
135+ 5\pi \end{bmatrix}$

3.3.5. $\quad (V+U)   X = \begin{bmatrix} -5-3\sqrt{2} \\
61 \end{bmatrix}$

3.3.6. $\quad 4U^2 + V^2 = \begin{bmatrix} 57/2 & -87/2 - \sqrt{2}/2 \\
-39+3\sqrt{2} & 271/2 \end{bmatrix}$

## Version history {-}

v1.0: initial version created 04/25 by ect6 (as part of a University of St Andrews VIP project)
  
