---
title: "Introduction to Logarithms: Answers"
author: "Zoe Gemmell"
abstract-title: Summary
abstract: Answers to questions relating to the study guide on Logarithms.

---

*These are answers to: [Questions: Introduction to Logarithms](qs-logarithms.qmd).* **Please attempt the questions before reading these answers!**

## Q1 {-}
For the following, find the value of $x$ if $x$ is a rational number:\
1.1. $\log_{7}(x) = 1$ rearranged gives $7^1=x$ so $x=7$\

1.2. $\log_{8}(x) = 3$ rearranged gives $8^3=x$ so $x=512$\

1.3. $\log_{12}(x) = 0$ rearranged gives $12^0=x$ so $x=1$\

1.4. $\log_{10}(100) = x$ rearranged gives $10^x=100$ so $x=2$\

1.5. $\log_{2}(17) = x$ rearranged gives $2^x=17$ but 17 is odd so this would not result in a rational number for $x$\

1.6. $\log_{4}(2) = x$ rearranged gives $4^x=2$ so $x=\dfrac{1}{2}$\

1.7. $\log_{3}(27) = x$ rearranged gives $3^x=27$ so $x=3$\

1.8. $\log_{10}(1) = x$ rearranged gives $10^x=1$ so $x=0$\

1.9. $\log_{x}(16) = 4$ rearranged gives $x^4=16$ so $x=\sqrt[4]{16}=2$\

1.10. $\log_{x}(49) = 2$ rearranged gives $x^2=49$ so $x=\sqrt{49}=7$\

1.11. $\log_{x}(13) = 4$ rearranged gives $x^4=13$ so $x=\sqrt[4]{13}$\

1.12. $\log_{2x}(12) = -1$ rearranged gives $(2x)^{-1}=12$ so $x=\dfrac{1}{24}$\

## Q2 {-}
Before attempting this question, write out the 5 laws next to their names:\

1. The Product Rule: $\log_{a}(M\cdot N)=\log_{a}(M)+\log_{a}(N)$\

2. The Quotient Rule: $\log_{a}\left(\dfrac{M}{N}\right)=\log_{a}(M)-\log_{a}(N)$\

3. The Power Rule: $\log_{a}(M^k)=k\cdot\log_{a}(M)$\

4. The Zero Rule: $\log_{a}(1)=0$\

5. The Identity Rule: $\log_{a}(a)=1$\

For the following, find the value of $x$ :\

2.1. $\log_{3}(\dfrac{1}{27}) = x$
\begin{align*}
x&=\log_{3}(1)-\log_{3}(27)\tag{\,Using Law 2} \\[0.5em]
&=0-\log_{3}(27)\tag{\,Using Law 4}\\[0.5em]
-x&=\log_{3}(27)
\end{align*}
Let $y=-x$, so Rearranging gives: $3^y=27$, so $y=3=-x$ implying that $x=-3$\

2.2. $\log_{4}(16) = x$\
\begin{align*}
x&=\log_{4}(4^2)\nonumber \\[0.5em]
&=2\cdot \log_{4}(4)\tag{\,Using Law 3} \\[0.5em]
&=2\cdot 1 \tag{\,Using Law 5} \\[0.5em]
&=2
\end{align*}

2.3. $\log_{7}\left(\dfrac{2}{49}\right) = x$\
\begin{align*}
x&=\log_{7}(2)-\log_{7}(49)\tag{\,Using Law 2} \\[0.5em]
&=\log_{7}(2)-2\nonumber \\[0.5em]
x+2&=\log_{3}(27)
\end{align*}
Rearranging gives: $3^{x+2}=27$, so $x+2=3$ implying that $x=1$\

2.4. $\log_{x}(YZ) = M$\
From question 1, $\log_{x}(YZ)=M$ rearranged gives $x^M=YZ$ so $x=\sqrt[M]{YZ}$\

2.5. $\log_{6}\left(\frac{36}{x}\right) = 1$\
\begin{align*}
1&=\log_{6}(36)-\log_{6}(x)\tag{\,Using Law 2} \\[0.5em]
&=2-\log_{6}(x)\nonumber \\[0.5em]
\log_{6}(x)&=1\nonumber \\[0.5em]
6^1&=x
\end{align*}

2.6. $\log_{5}(25)=x$\
\begin{align*}
x&=\log_{5}(5\cdot5)\tag{\,Using Law 1} \\[0.5em]
&=\log_{5}(5)+\log_{5}(5)\nonumber \\[0.5em]
&=1+1 \tag{\,Using Law 5} \\[0.5em]
&=2
\end{align*}

## Q3 {-}
Convert the following logs to the given base and evaluate\
3.1. $\log_3(25)$ to base $5$\
\begin{align*}
\log_3(25)=\dfrac{\log_5(25)}{\log_5(3)}\end{align*}

3.2. $\log_{4}(64)$  to base $16$\
\begin{align*}
\log_{4}(64)=\dfrac{\log_{16}(64)}{\log_{16}(4)}\end{align*}

3.3. $\log_{e}(100)$ to base $10$\
\begin{align*}
\log_{e}(100)=\dfrac{2}{\log_{10}(e)}\end{align*}

3.4. $\ln(27)$ to base $3$\
\begin{align*}
\ln(27)=\log_{3}(27)\end{align*}

3.5. $\log_{4}(8)$ to base $2$\
\begin{align*}
\log_{4}(8)=\dfrac{\log_{2}(8)}{\log_{2}(4)}=\dfrac{3}{2}\end{align*}

## Q4 {-}

For the following, find the value of $x$:\

4.1. $3^{x+1}=7^x$\
\begin{align*}
x=-\dfrac{\log(3)}{\log\left(\dfrac{7}{3}\right)}\end{align*}

4.2. $17^{2x}=4^{x-1}$\
\begin{align*}
x=\dfrac{\log(2)}{\log\left(\dfrac{2}{17}\right)}\end{align*}

4.3. $5^{x+1}+5^x=12$\
\begin{align*}
x=\dfrac{\log(2)}{\log(5)}\end{align*}

4.4. $2^{3x-1}=10^x$\
\begin{align*}
x=-\dfrac{\log(2)}{\log\left(\dfrac{5}{4}\right)}\end{align*}

4.5. $11^x=122^{(x-1)}$\
\begin{align*}
x=\dfrac{\log(122)}{\log\left(\dfrac{122}{11}\right)}\end{align*}

4.6. $2^{2x}-8\cdot2^x-16=0$\
\begin{align*}
x=2+\dfrac{log(1+\sqrt{2})}{log(2)}\end{align*}

---