---
title: "Answers: Laws of indices"
author: "Isabella Lewis, Akshat Srivastava"
abstract-title: Summary
abstract: Answers to questions relating to using laws of indices.
---

*These are the answers to [Questions: Laws of indices](../questions/qs-lawsofindices.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {-}

1.1. $3^4=81$
 
1.2. $125^{\frac{2}{3}}=5^2=25$
 
1.3. $32^{\frac{2}{5}}=2^2=4$
 
1.4. $729^{\frac{-2}{3}}=9^{-2}=\frac{1}{81}$
 
1.5. $4^3\cdot2^5=2^6\cdot2^5=2^{11}=2048$
 
1.6. $2^2\cdot3^2=(2\cdot3)^2=6^2$
 
1.7. $8^5\cdot6^5=(8\cdot6)^5=48^5$
 
1.8. $12^{6}\cdot 3^{6}=(12\cdot3)^{6}=36^{6} = 2176782336$
 
1.9. $\displaystyle \frac{9^2}{27^2}=3^{-2}=\frac{1}{9}$
 
1.10. $(5^2)^2=5^4=625$
 
1.11. $(35^0)^9=1$
 
1.12. $(35^9)^0=1$
 
1.13. $(729^9)^{\frac{1}{9}}=729^{\frac{9}{9}}=729$
 
1.14. $\displaystyle 7^{-3}= \frac{1}{7^3} = \frac{1}{343}$
 
1.15. $(\frac{4^5}{2^5})=(\frac{4}{2})^5=2^5$
 
1.16. $(\frac{2^{-2}}{13^{-2}})=(\frac{2}{13})^{-2}=(\frac{13}{2})^{2}$
 
1.17. $64^{\frac{4}{3}}=4^4=256$
 
1.18. $\displaystyle\left(\frac{4^3\cdot{3^3}}{6^3}\right)=\left(\frac{4\cdot3}{6}\right)^3=\left(\frac{12}{6}\right)^3=2^3=8$
 
1.19. $\left(\dfrac{4^2\cdot{8^2}}{2^2}\right)\cdot{\left(\dfrac{1}{2}\right)^2}={\left(\dfrac{4\cdot8}{2}\right)^2}\cdot{\left(\dfrac{1}{2}\right)^2}=\left(\dfrac{4\cdot8\cdot1}{2\cdot2}\right)^2=\left(\dfrac{32}{4}\right)^2=8^2=64$
 
1.20. $\displaystyle\dfrac{\left[\left(\frac{-2}{3}\right)^{-3}\cdot\left(\frac{-3}{5}\right)^{-3}\right]}{\left({\frac{2}{3}}\right)^{-3}}= \frac{\left({\frac{6}{15}}\right)^{-3}}{\left({\frac{2}{3}}\right)^{-3}}=\frac{\left({\frac{15}{6}}^{3}\right)}{\left({\frac{3}{2}}\right)^{3}}=\left(\frac{15\cdot2}{6\cdot3}\right)^3=\left(\frac{5}{3}\right)^3={\frac{125}{27}}$
 
1.21. $\displaystyle\dfrac{\left(\frac{1}{2}\right)^4\left(\frac{3}{5}\right)^4}{\left(\frac{8}{3}\right)^{4}}=\frac{\left(\frac{5}{6}\right)^{4}}{\left(\frac{8}{3}\right)^{4}}=\left(\frac{15}{48}\right)^4 = \left(\frac{5}{16}\right)^4 = \frac{625}{65536}$
 
1.22. $\displaystyle\left(\frac{2}{3}\right)^{14}\cdot\left(\frac{9}{12}\right)^{14}=\left(\left(\frac{2}{3}\right)\cdot\left(\frac{9}{12}\right)\right)^{14}=\left(\frac{18}{36}\right)^{14}=\left(\frac{1}{2}\right)^{14} = \frac{1}{16384}$


## Q2 {-}

2.1. $(b^{7})^{4}=b^{28}$
 

2.2. $y^{13}\cdot{y^{5}}=y^{18}$
 

2.3. $a^2\cdot b^2=(ab)^2$
 

2.4. $\dfrac{x^{13}}{x^5}=x^8$
 

2.5. $(3y^{-2})^5=(3)^5\cdot(y^{-2})^5=243y^{-10}$
 

2.6. $(a)^{-4}\cdot(b)^{-4}=(ab)^{-4}=\frac{1}{(ab)^4}$
 

2.7. $(7z^{-5})^3=(7)^3\cdot(z^{-5})^3=343z^{-15}$
 

2.8. $(\frac{8x^5}{4x^{-5}})=2x^{(5+5)}=2x^{10}$
 

2.9. $((x^{2})^3\cdot{x^{5}})=x^6\cdot{x^5}=x^{11}$
 

2.10. $\dfrac{2a^{-4}}{3a^{-2}}=\left(\dfrac{2}{3}\right)\cdot(a^{-4+2})=\dfrac{2}{3a^2}$
 

2.11. $\dfrac{x^5}{y^5}=\left(\dfrac{x}{y}\right)^5$
 

2.12. $\dfrac{2y^3}{2y^5}=y^{-2}$
 

2.13. $\displaystyle\left(\frac{2}{a}\right)^{4}\cdot\left(\frac{a}{12}\right)^{3}=\frac{2^4\cdot{a^3}}{a^4\cdot{12^3}}=\frac{16}{1728a}=\frac{1}{108a}$
 

2.14. $\dfrac{25t^{-4}}{60t^{5}}=\dfrac{5}{12t^9}$
 

2.15. $\displaystyle{\left(\frac{a}{b}\right)^{-4}}\cdot{\left(\frac{c}{d}\right)^4}\cdot{\left(\frac{e}{f}\right)^4}=\left(\frac{bce}{adf}\right)^4$
 

2.16. ${\dfrac{5^{x+1}\cdot6^{x+1}}{3^{x+1}}}=\left(\dfrac{5\cdot6}{3}\right)^{x+1}=10^{x+1}$
 

2.17. $\displaystyle a^{\frac{1}{2}}\cdot b^{-\frac{1}{2}}=\left(\frac{a}{b}\right)^{\frac{1}{2}}=\sqrt{\frac{a}{b}}$
 

2.18. $\left(\frac{a}{b}\right)^n\cdot\left(\frac{c}{d}\right)^{-n}=\left(\left(\frac{a}{b}\right)\cdot\left(\frac{d}{c}\right)\right)^n=\left(\frac{ad}{bc}\right)^n$

---
