---
title: "Answers: Multivariate implicit differentiation"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on multivariate implicit differentiation.
draft: true
---

*These are the answers to [Questions: Multivariate implicit differentiation](../questions/qs-multivariateimplicitdifferentiation.qmd).*

**Please attempt the questions before reading these answers!**

## Answers {.unnumbered}

### Q1 {.unnumbered}

1.1. $\quad$Implicit

1.2. $\quad$Explicit

1.3. $\quad$Explicit

1.4. $\quad$Implicit

1.5. $\quad$Explicit

1.6. $\quad$Implicit

1.7. $\quad$Explicit

1.8. $\quad$Implicit

1.9. $\quad$Explicit

1.10. $\quad$Implicit

### Q2 {.unnumbered}

2.1. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{x}{y}$

2.2. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{3x^2y}{x^3+3y^2}$

2.3. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{2}{5}x(y-1)^2$

2.4. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{y\cos(xy)+1}{x\cos(xy)-1}$

2.5. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{\mathrm{e}^{y}}{x\mathrm{e}^{y}+2y}$

2.6. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{2xy-3y^2}{x^2-6xy}$

2.7. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{y}{x}$

2.8. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = \dfrac{y}{x} + 2(x^2+y^2)$

2.9. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = \dfrac{y\sin(xy)+1}{3y^2-x\sin(xy)}$

2.10. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{\sin(y)-y\sin(x)}{x\cos(y)+\cos(x)}$

2.11. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -1$

2.12. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{y\mathrm{e}^{xy}+1}{x\mathrm{e}^{xy}-1}$

2.13. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{x^2-y}{y^2-x}$

2.14. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = -\dfrac{1}{4y\sqrt{x}}$

2.15. $\displaystyle \quad \dfrac{\mathrm{d}y}{\mathrm{d}x} = \dfrac{y}{x}+\dfrac{(x-y)^2}{2x^2}$

### Q3 {.unnumbered}

3.1. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{x}{z} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{y}{z}$.

3.2. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{4x-5xy}{3y^2z+3z^2} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{6yz^2-5x^2}{6y^2z+6z^2}$.

3.3. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{z}{x} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{z}{y}$.

3.4. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{z\mathrm{e}^{xz}}{x\mathrm{e}^{xz}-1} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{1}{x\mathrm{e}^{xz}-1}$.

3.5. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{z \cos(xz)}{x \cos(xz) - y \sin(yz)} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = \dfrac{z \sin(yz)}{x \cos(xz) - y \sin(yz)}$.

3.6. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{z}{x} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{z}{y}$.

3.7. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{x^2 - yz}{z^2 - xy} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{y^2 - xz}{z^2 - xy}$.

3.8. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{4xz^{3/2}}{2z^{1/2}(x^2 + y^2) + 1} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{4yz^{3/2}}{2z^{1/2}(x^2 + y^2) + 1}$.

3.9. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{(1+z^2)\mathrm{e}^{x}}{y^2(1+z^2)-1} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{2yz(1+z^2)}{y^2(1+z^2)-1}$.

3.10. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{z}{x(1-z)} - \dfrac{yz}{1-z} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{xz}{1-z}$.

3.11. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{\mathrm{e}^{yz} + yz \mathrm{e}^{xz}}{xy \mathrm{e}^{yz} + yx \mathrm{e}^{xz}} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{xz \mathrm{e}^{yz} + \mathrm{e}^{xz}}{xy \mathrm{e}^{yz} + yx \mathrm{e}^{xz}}$.

3.12. $\displaystyle \quad \dfrac{\partial z}{\partial x} = \dfrac{\cos(x) \cos(z)}{\sin(x)\sin(z) - 2yz} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = \dfrac{z^2}{\sin(x)\sin(z) - 2yz}$.

3.13. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{2x}{y \mathrm{e}^{z} + 1} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{\mathrm{e}^{z}}{y \mathrm{e}^{z} + 1}$.

3.14. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{z^2}{z-x-y} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{z^2}{z-x-y}$.

3.15. $\displaystyle \quad \dfrac{\partial z}{\partial x} = -\dfrac{yz+2\sqrt{xyz}}{xy-2\sqrt{xyz}} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial y} = -\dfrac{xz-2\sqrt{xyz}}{xy-2\sqrt{xyz}}$.

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
