---
title: "Answers: Multivariate chain rule"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the multivariate chain rule.
draft: true
---

*These are the answers to [Questions: Multivariate chain rule](../questions/qs-multivariatechainrule.qmd).*

**Please attempt the questions before reading these answers!**

## Answers {.unnumbered}

### Q1 {.unnumbered}

1.1. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = 2\mathrm{e}^{2t}\sin(t) \left( \cos(t) + \sin(t) \right)$

1.2. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \dfrac{3}{t} - \tan(t)$

1.3. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \dfrac{3}{2}t^{1/2} + 6t(t^2+1)^2$

1.4. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \exp(t\ln(t+1)) \left( \ln(t+1) + \dfrac{t}{t+1} \right) = \left( t+1 \right) ^t \left( \ln(t+1) + \dfrac{t}{t+1} \right)$

1.5. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = -\sin(t)\tan(t^2) + 2t \cos(t)\sec^2(t^2)$

1.6. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = 8t - 4 + 30\sin(t) + 5\cos(t) \left( 6t - 3 + 75 \sin^2(t) \right)$

1.7. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \dfrac{2t}{t-2} - \dfrac{t^2+1}{(t-2)^2} = \dfrac{t^2-4t-1}{(t-2)^2}$

1.8. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = 0$

1.9. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = t^2 \mathrm{e}^t \left( t^4 + 6t^3 + \mathrm{e}^t(2t + 3) \right)$

1.10. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \dfrac{2}{t} + t\mathrm{e}^{-t}(2-t)$

1.11. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = 4t \left( 2\ln(t) + 1 \right)$

1.12. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = (t^3+1) \left( 6t^2 \sin(3t) + 3(t^3+1)\cos(3t) \right)$

1.13. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \exp \left( \cosh(t) \right) \sinh(t) + \exp\left( \sinh(t) \right) \cosh(t)$

1.14. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \dfrac{1}{1+t^2}$

1.15. $\displaystyle \quad \dfrac{\mathrm{d}z}{\mathrm{d}t} = \dfrac{\exp(\sqrt{t})}{t+2} + \dfrac{\ln(t+2) \exp(\sqrt{t})}{2\sqrt{t}}$

### Q2 {.unnumbered}

2.1. $\displaystyle \quad \dfrac{\partial z}{\partial s} = 2(s+t)(2s^2+st-t^2) \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = 2(s+t)(s^2-2t^2-st)$.

2.2. $\displaystyle \quad \dfrac{\partial z}{\partial s} = 1 \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = \dfrac{\cos(t)-\sin(t)}{\cos(t)+\sin(t)}$.

2.3. $\displaystyle \quad \dfrac{\partial z}{\partial s} = 3t(s^2t^2-2s-t)\:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = 3s(s^2t^2-s-2t)$.

2.4. $\displaystyle \quad \dfrac{\partial z}{\partial s} = 2st \exp(s^2) \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = \exp(s^2)$.

2.5. $\displaystyle \quad \dfrac{\partial z}{\partial s} = \sin(st) + t(s-t^2) \cos(st) \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = -2t \sin(st) + s(s-t^2) \cos(st)$.

2.6. $\displaystyle \quad \dfrac{\partial z}{\partial s} = 2\sin(s)\cos(s)\cos(2t) \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = 2\sin(t)\cos(t)\cos(2s)$.

2.7. $\displaystyle \quad \dfrac{\partial z}{\partial s} = 2(2s+t) \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = 2s$.

2.8. $\displaystyle \quad \dfrac{\partial z}{\partial s} = \dfrac{1}{s+t} - \dfrac{1}{s} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = \dfrac{1}{s+t} - \dfrac{1}{t}$.

2.9. $\displaystyle \quad \dfrac{\partial z}{\partial s} = (2s+1)\sec^2(s^2+s+t^2-t) \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = (2t-1)\sec^2(s^2+s+t^2-t)$.

2.10. $\displaystyle \quad \dfrac{\partial z}{\partial s} = -\dfrac{2t}{s^2+t^2} \:$ and $\: \displaystyle \dfrac{\partial z}{\partial t} = \dfrac{2s}{s^2+t^2}$.

### Q3 {.unnumbered}

3.1. $\displaystyle \quad \dfrac{\partial w}{\partial s} = 2s(2+t^2)  \:$ and $\: \displaystyle \dfrac{\partial w}{\partial t} = 2t(2+s^2)$.

3.2. $\displaystyle \quad \dfrac{\partial w}{\partial s} = t(2s + t + u)  \:$ and $\: \displaystyle \dfrac{\partial w}{\partial t} = s(s+2t+u)+1  \:$ and $\: \displaystyle \dfrac{\partial w}{\partial u} = st+1$.

3.3. $\displaystyle \quad \dfrac{\partial w}{\partial s} = 2st^2\cos(s^2t^2) - \sin(s+t) \:$ and $\: \displaystyle \dfrac{\partial w}{\partial t} = 2s^2t\cos(s^2t^2) - \sin(s+t)$.

3.4. $\displaystyle \quad \dfrac{\partial w}{\partial s} = 4(s+u) \:$ and $\: \displaystyle \dfrac{\partial w}{\partial t} = 4t  \:$ and $\: \displaystyle \dfrac{\partial w}{\partial u} = 4(s+u)$.

------------------------------------------------------------------------

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
