---
title: "Answers: Matrix multiplication with special matrices"
author: "Tom Coleman"
abstract-title: Summary
abstract: Answers to questions for the study guide on matrix multiplication with special matrices.
---

These are the answers to [Questions: Matrix multiplication with special matrices](../questions/qs-matrixmultiplicationspecial.qmd).

**Please attempt the questions before reading these answers!**

---
 
<!-- ## Q1 {-} -->

<!-- 1.1. $\displaystyle \quad Q   \mathbf{r} = \begin{bmatrix} 27+\pi \end{bmatrix}$ -->

<!-- 1.2. $\displaystyle \quad \mathbf{r}   Q = \begin{bmatrix} -2 & -3 & -1 & -4 \\6 & 9 & 3 & 12 \\2\pi & 3\pi & \pi & 4\pi \\10& 15 & 5 &20 \end{bmatrix}$ -->

<!-- 1.3. This is undefined as $Q$ has $4$ columns and $S$ has $2$ rows. -->

<!-- 1.4. $\displaystyle \quad ST = \begin{bmatrix} -9 & 30 \\ 13 & 18 \end{bmatrix}$ -->

<!-- 1.5. $S^2$ is undefined as $S$ has $3$ columns and $S$ has $2$ rows. -->

<!-- 1.6. $\displaystyle \quad TS = \begin{bmatrix} 23 & -34 & 31 \\ 1 & -6 & 33 \\ -24 & 32 & -8 \end{bmatrix}$ -->

<!-- 1.7. $\quad UV = \begin{bmatrix} 6-\sqrt{2} & 29/2 \\-12+3\sqrt{2} & -59/2 \end{bmatrix}$ -->

<!-- 1.8. $\quad VU = \begin{bmatrix} -3/2-\sqrt{2} & 2+2\sqrt{2} \\18 & -22 \end{bmatrix}$ -->

<!-- 1.9. $\quad W\mathbf{r} =  \begin{bmatrix} -3 + 7\pi \\ -45 + 5\pi \\44 +3\sqrt{7} - 8\pi \end{bmatrix}$ -->

<!-- 1.10. $\quad SW =  \begin{bmatrix} -1 & 7 + 5\sqrt{7} & -48 & 57 + \pi\\ 11 & -13 -\sqrt{7} & 22 & -33-3\pi \end{bmatrix}$ -->

<!-- 1.11 $S\mathbf{x}$ is undefined as $S$ has $3$ columns and $\mathbf{x}$ has $2$ rows. -->

<!-- 1.12. $\quad T   U = \begin{bmatrix} -23 & 34 \\-1 & 6 \\ 24 & -32 \end{bmatrix}$ -->

<!-- 1.13. $\quad T   V = \begin{bmatrix} 18-5\sqrt{2} & -89/2 \\6+7\sqrt{2} & 21/2 \\24 & 56 \end{bmatrix}$ -->

<!-- 1.14. $\quad T   \mathbf{x} = \begin{bmatrix} 17 \\29 \\4 \end{bmatrix}$ -->

<!-- 1.15. $\quad U   \mathbf{x} = \begin{bmatrix} -3 \\10 \end{bmatrix}$ -->

<!-- 1.16. $\quad V   \mathbf{x} = \begin{bmatrix} -1/4 + 4\sqrt{2} \\31/2 \end{bmatrix}$ -->

<!-- 1.17. $\quad \mathbf{x}   Q = \begin{bmatrix} -8 & 12 & 4 & 16 \\ 1 & 3/2 & 1/2 & 2 \end{bmatrix}$ -->

<!-- 1.18. $\quad V   V = \begin{bmatrix} 1/2 & -7/2 -\sqrt{2} /2 \\21+3\sqrt{2} & 95/2 \end{bmatrix}$ -->

<!-- 1.19. $\quad U   U = \begin{bmatrix} 7 & -10 \\-15 & 22 \end{bmatrix}$ -->

<!-- 1.20. $\quad U   \mathbf{x}   Q = \begin{bmatrix} -6 & -9 & -3 & -12 \\20 & 30 & 10 & 40 \end{bmatrix}$ -->

<!-- r. $\quad U^3 = \begin{bmatrix} -37 & 54 \\ -->
<!-- 81 & -118 \end{bmatrix}$ -->

<!-- s. $\quad S   T   U = \begin{bmatrix} 99 & -138 \\ -->
<!-- 41 & -46 \end{bmatrix}$ -->

<!-- t. $\quad T   X   Q   R = \begin{bmatrix} 459 +17\pi \\ -->
<!-- 783 + 29\pi \\ -->
<!-- 108 +4\pi \end{bmatrix}$ -->

<!-- u. $\quad 3U   X = \begin{bmatrix} -18 \\ -->
<!-- 60 \end{bmatrix}$ -->

<!-- v. $\quad (S   T)-2U = \begin{bmatrix} -11 & 26 \\ -->
<!-- 7 & 10 \end{bmatrix}$ -->

<!-- w. $\quad W   R + T   X = \begin{bmatrix} 14+7\pi \\ -->
<!-- -16 +5\pi \\ -->
<!-- 18+ 3\sqrt{7} -8\pi \end{bmatrix}$ -->

<!-- x. $\quad -R   Q   R = \begin{bmatrix} 27+\pi \\ -->
<!-- -81 -3\pi \\ -->
<!-- -27\pi + \pi^2 \\ -->
<!-- 135+ 5\pi \end{bmatrix}$ -->

<!-- y. $\quad (V+U)   X = \begin{bmatrix} -5-3\sqrt{2} \\ -->
<!-- 61 \end{bmatrix}$ -->

<!-- z. $\quad 4U^2 + V^2 = \begin{bmatrix} 57/2 & -87/2 - \sqrt{2}/2 \\ -->
<!-- -39+3\sqrt{2} & 271/2 \end{bmatrix}$ -->

---

## Q1 {-}

1.1. $$\begin{aligned} 3x + 3y &= 4 \\[0.2em] x - y &= 5\end{aligned}$$

1.2. $$\begin{aligned} 3x + 3y &= 4 \\[0.2em] x - y &= 5\\[0.2em] -4x + 3y &= 0\end{aligned}$$

1.3. $$\begin{aligned} 3x + 3y + 3z &= 4 \\[0.2em] y - z  &= 5\\[0.2em] -4x + 3y + z &= 0\end{aligned}$$

1.4. $$\begin{aligned} 3x + 3y + 3z &= 4\end{aligned}$$

1.5. $$\begin{aligned} 3x + 3y + 3z + 3t &= 4 \\[0.2em] x - y\;\;\;\qquad + t &= 5\end{aligned}$$

---

## Q2 {-}

2.1. $\displaystyle\quad \begin{bmatrix}9&-1\\1&1\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix} = \begin{bmatrix}-4\\1\end{bmatrix}$

2.2. $\displaystyle\quad \begin{bmatrix}1&3&1\\-1&-1&9\end{bmatrix}\begin{bmatrix}x\\y\\z\end{bmatrix} = \begin{bmatrix}8\\-1\end{bmatrix}$

2.3. $\displaystyle\quad \begin{bmatrix}3&1\\1&-1\\8&-9\end{bmatrix}\begin{bmatrix}x\\y\end{bmatrix} = \begin{bmatrix}4\\5\\1\end{bmatrix}$

2.4. $\displaystyle\quad \begin{bmatrix}3&3&3\\0&0&1\\-4&-4&8\end{bmatrix}\begin{bmatrix}x\\y\\z\end{bmatrix} = \begin{bmatrix}4\\1\\1\end{bmatrix}$

2.5. $\displaystyle\quad \begin{bmatrix}2&2&2&9\\-1&-1&-1&-1\end{bmatrix}\begin{bmatrix}x\\y\\z\\t\end{bmatrix} = \begin{bmatrix}4\\-10\end{bmatrix}$

---

## Q3 {-}

3.1. $\quad S0_{3\times 9} = 0_{2\times 9}$

3.2. $\quad 0_{9\times 3}T = 0_{9\times 2}$

3.3. $\quad SI_3 = S$

3.4. $\quad I_2S = S$

3.5. $\quad I_2T$ is undefined as $I_2$ has two columns and $T$ has three rows.

---

## Q4 {-}

For 4.1 to 4.4, pick $A = B = I_2$, the $2\times 2$ identity matrix. In this case, $AB = I_2$ which is both upper triangular and lower triangular, a diagonal matrix, and the $2\times 2$ identity matrix.

For 4.5, pick $$A = \begin{bmatrix}1&1\\0&1\end{bmatrix}\qquad\textsf{ and }\qquad B = \begin{bmatrix}1&0\\1&1\end{bmatrix}$$ where $A$ is upper triangular and $B$ is lower triangular. But $$AB = \begin{bmatrix}1&1\\0&1\end{bmatrix}\begin{bmatrix}1&0\\1&1\end{bmatrix} = \begin{bmatrix}2&1\\1&1\end{bmatrix}$$ which is neither upper nor lower triangular.

---

---

## Version history {-}

v1.0: initial version created 05/26 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
