---
title: "Powers and nth roots: Answers"
author: "Isabella Lewis"
abstract-title: Summary
abstract: Answers to questions relating to the guide on powers and nth roots.
---

*These are the answers to [Questions: Powers and nth roots]*
**Please attempt the questions before reading these answers!**

## Q1 {-}
Simplify the following expressions, leaving your answer as a singular power:\

1.1. $(a)^2\cdot(b)^2=(ab)^2$\

1.2. $(a)^{-4}\cdot(b)^{-4}=(ab)^{-4}=\frac{1}{(ab)^4}$\

1.3. $2^2\cdot3^2=(2\cdot3)^2=6^2$\

1.4. $8^5\cdot6^5=(8\cdot6)^5=48^5$\

1.5. $12^{11}\cdot3^{11}=(12\cdot3)^{11}=36^{11}$\

1.6. $(\frac{x^5}{y^5})=(\frac{x}{y})^5$\

1.7. $(\frac{4^5}{2^5})=(\frac{4}{2})^5=2^5$\

1.8. $(\frac{2^{-2}}{13^{-2}})=(\frac{2}{13})^{-2}=(\frac{13}{2})^{2}$\

1.9. $(\frac{a}{b})^n\cdot(\frac{c}{d})^n=((\frac{a}{b})\cdot(\frac{c}{d}))^n=(\frac{ac}{bd})^n$\

1.10. $(\frac{2}{3})^{14}\cdot(\frac{9}{12})^{14}=((\frac{2}{3})\cdot(\frac{9}{12}))^{14}=((\frac{18}{36}))^{14}=((\frac{1}{2}))^{14}$\

1.11. $(a^{\frac{1}{2}})\cdot(b^{\frac{1}{2}})=(ab)^{\frac{1}{2}}=\sqrt{ab}$\


## Q2 {-}
Evaluate the following:\

2.1. $(\frac{4^3\cdot{3^3}}{6^3})=(\frac{4\cdot3}{6})^3=(\frac{12}{6})^3=2^3=8$\

2.2. $(\frac{4^2\cdot{8^2}}{2^2})\cdot{(\frac{1}{2})^2}={(\frac{4\cdot8}{2})^2}\cdot{(\frac{1}{2})^2}=(\frac{4\cdot8\cdot1}{2\cdot2})^2=(\frac{32}{4})^2=8^2=64$\

2.3. ${(\frac{a}{b})^4}\cdot{(\frac{c}{d})^4}\cdot{(\frac{e}{f})^4}=(\frac{ace}{bdf})^4$\

2.4. $\frac{({\frac{-2}{3}})^{-3}\cdot({\frac{-3}{5}})^{-3}}{({\frac{2}{3}})^{-3}}=\frac{({\frac{6}{15}})^{-3}}{({\frac{2}{3}})^{-3}}=\frac{({\frac{15}{6}}^{3})}{({\frac{3}{2}})^{3}}=(\frac{15\cdot2}{6\cdot3})^3=(\frac{5}{3})^3={\frac{125}{27}}$\

2.5. ${\frac{5^{x+1}\cdot6^{x+1}}{3^{x+1}}}=(\frac{5\cdot6}{3})^{x+1}=10^{x+1}$\

2.6. $\frac{\frac{(\frac{1}{2})^4}{(\frac{3}{5})^4}}{(\frac{8}{3})^{4}}=\frac{(\frac{5}{6})^{4}}{(\frac{8}{3})^{4}}=(\frac{15}{48})^4$\


## Q3 {-}
For the following, find the value of $x$:\

3.1. $(4^x)\cdot(2^x)=64$ then ${(4\cdot2)^x=64}$ and hence ${8^x=64}$ and so ${x=2}$\

3.2.  ${\frac{5^{x+1}\cdot6^{x+1}}{3^{x+1}}}=(\frac{5\cdot6}{3})^{x+1}=100$ hence, ${10^{x=1}=100}$ and so ${x=1}$\

3.3. $\frac{(\frac{1}{2})^x\cdot(\frac{-1}{4})^x}{(\frac{2}{3})^x}=\frac{-27}{4096}$ , combining the first two fractions, $\frac{({\frac{1}{8})^x}}{({\frac{2}{3})^x}}=(\frac{-1}{8})^x\cdot(\frac{3}{2})^x=(\frac{-3}{16})^x={\frac{-27}{4096}}$ and so ${x=3}$\


## Q4 {-}
Simplify the following expressions:\

4.1. $\sqrt{8}=\sqrt{4\cdot2}=\sqrt{4}\cdot\sqrt{2}=2\sqrt{2}$\

4.2. $\sqrt{3}\cdot\sqrt{7}=\sqrt{3\cdot7}=\sqrt{21}$\

4.3. $(\frac{\sqrt{24}}{\sqrt{6}})=\sqrt{\frac{24}{6}}=\sqrt{4}=2$\

4.4. $(\sqrt{5})^2=\sqrt{25}=5$\

4.5. $(\sqrt{2})^4=(\sqrt{2})^2\cdot(\sqrt{2})^2=2\cdot2=4$\

4.6. $\sqrt{75}=\sqrt{25}\cdot\sqrt{3}=5\sqrt{3}$\

4.7. $\sqrt{4^3}\cdot\sqrt[3]{8}$\
$\sqrt{4^3}=(\sqrt{4})^3=2^3$\
$\sqrt[3]{8}=2$\
$\sqrt{4^3}\cdot\sqrt[3]{8}=2^3\cdot2=2^4=16$\

4.8. $\sqrt{6}\cdot\sqrt{15}=\sqrt{3\cdot3\cdot2\cdot5}=3\sqrt{10}$\

4.9. $\sqrt{75}-\sqrt{27}=5\sqrt{3}-3\sqrt{3}=2\sqrt{3}$\

4.10. $(8+\sqrt{2})\cdot(3-\sqrt{2})=24-2=3\sqrt{2}-8\sqrt{8}=22-5\sqrt{2}$\

4.11. $(3\sqrt{7})^2(8\sqrt{3})^2=(3\sqrt{7}\cdot8\sqrt{3})^2=(24\sqrt{21})^2=24^2\cdot21=12096$\

4.12. $(3-\sqrt{8})^2=9+8-2(3\sqrt{8})=17-6\sqrt{8}$\

4.13. $(7+\sqrt{5})\cdot(1+\sqrt{5})=7+5+\sqrt{5}+7\sqrt{5}=12+8\sqrt{5}$\

4.14. $\sqrt{45}+\sqrt{125}=\sqrt{9}\cdot\sqrt{5}+\sqrt{25}\cdot\sqrt{5}=3\sqrt{5}+5\sqrt{5}=8\sqrt{5}$\

4.15. $\sqrt{108}=\sqrt{36\cdot3}=6\sqrt{3}$


## Q5 {-}
Simplify the following:\

5.1. $\frac{8}{\sqrt{3}}=\frac{8\sqrt{3}}{3}$\

5.2. $\frac{7+\sqrt{5}}{3+\sqrt{5}}=\frac{7+\sqrt{5}}{3+\sqrt{5}}\cdot\frac{3-\sqrt{5}}{3-\sqrt{5}}=\frac{16-4\sqrt{5}}{9-5}=\frac{16-4\sqrt{5}}{4}=4-\sqrt{5}$\

5.3. $(\frac{2-\sqrt{3}}{3+\sqrt{3}})=(\frac{(2-\sqrt{3})\cdot(3-\sqrt{3})}{(3+\sqrt{3})\cdot(3-\sqrt{3})})=(\frac{6+3-3\sqrt{3}-2\sqrt{3}}{9-3})=(\frac{9-5\sqrt{3}}{6})$\

5.4. $\frac{21}{2+\sqrt{3}}=\frac{42-21\sqrt{3}}{4-3}=42-21\sqrt{3}$\

5.5. $\frac{1}{4-\sqrt{8}}=\frac{4+\sqrt{8}}{(4-\sqrt{8})\cdot(4+\sqrt{8})}=\frac{4+\sqrt{8}}{16-8}=\frac{4+\sqrt{8}}{8}=\frac{1}{2}+\frac{1}{4}\sqrt{2}$\
---
