---
title: "Answers: The product rule"
author: "Sara Delgado Garcia"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the product rule.
---

*These are the answers to [Questions: The product rule](../questions/qs-productrule.qmd).* 

**Please attempt the questions before reading these answers!**

---

1.1. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(xe^x\right)=e^x + xe^x.$

---

1.2. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(x^2e^{2x}\right)=2xe^{2x}+2x^2e^{2x}.$

---

1.3. As $\tan(x) = \sin(x)/cos(x)$, the function becomes $5x^3\sin(x)$ and so $$\dfrac{\mathrm{d}}{\mathrm{d}x}\left(5x^3\tan(x)\cos(x)\right)= \dfrac{\mathrm{d}}{\mathrm{d}x}\left(5x^3\sin(x)\right) = 15x^2\sin(x) + 5x^3\cos(x).$$

---

1.4. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(x\ln(x)\right)=\ln(x)+1.$

---

1.5. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left((x^3+x^2-5)(x+1)\right)=(3x^2+2x)(x+1)+(x^3+x^2-5).$

---

1.6. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left((13x^2 + 5x +2)(x^3 + 2)\right)=(26x+5)(x^3 + 2) + 3x^2(13x^2 + 5x + 2).$

---

1.7. Take the $x$ inside the first bracket so the function becomes $(5x^3 + 3x^2 + 2x)(x^2 +x +1)$. Then 
$$
\begin{aligned}
\dfrac{\mathrm{d}}{\mathrm{d}x}\left(x(5x^2 + 3x + 2)(x^2 +x +1)\right)&= \dfrac{\mathrm{d}}{\mathrm{d}x}\left((5x^3 + 3x^2 + 2x)(x^2 +x +1)\right)\\[1em]
&= (10x^2+6x+2)(x^2 + x + 1) + (5x^3 + 3x^2 + 2x)(2x + 1).
\end{aligned}
$$
---

1.8. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left((10x^2 + 21)\cos(x)\right)=20x\cos(x) - (10x^2+21)\sin(x).$

---

1.9. Using the definitions of $\cosh(2x)$ and $\sinh(3x)$:

$$
\begin{aligned}
\dfrac{\mathrm{d}}{\mathrm{d}x}\left(\cosh(2x)\sinh(3x)\right)&=\dfrac{\mathrm{d}}{\mathrm{d}x}\left(\left(\frac{e^{2x}+e^{-2x}}{2}\right)\left(\frac{e^{3x} - e^{-3x}}{2}\right)\right)\\[1em]
&= \left(\frac{e^{2x}+e^{-2x}}{2}\right)\left(\frac{3e^{3x} + 3e^{-3x}}{2}\right) + \left(\frac{2e^{2x}-2e^{-2x}}{2}\right)\left(\frac{e^{3x} - e^{-3x}}{2}\right)\\[1em]
&= 3\cosh(2x)\cosh(3x) + 2\sinh(2x)\sinh(3x)
\end{aligned}
$$

---

1.10. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left((x^2 +3)\ln(x)\right)=2x\ln(x) + \frac{x^2 + 3}{x}.$

---

1.11. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\sin(x)\sqrt{x}\right)=\cos(x)\sqrt{x} + \frac{\sin(x)}{2\sqrt{x}}.$

---

1.12. Since $\displaystyle \cosh(x)= \frac{e^{x} + e^{-x}}{2}$, it follows that $$
\begin{aligned}\dfrac{\mathrm{d}}{\mathrm{d}x}\left(\cosh(x)\ln(x)\right)&=\dfrac{\mathrm{d}}{\mathrm{d}x}\left(\left(\frac{e^{x}+e^{-x}}{2}\right)\ln(x)\right)\\[1em] &= \left(\frac{e^{x}-e^{-x}}{2}\right)\ln(x) + \left(\frac{e^{x}+e^{-x}}{2}\right)\frac{1}{x}\\[1em] &=\sinh(x)\ln(x) + \frac{\cosh(x)}{x} \end{aligned}$$ since $\displaystyle\sinh(x) = \frac{e^x -e^{-x}}{2}$.

---

1.13. Factorize to get $x^2(\sqrt{x}+\cos(x))$, then $$
\begin{aligned}\dfrac{\mathrm{d}}{\mathrm{d}x}\left(x^2\sqrt{x}+x^2\cos(x)\right)&=\dfrac{\mathrm{d}}{\mathrm{d}x}\left(x^2(\sqrt{x}+\cos(x))\right)\\[1em] &= 2x(\sqrt{x}+\cos(x)) + x^2\left(\frac{1}{2\sqrt{x}} - \sin(x)\right).\end{aligned}$$

---

1.14. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(e^{-5x}(x^3+5)\right)=3x^2e^{-5x} - 5e^{-5x}(x^3+5).$

---

1.15. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{2}{5}\sinh(x)+\frac{2}{13}\cosh(x)\right)=\frac{2}{5}\cosh(x)+\frac{2}{13}\sinh(x).$

---

1.16. Using the product rule twice here:
$$\dfrac{\mathrm{d}}{\mathrm{d}x}\left(\ln(x) \ln (3x) \ln (100x)\right)=\frac{\ln(3x)\ln(100x) + \ln(x)\ln(100x) + \ln(x)\ln(3x)}{x}.$$

---

1.17. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left((x^2 + 5x + 2)\sin(x)\right)=(2x+5)\sin(x) + (x^2 + 5x + 2)\cos(x).$

---

1.18. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(-\ln(x)\ln(3x)\right)= -\frac{1}{x}(\ln(3x)+\ln(x)).$

---

1.19. Using the product rule twice:
$$
\begin{aligned}
\dfrac{\mathrm{d}}{\mathrm{d}x}&\left((x^5 + 3)(x^2 + 3x)(x^7 + x^4)\right)\\
&= 5x^4(x^2 +3x)(x^7 + x^4) + (x^5 + 3)(2x + 3)(x^7 + x^4) + (x^5 +3)(x^2 + 3x)(7x^6 + 4x^3).
\end{aligned}
$$
---

1.20. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left((\sin(x) + 3x)e^{-x}\right)= (\cos(x) + 3)e^{-x} - (\sin(x) + 3x)e^{-x}.$


---

---

## Version history and licensing {-}

v1.0: initial version created 05/25 by Sara Delgado Garcia as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

