---
title: "Answers: Introduction to integration"
author: "Donald Campbell"
abstract-title: Summary
abstract: Answers to questions relating to the guide on introduction to integration.
draft: true
---

*These are the answers to [Questions: Introduction to integration](../questions/qs-introtointegration.qmd).*

**Please attempt the questions before reading these answers!**

<!-- ANSWERS TO INTRO TO INTEGRATION -->

### Q1 {.unnumbered}

1.1. $\displaystyle \quad \int x^4 \, \mathrm{d}x = \dfrac{1}{5}x^5 + C$.

1.2. $\displaystyle \quad \int 2x \, \mathrm{d}x = x^2 + C$.

1.3. $\displaystyle \quad \int 7x^5 \, \mathrm{d}x = \dfrac{7}{6}x^6 + C$.

<!-- 1.4. $\displaystyle \quad \dfrac{3}{2}x^2 + C$. -->

1.5. $\displaystyle \quad \int -5 \, \mathrm{d}t = -5t + C$.

<!-- 1.6. $\displaystyle \quad x^2 - \dfrac{5}{3}x^3 + C$. -->

<!-- 1.7. $\displaystyle \quad \dfrac{4}{3}x^3 + 2x + C$. -->

<!-- 1.8. $\displaystyle \quad -10x^{-1} - x^2 + C$. -->

<!-- 1.9. $\displaystyle \quad \dfrac{1}{3}x^9 - \dfrac{4}{3}x^{-3} - x^2 + C$. -->

<!-- 1.10. $\displaystyle \quad \dfrac{5}{2}x^2 + x^{-2} - \dfrac{3}{5}x^5 + C$. -->

### Q2 {.unnumbered}


2.1. $\displaystyle \quad \int \dfrac{3}{y^3} \, \mathrm{d}y = -\dfrac{3}{2}y^{-2} + C$.

2.2. $\displaystyle \quad \int 6x^{-4} \, \mathrm{d}x = -2x^{-3} + C$.

2.3. $\displaystyle \quad \int -\dfrac{2}{x^5} \, \mathrm{d}x = \dfrac{1}{2}x^{-4} + C$.

2.4. $\displaystyle \quad \int \dfrac{8}{3x^6} \, \mathrm{d}x = -\dfrac{8}{15}x^{-5} + C$.

2.5. $\displaystyle \quad \int -\dfrac{7}{2z^7} \, \mathrm{d}z = \dfrac{7}{12}z^{-6} + C$.

<!-- 2.6. $\displaystyle \quad -\dfrac{5}{3}x^{-3} - \dfrac{3}{4}x^{-4} + C$. -->

<!-- 2.7. $\displaystyle \quad -\dfrac{2}{3}x^{-2} + \dfrac{1}{5}x^{-6} + C$. -->

<!-- 2.8. $\displaystyle \quad -\dfrac{7}{3}x^{-3} + \dfrac{1}{4}x^4 + \dfrac{2}{5}x^{-5} + C$. -->

<!-- 2.9. $\displaystyle \quad -\dfrac{3}{4}x^{-4} - \dfrac{4}{5}x^{-5} - x + C$. -->

<!-- 2.10. $\displaystyle \quad -\dfrac{9}{8}x^{-8} - \dfrac{4}{35}x^{-5} + \dfrac{1}{3}x^{-7} + C$. -->

### Q3 {.unnumbered}

3.1. $\displaystyle \quad \int x^{1/3} \, \mathrm{d}x = \dfrac{3}{4} x^{4/3} + C$.

3.2. $\displaystyle \quad \int 3t^{-2/3} \, \mathrm{d}t = 9t^{1/3} + C$.

3.3. $\displaystyle \quad \int \dfrac{4x^{1/4}}{3} \, \mathrm{d}x = \dfrac{16}{15} x^{5/4} + C$.

3.4. $\displaystyle \quad \int \dfrac{2}{5x^{1/3}} \, \mathrm{d}x = \dfrac{3}{5} x^{2/3} + C$.

3.5. $\displaystyle \quad \int \dfrac{5}{6y^{-4/3}} \, \mathrm{d}y = \dfrac{5}{14} y^{7/3} + C$.

<!-- 3.6. $\displaystyle \quad \dfrac{3}{2} x^{4/3} + C$. -->

<!-- 3.7. $\displaystyle \quad 8 x^{3/4} + C$. -->

<!-- 3.8. $\displaystyle \quad \dfrac{1}{4}x^4 + \dfrac{9}{8} x^{2/3} + \dfrac{4}{5} x^{5/4} + C$. -->

<!-- 3.9. $\displaystyle \quad \dfrac{5}{6} x^{6/5} - 6x^{2/3} + C$. -->

<!-- 3.10. $\displaystyle \quad \dfrac{4}{9} x^{9/4} + C$. -->

<!-- 3.11. $\displaystyle \quad x^2 - \dfrac{3}{7} x^{7/3} + C$. -->

<!-- 3.12. $\displaystyle \quad \dfrac{1}{12}x^4 - \dfrac{2}{7} x^{7/3} + C$. -->

<!-- 3.13. $\displaystyle \quad \dfrac{135}{14}x^{14/3} + \dfrac{45}{2}x^{8/3} + 30x^{2/3} + C$. -->

<!-- 3.14. $\displaystyle \quad \dfrac{1}{3}x^9 + \dfrac{1}{2}x^8 + x^6 + \dfrac{8}{5}x^5 + x^3 + 2x^2 + C$. -->

<!-- 3.15. $\displaystyle \quad \dfrac{32}{19}x^{19/4} + \dfrac{96}{11}x^{11/4} + 24x^{3/4} + C$. -->

<!-- ### Q4 {.unnumbered} -->

<!-- 4.1. $\displaystyle \quad \dfrac{1}{3}x^3 - 2x + C$. -->

<!-- 4.2. $\displaystyle \quad \dfrac{1}{2}x^2 + 3x^{-1} + C$. -->

<!-- 4.3. $\displaystyle \quad \dfrac{2}{5}x^{5/2} - 2x^{1/2} + C$. -->

<!-- 4.4. $\displaystyle \quad \dfrac{3}{11}x^{11/3} + 3x^{5/3} + C$. -->

<!-- 4.5. $\displaystyle \quad \dfrac{1}{2}x^4 - x^2 - 3x - 3x^{-1} + C$. -->

<!-- 4.6. $\displaystyle \quad -18x^{-2} + 8x^{-3} - x^{-4} + C$. -->

<!-- 4.7. $\displaystyle \quad -\dfrac{16}{3}x^{3/2} - 10x^{-1/2} + C$. -->

### Q5 {.unnumbered}

5. $\displaystyle \quad \int e^{2x} \, \mathrm{d}x =  \frac{1}{2}e^{2x} + C$

5. $\displaystyle \quad \int -3e^{-3x} \, \mathrm{d}x = e^{-3x} + C$

5. $\displaystyle \quad \int 2e^{11x} \, \mathrm{d}x = \frac{2}{11}e^{11x} + C$

5. $\displaystyle \quad \int \frac{4}{x} \, \mathrm{d}x = 4\ln|x| + C$

5. $\displaystyle \quad \int -\frac{5}{3x} \, \mathrm{d}x = -\frac{5}{3}\ln|x| + C$

5.1. $\displaystyle \quad \int \cos (x) \, \mathrm{d}x = \sin ( x ) + C$.

5.2. $\displaystyle \quad \int \sin ( 2x ) \, \mathrm{d}x = -\dfrac{1}{2} \cos ( 2x ) + C$.

5.3. $\displaystyle \quad \int \dfrac{5}{6} \cos ( x ) \, \mathrm{d}x = \dfrac{5}{6} \sin ( x ) + C$.

5.4. $\displaystyle \quad \int \cos ( 3x ) \, \mathrm{d}x = \dfrac{1}{3} \sin ( 3x ) + C$.

5.5. $\displaystyle \quad \int \sin \left( \dfrac{x}{3} \right) \, \mathrm{d}x = -3 \cos \left( \dfrac{x}{3} \right) + C$.

<!-- 5.6. $\displaystyle \quad \dfrac{4}{15} \sin \left( 3x-\dfrac{\pi}{4} \right) + C$. -->

<!-- 5.7. $\displaystyle \quad \dfrac{9}{4} \cos \left( \dfrac{\pi}{3} - \dfrac{4x}{9} \right) + C$. -->

<!-- 5.8. $\displaystyle \quad -\dfrac{1}{6} \sin \left( 3x + \dfrac{\pi}{2} \right) + C$. -->

<!-- 5.9. $\displaystyle \quad -16 \cos \left( \dfrac{x}{4} - \dfrac{\pi}{2} \right) + C$. -->

<!-- 5.10. $\displaystyle \quad -\dfrac{3}{25} \sin \left( \dfrac{\pi}{6} - 5x \right) + C$. -->

<!-- ANSWERS TO DEFINITE INTEGRATION -->

## Answers {.unnumbered}

### Q1 {.unnumbered}

1.1. $\displaystyle \quad \int_{1}^{4} 2 \, \mathrm{d}x = 6$

1.2. $\displaystyle \quad \int_{-2}^{2} 3x \, \mathrm{d}x = 0$

<!-- 1.3. $\displaystyle \quad \int_{-2}^{1} ( 3-5x ) \, \mathrm{d}x = \dfrac{33}{2}$ -->

1.4. $\displaystyle \quad \int_{2}^{4} 2x^3 \, \mathrm{d}x = 120$

<!-- 1.5. $\displaystyle \quad \int_{0}^{2} ( 4x^2 - 3x + 1 ) \, \mathrm{d}x = \dfrac{20}{3}$ -->

<!-- 1.6. $\displaystyle \quad \int_{0}^{2} ( 2x^4 + 3) \, \mathrm{d}x = \dfrac{94}{5}$ -->

<!-- 1.7. $\displaystyle \quad \int_{-2}^{2} ( x-2 ) ( 2x+1 ) \, \mathrm{d}x = \dfrac{8}{3}$ -->

<!-- 1.8. $\displaystyle \quad \int_{0}^{3} x^2 ( 3x-2 ) \, \mathrm{d}x = \dfrac{171}{4}$ -->

### Q2 {.unnumbered}

2.1. $\displaystyle \quad \int_{1}^{27} \dfrac{4}{\sqrt[3]{x}} \, \mathrm{d}x = 48$

<!-- 2.2. $\displaystyle \quad \int_{1}^{4} (2\sqrt{x} + x^2) \, \mathrm{d}x = \dfrac{91}{3}$ -->

<!-- 2.3. $\displaystyle \quad \int_{1}^{4} ( x^{3/2} - x^{-1/2} ) \, \mathrm{d}x = \dfrac{52}{5}$ -->

<!-- 2.4. $\displaystyle \quad \int_{0}^{3} ( 2x^3 - 7x + 5 ) \, \mathrm{d}x = 24$ -->

<!-- 2.5. $\displaystyle \quad \int_{1}^{4} ( 6x^{-2} - 2x^{1/2} ) \, \mathrm{d}x = -\dfrac{29}{6}$ -->

<!-- 2.6. $\displaystyle \quad \int_{0}^{1} (2x+1)^3 \, \mathrm{d}x = 10$ -->

<!-- 2.7. $\displaystyle \quad \int_{-1}^{1} (4-3x)^2 \, \mathrm{d}x = 38$ -->

<!-- 2.8. $\displaystyle \quad \int_{0}^{2} (1+x)^3 \, \mathrm{d}x = 20$ -->

<!-- 2.9. $\displaystyle \quad \int_{1}^{4} \left( \dfrac{x}{2} - 3 \right)^2 \, \mathrm{d}x = \dfrac{39}{4}$ -->

<!-- 2.10. $\displaystyle \quad \int_{-1}^{1} (2x+3)^2 \, \mathrm{d}x = \dfrac{62}{3}$ -->

### Q3 {.unnumbered}

3. $\displaystyle \quad \int_{0}^{\ln(3)} 4e^x \, \mathrm{d}x = 8$

3. $\displaystyle \quad \int_{0}^{5} e^{-3x} \, \mathrm{d}x = \frac{1}{3}\left(1 - e^{-15}\right)$

3. $\displaystyle \quad \int_{1}^{2} -4e^{4x} \, \mathrm{d}x = e^4(1-e^4)$

3. $\displaystyle \quad \int_{1}^{2} \frac{2}{x} \, \mathrm{d}x = 2\ln(2)$

3. $\displaystyle \quad \int_{1}^{e^3} -\frac{4}{x} \, \mathrm{d}x = -12$

3. $\displaystyle \quad \int_{e^3}^{e^9} \frac{9}{5x} \, \mathrm{d}x = \frac{54}{5}$

3.1. $\displaystyle \quad \int_{0}^{\pi/2} \sin ( x ) \, \mathrm{d}x = 1$

3.2. $\displaystyle \quad \int_{0}^{\pi} \cos ( x ) \, \mathrm{d}x = 0$

<!-- 3.3. $\displaystyle \quad \int_{\pi/2}^{\pi} \sin ( x ) \, \mathrm{d}x = 1$ -->

<!-- 3.4. $\displaystyle \quad \int_{\pi}^{2\pi} \sin ( x ) \, \mathrm{d}x = -2$ -->

<!-- 3.5. $\displaystyle \quad \int_{0}^{3\pi/2} \sin ( x ) \, \mathrm{d}x = 1$ -->

3.6. $\displaystyle \quad \int_{0}^{\pi/4} \sin ( 2x ) \, \mathrm{d}x = \dfrac{1}{2}$

<!-- 3.7. $\displaystyle \quad \int_{0}^{\pi} \sin ( 2x ) \, \mathrm{d}x = 0$ -->

<!-- 3.8. $\displaystyle \quad \int_{\pi/4}^{3\pi/2} \cos ( 2x ) \, \mathrm{d}x = -\dfrac{1}{2}$ -->

<!-- 3.9. $\displaystyle \quad \int_{\pi/4}^{\pi/2} \cos ( 2x ) \, \mathrm{d}x = -\dfrac{1}{2}$ -->

<!-- 3.10. $\displaystyle \quad \int_{0}^{4\pi} \cos \left( \dfrac{x}{2} \right) \, \mathrm{d}x = 0$ -->

### Q4 {.unnumbered}

4.1. $\displaystyle \quad \int_{0}^{\pi/6} \cos(2x) \, \mathrm{d}x = \dfrac{\sqrt{3}}{4}$

4.2. $\displaystyle \quad \int_{-\pi/4}^{0} \sin(3x) \, \mathrm{d}x = -\dfrac{1}{3} - \dfrac{1}{3\sqrt{2}}$

<!-- 4.3. $\displaystyle \quad \int_{0}^{\pi/3} ( \sin(x) + \cos(x) ) \, \mathrm{d}x = \dfrac{1}{2} + \dfrac{\sqrt{3}}{2}$ -->

<!-- 4.4. $\displaystyle \quad \int_{\pi/6}^{\pi/2} \cos\left(4x - \dfrac{\pi}{3}\right) \, \mathrm{d}x = -\dfrac{\sqrt{3}}{4}$ -->

<!-- 4.5. $\displaystyle \quad \int_{-\pi/6}^{\pi/6} \sin(x) \, \mathrm{d}x = 0$ -->

<!-- 4.6. $\displaystyle \quad \int_{0}^{\pi/2} \cos\left(2x + \dfrac{\pi}{6}\right) \, \mathrm{d}x = -\dfrac{1}{2}$ -->

<!-- 4.7. $\displaystyle \quad \int_{-\pi/3}^{\pi/3} \sin(5x) \, \mathrm{d}x = 0$ -->

<!-- 4.8. $\displaystyle \quad \int_{\pi/6}^{\pi/4} ( \cos(x) - \sin(x) ) \, \mathrm{d}x = \sqrt{2} - \dfrac{\sqrt{3}}{2} - \dfrac{1}{2}$ -->

<!-- 4.9. $\displaystyle \quad \int_{0}^{\pi/4} \cos(6x) \, \mathrm{d}x = -\dfrac{1}{6}$ -->

<!-- 4.10. $\displaystyle \quad \int_{-\pi/6}^{\pi/6} \sin\left(3x - \dfrac{\pi}{4}\right) \, \mathrm{d}x = -\dfrac{\sqrt{2}}{3}$ -->

---

---

## Version history and licensing {.unnumbered}

v1.0: initial version created 05/25 by Donald Campbell as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
