---
title: "Answers: Using the quadratic formula"
author: "Tom Coleman"
abstract-title: Summary
abstract: Answers to questions relating to the guide on using the quadratic formula.

---

*These are the answers to [Questions: Using the quadratic formula](../questions/qs-quadraticformula.qmd).*

**Please attempt the questions before reading these answers!**

## Answers {-}

### Q1 {-}

1.1. The two roots of $x^2 - 7x + 6 = 0$ are $x = 1$ and $x = 6$.

1.2. The two roots of $x^2 + 14x + 45 = 0$ are $x=-9$ and $x=-5$.

1.3. The two roots of $x^2 - 4x + 13 = 0$ are $x=2-3i$ and $x=2+3i$.

1.4. The two roots of $x^2 - x - 56 = 0$ are $x = -7$ and $x=8$.

1.5. The one distinct root of $s^2 + 4s + 4 = 0$ is $x = -2$.

1.6. The two roots of $t^2 + 4t - 4 = 0$ are $t = -2 - 2\sqrt{2}$ and $t = -2 + 2\sqrt{2}$

1.7. The two roots of $m^2 - 144 = 0$ are $m = -12$ and $m = 12$. 

1.8. The two roots of $5c^2 - 25 + 30 = 0$ are $c = -1$ and $c=1$.

1.9. The two roots of $2n^2 + n + 1 = 0$ are $\displaystyle n = \frac{-1 - i\sqrt{7}}{4}$ and $\displaystyle n = \frac{-1 + i\sqrt{7}}{4}$

1.10. The two roots of $-3c^2 + 9c - 1 = 0$ are $c = \frac{3}{2} - \frac{\sqrt{69}}{6}$ and $c = \frac{3}{2} + \frac{\sqrt{69}}{6}$.

1.11. The two roots of $\frac{x^2}{2} - \frac{7x}{2} + 3 = 0$ are $x = 1$ and $x = 6$. 

1.12. The one distinct root of $e^{2x} - 4e^x + 4 = 0$ is $e^x = 2$, giving $x = \ln(2)$ as a solution.

1.13. The two roots of $-9s^2 + 3s - 1 = 0$ are $\displaystyle s = \frac{1 - i\sqrt{3}}{6}$ and $\displaystyle s = \frac{1 + i\sqrt{3}}{6}$.

1.14. The two roots of $2e^{6x} + e^{3x} + 1 = 0$ are $\displaystyle e^{3x} = \frac{-1 - i\sqrt{7}}{4}$ and $\displaystyle e^{3x} = \frac{-1 + i\sqrt{7}}{4}$, and so there are no real solutions for $x$.

1.15. The one distinct root of $\cos^2(x) + 4\cos(x) - 4 = 0$ is $\cos(x) = 2$, and so there are no real solutions for $x$ as $-1\leq \cos(x) \leq 1$ for all real $x$. 

1.16. The two distinct roots of $8m^2 - 4m - 1 = 0$ are $\displaystyle m = \frac{1-\sqrt{3}}{4}$ and $\displaystyle m = \frac{1+\sqrt{3}}{4}$

### Q2 {-}

In [Questions: Introduction to quadratic equations](../questions/qs-introtoquadratics.qmd), you saw that the following expressions are all quadratic equations in disguise. Solve these for the variable indicated. 

2.1. The two roots of $x = 1/x - 1$ are $\displaystyle x = \frac{-1-\sqrt{5}}{2}$ and $\displaystyle x = \frac{-1+\sqrt{5}}{2}$.

2.2. The two roots of $(y-1)(y-4) = -(y+2)(y+3)$ are $y = -i\sqrt{5}$ and $y = i\sqrt{5}$.

2.3. The one distinct root of $4m(m+1) + 6 = 5$ is $m = -1/2$.

2.4. The two roots of $(t-1)(t+1) = -2$ are $t = -i$ and $t=i$.

2.5. The two roots of $\frac{x-1}{x-2} = 5x$ are $\displaystyle x=\frac{11-\sqrt{101}}{10}$ and $\displaystyle x=\frac{11+\sqrt{101}}{10}$. 

2.6. The two solutions in $e^x$ for $\frac{e^{x} - e^{-x}}{2} = 1$ are $e^x = 1 - \sqrt{2}$ and $e^x = 1 + \sqrt{2}$. Of these, $x = \ln(1+\sqrt{2})$ is a valid solution in $x$, as $e^x$ cannot be negative. 

---

---

## Version history and licensing {-}

v1.0: initial version created 04/23 by tdhc.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)


