---
title: "Answers: The quotient rule"
author: "Sara Delgado Garcia"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the quotient rule.
---

*These are the answers to [Questions: The quotient rule](../questions/qs-quotientrule.qmd).* 

**Please attempt the questions before reading these answers!**

---

1.1. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{e^x}{x}\right)=\frac{e^x(x-1)}{x^2}.$

---

1.2. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{e^{7x}}{x^5}\right)=\frac{(7x -5)e^{7x}}{x^{6}}.$

---

1.3. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{\ln(x)}{x^2}\right)=\frac{1-2\ln(x)}{x^3}$

---

1.4. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{e^{-x}}{x^2+11x-2}\right)= -\frac{(x^2 +13x +9)e^{-x}}{(x^2 + 11x -2)^2}$

---

1.5. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{x^3+5x-5}{x^2+3}\right)=\frac{(3x^2+5)(x^2+3)-(x^3+5x-5)(2x)}{(x^2+3)^2}.$

---

1.6. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{\cos(x)}{x^2+3x-1}\right)=\frac{-\sin (x)(x^2+3x-1)-\cos(x)(2x+3)}{(x^2+3x-1)^2}.$

---

1.7. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{\tan(x)}{\cos(x)}\right)=\frac{\sec^2(x)\cos(x) + \tan(x)\sin(x)}{\cos^2(x)}$

---

1.8. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{\ln(3x)}{\ln(5)+x}\right)= \frac{1}{x(\ln(5)+ x)} - \frac{\ln(3x)}{(\ln(5) + x)^2}$

---

1.9. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{x^2+3x}{\cos(x)}\right)=\frac{(2x+3)\cos(x) + (x^2+3x)\sin(x)}{\cos^2(x)}$

---

1.10. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{\ln(x)}{x^3+3}\right)=\frac{(x^3+3)-3x^3\ln (x)}{x(x^3+3)^2}$

---

1.11. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{5\tan(x)}{x}\right)=\frac{5x\sec^2(x)-5\tan (x)}{x^2}.$

---

1.12. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{3x^7-27x^2+2\sqrt{x}}{x^2+1}\right)=\frac{15x^8 \sqrt{x} +21x^6\sqrt{x} - 54x\sqrt{x} - 4x^2 + x^2+1}{\sqrt{x}(x^2+1)^2}.$.

---

1.13. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{e^{-3x}}{e^{2x}}\right)=\frac{-3e^{-3x}\,e^{2x}-2e^{-3x}\,e^{2x}}{e^{4x}}=-5e^{-5x}.$

---

1.14. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{e^3x^3}{e^x}\right)= \frac{3e^{3+ x}x^2-e^{3+x}x^3e^x}{e^{2x}}= \frac{x^2e^{x+3}(3+ x)}{e^{2x}}.$

---

1.15. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{x^5}{x^5+1}\right)=\frac{5x^4(x^5+1)-x^5(5x^4)}{(x^5+1)^2} = \frac{x^4}{(x^5+1)^2}$

---

1.16. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{\tan(x)}{\ln(x)}\right)=\frac{x\sec^2(x)\ln (x)-\tan(x)}{x(\ln(x))^2}.$

---

1.17. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{3\sin(x)}{\ln(x)}\right)=\frac{3x\cos(x)\ln (x)-3\sin(x)}{x(\ln(x))^2}$

---

1.18. $\displaystyle \quad \dfrac{\mathrm{d}}{\mathrm{d}x}\left(\frac{\tan(x)+5x}{\sec(3x)}\right)= \frac{\sec^2(x) +5 - (3\tan(3x))(5x + \tan(x))}{\sec(3x)}.$

---

---

## Version history and licensing {-}

v1.0: initial version created 05/25 by Sara Delgado Garcia as part of a University of St Andrews VIP project.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

