---
title: "Answers: Introduction to radians"
author: "Ifan Howells-Baines, Mark Toner"
abstract-title: Summary
abstract: Answers to the questions relating to the guide on radians.
---

*These are the answers to [Questions: Introduction to radians](../questions/qs-radians.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {-}

1.1. Multiplying $30^\circ$ by $\pi$ and dividing by $180$ gives $\dfrac{30\pi}{180} \textsf{ rad} = \dfrac{\pi}{6} \textsf{ rad} = 0.524 \textsf{ rad}$ to three decimal places.
 

1.2. Multiplying $105^\circ$ by $\pi$ and dividing by $180$ gives $\dfrac{105\pi}{180} \textsf{ rad} = \dfrac{7\pi}{12} \textsf{ rad} = 1.833 \textsf{ rad}$ to three decimal places.
 

1.3. Multiplying $298^\circ$ by $\pi$ and dividing by $180$ gives $\dfrac{298\pi}{180} \textsf{ rad} = \dfrac{149\pi}{90} \textsf{ rad} = 5.201 \textsf{ rad}$ to three decimal places.
 

1.4. Multiplying $61^\circ$ by $\pi$ and dividing by $180$ gives $\dfrac{61\pi}{180} \textsf{ rad} = 1.064 \textsf{ rad}$ to three decimal places.
 

1.5. Multiplying $353^\circ$ by $\pi$ and dividing by $180$ gives $\dfrac{353\pi}{180} \textsf{ rad} = 6.161 \textsf{ rad}$ to three decimal places.
 

1.6. Multiplying $197^\circ$ by $\pi$ and dividing by $180$ gives $\dfrac{197\pi}{180} \textsf{ rad} = 3.438 \textsf{ rad}$ to three decimal places.
 

## Q2 {-}

2.1. Multiplying $\dfrac{\pi}{3} \textsf{ rad}$ by $180$ and dividing by $\pi$ gives $\dfrac{180\pi}{3\pi} ^\circ = 60 ^\circ$.
 

2.2.  Multiplying $\dfrac{2\pi}{3}\textsf{ rad}$ by $180$ and dividing by $\pi$ gives $\dfrac{360\pi}{3\pi} ^\circ = 120 ^\circ$.
 

2.3.  Multiplying $\dfrac{\pi}{7} \textsf{ rad}$ by $180$ and dividing by $\pi$ gives $\dfrac{180\pi}{7\pi} ^\circ = 25.714 ^\circ$ to three decimal places.
 

2.4.  Multiplying $\dfrac{5\pi}{7}\textsf{ rad}$ by $180$ and dividing by $\pi$ gives $\dfrac{900\pi}{7\pi} ^\circ = 128.571 ^\circ$ to three decimal places.
 

2.5.  Multiplying $5\textsf{ rad}$ by $180$ and dividing by $\pi$ gives $\dfrac{900}{\pi} ^\circ = 286.479 ^\circ$ to three decimal places.
 

2.6. Multiplying $\dfrac{3}{4} \textsf{ rad}$ by $180$ and dividing by $\pi$ gives $\dfrac{540}{4\pi} ^\circ = \dfrac{135}{\pi} ^\circ = 42.972 ^\circ$ to three decimal places.
 

## Q3 {-}

3.1. In this case, the length of the arc is $\dfrac{7\pi}{8} = 2.749$ (to 3dp) and the area of the sector is $\dfrac{49\pi}{16} = 9.621$ (to 3dp).
 

3.2. In this case, the length of the arc is $\dfrac{\pi}{2} = 1.571$ (to 3dp) and the area of the sector is $\dfrac{\pi}{12} = 0.262$ (to 3dp).
 

3.3. In this case, the length of the arc is $14\pi = 43.982$ (to 3dp) and the area of the sector is $\dfrac{525\pi}{2} = 824.668$ (to 3dp).

---

---