---
title: "Answers: Rationalizing the denominator"
author: "Maximilian Volmar"
abstract-title: Summary
abstract: Answers to questions relating to the guide on rationalizing the denominator.
draft: true
---

*These are the answers to [Questions: Rationalizing the denominator](../questions/qs-rationalizingthedenominator.qmd).* 

**Please attempt the questions before reading these answers!**

## Q1 {-}

1.1. $\quad \dfrac{5}{\sqrt{3}} = \dfrac{5\sqrt{3}}{3}$

1.2. $\quad \dfrac{7}{2\sqrt{5}} = \dfrac{7\sqrt{5}}{10}$

1.3. $\quad \dfrac{11}{4\sqrt{7}} = \dfrac{11\sqrt{7}}{28}$

1.4. $\quad \dfrac{8}{5\sqrt{6}} = \dfrac{4\sqrt{6}}{15}$

1.5. $\quad \dfrac{3\sqrt{2}}{\sqrt{5}} = \dfrac{3\sqrt{10}}{5}$

1.6. $\quad \dfrac{9}{\sqrt{10}} = \dfrac{9\sqrt{10}}{10}$

1.7. $\quad \dfrac{\sqrt{7}}{\sqrt{3}} = \dfrac{\sqrt{21}}{3}$

1.8. $\quad \dfrac{\sqrt{2}}{\sqrt{6}} = \dfrac{\sqrt{3}}{3}$

1.9. $\quad \dfrac{12}{\sqrt{11}} = \dfrac{12\sqrt{11}}{11}$

1.10. $\quad \dfrac{\sqrt{8}}{\sqrt{2}} = 2$

1.11. $\quad \dfrac{15}{3\sqrt{7}} = \dfrac{5\sqrt{7}}{7}$

1.12. $\quad \dfrac{6\sqrt{3}}{\sqrt{10}} = \dfrac{3\sqrt{30}}{5}$

1.13. $\quad \dfrac{\sqrt{18}}{\sqrt{9}} = \sqrt{2}$

1.14. $\quad \dfrac{2\sqrt{5}}{\sqrt{12}} = \dfrac{\sqrt{30}}{3}$

1.15. $\quad \dfrac{4}{\sqrt{2}} = 2\sqrt{2}$

1.16. $\quad \dfrac{10}{5\sqrt{13}} = \dfrac{2\sqrt{13}}{13}$

---

## Q2 {-}

2.1. $\quad \dfrac{5}{2 + \sqrt{3}} = 10 - 5\sqrt{3}$

2.2. $\quad \dfrac{7}{4 - \sqrt{2}} = \dfrac{4 + \sqrt{2}}{2}$

2.3. $\quad \dfrac{3}{\sqrt{5} + 1} = \dfrac{3\sqrt{5} - 3}{4}$

2.4. $\quad \dfrac{\sqrt{7}}{\sqrt{3} - 1} = \dfrac{\sqrt{21}+\sqrt{7}}{2}$

2.5. $\quad \dfrac{2 + \sqrt{5}}{1 - \sqrt{2}} = {-2 - 2\sqrt{2} - \sqrt{5} - \sqrt{10}}$

2.6. $\quad \dfrac{3\sqrt{2} + 5}{4 + \sqrt{6}} = \dfrac{12\sqrt{2} - 6\sqrt{3} + 20 - 5\sqrt{6}}{10}$

2.7. $\quad \dfrac{8}{3 - \sqrt{7}} = 12 + 4\sqrt{7}$

2.8. $\quad \dfrac{6}{2 + \sqrt{5}} = -12 + 6\sqrt{5}$

2.9. $\quad \dfrac{\sqrt{10}}{\sqrt{2} + 3} = \dfrac{3\sqrt{10} - 2\sqrt{5}}{7}$

2.10. $\quad \dfrac{2\sqrt{3} + 5}{\sqrt{7}-1} = \dfrac{2\sqrt{21} + 5\sqrt{7} + 2\sqrt{3} + 5}{6}$

2.11. $\quad \dfrac{\sqrt{6} - \sqrt{2}}{2 + \sqrt{5}} = -2\sqrt{6} + 2\sqrt{5} + 2\sqrt{2} - \sqrt{10}$

2.12. $\quad \dfrac{4 + \sqrt{3}}{5 - \sqrt{7}} = \dfrac{4\sqrt{7} + 5\sqrt{3} + \sqrt{21} + 20}{18}$

2.13. $\quad \dfrac{2}{4 - \sqrt{11}} = \dfrac{8 + 2\sqrt{11}}{5}$

2.14. $\quad \dfrac{\sqrt{8} + \sqrt{3}}{\sqrt{7} - 2} = \dfrac{2\sqrt{14} + 4\sqrt{2} + \sqrt{21} + 2\sqrt{3}}{3}$

---

## Q3 {-}

3.1. $\quad$ To prove this equation, rationalize the denominator of the left hand side of the equation.

Since the denominator contains two square roots you can multiply the numerator and denominator by $-2\sqrt{3} + \sqrt{5}$ or by $2\sqrt{3} - \sqrt{5}$ to rationalize the denominator.

If you multiply the numerator and denominator by $2\sqrt{3} - \sqrt{5}$ you get:

$$
\dfrac{\sqrt{11}}{2\sqrt{3} + \sqrt{5}} \cdot \dfrac{2\sqrt{3} - \sqrt{5}}{2\sqrt{3} - \sqrt{5}} = \dfrac{\sqrt{11}(2\sqrt{3} - \sqrt{5})}{(2\sqrt{3})^2 - 2\sqrt{15} + 2\sqrt{15} - (\sqrt{5})^2}
$$

Simplifying the denominator and expanding the brackets gives you:

$$
\dfrac{2\sqrt{33} - \sqrt{55}}{4(3) - 5}
$$

Simplifying further gives you the final answer and the right hand side of the equation you are proving:

$$
\dfrac{2\sqrt{33} - \sqrt{55}}{7}
$$

If you instead multiply the numerator and denominator by $-2\sqrt{3} + \sqrt{5}$ you get:

$$
\dfrac{\sqrt{11}}{2\sqrt{3} + \sqrt{5}} \cdot \dfrac{-2\sqrt{3} + \sqrt{5}}{-2\sqrt{3} + \sqrt{5}} = \dfrac{\sqrt{11}(-2\sqrt{3} + \sqrt{5})}{(\sqrt{5})^2 + (2\sqrt{3})^2 + 2\sqrt{15} - 2\sqrt{15} - (-2\sqrt{3})^2}
$$

Simplifying the denominator and expanding the brackets gives you:

$$
\dfrac{- 2\sqrt{33} + \sqrt{55}}{5 - 4(3)}
$$

Further simplifying the denominator gives you:

$$
\dfrac{- 2\sqrt{33} + \sqrt{55}}{-7}
$$

To get a positive denominator, multiplying both the numerator and the denominator by $-1$ gives you the right hand side of the equation you are proving:

$$
\dfrac{2\sqrt{33} - \sqrt{55}}{7}
$$

3.2. $\quad \dfrac{5-\sqrt{2}}{\sqrt{10}-\sqrt{3}} = \dfrac{5\sqrt{10}-5\sqrt{3}-2\sqrt{5}+\sqrt{6}}{7}$

---

---

## Version history and licensing {-}

v1.0: initial version created 09/24 by Maximilian Volmar.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
