---
title: "Answers: The scalar product"
author: "Ritwik Anand"
abstract-title: Summary
abstract: Answers to questions relating to the guide on the scalar product.
---

*These are the answers to [Questions: The scalar product](../questions/qs-scalarproduct.qmd).*

**Please attempt the questions before reading these answers!**

## Q1 {-}

1.1. For $\mathbf{a}= \begin{pmatrix}6\\3\\4\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}1\\4\\2\end{pmatrix}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = 26$.

1.2. For $\mathbf{a}= \begin{pmatrix}10\\-7\\4\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}3\\-5\\13\end{pmatrix}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = 117$.

1.3. For $\mathbf{a}= \begin{pmatrix}-44\\-12\\3\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}61\\-25\\93\end{pmatrix}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = -2237$.

1.4. For $\mathbf{a}= \begin{pmatrix}54\\38\\0\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}32\\-55\\13\end{pmatrix}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = -362$.

1.5. For $\mathbf{a}= 2\mathbf{i} + 7\mathbf{j} + \mathbf{k}$ and $\mathbf{b}= 6\mathbf{i} + 4\mathbf{j} + 8\mathbf{k}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = 48$.

1.6. For $\mathbf{a}= -3\mathbf{i} + 10\mathbf{j} - 8\mathbf{k}$ and $\mathbf{b}= \mathbf{i} - 12\mathbf{j} + 9\mathbf{k}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = -195$.

1.7. For $\mathbf{a}= 17\mathbf{j} + 23\mathbf{k}$ and $\mathbf{b}= 6\mathbf{i} - 23\mathbf{j} - 8\mathbf{k}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = -575$.

1.8. For  $\mathbf{a}= \mathbf{i}$ and $\mathbf{b}= \mathbf{j}$, the scalar product is $\mathbf{a}\cdot\mathbf{b} = 0$.

As the scalar product of $\mathbf{a}= \mathbf{i}$ and $\mathbf{b}= \mathbf{j}$ is $0$, they are perpendicular to each other. This is true for any combination of any *distinct* pair of $\mathbf{i}$, $\mathbf{j}$, and $\mathbf{k}$. However, since any vector is parallel to itself, it follows that $\mathbf{i}\cdot \mathbf{i} = |\mathbf{i}||\mathbf{i}| = |1||1| = 1$; similar results hold for $\mathbf{j}\cdot \mathbf{j}$ and $\mathbf{k}\cdot \mathbf{k}$.

## Q2 {-}

2.1. For $\mathbf{a}= \begin{pmatrix}-5\\2\\-3\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}2\\-2\\11\end{pmatrix}$, the angle $\theta$ is $132.2^\circ$.

2.2. For $\mathbf{a}= \begin{pmatrix}1\\1\\1\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}1\\-1\\1\end{pmatrix}$, the angle $\theta$ is $70.5^\circ$.

2.3. For $\mathbf{a}= \begin{pmatrix}-8\\1\\-4\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}-1\\-5\\7\end{pmatrix}$, the angle $\theta$ is $108.7^\circ$.

2.4. For $\mathbf{a}= \begin{pmatrix}1.2\\-1.4\\-3.1\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}-5.4\\9.7\\-7.5\end{pmatrix}$, the angle $\theta$ is $86.2^\circ$.

2.5. For $\mathbf{a}= \begin{pmatrix}45\\65\\54\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}-19\\-58\\71\end{pmatrix}$, the angle $\theta$ is $95.1^\circ$.

2.6. For $\mathbf{a}= \begin{pmatrix}1\\0\\0\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}0\\0\\1\end{pmatrix}$, the angle $\theta$ is $90^\circ$.

2.7. For $\mathbf{a}= \begin{pmatrix}-1\\-2\\3\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}4\\-5\\6\end{pmatrix}$, the angle $\theta$ is $43.0^\circ$.

2.8. For $\mathbf{a}= \begin{pmatrix}-17\\3\\8\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}12\\-19\\-16\end{pmatrix}$, the angle $\theta$ is $137.8^\circ$.

## Q3 {-}

3.1. For $\mathbf{a}= \begin{pmatrix}2\\4\\7\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}1\\\lambda\\-2\end{pmatrix}$ to be perpendicular, then $\lambda= 3$.

3.2. For $\mathbf{a}= \begin{pmatrix}0\\1\\\lambda\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}1\\2\\3\end{pmatrix}$ to be perpendicular, then $\displaystyle\lambda= -\frac{2}{3}$.

3.3. For $\mathbf{a}= \begin{pmatrix}9\\-2\\11\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}\lambda\\-\lambda\\3\end{pmatrix}$ to be perpendicular, then $\lambda= -3$.

3.4. For $\mathbf{a}= \begin{pmatrix}\lambda\\6\\1\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}\lambda\\\lambda\\8\end{pmatrix}$ to be perpendicular, then $\lambda= -2$ or $\lambda= -4$.

3.5. For $\mathbf{a}= \begin{pmatrix}-2\lambda^2\\4\\14\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}3\\2\lambda\\1\end{pmatrix}$ to be perpendicular, then $\displaystyle\lambda = \frac{7}{3}$ or $\lambda= -1$.

3.6. For $\mathbf{a}= \begin{pmatrix}-5\\9\\2\lambda\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}\lambda\\-2\\\lambda\end{pmatrix}$ to be perpendicular, then $\displaystyle\lambda= \frac{9}{2}$ or $\lambda= -2$.

3.7. For $\mathbf{a}= \begin{pmatrix}-7\\4\\2\lambda\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}2\lambda\\1\\6\lambda\end{pmatrix}$ to be perpendicular, then $\displaystyle\lambda= \frac{2}{3}$ or $\displaystyle\lambda= \frac{1}{2}$.

3.8. For $\mathbf{a}= \begin{pmatrix}-25\\-1\lambda^2\\-2\end{pmatrix}$ and $\mathbf{b}= \begin{pmatrix}3\lambda\\-11\\7\end{pmatrix}$ to be perpendicular, then $\lambda= 7$ or $\displaystyle\lambda= -\frac{2}{11}$.

---

---
