---
title: "Answers: Solving exponential equations"
author: "Zoë Gemmell, Isabella Lewis, Akshat Srivastava"
abstract-title: Summary
abstract: Answers to questions relating to solving exponential equations.
---

*These are the answers to [Questions: Solving exponential equations](../questions/qs-solvingeqsindices.qmd)*

**Please attempt the questions before reading these answers!**

Throughout this answer sheet, the natural logarithm $\log_e(x)$ is written as $\ln(x)$.

---

1. The solution to $\sqrt[4]{x-4} = 5$ is $x = 629$.
 
 
<!--$\sqrt[4]{x-4}=5\implies (x-4)^\frac{4}{4}=5^4 \implies x-4=625 \implies x=629$\-->

2. The solution to $x^4=2^8$ is $x = 4$.
 
 
<!--$x^4=2^8\implies x^4=4^4\implies x=4$\-->

3. The solution to $11^x=121^{x-1}$ is $x = 2$.
 
 
<!-- \begin{align*} -->
<!-- x=\dfrac{\log(122)}{\log\left(\dfrac{122}{11}\right)}\end{align*} -->

4. The solution to $x^{0.5}$ is $x = 529$.
 
 
<!--$x^{0.5}=23\implies x=23^2 \implies x=529$\-->

5. The solution to $8^{2-x}=2^{4+3x}$ is $x = \dfrac{1}{3}$.
 
 
<!--8^{2-x}=2^{4+3x}\implies 2^{3(2-x)}=2^{4+3x} \implies 6-3x=4+3x \implies 2=6x\implies x=\frac{1}{3}$\-->

6. The solution to $2^{3x} = 10$ is $x = \dfrac{\log_2(10)}{3}$.
 
 
<!--$2^{3x}=10\implies3x\ln2=\ln10\implies x=\frac{\ln10}{3\ln2}$\-->

7. The solution to $5^{3-x}=625$ is $x = -1$.
 
 
<!--$5^{3-x}=625\implies5^{3-x}=5^4\implies3-x=4\implies x=-1$\-->

8. The solution to $16^{2x}=4^{x-1}$ is $x = -\dfrac{1}{3}$.
 
 
<!-- \begin{align*} -->
<!-- x=\dfrac{\log(2)}{\log\left(\dfrac{2}{17}\right)}\end{align*} -->

9. The solution to $7^{2-x}=4^{2x+3}$ is $x = \log_{112}\left(\dfrac{49}{64}\right)$.
 
 
<!-- $\frac{\ln(\frac{49}{64})}{\ln(112)}$ -->
<!--$7^{2-x}=4^{2x+3}\implies(2-x)\ln7=(2x+3)\ln4\implies2\ln7-x\ln7=2x\ln4+3\ln4\implies2\ln7-3\ln4=x(2\ln4+\ln7)\implies x=\frac{\ln(\frac{49}{64})}{\ln(112)}$\-->

10. The solution to $16=8^{3-7x}$ is $x = \dfrac{5}{21}$.
 
 
<!--$16=8^{3-7x}\implies2^4=2^{3(3-7x)}\implies4=9-21x\implies21x=5\implies x=\frac{5}{21}$\-->

11. The solution to $e^{3-8x}-9=0$ is $x = \dfrac{3-\ln(9)}{8}$.
 
 
<!-- <!--$e^{3-8x}-9=0\implies e^{3-8x}=9\implies \ln(e^{3-8x})=\ln(9)\implies3-8x=2\ln3\implies x=\frac{3-2\ln3}{8}$\-->

12. The solution to $e^{4-3x}+8=12$ is $x = \frac{4-\ln(4)}{3}$.
 
 
<!-- <!--$e^{4-3x}+8=12\implies e^{4-3x}=4\implies4-3x=\ln4\implies x=\frac{4-2\ln2}{3}$\--> 

13. The solution to $\sqrt[3]{2^{4x}-4}=5$ is $x = \dfrac{\log_2(129)}{4}$.
 
 

<!-- $\frac{\ln129}{4\ln2}$ -->
<!-- <!--$\sqrt[3]{2^{4x}-4}=5\implies(2^{4x}-4)^\frac{3}{3}=5^3\implies2^{4x}-4=125\implies2^{4x}=129\implies4x\ln2=\ln129\implies x=\frac{\ln129}{4\ln2}$\--> 

14. The solution to $\sqrt[3]{e^{2x}-13}=81^{\frac{1}{4}}$ is $x = \dfrac{\ln(40)}{2}$.
 
 

<!-- <!--$\sqrt[3]{e^{2x}-13}=81^{\frac{1}{4}}\implies(e^{2x}-13)^\frac{3}{3}=3^3\implies e^{2x}-13=27\implies 2x=\ln40\implies x=\frac{\ln40}{2}$\-->

15. The solution to $\dfrac{5xa^{-7}b^{9}}{9a^2b^{-10}} = \dfrac{25b^{19}}{3a^9}$ is $x = 15$.
 
 
<!--$\frac{5xa^{-7}b^{9}}{9a^2b^{-10}} = \frac{25b^{19}}{3a^9}\implies\frac{5xb^{(9+10)}}{9a^{(2+7)}}=\frac{25b^{19}}{3a^9}\implies\frac{5xb^{19}}{9a^9}=\frac{25b^{19}}{3a^9}\implies\frac{5x}{9}=\frac{25}{3}\implies15x=25\cdot9\implies x=15$\-->

16. The solution to  $4^x\cdot 2^x=64$ is $x = 2$.
 
 
<!-- then ${(4\cdot2)^x=64}$ and hence ${8^x=64}$ and so ${x=2}$\ -->

17. The solution to ${\dfrac{5^{x+1}\cdot6^{x+1}}{3^{x+1}}}=100$ is $x = 1$. 
 
 
<!-- =(\frac{5\cdot6}{3})^{x+1}=100$ hence, ${10^{x+1}=100}$ and so ${x=1}$\ -->

18. The solution to $\quad \dfrac{\left[\left(\frac{1}{2}\right)^x\cdot\left(\frac{-1}{4}\right)^x\right]}{\left(\frac{2}{3}\right)^x}=-\frac{27}{4096}$ is $x = 3$.
 
 
<!-- $\frac{(\frac{1}{2})^x\cdot(\frac{-1}{4})^x}{(\frac{2}{3})^x}=\frac{-27}{4096}$ , combining the first two fractions, $\frac{({\frac{1}{8})^x}}{({\frac{2}{3})^x}}=(\frac{-1}{8})^x\cdot(\frac{3}{2})^x=(\frac{-3}{16})^x={\frac{-27}{4096}}$ and so ${x=3}$\ -->

19. The solution to $3^{x+1}=7^x$ is $x = \log_{7/3}(3)$.
 
 
<!-- \begin{align*} -->
<!-- x=-\dfrac{\log(3)}{\log\left(\dfrac{7}{3}\right)}\end{align*} -->

20. The solution to $5^{x+1}+5^x=12$ is $x = \log_5(2)$.
 
 
<!-- \begin{align*} -->
<!-- x=\dfrac{\log(2)}{\log(5)}\end{align*} -->

21. The solution to $2^{3x-1}=10^x$ is $x = \log_{4/5}(2)$.
 
 
<!-- \begin{align*} -->
<!-- x=-\dfrac{\log(2)}{\log\left(\dfrac{5}{4}\right)}\end{align*} -->

22. The solution to $2^{2x}-2^{x+3}-2^4=0$ is $x = \log_2(4+4\sqrt{2})$.
 
<!-- \begin{align*} -->
<!-- x=2+\dfrac{log(1+\sqrt{2})}{log(2)}\end{align*} -->






<!-- ## Q4 {-} -->
<!-- Simplify the following expressions:\ -->

<!-- 4.1. $\sqrt{8}=\sqrt{4\cdot2}=\sqrt{4}\cdot\sqrt{2}=2\sqrt{2}$\ -->

<!-- 4.2. $\sqrt{3}\cdot\sqrt{7}=\sqrt{3\cdot7}=\sqrt{21}$\ -->

<!-- 4.3. $(\frac{\sqrt{24}}{\sqrt{6}})=\sqrt{\frac{24}{6}}=\sqrt{4}=2$\ -->

<!-- 4.4. $(\sqrt{5})^2=\sqrt{25}=5$\ -->

<!-- 4.5. $(\sqrt{2})^4=(\sqrt{2})^2\cdot(\sqrt{2})^2=2\cdot2=4$\ -->

<!-- 4.6. $\sqrt{75}=\sqrt{25}\cdot\sqrt{3}=5\sqrt{3}$\ -->

<!-- 4.7. $\sqrt{4^3}\cdot\sqrt[3]{8}$\ -->
<!-- $\sqrt{4^3}=(\sqrt{4})^3=2^3$\ -->
<!-- $\sqrt[3]{8}=2$\ -->
<!-- $\sqrt{4^3}\cdot\sqrt[3]{8}=2^3\cdot2=2^4=16$\ -->

<!-- 4.8. $\sqrt{6}\cdot\sqrt{15}=\sqrt{3\cdot3\cdot2\cdot5}=3\sqrt{10}$\ -->

<!-- 4.9. $\sqrt{75}-\sqrt{27}=5\sqrt{3}-3\sqrt{3}=2\sqrt{3}$\ -->

<!-- 4.10. $(8+\sqrt{2})\cdot(3-\sqrt{2})=24-2=3\sqrt{2}-8\sqrt{8}=22-5\sqrt{2}$\ -->

<!-- 4.11. $(3\sqrt{7})^2(8\sqrt{3})^2=(3\sqrt{7}\cdot8\sqrt{3})^2=(24\sqrt{21})^2=24^2\cdot21=12096$\ -->

<!-- 4.12. $(3-\sqrt{8})^2=9+8-2(3\sqrt{8})=17-6\sqrt{8}$\ -->

<!-- 4.13. $(7+\sqrt{5})\cdot(1+\sqrt{5})=7+5+\sqrt{5}+7\sqrt{5}=12+8\sqrt{5}$\ -->

<!-- 4.14. $\sqrt{45}+\sqrt{125}=\sqrt{9}\cdot\sqrt{5}+\sqrt{25}\cdot\sqrt{5}=3\sqrt{5}+5\sqrt{5}=8\sqrt{5}$\ -->

<!-- 4.15. $\sqrt{108}=\sqrt{36\cdot3}=6\sqrt{3}$ -->


<!-- ## Q5 {-} -->
<!-- Simplify the following:\ -->

<!-- 5.1. $\frac{8}{\sqrt{3}}=\frac{8\sqrt{3}}{3}$\ -->

<!-- 5.2. $\frac{7+\sqrt{5}}{3+\sqrt{5}}=\frac{7+\sqrt{5}}{3+\sqrt{5}}\cdot\frac{3-\sqrt{5}}{3-\sqrt{5}}=\frac{16-4\sqrt{5}}{9-5}=\frac{16-4\sqrt{5}}{4}=4-\sqrt{5}$\ -->

<!-- 5.3. $(\frac{2-\sqrt{3}}{3+\sqrt{3}})=(\frac{(2-\sqrt{3})\cdot(3-\sqrt{3})}{(3+\sqrt{3})\cdot(3-\sqrt{3})})=(\frac{6+3-3\sqrt{3}-2\sqrt{3}}{9-3})=(\frac{9-5\sqrt{3}}{6})$\ -->

<!-- 5.4. $\frac{21}{2+\sqrt{3}}=\frac{42-21\sqrt{3}}{4-3}=42-21\sqrt{3}$\ -->

<!-- 5.5. $\frac{1}{4-\sqrt{8}}=\frac{4+\sqrt{8}}{(4-\sqrt{8})\cdot(4+\sqrt{8})}=\frac{4+\sqrt{8}}{16-8}=\frac{4+\sqrt{8}}{8}=\frac{1}{2}+\frac{1}{4}\sqrt{2}$\ -->

---

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Zoë Gemmell, Isabella Lewis, Akshat Srivastava as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
