---
title: "Answers: Solving equations involving logarithms"
author: "Tom Coleman, Ellie Gurini"
abstract-title: Summary
abstract: Answers to questions relating to solving equations involving logarithms.
---

*These are the answers to [Questions: Solving equations involving logarithms](../questions/qs-solvingeqslogarithms.qmd)*

**Please attempt the questions before reading these answers!**

Throughout this answer sheet, the natural logarithm $\log_e(x)$ is written as $\ln(x)$.

---

## Q1 {-}

1.1. Here, $y=x^{1/4}$ and $x = y^4$.

1.2. Here, $y=x^3$ and $x = y^{1/3}$.

1.3. Here, $x = \sqrt{y^{1/2}x^3}$, $y = x^4/z^6$, $z = \sqrt[3]{x^2y^{-1/2}}$.

---

## Q2 {-}

2.1. The solution to $6\log_3(x)+\log_3(5)=9$ is $x=\sqrt[6]{\frac{3^9}{5}}$.

2.2. The solution to $\log_2(16x)=6$ is $x=4$.

2.3. The solution to $\log_{12}e^{2t} = 4$ is $t = 2\ln(12) = \ln(144)$.

2.4. The solution to $log_9(x)+log_3(3x)=6$ is $x=3^{10/3}$.

2.5. The solution to $4\ln\sqrt{x} - \ln(1-2x) = 0$ is $x = -1 + \sqrt{2}$.

2.6. The solution to $\ln(x+1) - \ln(x) = e$ is $x = \dfrac{1}{e^e - 1}$.

2.7. There are no solutions to $\log_{10}(2y + 10) = \log_{10}(y-2)$.

2.8. The solutions to $\log_3\sqrt{x} - \log_9 \sqrt{4x - 3} = 0$ are $x = 1$ and $x = 3$.

2.9. The solutions to $\log_3(2-3x) = \log_9(6x^2 - 19x + 2)$ are $x = -1/3$ and $x= -2$.

2.10. The solutions to $\log_3(x) - 2\log_x(3) = 1$ are $x = 9$ and $x = 1/3$.

---

## Q3 {-}

The solutions are $x = 15$ and $y = 1/2$. 

---

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Ellie Gurini as part of a University of St Andrews STEP project, and updated 10/25 by tdhc.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
