---
title: "Answers: Trigonometric identities (radians)"
author: "Dzhemma Ruseva"
abstract-title: Summary
abstract: A selection of questions on trigonometric identities, using radians to measure angles.

---

*These are the answers to [Questions: Trigonometric identities (radians)](../questions/qs-trigonometricidentities-radians.qmd).*

**Please attempt the questions before reading these answers!**


## Q1 {-}

1.1.  $\quad 2(6\sin^2(\theta))+3(4\cos^2(\theta)) = 12(\sin^2(\theta)+\cos^2(\theta)) = 12$

1.2.  $\quad 10(7\sin^2(\theta))+14(5\cos^2(\theta)) = 70$

1.3.  $\quad 5\left(\dfrac{6}{\csc^2(\theta)}\right)+15\left(\dfrac{2}{\sec^2(\theta)}\right) = 30$

1.4.  $\quad (\cos^2(\theta)-\sin^2(\theta))^2 + 4\sin^2(\theta)\cos^2(\theta) = \cos^2(2\theta) + \sin^2(2\theta) = 1$

<!-- 1.5.  $\ \quad7\cos(\pi/2-\theta)\sin(\theta)+7\sin(\pi/2-\theta)\cos(\theta)$ -->

<!-- **Answer:** $\ 7\cos(\pi/2-\theta)\sin(\theta)+7\sin(\pi/2-\theta)\cos(\theta) = 7\sin^2(\theta) + 7\cos^2(\theta) = 7$ -->

<!-- 1.6.  $\ \quad6\sin(\theta+2\pi)\sin(\theta+4\pi)+6\cos(\theta-2\pi)\cos(\theta-4\pi)$ -->

<!-- **Answer:** $\ 6\sin(\theta+2\pi)\sin(\theta+4\pi)+6\cos(\theta-2\pi)\cos(\theta-4\pi) = 6\sin^2(\theta) + 6\cos^2(\theta) = 6$ -->

1.5.  $\quad 2\sin(\pi/6)\cos(\pi/12)+2\cos(\pi/6)\sin(\pi/12) = 2\sin(\pi/6+\pi/12) = 2\sin(\pi/4) = \sqrt{2}$

1.6.  $\quad 3\cos(\pi/4)\cos(\pi/12)-3\sin(\pi/4)\sin(\pi/12) = 3\cos(\pi/3) = \dfrac{3}{2}$

1.7.  $\quad \sin(5\pi/6)+\sin(\pi/6) = 2\sin\left(\dfrac{180}{2}\right)\cos\left(\dfrac{120}{2}\right) = 2\sin(\pi/2)\cos(\pi/3) = 1$ 

1.8. $\quad \cos(5\pi/6)+\sin(\pi/6) = 2\cos(\pi/2)\cos(\pi/3) = 0$  


## Q2 {-}

2.1. $\quad \tan(\theta)\cos(-\theta) = \dfrac{\sin(\theta)}{\cos(\theta)}\cdot\cos(\theta) = \sin(\theta)$

2.2  $\quad \displaystyle\tan(-\theta)\csc(-\theta)\sec(-\theta) = \left(-\frac{\sin(\theta)}{\cos(\theta)}\right)\left(\frac{1}{-\sin(\theta)}\right)\left(\frac{1}{\cos(\theta)}\right) = \left(\frac{1}{\cos^2(\theta)}\right) = \sec^2(\theta)$

2.3. $\quad\tan^2(\theta)+\sin^2(\theta)+\cos^2(\theta) = \tan^2(\theta)+1 = \sec^2(\theta)$

2.4. $\quad \dfrac{2\sin(\theta)}{\cos(\theta)(1-\tan^2(\theta))} = \tan(2\theta)$

<!-- 2.5. $\ \quad\sin(\pi/2+\theta)-\sin(\pi/2-\theta)$ -->

<!-- **Answer:** $\ \sin(\pi/2+\theta)-\sin(\pi/2-\theta) = 2\sin(\pi/2)\cos(\theta) = 2\cos(\theta)$ -->

2.5. $\quad\displaystyle\frac{\sin(7\theta)+\sin(3\theta)}{\cos(7\theta)-\cos(3\theta)} = \frac{2\sin(5\theta)\cos(2\theta)}{-2\sin(5\theta)\sin(2\theta)} = -\cot(\theta)$

2.6. $\quad\displaystyle\frac{\sin(5\theta)-\sin(\theta)}{\cos(5\theta)+\cos(\theta)} = \tan(2\theta)$
 
## Q3 {-}

3.1. $\cos(5\pi/6) = \dfrac{\sqrt{3}}{2}$

3.2. Here $\sin(3\pi/4) = \dfrac{1}{\sqrt{2}}$, and $\sin(5\pi/4) = -\dfrac{1}{\sqrt{2}}$.

3.3. $\cos(13\pi/18) = -0.766$ to three decimal places.

## Q4 {-}

4.1. $\sin(\pi/12) = \sin(\pi/4)\cos(\pi/6) - \cos(\pi/4)\sin(\pi/6) = \dfrac{\sqrt3}{2\sqrt2} - \dfrac{1}{2\sqrt2} = \dfrac{\sqrt3-1}{2\sqrt2}$ 

4.2. $\quad\cos(\pi/12) = \dfrac{\sqrt3+1}{2\sqrt2}$

4.3. $\quad \tan(\pi/12) =\dfrac{\sqrt3+1}{\sqrt3-1}$

4.4. $\quad \sin(5\pi/12) = \sin(\pi/4)\cos(\pi/6) + \cos(\pi/4)\sin(\pi/6) = \dfrac{\sqrt3+1}{2\sqrt2}$

4.5. $\quad\cos(5\pi/12) = \dfrac{\sqrt3-1}{2\sqrt2}$

4.6. $\quad\tan(5\pi/12) = \dfrac{\sqrt3+1}{\sqrt3-1}$

---

---

## Version history and licensing {-}

v1.0: initial version created 08/23 by Dzhemma Ruseva as part of a University of St Andrews STEP project.

  - v1.1: edited 05/24 by tdhc, and split into versions for both degrees and radians.

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

