---
title: "Answers: Introduction to $t$-testingg"
author: "Millie Harris"
abstract-title: Summary
abstract: Answers to a selection of questions for the study guide on introduction to $t$-testing.
draft: True
---

*These are the answers to [Questions: Introduction to](../questions/qs-introtottesting.qmd)* [$t$-testing](../questions/qs-introtottesting.qmd).

**Please attempt the questions before reading these answers.**

## Q1

**1.1.** Sample size less than $30$.

**1.2.** A hypothesis test where the test statistic follows the $t$ distribution.

**1.3.** A $t$-test with equal variances.

**1.4.** A $t$-test with unequal variances.

## Q2 

**2.1.** $\bar{x}$ is the sample mean. $\mu_0$ is the known value. $s$ is the sample standard deviation. $n$ is the sample size.

**2.2.** $\mu_1$ is sample mean 1. $\mu_2$ is sample mean 2. $s_1$ is sample standard deviation 1. $s_2$ is sample standard deviation 2. $n_1$ is sample size 1. $n_2$ is sample size 2.

**2.3.**

a\) $s_1 = s_2$

b\) $s_1 \neq s_2$

## Q3

**3. 1.** $H_0: \bar{x} = \mu_0 H_1: \bar{x} > \mu_0$

**3.2.** $H_0: \mu_1 = \mu_2 H_1: \mu_1 > \mu_2$

**3.3.** $H_0: \mu_1 = \mu_2 H_1: \mu_1 \neq \mu_2$

$(10-7)/(s/\sqrt{19}) = 26.1534$

Student’s $t$-test.

One sample $t$-test are always Student $t$-tests.

$(12 - 13)/((2/\sqrt{15}) + (2/\sqrt{16})) = -0.9839$

Student’s $t$-test.

$s1_ = s_2$

$(45-51)/((3/\sqrt{19}) + (3.5/\sqrt{18})) = -3.9651$

Welch’s $t$-test.

$s_1 \neq s_2$

## Version history and licensing {.unnumbered}

v1.0: initial version created 03/26 by Millie Harris (as part of a University of St Andrews VIP project)

[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
