---
title: Conditional Probability and Bayes Theorem
author: Sophie Chowgule
abstract-title: Summary
abstract: Conditional probability and Bayes’ Theorem are fundamental concepts in the area of probability theory. They are key to understanding how the probability of an event is affected by the introduction of new information. In this guide, you will learn how to calculate conditional probabilities, apply the multiplication rule, test for independence, distinguish between independent and disjoint events, and use Bayes' Theorem to update predictions.
categories:
  - Probability
  - Statistics
draft: true
---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this guide, it is highly recommended that you read [Guide: Introduction to probability].*

# Introduction

<!-- robabilities don’t always stay the same — they can change when new information becomes available. \textsf  -->
<!-- For example, seeing dark clouds makes it more likely that it will rain, or knowing that a sweet shop has just had a delivery makes it more likely you’ll find your favourite sweets. These situations show how learning something new can shift how likely you think an event is. -->

<!-- This guide introduces two key ideas that help explain and measure these changes: **conditional probability** and **Bayes' Theorem**. You’ll learn how to update probabilities based on new evidence, calculate the chance of two events both happening, and test whether events are independent or not. These tools are essential for solving problems involving uncertainty, whether in everyday reasoning or real-world data. -->

In everyday life, events often affect one another and knowing one thing can change what you expect about something else. For example, seeing clouds makes it more likely that it will rain, or knowing that a sweet shop has just had a delivery makes it more likely you will find your favourite sweets. These examples show how new information can change the way we think about probabilities. 

**Conditional probability** and **Bayes’ Theorem** help explain and quantify these changes. They allow you to update predictions based on new information, deal with uncertainty, and apply probability theory to real-world problems.

# Conditional probability

In everyday life, the likelihood of an event often changes as you learn new information. For example, if you are planning to leave the house and see clouds gathering, you may assume it is more likely to rain and decide to take an umbrella. The idea that the probability of one event can change based on the occurrence of another can be understood using conditional probability. **Conditional probability** calculates the probability of an event happening given that another event has already occurred. More formally:

::: {.callout-note icon="true"}
## Definition of conditional probability

If $A$ and $B$ are events, then the **conditional probability** of $A$ occurring given that $B$ has occurred, written as $P(A \mid B)$, is defined as:

$$
P(A \mid B)=\dfrac{P(A \cap B)}{P(B)}.
$$

where:

-  $P(A \cap B)$ is the probability that both $A$ and $B$ occur.
-  $P(B)$ is the probability that $B$ occurs on its own, regardless of $A$.
:::

::: {.callout-note} 
The notation $P(A \mid B)$ is read as "the probability of $A$ given $B$", where "$\mid$" means "given".
:::

::: {.callout-note} 
The notation $P(A \cap B)$ is read as "the probability of $A$ and $B$," where "$\cap$" means intersection. The intersection represents the shared outcomes between $A$ and $B$, meaning the outcomes where both events occur.


For a more detailed explanation on the set notations used here, see [Guide: Operations on Sets].
:::

::: {.callout-warning} 
Conditional probability is only defined when $P(B) > 0$, meaning that the event $B$ must have a chance of occurring. Otherwise, it would not make sense to talk about the probability of $A$ occurring given that $B$ has occurred if $B$ itself has no chance of happening. This is also reflected in the formula for conditional probability, where division by $P(B)$ would not be possible if $P(B) = 0$, as $P(A \mid B)$ would be undefined.
:::

::: {.callout-note appearance="simple"}

## Example 1

Suppose you roll a fair six-sided die. The possible outcomes are ${1, 2, 3, 4, 5, 6}$. You cannot see the result, but you are told that the number is greater than 2. Given this information, what is the probability that the number is even?

Knowing that the result is greater than $2$, the possible outcomes are now ${3, 4, 5, 6}$ and among these outcomes, the even numbers are $4$ and $6$. 

With this new information, you can now apply the formula for conditional probability:
$$ 
P(\text{Even} \mid X>2)=\dfrac{P(\text{Even and } X > 2)}{P(X > 2)}.
$$
To use this formula, you first find the individual probabilities:

* $P(\text{Even and } X > 2)$ is the probability of rolling an even number above $2$, meaning either a $4$ or a $6$, so:
$$
P(\text{Even and } X>2)=\dfrac{2}{6}.
$$
* $P(X > 2)$ is the probability that the roll is greater than 2, which includes the outcomes $3, 4, 5,$ and $6$, so:
$$
P(X>2)=P(X>2)=\dfrac{4}{6}
$$
Substituting these into the formula gives:
$$
P(\text{Even}∣X>2)=\dfrac{2/6}{4/6}=\dfrac{2}{4}=\dfrac{1}{2}
$$
Thus, given that the roll is greater than 2, the probability that it is even is $\frac{1}{2}$.


:::

::: {.callout-note appearance="simple"}

## Example 2

Now imagine you draw a card at random from a standard deck of cards. You cannot see which card was drawn, but you are told that it is a face card, that is, a Jack, Queen, or King. Given this information, what is the probability that the card is a King?

Since you know the card is a face card, the possible outcomes are now limited to the four Jacks, four Queens, and four Kings, with one King in each suit.

As in previous example, you can now apply the formula for conditional probability:
$$
P(\text{King} \mid \text{Face card})=\dfrac{P(\text{King and Face card})}{P(\text{Face card})}.
$$
First find the individual probabilities:

* $P(\text{King and Face card})$ is the probability that the card is a King. Since there are 4 Kings in the deck:
$$
P(\text{King and Face card})=452.
$$
* $P(\text{Face card})$ is the probability that the card is any face card. There are 12 face cards in total, so:
$$
P(\text{Face card})=\dfrac{12}{52}.
$$
Substituting these into the conditional probability formula gives:
$$
P(\text{King∣Face card})=\dfrac{4/52}{12/52}='dfrac{4}{12}=\dfrac{1}{3}.
$$
Thus, given that the card is a face card, the probability that it is a King is $\dfrac{1}{3}$.
:::

# Multiplication rule

Sometimes you want to find the probability that two events both happen. For example, suppose you are picking two cards from a deck, one after the other. You might know the probability that the first card is a Queen, and you might also know the probability that the second card is a Queen given that the first card was a Queen. But what if you want to find the probability that both cards are Queens?

The multiplication rule allows you to calculate the probability that two events both occur, based on a conditional probability and the probability of one of the events. It comes directly from rearranging the formula for conditional probability, and it is useful when you have partial information about two related events.

::: {.callout-note}

## Multiplication rule

If $A$ and $B$ are events, then the probability that both $A$ and $B$ occur, P(A \cap B), is given by:
$$
P(A \cap B)=P(B)P(A \mid B).
$$
where: 

* $P(B)$ is the probability that $B$ occurs, regardless of $A$.
* $P(A \mid B)$ is the probability that $A$ occurs given that $B$ has occurred.
:::

::: {.callout-note appearance="simple"}
## Example 3

Suppose you draw two cards from a standard deck of cards, one after the other, without replacement. What is the probability that both cards drawn are queens?

To solve this, you can use the multiplication rule:
$$
P(\text{First queen and Second queen})=P(\text{First queen})×P(\text{Second queen∣First queen}).
$$
First, you need to work out two things:

* The probability that the first card is a queen.
* The probability that the second card is a queen given that the first card was a queen.

There are $4$ queens in a deck of $52$ cards, one for each suit. Hence the probability that the first card is a queen is:
$$
P(\text{First queen})=\dfrac{4}{52}.
$$
If the first card was a queen, then there are now only $3$ queens left out of the remaining $51$ cards. This means the probability that the second card is a queen given that the first card was a queen is:
$$
P(\text{Second queen} \mid \text{First queen}) = \dfrac{3}{51}
$$
Now substitute these two probabilities into the multiplication rule to get:
$$
P(\text{Two queens})=\dfrac{4}{52} \times \dfrac{3}{51} = \dfrac{12}{2652}=\dfrac{1}{221} \approx 0.0045.
$$
Thus, the probability of drawing two queens without replacement is approximately $0.0045$.
:::

# Checking for independence using conditional probability

Conditional probability can also be used to check whether two events are independent or not. If two events $A$ and $B$ are independent, then knowing that $B$ has occurred does not change the probability of $A$ occurring.  

This means:
$$
P(A∣B)= P(A).
$$
If $P(A \mid B)$ is not equal to $P(A)$, then knowing that $B$ has occurred changes the probability of $A$, and so $A$ and $B$ are dependent events.

::: {.callout-tip}
For a more detailed explanation of independent and dependent events, see [Guide: Introduction to Probability].
:::

::: {.callout-note appearance="simple"}
## Example 4

Imagine you roll a fair six-sided die. Let $A$ be the event that the die shows an even number, and let $B$ be the event the die shows a number greater than 4.

First, find:

* $P(A)$, the probability the die shows an even number, $2, 4,$ or $6$ is:
$$
P(A)=\dfrac{3}{6}=\dfrac{1}{2}.
$$
* Now find $P(A \mid B)$, the probability the number is even given that it is greater than $4$. The outcomes greater than $4$ are $5$ and $6$ and among the two, only $6$ is even. So:
$$
P(A \mid B)=\dfrac{1}{2}
$$

Since:
$$
P(A \mid B)=\dfrac{1}{2}=P(A)
$$
the events $A$ and $B$ are independent.

:::

::: {.callout-note appearance="simple"}
## Example 5

Suppose again you draw one card from a standard deck of 52 cards. Let $A$ be the event the card is a Queen, and let $B$ be the event the card is a face card.

First, find:

* $P(A)$, the probability the card is a Queen:
$$
P(A)=\dfrac{4}{52}=\dfrac{1}{13}.
$$
* Now find $P(A \mid B)$, the probability the card is a Queen given that it is a face card.
There are 12 face cards in total, and 4 of them are Queens, so:
$$
P(A \mid B)=\dfrac{4}{12}=\dfrac{1}{3}.
$$

Since:
$$
P(A∣B) = \dfrac{1}{3} \neq \dfrac{1}{13} = P(A)
$$
the events $A$ and $B$ are dependent.
:::

# Disjoint events

When working with probability, it is important to understand the difference between disjoint events and independent events.


* **Disjoint** events (also called mutually exclusive events) are events that cannot occur at the same time. If $A$ and $B$ are disjoint, then:
$$
P(A \cap B)= 0.
$$
For example, flipping a coin once cannot result in both heads and tails. 

* **Independent** events are events where the outcome of one event does not affect the probability of the other.
If $A$ and $B$ are independent, then:
$$
P(A \cap B)= P(A)P(B).
$$
For example, flipping a coin and rolling a die are independent events, the result of the coin flip does not change the probabilities of the die roll.

| Feature| Disjoint Events| Independent Events|
|:--------|:----|:----|
| Can both events occur at the same time? | No | Yes |
| Formula     | $P(A \cap B) = 0$| $P(A \cap B) = P(A) P(B)$|
| Relationship between events | Knowing one happened means the other did not | Knowing one happened does not change the probability of the other |


## Bayes' theorem

Sometimes, it is easier to find the probability of one event given another, rather than the other way around. **Bayes' Theorem** provides a way to "reverse" conditional probabilities, allowing you to find the probability of $A$ given $B$ when you know the probability of $B$ given $A$. Bayes' Theorem is very useful for updating predictions based on new information, especially when it is difficult to calculate probabilities directly.

::: {.callout-note}
## Definition of Bayes' Theorem

If $A$ and $B$ are events with $P(B) > 0$, then Bayes' Theorem states:

$$
P(A \mid B) = \dfrac{P(B \mid A) P(A)}{P(B)}.
$$

where:

* $P(A \mid B)$ is the probability of $A$ given $B$,
* $P(B \mid A)$ is the probability of $B$ given $A$,
* $P(A)$ and $P(B)$ are the individual probabilities of $A$ and $B$.
:::

::: {.callout-note appearance="simple"}
## Example 8
Suppose in a sweet shop:

* $30\%$ of sweets are chocolate,
* $70\%$ of sweets are not chocolate,
* A chocolate sweet has a $70\%$ chance of being red,
* A non-chocolate sweet has a $20\%$ chance of being red.

You pick a sweet at random and find that it is red. What is the probability that it is a chocolate sweet?

Let $A$ be the event that the sweet is chocolate, and $B$ be the event the sweet is red.

You know:

* $P(A) = 0.3$,
* $P(B) = 0.4$ 
* $P(B \mid A) = 0.7$.

Then using Bayes' Theorem you can find out the probability the sweet is chocolate given that it is red:
$$
P(A \mid B) = \dfrac{P(B \mid A)P(A)}{P(B)} =  \dfrac{(0.7)(0.3)}{0.4} \approx 0.525
$$
Thus, given that the sweet is red, there is about a $52\%$ chance that it is chocolate.
:::

::: {.callout-note appearance="simple"}
## Example 9
Suppose:

* $20\%$ of days are rainy,  
* $80\%$ of days are not rainy,  
* On a rainy day, the forecast predicts rain $90\%$ of the time,  
* On a non-rainy day, the forecast predicts rain $10\%$ of the time.  

You are told that the forecast predicts rain on $26\%$ of days. So if the forecast predicts rain, what is the probability that it will actually rain?

Let $A$ be the event it rains, and $B$ be the event the forecast predicts rain.

You know:

* $P(A) = 0.2$,
* $P(B) = 0.26$,
* $P(B \mid A) = 0.9$.

Now applying Bayes' Theorem gives:
$$
P(A \mid B) = \dfrac{P(B \mid A)P(A)}{P(B)} =  \dfrac{(0.9)(0.2)}{0.26} \approx 0.6923
$$

Thus, if the forecast predicts rain, there is about a $69\%$ chance that it will actually rain.
:::

::: {.content-hidden when-format="html"}

# Quick Check Problems

1. Are the following statements true or false?

(a) Conditional probability measures the probability of an event without any additional information.  

(b) If $P(A \mid B) = P(A)$, then $A$ and $B$ are independent. 

(c) Disjoint events are always independent.

2. A fair six-sided die is rolled.

(a) Given that the roll is greater than 2, what is the probability of rolling a 5?

(b) Given that the roll is even, what is the probability that the roll is a 2? 

(c) Are "rolling an even number" and "rolling a number greater than 4" independent?

3. A card is drawn at random from a standard deck.

(a) Given that the card is a face card (Jack, Queen, King), what is the probability that it is a Queen?  

(b) Are the events "drawing a Queen" and "drawing a face card" independent?

4. Using Bayes' Theorem:

A sweet is picked at random, just as in example 8. If the sweet picked is red:

(a) What information does Bayes’ Theorem help you find?  

(b) What is the formula you would use to find the probability the sweet is chocolate, given that it is red.  

:::

# Further reading {-}

[For more questions on the subject, please go to Questions: PMFs, PDFs, and CDFs.](../questions/qs-pmfspdfscdfs.qmd)

[For more on why some PMFs and PDFs are valid, please go to Proof sheet: PMFs, PDFs, CDFs.](../proofsheets/ps-pmfspdfscdfs.qmd)

For more on probability distributions see [Overview: Probability distributions]

## Version history and licensing {-}

v1.0: initial version created 12/24 by Sophie Chowgule as part of a University of St Andrews VIP project.
  
[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)

