---
title: "Further sigma notation"
author: Tom Coleman, Ifan Howells-Baines, Mark Toner
abstract-title: Summary
abstract: Sigma notation is used to express many additions at once. Understanding what this notation is, how it works, and how to manipulate them is a valuable skill to learn for use in almost any area of mathematics.
draft: true
---

```{r, setup, include = FALSE}
library("webexercises")
```

<!-- *Before reading this guide, it is recommended that you read GUIDE and GUIDE* -->


## Properties

In this section you will learn about a few properties of sigma notation which means you'll have a toolkit to rearrange sums!

The first property you'll learn about sigma notation is *distribuitivity*. This property allows you to take constants from inside the sigma notation to outside the summation.

::: {.callout-note}
## Distribuitivity

  Let $a_k,a_{k+1}, \ldots, a_n$ be a sequence of numbers (where $k$ and $n$ are integers with $k \leq n$) and $C$ be any constant. Then $$\sum_{i=k}^n Ca_i = C \sum_{i=k}^n a_i.$$ 

:::

You can see this is true by writing the entire sum out, like this: 

$$
\begin{array}{rcl}
\sum_{i=k}^nCa_i &=& Ca_k + Ca_{k+1} + Ca_{k+2} + \ldots + Ca_n \\ 
&=& C(a_k + a_{k+1} + a_{k+2} + \ldots + a_n) \\ 
&=& C\sum_{i=k}^n a_k 
\end{array}
$$

::: {.callout-note appearance="simple"}
## Example 7

  What is the value of $\sum_{n=2}^56n^2$?
  
  Using distributivity, $\sum_{n=2}^56n^2 = 6\sum_{n=2}^5n^2$. From Example 2, you know that $\sum_{n=2}^5n^2 = 54$. Therefore, $6\sum_{n=2}^5n^2 = 6 \times 54 = 324$.
:::


## Double sums

Sometimes, you'll want to multiply two sums together. This can be written succinctly using something called *double sums*.

::: {.callout-note appearance="simple"}

## Double sums

  Let $a_{k},a_{k+1},\ldots,a_n$ and $b_t,b_{t+1},\ldots,b_m$ be two sequences of numbers (where $k,n,t$, and $m$ are integers with $k \leq n$ and $t \leq m$). Then the **double sum** $\sum_{i=k}^n\sum_{j=t}^m a_i b_j$ is defined as
  
$$
\begin{array}{rcl}
\sum_{i=k}^n\sum_{j=t}^m a_i b_j &=& a_kb_t + a_kb_{t+1} + \ldots + a_kb_m + a_{k+1}b_t + a_{k+1}b_{t+1}\\ 
& & \qquad+ \ldots + a_{k+1}b_m + \ldots + a_nb_m.
\end{array}
$$  
:::

::: {.callout-tip}
  You might find it easier to remember the above by thinking of $\sum_{i=k}^n\sum_{j=t}^m a_i b_j$ as $a_1(\sum_{j=t}^mb_j) + a_2(\sum_{j=t}^mb_j) + \ldots + a_n(\sum_{j=t}^mb_j).$
:::

You will now see how this relates to multiplying two sums together. Suppose that $a_k,a_{k+1},\ldots,a_n$ and $b_t,b_{t+1},\ldots,b_m$ are like above, and consider the product $(\sum_{i=k}^na_i)(\sum_{j=t}^mb_j)$. Writing it all out and performing the multiplication, you get 

$$
\begin{array}{rcl}
\left(\sum_{i=k}^na_i\right)\left(\sum_{j=t}^mb_j\right) &=& (a_k+a_{k+1}+\ldots+a_n)(b_t + b_{t+1}+\ldots+b_m) \\ &=& a_kb_t + a_kb_{t+1} + \ldots + a_kb_m + a_{k+1}b_t + a_{k+1}b_{t+1} + \\ & &\quad\quad \ldots + a_{k+1}b_m + a_{k+2}b_t + \ldots + a_nb_m \\[0.5em] &=& \sum_{i=k}^n\sum_{j=t}^m a_i b_j
\end{array}
$$ 

You can write this as a result:

::: {.callout-note}
## Double sums and products of two sums
  Let $a_{k},a_{k+1},\ldots,a_n$ and $b_t,b_{t+1},\ldots,b_m$ be two sequences of numbers (where $k,n,t$, and $m$ are integers with $k \leq n$ and $t \leq m$). Then $$\sum_{i=k}^n\sum_{j=t}^m a_i b_j = (\sum_{i=k}^na_i)(\sum_{j=t}^mb_j).$$

:::

::: {.callout-note appearance="simple"}

## Example 10

Write $(1+2+3+4+5+6)(2+4+6+8+10+12)$ as a double sum and as a product of two sums.

First, notice you can write out the above expression in the form $(1)(2) + (1)(4) + ... (1)(12) + (2)(2) + (2)(4) ... (3)(2) + ...(6)(12)$ 

From the definition above you may now rewrite the expression to the double sum 

$$\sum_{i=1}^6\sum_{j=1}^6 i*2j$$
using the distrubitivity property this can be written as $$2\sum_{i=1}^6\sum_{j=1}^6 ij$$

This can then be written using the product of two sums rule above to $$2\sum_{i=1}^6i\sum_{j=1}^6j$$

It is evident that the two sums are the same with different index variables this means that they can be combined to form $$2\sum_{k=1}^6k^2$$ 

$k$ has been used to differentiate the new sum from the ones involving $i$ and $j$ before but as always the choice of index variable is relatively unimportant

:::

## Quick check problems {-}


<!-- add facility to check answers at end rather than one at a time -->

::: {.webex-check .webex-box}

1. What is the value of $\displaystyle\sum_{i = 2}^{6} i$.

Answer: The value of the above is: `r fitb(20)`.

2. Given $\displaystyle\sum_{j = 1}^{100} i$ Identify the index of the sum.

Answer: The index is `r fitb("i")`

3. You are given several statements below based on the properties of sums. Identify whether they are true or false.

(a) The sum $3 + 6 + 9 + 12$ can be expressed as $\displaystyle\sum_{i = 0}^{4} 3i$ Answer: `r torf(TRUE)`.

(b)  The sum $-1 + 1 - 1 + 1$ can be expressed as $\displaystyle\sum_{i = 1}^{4} -i$ Answer: `r torf(FALSE)`.

(c)  $\displaystyle\sum_{i = 1}^{100} i = \sum_{i = 0}^{101} i$  Answer: `r torf(FALSE)`.

(d)  $\displaystyle\sum_{i = 1}^{100} 6i = 6 \sum_{i = 0}^{100} i$  Answer: `r torf(TRUE)`.

(e)  $\displaystyle\sum_{i = 1}^{100} 9i + \sum_{i = 1}^{100} 3i = \sum_{i = 1}^{100} 27i^2$  Answer: `r torf(FALSE)`.

(f) $\displaystyle\sum_{i = 1}^{100} 12i - \sum_{i = 1}^{100} 4i = 8 \sum_{i = 1}^{100} i$  Answer: `r torf(TRUE)`.

4. You are given several statements below based on the properties of sums. Identify whether they are true or false.

(a) $\sum_{i=1}^{10}\sum_{j=2}^6 ij$ can be expressed as $\displaystyle\left(\sum_{i=2}^6i\right)\left(\sum_{j=1}^{10} j\right)$ Answer: `r torf(FALSE)`.

(b) $\displaystyle\left(\sum_{i=1}^52i\right)\left(\sum_{j=5}^{10} 3j\right)$ can be expressed as $\displaystyle 6\left(\sum_{i=1}^5\sum_{j=5}^{10} ij\right)$$ Answer: `r torf(TRUE)`.

(c) The sum $(1+2+3+4+5+6)(-1-2)(3+6+9)$ can be expressed as $\displaystyle\sum_{i=1}^6\sum_{j=1}^2\sum_{k=1}^3 -3ijk$$ Answer: `r torf(TRUE)`.

:::

## Further reading

<!-- [For more questions on the subject, please go to Questions: Sigma Notation.](qs-sigmanotation.qmd) -->