---
title: "Introduction to the Laws of indices"
author: "Zheng Chen"
abstract-title: Summary
abstract: Indices are used in many aspects of modern technology. Economics, Biology, Demographics and many more fields rely on exponential growth. Chemicals, radioactive waste, sound are all examples of exponential decay. In mathematics, a knowledge of indices is important for an understanding of algebraic processes. The laws of indices enable expressions involving powers to be manipulated more efficiently than writing them out in full.
---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this guide, it is recommended that you read (Guide: Introduction to Logarithms) and (Guide: Dealing with powers and nth roots).*

## What are indices? {.unnumbered}

Indices are used to display how many times a number has been multiplied by itself. They can also be used to represent roots and fractions, such as the square root. The laws of indices make it possible to alter expressions involving powers more quickly than if they were written out whole.

This guide will introduce six properties of indices: multiplication, division, brackets,  powers of zero, negative indices and fractional indices.

::: callout-note

## Definition of an index

A number or a variable may have an **index**. The **index** of a variable (or a constant) is a value that is raised to the power of the variable. Indices are also known as powers or exponents. It shows the number of times a given number has to be multiplied. It is represented in the form

$$ a^m =\underbrace{a\cdot a \cdot a \cdot \ldots \cdot a}_{m\textsf{ times}}$$

Here, $a$ is the base and $m$ is the index.
:::

::: {.callout-note appearance="simple"}

## Example 1

Indices are basically a shorthand way of writing multiplications of the same number.
Suppose you have
$$2·2·2·2·2$$ 
you can write this as '$2$ to the power of $5$
$$2^5$$
So
$$2^5 = 2·2·2·2·2 = 32$$

In this example, $2$ is the base and $5$ is the index.
:::

## Laws of indices

Using indices is a way of writing something down. In mathematics you may want to use indices in other ways. For example, what do these expressions mean: $a^{-1}$ or $a^0$ or $a^{\LARGE\frac{1}{2}}$ ? 

To proceed further, you need to learn rules to operate with so you can find out what these notations mean.

::: {#law-1-link .callout-note}

## Law 1: Multiplication

If the two terms have the same base (in this case $a$) and are multiplied together, then their indices are **added** (in this case $m+n$)

$$a^m·a^n = a^{m+n}$$

For example: 

Suppose you have $3^2$ and you want to multiply it by $3^3$. That is
$$3^2·3^3 = 3·3 \ \ ·\ \ 3·3·3 $$
which is equal to $3^5$.

Therefore, using Law 1 you can get $$3^2·3^3 = 9·27 = 243 = 3^5 = 3^{2+3}$$
:::

::: {.callout-note appearance="simple"}

## Example 2

Simplify the following expression: $x^2y^3· x^3y^{-1}$

You can treat $x$ and $y$ as two separate terms and you are now simplifying $x^2·x^3$ and $y^3·y^{-1}$. Using Law 1, you can add the indices to get: $x^{2+3}$ and $y^{3+(-1)}$. Remembering to multiply the $x$ and $y$ terms, you then get $$x^2y^3· x^3y^{-1} = x^{2+3}y^{3-1} = x^5y^2$$
:::

::: {#law-2-link .callout-note}

## Law 2: Division

If the two terms have the same base (in this case $a$) and are to be divided, then their indices are **subtracted** (in this case $m-n$)

$$\dfrac{a^m}{a^n} = a^{m-n}$$ 
For example: 

Suppose you want to divide $2^5$ by $2^3$.
$$\dfrac{2^5}{2^3} = \dfrac{2·2·2·2·2}{2·2·2}$$
You can now cancel the common factors of $2$. Three of the $2$'s at the bottom can be cancelled out, so you are left with $$\dfrac{2·2}{1} = 2^2 = 4$$
Therefore, you can get
$$\dfrac{2^5}{2^3} = 4 = 2^2 = 2^{5-3}$$
:::

::: {.callout-note appearance="simple"}

## Example 3

Simplify the following expression: $\dfrac{x^2y^3}{x^5y}$

You can treat $\dfrac{x^2y^3}{x^5y}$ as the product of two fractions: $\dfrac{x^2}{x^5}$ and $\dfrac{y^3}{y}$.\
Using Law 2, you can simplify the fractions to get:\ $\dfrac{x^2}{x^5} = x^{2-5} = x^{-3}$ and $\dfrac{y^3}{y} = y^{3-1} = y^2$, remembering to multiply the fractions, you get $$\dfrac{x^2y^3}{x^5y} = x^{2-5}y^{3-1} = x^{-3}y^2$$
:::

::: {#law-3-link .callout-note}

## Law 3: Brackets

To raise a value or variable (in this case $a$) presented in index form to another index, **multiply** the indices together ($m$ and $n$)
$$(a^m)^n = a^{m·n}$$ 
For example: 

Suppose you had $3^2$ and you want to raise it all to the power of $3$. That is $$(3^2)^3$$
this means $$3^2·3^2·3^2$$
[Law 1](#law-1-link) tells you to add the indices together. So you can get $$3^6$$
But note that $6$ is $2·3$. This suggests that Law 3 also works. 
Therefore, using Law 3 you can get $$(3^2)^3 = 729 = 3^6 = 3^{2·3}$$
:::

::: {.callout-note appearance="simple"}

## Example 4

Simplify the following expression: $(x^2y^3)^4$

Using Law 3, you get
$$(x^2y^3)^4 = (x^2)^4·(y^3)^4 = x^{2·4}y^{3·4} = x^8y^{12}$$
:::

::: {#law-4-link .callout-note}

## Law 4: Power of $0$

Anything to the power of zero is equal to one: $$a^0 = 1$$

Note:

Anything to the power of one is equal to itself $$a^1 = a$$ 
and

$1$ to the power of anything is $1$ $$1^a=1$$

:::

::: callout-warning

$0^0$ is indeterminate, anything to the power of $0$ is $1$, but $0$ to the power of anything is $0$, so it is not defined.
:::

::: {.callout-note appearance="simple"}

## Example 5

Simplify the following expression: $(x^2 + y^5)^0$

Using Law 4, you can get $$(x^2 + y^5)^0 = 1$$
:::


::: callout-tip

## Proof of Law 4

[Law 2](#law-2-link) helps to explain Law 4:

Since anything divided by itself is equal to one, so $$\dfrac{a^m}{a^m} = 1$$

Also
$$\dfrac{a^m}{a^m} = a^{m-m} = a^0 = 1$$ Therefore, $$a^0 = 1$$
:::

::: callout-note

## Law 5: Negative indices

If the index is a negative value, then it can be shown as the reciprocal of the positive index raised to the same variable $$a^{-m} = \dfrac{1}{a^m}$$ 

For example: 

Suppose you want to divide $2^3$ by $2^7$ $$\dfrac{2^3}{2^7}=\dfrac{2·2·2}{2·2·2·2·2·2·2}$$
Again, you can find the common factors of $2$. The three $2$'s at the top can be cancelled out, so you are left with $$\dfrac{2^3}{2^7}=\dfrac{1}{2·2·2·2}=\dfrac{1}{2^4}$$

Now consider [Law 2](#law-2-link), you can do the similar calculation by subtracting the indices $$\dfrac{2^3}{2^7}=2^{3-7}=2^{-4}$$
You have done the calculation in two different ways. So you get $$\dfrac{2^3}{2^7}=2^{3-4}=2^{-4}=\dfrac{1}{2^4}$$

:::

::: {.callout-note appearance="simple"}

## Example 6

Simplify the following expression: $(3x+4y)^{-1}$

Using Law 5, you can get
$$(3x+4y)^{-1} = \dfrac{1}{3x+4y}$$
:::

::: callout-note

## Law 6: Fractional indices

An index in the form of a fraction can be represented as the radical form:

$$a^{\LARGE(\frac{m}{n})}= (\sqrt[n]{a})^m$$ 
For example:

Suppose you found that $$2^r·2^r=2$$
This means that multiplying $2^r$ by $2^r$ gives the result $2$. So $2^r$ is a square root of $2$.

Note that $2=2^1$ and consider [Law 1](#law-1-link), $2^r·2^r=2^{2r}$. If $2^r·2^r=2$ then you can get $$2^{2r}=2^1$$
from which $$2r=1$$
so $$r=\dfrac{1}{2}$$
This shows that $$2^{\LARGE\frac{1}{2}}=\sqrt[1]{2}=\sqrt{2}$$
:::

::: {.callout-note appearance="simple"}

## Example 7

Simplify $10000^{\LARGE(\frac{3}{4})}$

Using Law 7, you can re-express $10000^{\LARGE(\frac{3}{4})}$ as $(\sqrt[4]{10000})^3$, because $10^4=10000$, $\sqrt[4]{10000} = 10$. So $(\sqrt[4]{10000})^3 = 10^3 = 1000$.
:::

::: {.callout-note appearance="simple"}

## Example 8

Simplify $27^{\LARGE(\frac{-2}{3})}$

Using Law 7, you can get $27^{\LARGE(\frac{-2}{3})} = (\sqrt[3]{27})^{-2} = 3^{-2} = \dfrac{1}{3^2} = \dfrac{1}{9}$.
:::

# Solving equations using indices

You can use laws of indices to solve equations, here are some examples:

::: {.callout-note appearance="simple"}

## Example 9

Solve $x^{\LARGE\frac{1}{2}}=8$

Start by squaring both sides of the equation to get $(x^{\LARGE\frac{1}{2}})^2 = 8^2$, then you get the answer $x = 64$. To check if the answer is correct, you can substitute $64$ back into the equation: $64^{\LARGE\frac{1}{2}} = \sqrt[2]{64}=8$.
:::

::: {.callout-note appearance="simple"}

## Example 10

Solve $x^{-2}=9$

$x^{-2} = 9$ can be re-expressed as $\dfrac{1}{x^2} = 9$.
Multiplying both sides by $x^2$ gives you $1=9x^2$.
Then dividing both sides by $9$ gives you $\dfrac{1}{9}=x^2$.
Now you can square root both sides to obtain: $\sqrt[2]{\dfrac{1}{9}}=x$.
Remember you can have positive and negative roots. Therefore, you get $x= \dfrac{1}{3}$ or $x= -\dfrac{1}{3}$.
:::

::: {.callout-note appearance="simple"}

## Example 11

Solve $3^{4x}=27^{5-x}$

As $27=3^3$, the equation can be rewritten as: $3^{4x}=(3^3)^{5-x}$. Then using the laws of indices, $3^{4x}=3^{15-3x}$. Since both sides are equal, $4x=15-3x$.
Then $x=\dfrac{15}{7}$.
:::

::: {.callout-note appearance="simple"}

## Example 12

Solve $x^{\LARGE\frac{5}{3}} + 3x^{\LARGE\frac{2}{3}} = 10x^{-\LARGE\frac{1}{3}}$

If you look at all of the indices in the question, the denominator is three and that is a hint of what you need to multiply by. Multiply $x^{\LARGE\frac{1}{3}}$ on both sides of the equation, you can get $x^{\LARGE\frac{6}{3}} + 3x^{\LARGE\frac{3}{3}} = 10x^0$, you can further simplify it to get $x^2 +3x = 10$. And now have a quadratic equation, subtract $10$ from both sides gives you $x^2+3x-10=0$, factorising this equation gives you $(x+5)(x-2)=0$, then you can get $x=-5$ and $x=2$. 
:::

::: {.callout-note appearance="simple"}

## Example 13

Solve $e^{3x}=12$

Taking the logarithm of both sides gives you $\log_e(e^{3x})=\log_e(12)$.\
$\log_e(x)$ is the natural logarithm often denoted $\ln(x)$, so you can write the equation as $\ln(e^{3x})=\ln(12)$. \
Using the power rule of logarithms, you can express the equation as $3x \cdot \ln(e) = \ln(12)$, then by the identity rule, you can get $3x \cdot (1)=\ln(12)$. Rearranging the equation gives you $x=\dfrac{\ln(12)}{3}$.

[To see more about Euler's number $e$, please go the Guide: Introduction to Logarithms](Logarithms_Study_Guide.qmd)
:::

## Quick check problems {.unnumbered}

<!-- add facility for webexercises to work on html -->

::: {.content-visible when-format="html"}

<!-- add facility to check answers at end rather than one at a time -->

::: {.webex-check .webex-box}

1. Solve $\sqrt[3]{9x-1}=4$

Answer: It is `r fitb("$\frac{65}{9}$")`

2. Solve $x^{\dfrac{2}{3}}=4\dfrac{17}{27}$

Answer: It is `r fitb("$\frac{25}{9}$")`

3. Determine whether the following calculations are correct:

(a) $\dfrac{17x^{17}y^{14}}{15x^{18}y^{18}} = \dfrac{17}{15xy}$ `r torf(FALSE)`

(b) $(5x^2·2x^5·3x^4)^2 = 900x^{22}$ `r torf(TRUE)`

(c) $\dfrac{12x^{14}y^{-4}}{12x^7y^{11}} = \dfrac{x^6}{y^7}$ `r torf(FALSE)`
:::

:::

::: {.content-hidden when-format="html"}

1. Solve $\sqrt[3]{9x-1}=4$

2. Solve $x^{\dfrac{2}{3}}=4\dfrac{17}{27}$

3. Determine whether the following calculations are correct:

(a) $\dfrac{17x^{17}y^{14}}{15x^{18}y^{18}} = \dfrac{17}{15xy}$ 

(b) $(5x^2·2x^5·3x^4)^2 = 900x^{22}$ 

(c) $\dfrac{12x^{14}y^{-4}}{12x^7y^{11}} = \dfrac{x^6}{y^7}$

:::

[For more questions on the subject, please go to Questions: Laws of indices](qs-lawsofindices.qmd)
