---
title: "Dealing With Powers and nth roots"
author: "Zoe Gemmell"
abstract-title: Summary
abstract: Simplifying expressions involving powers and $n$th roots is a valuable skill to learn. In this guide you will learn a few manipulation techniques that will hopefully be useful going further into your maths career.

---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this guide, it is recommended that you read (Guide: Laws of indices). This guide uses $\cdot$ for multiplication. Power is another word for indice/index.*

This guide will focus on expressions with bases and powers. You can recognise them from combinations of expressions in the following format:
\begin{align*}
base^{power}
\end{align*}

## What is a base? {-}

A base is a number that is raised to a power. It can be any number you can think of; single digit, decimal numbers, a million. This is the number that gets multiplied by itself.

What is a power you might then ask? A power is any number that you can raise a base to, it dictates how many times the base is multiplied by itself. 

::: {.callout-note appearance='simple'}

## Example 1

\begin{align*}
3^5 \textsf{ means } \underbrace{3\cdot3\cdot3\cdot3\cdot3}_{5\,times} \end{align*}

You would say this out loud as 'three multiplied by itself five times', 'three to the fifth power' or 'three to the five'.
:::

## Working with powers - The Definitions

Before you have a look at the laws here are some definitions:

::: {.callout-note}
## Definition of expression

A mathematical expression is a combination of symbols that has a finite length.
:::

::: {.callout-note}
## Definition of commutativity

Changing the order of the numbers involved in your expression does not change the answer.
:::

::: {.callout-note appearance='simple'}

## Example 2

$2+3=5=3+2$

The order of the 2 and 3 can be swapped and the answer stays the same.

:::

::: {.callout-note}
## Definition of terminoligy in a fraction

The numerator of a fraction is everything on top of the line, the denominator is everything underneath the line:

\begin{align*}
\dfrac{numerator}{denominator}\end{align*}

:::

:::{.callout-tip}

Both addition and multiplication are commutative

:::

# Now onto the laws:

:::{.callout-note}
## Law 7: Multiplication of variables with the same indices but different bases

When multiplying variables with the same powers you can expand and rewrite them into a nicer format:

\begin{align*}
a^r \cdot b^r = (ab)^r \end{align*}

Where the bases are multiplied together then raised to the rth power.

:::

:::{.callout-note appearance='simple'}
## Example 3

\begin{align*}
2^3 \cdot 3^3
&= \underbrace{(2\cdot 2\cdot 2)}_{3\,times}\cdot \underbrace{(3\cdot 3\cdot 3)}_{3\,times}\nonumber \\[0.5em]
&= 2\cdot 3 \cdot 2 \cdot 3\cdot 2 \cdot 3 \tag{\,by commutativity}\\[0.5em]
&= (2\cdot 3)^3\nonumber
\end{align*}
:::

:::{.callout-note}
## Law 8: Division of variables with the same indices but different bases

When dividing variables with the same powers you can expand and rewrite them into a nicer format:

\begin{align*}
\dfrac{a^r}{b^r} = (\dfrac{a}{b})^r \end{align*}

Where the numerator base (a) is divided by the denominator base (b) then raised to the rth power.

:::

:::{.callout-note appearance='simple'}
## Example 4

\begin{align*}
\dfrac{4^4}{5^4}
&= \dfrac{\overbrace{4\cdot 4\cdot 4\cdot 4}^{4\,times}}{\underbrace{5\cdot 5\cdot 5\cdot 5}_{4\,times}}\nonumber \\[0.5em]
&= \dfrac{4}{5}\cdot \dfrac{4}{5}\cdot \dfrac{4}{5}\cdot \dfrac{4}{5} \tag{\,by commutativity}\\[0.5em]
&= (\dfrac{4}{5})^4
\end{align*}
:::

:::{.callout-note}
## Law 9: fractional power, the nth root

When multiplying by bases with fractional powers (some sort of nth root) :

\begin{align*}
a^{1/n} \cdot b=\sqrt[n]{a \cdot b^n} \end{align*}

Where the aim of the manipulation is to put everything inside the square root sign, then to continue with the calculation.

:::

:::{.callout-note appearance='simple'}
## Example 5

\begin{align*}
2^{1/3}\cdot 4
&= 2^{1/3}\cdot 4^{3/3}\nonumber \\[0.5em]
&= \sqrt[3]{2\cdot 4^3}\nonumber \\[0.5em]
&= \sqrt[3]{2\cdot (2\cdot 2)^3}\nonumber \\[0.5em]
&= \sqrt[3]{2^7} \tag{\,$(2^2)^3=2^{2\cdot 3}=2^6$}\\[0.5em] 
&= 2^{7/3}
\end{align*}
:::

:::{.callout-note}
## Law 10: Multiplication under the root sign

When you have a term under a $n$th root sign which you can factorise (split up into different factors) this can be done and the $n$th root signs can be dealt with separately.

\begin{align*}
\sqrt[n]{a\cdot b}=\sqrt[n]{a}\cdot\sqrt[n]{b}\end{align*}

Where you are using the commutativity of multiplication to split up the $n$th root and deal with terms separately.

:::

:::{.callout-note appearance='simple'}
## Example 6

\begin{align*}
\sqrt{12}
&= \sqrt{4\cdot 3}\nonumber \\[0.5em]
&= \sqrt{4}\cdot\sqrt{3}\nonumber \\[0.5em]
&= 2\cdot\sqrt{3}
\end{align*}

:::

# Solving equations

Using the laws above you can solve equations

::: {.callout-tip}

When dealing with equations, you may find yourself faced with the following form:
\begin{align*}
\dfrac{1}{a+\sqrt{b}}\end{align*}

In which case you will want to use the **conjugate** of the denominator to *creatively* multiply the fraction by 1. The conjugate of $a+\sqrt{b}$ is $a-\sqrt{b}$, to find this for any espression you change the sign in front of the root.

\begin{align*}
\dfrac{1}{a+\sqrt{b}}\cdot 1&= \dfrac{1}{a+\sqrt{b}}\cdot\dfrac{a-\sqrt{b}}{a-\sqrt{b}}\nonumber \\[0.5em]
&= \dfrac{a-\sqrt{b}}{(a+\sqrt{b})(a-\sqrt{b})}\nonumber \\[0.5em]
&= \dfrac{a-\sqrt{b}}{a^2+a\sqrt{b}-a\sqrt{b}-(\sqrt{b})^2}\nonumber \\[0.5em]
&= \dfrac{a-\sqrt{b}}{a^2-b}
\end{align*}

Now the fraction only has square roots in the numerator, this is better because it can often make expressions you are dealing with more concise.

:::

:::{.callout-note appearance='simple'}
## Example 7

\begin{align*}
2^{x+1}\cdot 3^x&=72\nonumber \\[0.5em]
2(2\cdot 3)^x&=72\nonumber \\[0.5em]
(2\cdot 3)^x&=36\nonumber \\[0.5em]
6^x&=36
\end{align*}

From here you can count up powers of 6 to work out the value of x:
$6^1=6$, $6^2=36$ so $x=2$
:::

:::{.callout-note appearance='simple'}
## Example 8

Here is a rather long example using multiple laws from this guide and the intro to indices guide.

\begin{align*}
\sqrt{(6x)^3}&=8\sqrt{27}\nonumber \\[0.5em]
\sqrt{x^3}\cdot\sqrt{6^3}&=8\sqrt{27}\tag{\,Using Law 7 and Law 10} \\[0.5em]
\sqrt{x^3}\cdot\sqrt{(2\cdot 3)^3}&=8\sqrt{27}\tag{\,Using Law 7} \\[0.5em]
\sqrt{x^3}\cdot\sqrt{2^3}\sqrt{3^3}&=8\sqrt{27}\tag{\,Using Law 10} \\[0.5em]
\end{align*}
to simplify the appearance of the calculation, swap $2^3$ for $8$
\begin{align*}
\sqrt{x^3}\cdot\sqrt{8}\sqrt{27}&=8\sqrt{27}\nonumber \\[0.5em]
\sqrt{x^3}\cdot\sqrt{8}&=8\tag{\,cancel $\sqrt{27}$} \\[0.5em]
\sqrt{x^3}&=\dfrac{8}{8^{1/2}}\nonumber \\[0.5em]
\sqrt{x^3}&=\sqrt{8}\tag{\,Using Law 2} \\[0.5em]
\end{align*}
Finally, switch back to $2^3$
\begin{align*}
x^3&=8=2^3
\end{align*}

So x=2
:::

## Quick check problems {.unnumbered}

::: {.content-visible when-format="html"}

::: {.webex-check .webex-box}

1. What is the singular of indices?

Answer: `r fitb("index")`

2. Solve $3x^3\cdot 5=45$ for x

Answer: x equals `r fitb("$\\sqrt[3]{3}$")`

3. Determine whether the following calculations are correct:

(a) $\dfrac{3x^a}{y^{8b}}\cdot\dfrac{4z^a}{y^{d}}= \dfrac{12(xz)^a}{y^{d+8b}}$ `r torf(TRUE)`

(b) $\dfrac{4^2}{2^4}=2$ `r torf(FALSE)`

(c) $(7^2)^0=1$ `r torf(TRUE)`

(d) $x^2+x^3$ is greater than $x$ for all values of $x$ `r torf(FALSE)`
:::

:::

::: {.content-hidden when-format="html"}

1. What is the singular of indices?

2. Solve $3x^3\cdot 5=45$ for x

3. Determine whether the following calculations are correct:

(a) $\dfrac{3x^a}{y^{8b}}\cdot\dfrac{4z^a}{y^{d}}= \dfrac{12(xz)^a}{y^{d+8b}}$

(b) $\dfrac{4^2}{2^4}=2$

(c) $(7^2)^0=1$

(d) $x^2+x^3$ is greater than $x$ for all values of $x$

:::

[For more questions on the subject, please go to Questions: Needs to be added](.qmd)