---
title: "Rationalizing the denominator"
author: "Maximilian Volmar"
abstract-title: Summary
abstract: Rationalizing the denominator is a technique for simplifying fractions involving square roots in the denominator. This study guide also covers the topic of quadratic conjugates which are sometimes used to rationalize the denominator of a fraction.
categories:
  - Algebra
  - Key Skills
draft: true
---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this guide, it is recommended that you read [Guide: Laws of indices](lawsofindices.qmd) and [Guide: Expanding Brackets](expandingthebrackets.qmd). The only irrational numbers you will see in this guide are are square roots, if you want to learn more about irraional numbers, have a look at the [Guide: Number Theory](numbertheory.qmd).*

# What is rationalizing the denominator? {-}

When you rationalize the denominator, you rewrite a fraction so that the denominator contains no square roots or other irrational numbers.

For example, in the fraction $\dfrac{3}{\sqrt{2}}$, the denominator contains a square root, which is irrational. You want to rewrite the fraction so that it looks like this: $\dfrac{3\sqrt2}{2}$ where the numerator can be irrational, but the denominator is free of square roots and a rational number, in this case 2.

This process is helpful for doing operations like addition or subtraction on the fraction and can also be useful when trying to approximate such a fraction.

::: {#definition-1-link .callout-note}

## Note

When you rewrite fractions you might multiply the numerator and denominator by the same value $k$ where $k$ is any number. When you are doing this, you are multiplying the fraction by $\dfrac{k}{k}$ which is the same as multiplying the fraction by $1$.

You are therefore not changing the value of the fraction, you are rewriting it.

:::

# Expressions of the form $\frac{a}{b\sqrt{c}}$ {-}

For fractions like $\dfrac{a}{b\sqrt{c}}$, where a is any number and b and c are integers, you rationalize the denominator by multiplying both the numerator and denominator by the square root in the denominator: $\sqrt{c}$. This gives you:

$$
\frac{a}{b\sqrt{c}} \cdot \frac{\sqrt{c}}{\sqrt{c}} = \frac{a\sqrt{c}}{b(\sqrt{c})^2}
$$

Simplifying the denominator gives you

$$
\frac{a\sqrt{c}}{bc}
$$

The denominator is now rational and free of square roots as $b$ and $c$ are integers so $bc$ is also an integer. Example 1 shows you how to rationalize the fraction you saw above: $\dfrac{3}{\sqrt{2}}$

::: {.callout-note appearance="simple"}

## Example 1

Simplify $\dfrac{3}{\sqrt{2}}$ by rationalizing the denominator:

To rationalize this, you multiply both the numerator and denominator by $\sqrt{2}$, giving you:

$$
\frac{3}{\sqrt{2}} \cdot \frac{\sqrt{2}}{\sqrt{2}} = \frac{3\sqrt{2}}{(\sqrt2)^2}
$$

Simplifying gives you: $\dfrac{3\sqrt{2}}{2}$

:::

::: {.callout-note appearance="simple"}

## Example 2

Simplify $\dfrac{3}{2\sqrt{5}}$ by rationalizing the denominator:

Multiply both the numerator and denominator by $\sqrt{5}$, giving you:

$$
\frac{3}{2\sqrt{5}} \cdot \frac{\sqrt{5}}{\sqrt{5}} = \frac{3\sqrt{5}}{2(\sqrt5)^2}
$$

Simplifying gives you: $\dfrac{3\sqrt{5}}{10}$

:::

::: {.callout-note appearance="simple"}

## Example 3

Simplify $\dfrac{5+\sqrt{2}}{7\sqrt{3}}$ by rationalizing the denominator:

Multiply both the numerator and denominator by $\sqrt{3}$, giving you:

$$
\frac{5+\sqrt{2}}{7\sqrt{3}} \cdot \frac{\sqrt{3}}{\sqrt{3}} = \frac{(5 + \sqrt{2})\sqrt{3}}{7(\sqrt{3})^2}
$$
[Expanding the brackets](expandingthebrackets.qmd) and simplifying then gives you:

$$
\frac{5\sqrt{3} + \sqrt{2}\sqrt{3}}{7(3)} = \frac{5\sqrt{3}+\sqrt{6}}{21}
$$

:::

# What is a quadratic conjugate? {-}

::: {#definition-1-link .callout-note}

## Definition of a quadratic conjugate

Given an expression of the form $b + c\sqrt{d}$, where $b$, $c$ and $d$ are integers, the quadratic conjugate is the expression with the same terms but with the opposite sign in front of the term with a square root.

The quadratic conjugate of the expression $b + c\sqrt{d}$ is therefore $b - c\sqrt{d}$.

:::

::: {.callout-note appearance="simple"}

## Example 4

What is the quadratic conjugate of $7 + 2\sqrt{3}$:

$$
7 - 2\sqrt{3}
$$

:::

::: {.callout-note appearance="simple"}

## Example 5

What is the quadratic conjugate of $- 2 - 3\sqrt{5}$:

$$
-2 + 3\sqrt{5} = 3\sqrt{5} - 2
$$

:::

These conjugates are useful for eliminating square roots when rationalizing denominators of a particular form. Multiplying an expression by its quadratic conjugate eliminates the square root. You can see this when you multiply $b + c\sqrt{d}$ by its quadratic conjugate to get

$$
(b + c\sqrt{d})(b - c\sqrt{d}) = b^2 - bc\sqrt{d} + bc\sqrt{d} - (c\sqrt{d})^2
$$

Simplifying this gives you

$$
b^2 - c^2d
$$

This result is rational, free of square roots.

# Expressions of the form $\frac{a}{b + c\sqrt{d}}$ {-}

Here a is any number and b, c and d are integers. In this case, rationalizing the denominator involves multiplying the numerator and the denominator by the quadratic conjugate of ${b + c\sqrt{d}}$, which would be $b - c\sqrt{d}$. As you saw above, the denominator will become $b^2 - c^2d$. The entire fraction therefore becomes:

$$
\frac{a}{b + c\sqrt{d}} \cdot \frac{b - c\sqrt{d}}{b - c\sqrt{d}} = \frac{a(b - c\sqrt{d})}{b^2 - c^2d}
$$

As you can see, the denominator is now $b^2 - c^2d$ and has been successfully rationalized.

::: {.callout-note appearance="simple"}

## Example 6

Simplify $\dfrac{2}{7 + 2\sqrt{5}}$ by rationalizing the denominator. Provide your answers in their simplest form and with a positive denominator:

The quadratic conjugate of the denominator is:

$$
7 - 2\sqrt{5}
$$

Multiplying the numerator and denominator by the quadratic conjugate gives you:

$$
\frac{2}{7 + 2\sqrt{5}} \cdot \frac{7 - 2\sqrt{5}}{7 - 2\sqrt{5}} = \frac{2(7 - 2\sqrt{5})}{49 - 14\sqrt{5} + 14\sqrt{5} - (2\sqrt{5})^2}
$$
Expanding the brackets and simplifying the denominator gives you:

$$
 \frac{14 - 4\sqrt{5}}{49 - 4(5)}
$$

Further simplifying the denominator gives you:

$$
\frac{14 - 4\sqrt{5}}{29}
$$

:::

::: {.callout-note appearance="simple"}

## Example 7

Simplify $\dfrac{3}{2 + 5\sqrt{3}}$ by rationalizing the denominator. Provide your answers in their simplest form and with a positive denominator:

The quadratic conjugate of the denominator is:

$$
2 - 5\sqrt{3}
$$

Multiplying the numerator and denominator by the quadratic conjugate gives you:

$$
\dfrac{3}{2 + 5\sqrt{3}} \cdot \frac{2 - 5\sqrt{3}}{2 - 5\sqrt{3}} = \frac{3(2 - 5\sqrt{3})}{4 - 10\sqrt{3} + 10\sqrt{3} - (5\sqrt{3})^2}
$$
Expanding the brackets and simplifying the denominator gives you:

$$
 \frac{6 - 15\sqrt{3}}{4 - 25(3)}
$$

Further simplifying the denominator gives you:

$$
\frac{6 - 15\sqrt{3}}{-71}
$$

Multiplying both the numerator and the denominator by $-1$ to get a positive denominator gives you:

$$
\frac{15\sqrt{3} -6}{71}
$$

:::

::: {.callout-note appearance="simple"}

## Example 8

Simplify $\dfrac{2 + \sqrt{7}}{5 - \sqrt{3}}$ by rationalizing the denominator. Provide your answers in their simplest form and with a positive denominator:

The quadratic conjugate of the denominator is:

$$
5 + \sqrt{3}
$$

Multiplying the numerator and denominator by the quadratic conjugate gives you:

$$
\frac{2 + \sqrt{7}}{5 - \sqrt{3}} \cdot \frac{5 + \sqrt{3}}{5 + \sqrt{3}} = \frac{(2 + \sqrt{7})(5 + \sqrt{3})}{(5 - \sqrt{3})(5 + \sqrt{3})}
$$

Expanding the brackets gives you:

$$
\frac{2(5) + 2\sqrt{3} + 5\sqrt{7} + \sqrt{7}(\sqrt{3})}{25 + 5\sqrt{3} - 5\sqrt{3} - (\sqrt{3})^2}
$$

This simplifies to:

$$
\frac{10 + 2\sqrt{3} + 5\sqrt{7} + \sqrt{21}}{25 - 9}
$$

Simplifying the denominator gives you:

$$
\frac{10 + 2\sqrt{3} + 5\sqrt{7} + \sqrt{21}}{16}
$$

:::

# Quick check problems {-}

<!-- add facility for webexercises to work on html -->

::: {.content-visible when-format="html"}

<!-- add facility to check answers at end rather than one at a time -->

::: {.webex-check .webex-box}

Rationalize the denominator for each of the following expressions. Provide your answers in their simplest form and with a positive denominator.

1. $\dfrac{5}{\sqrt{2}} = \dfrac{a\sqrt{b}}{c}$, where $a=$ `r fitb(5)`, $b=$ `r fitb(2)` and $c=$ `r fitb(2)`.

2. $\dfrac{7}{5\sqrt{3}} = \dfrac{a\sqrt{b}}{c}$, where $a=$`r fitb(7)`, $b=$ `r fitb(3)`, and $c=$ `r fitb(15)`.

3. $\dfrac{7}{2 + \sqrt{5}} = \dfrac{a + b\sqrt{c}}{d}$, where $a=$ `r fitb(-14)`, $b=$ `r fitb(7)`, $c=$ `r fitb(5)` and $d=$ `r fitb(1)`

4. $\dfrac{5\sqrt{2}}{7 - 2\sqrt{2}} = \dfrac{a + b\sqrt{c}}{d}$, where $a=$ `r fitb(20)`, $b=$ `r fitb(35)`, $c=$ `r fitb(2)` and $d=$ `r fitb(41)`.


:::

:::

::: {.content-hidden when-format="html"}

Rationalize the denominator for each of the following expressions. Provide your answers in their simplest form and with a positive denominator.

1. $\dfrac{5}{\sqrt{2}}$

2. $\dfrac{7}{5\sqrt{3}}$

3. $\dfrac{7}{2 + \sqrt{5}}$

4. $\dfrac{5\sqrt{2}}{7 - 2\sqrt{2}}$

:::

# Further reading {-}

[For more questions on the subject, please go to Questions: Rationalizing the denominator.](../questions/qs-rationalizingthedenominator.qmd)

## Version history {-}

v0.1: Draft version created 9/24 by Maximilian Volmar.