---
title: "Solving equations involving logarithms"
author: "Ellie Gurini, Krish Chaudhary, Mark Toner"
abstract-title: Summary
abstract: This guide serves to introduce rearranging equations involving logarithms. This can be a useful skill, especially when considering the uses trigonometry has in describing motion.
draft: true

---

```{r, setup, include = FALSE}
library("webexercises")
```

*Before reading this, you may want to read the guides on logarithms, trigonometry, radians, and trigonometric identities.* 

In [Guide: Introduction to logarithms](logarithms.qmd), you learned about the different ways that you can manipulate expressions involving powers (like $x^3$ and $2^{80}$) and $n$th roots (such as $\sqrt[4]{x}$ and $2^{1/80}$). In general life however, this knowledge will not be enough; you will need to apply the ideas of logarithms to help you solve equations. 

Solving equations involving logarithms is a key skill in areas whenever logarithmic concepts play a role: economics, physics (particularly acoustics, where the decibel is a logarithmic measure), chemistry (pH is a logarithmic measure), biology, mathematics and statistics, computational complexity, and even music theory!

Before you get started however, it is worth restating the recommendation above:

::: {.callout-important}

**This guide assumes an excellent knowledge of logarithms and the laws of logarithms. Please make sure that you have read [Guide: Introduction to logarithms](logarithms.qmd) before continuing.** 

The numbering of the laws will follow the numbering in this guide and on [Factsheet: Laws of logarithms](../factsheets/f-lawsoflogs.qmd).

:::

# Discussion of techniques

In general, the first golden rule of solving equations involving logarithms is the following:

::: {.callout-tip}

## First golden rule

**Make sure all logarithms are in the same base before simplifying**. To do this (if applicable) you could use the **change of base rule**.

This is because Laws 1 and 2 of the laws of logarithms can only be applied when the logarithms have the same base. 

:::

It may be that you have logarithms in different bases in your equation; so how can you make them to be in the same base? The answer is the **change of base** rule (Law 6), which you should use in this scenario.

You have seen in [Guide: Introduction to logarithms](logarithms.qmd) that **logarithms undo exponentiation and exponentiation undoes logarithms**. More formally, you have that for all $a > 0$ with $a \neq 1$ and all real numbers $y$ (where the expression is defined): 

$$\quad a^{\log_a(y)} = y\qquad \textsf{ and }\qquad \log_a (a^y) = y$$
However, this only works if there is one term on each side of the equation. For instance, you can notice that $$\log_a(x) + \log_a(y) = \log_a(z)$$ does **not** automatically imply that $x + y = z$. This is because Law 1 of the laws of logarithms, it actually follows that $$\log_a(x) + \log_a(y) = \log_a(xy) = \log_a(z)$$ and so it actually implies that $xy = z$. 

So the second golden rule of solving equations involving logarithms is the following:

::: {.callout-tip}

## Second golden rule

**To undo a logarithm, you need exactly one term on each side of the equation. If both terms are logarithms, they should be in the same base**.

:::

So for instance, if you are solving an equation involving logarithms, you can isolate the variable on one side of the equation, and have a constant on the other (see [Guide: Introduction to rearranging equations](introtorearrange.qmd) for more). Perhaps it looks like $\log_a(x) = b$. From there, you can exponentiate both sides with base $a$ to get $$a^{\log_a(x)} = x = a^b$$ and so $x=a^b$.

However, please be aware of the following:

::: {.callout-warning}

**You cannot take logarithms of a negative number!**

:::

So if you are solving an equation involving logarithms, you need to check if the solution is *valid* by putting any answers into your original equation. 

---


---

This guide should help to get a grasp of rearranging trigonometric and logarithmic equations. This can be a very useful skill, especially when considering modelling things. For example, trigonometric equations are often used to describe signal waves and motion, whereas logarithms (or exponentials) tend to be used when describing growth and decay.

## Logarithmic equations {-}

Here's a quick reminder that you may want to reread the guide on logarithms before starting this section. 

::: {.callout-tip}

Remember that $\log_{a}{b}=c$ and $a^c=b$ are interchangeable.

:::

So one type of equation will likely be similar to $5^x=25$. If you use the format above, you can label a=5, b=25, and c=x. Then, you would rewrite in the form $\log_a{b}=\log_5{25}=x$, giving $x=2$. This is commonly phrased as asking a question about modelling some form of exponential growth. 

Another type may be to have an equation inside the logarithm. Lets take a look at an example to explain this one.

::: {.callout-note appearance="simple"}

## Example 6

$$\log_{10}(5x+7)=1$$
You want to find x. Using the tip from above, you can rewrite this as:
$10^1=5x+7$. From there, you can subtract 7 from both sides, giving $3=5x$ and then divide both sides by 5, giving $x=\frac{3}{5}$.

:::

You may also come across equations which are similar to the one above, but cleverly hidden through logarithm rules. Lets go through one of those.

::: {.callout-note appearance="simple"}

## Example 7

$$\log_{10}(4x)-\log_{10}(3)=2$$

Find x. 

You start by rewriting the left hand side of the equation into one logarithm. The guide on logarithms should have a section on this. This will give you $\log_{10}(\frac{4x}{3})=2$. 

Now, you should rewrite this as an exponential to get $10^2= \frac{4x}{3}$. To finish solving, you will divide both sides by $\frac{4}{3}$. This gives that $x=75$.

:::

::: {.callout-note appearance="simple"}

## Example 8

Here's a little example/proof which should help to understand the next example more completely. 

Lets have a look at an equation where a number is raised to the power of a logarithm in its own base. 

$$e^{\log_e(x)}=y$$ Find y in terms of x.

Firstly, label up the equation according to the note at the start of this. This gives a=e, b=y, c=$\log_e(x)$. From there, rewrite the equation as a logarithm, $\log_e(y)=\log_e(x)$. This means that $y=x$. We can say this for a log function but not for, lets say, a trigonometric function, as log functions don't have repeating values. 

On a wider scale, this proves that $$a^{\log_a(b)}=b$$. Whilst e was the base used in this example, it doesn't affect the outcome. You can repeat this exercise with a base of 2 if you would like to confirm. 

:::


Another use of logarithms is in solving simultaneous equations. This takes advantage of the relationship between logarithms and exponentials.

::: {.callout-note appearance="simple"}

## Example 9

Solve this set of simultaneous equations
$$e^y=2x+1$$
$$\ln(3x)=y$$
The first step for this problem would to be to substitute $y=\ln(3x)$ into the first equation. This gives $e^{\ln(3x)}=2x+1$. Now, lets label: a=e, b=2x+1 and c=$\ln(3x)$. 

Thus, refer to our example 8 to see that $ e^{ln(3x)}=3x$, and so $3x=2x+1$. Subtracting 2x from either side gives that $x=1$. Substituting this back into our equation gives that $y=\ln(3)$ or approximately 1.099.

:::

Here's another example of the relationship between logarithms and exponentials.

::: {.callout-note appearance="simple"}

## Example 10

Solve $$5e^{-x}+3e^x=9$$

To start with this problem, you should multiply everything by $e^x$, giving $5+3e^{2x}=9e^x$. 

Lets rename $e^x=y$, which should hopefully give a more familiar equation: $5+3y^2=9y$. You can rearrange and solve this quadratic using the quadratic equation. This gives y=$\frac{9+\sqrt{21}}{16}$ or $\frac{9-\sqrt{21}}{16}$. 

$e^x=y$ implies that $\ln(y)=x$, so you substitute y into this equation to give your final answer. This leaves you with x=$\ln{(\frac{9+\sqrt{21}}{16})}$ or $\ln{(\frac{9-\sqrt{21}}{16})}$, which are (to 3sf) -0.164 and -1.29 respectively. 

:::

A final thing you may want to consider is how to solve an equationn if you have logarithms in different bases. This will make use of the change of base formula.

::: {.callout-note}
## Change of base formula

$$\log_a(b)=\frac{\log_c(b)}{\log_c(a)}$$
:::

::: {.callout-note appearance="simple"}

## Example 11

$$\log_{8}(x)+\log_2(y)=\log_2(4y+1)$$
Represent y in terms of x.

Begin by rewriting $\log_{8}(x)$ in base 2, using the formula. This gives $\log_8(x)=\frac{\log_2(x)}{\log_2(8)}$. Now, you can see that $\log_2(8)=3$, as $2^3=8$ (you can use the method in Example 6 to check this). This means that $\log_8(x)=\frac{1}{3}\log_2(x)$. 

Applying how powers work with logarithms, and inserting back into the equation you want to solve gives $\log_2(x^{\frac{1}{3}})+\log_2(y)=\log_2(4y+1)$. To get the right hand side into one log, you can say that $\log_2(x^{\frac{1}{3}}y)$ due to the rules for adding logs. 

As the left and right hand side are in the same base, you can then say that $x^{\frac{1}{3}}y=4y+1$. Rearranging this gives $y= \frac{-1}{4-x^{\frac{1}{3}}}$.

:::


## Quick check problems {-}

<!-- add facility to check answers at end rather than one at a time -->

::: {.webex-check .webex-box}

1. You are given 3 questions and there supposed solutions. Determine if the solutions are True or False:

a) For $sin(4x)= 1$ a solution is $x =\frac{\pi}{8}$ `r torf("TRUE")`

b) For $$tan(x+15)=\sqrt{3}$$ 

a solution is $x=\frac{\pi-15}{4}$ `r torf(FALSE)`.

c) For $$cos(2x+25)= 0$$ 

a solution is $x=\frac{\pi+25}{4}$ `r torf(FALSE)`.



2. Using trigonometric identities solve the following. (The expected identities are given in Guide: Trigonometric Identities). Please give angles in degrees.

a) $$x = 2sin^2(\theta) + 2cos^2(\theta)$$  

Answer: $x =$ `r fitb(2)`

b) $$4sin^2(\theta) + 6cos^2(\theta) - 4 =0$$  Answer: $\theta =$ `r fitb(90)`

c)  $2cot^2(\theta) = csc^2(\theta)$  Answer: $\theta =$ `r fitb(45)`


3. Solve the following equations for x.

a) $\log_{3}{5x+4}=2$

Answer: $x =$ `r fitb(1)`.

b) $\log_{10}{5x} - \log_{10}{9} =3$  

Answer: $x =$ `r fitb(1800)`


:::
# Further reading {-}

For more questions on the subject, please go to [Questions: Solving equations involving logarithms](../questions/qs-solvingeqsindices.qmd).

## Version history and licensing {-}

v1.0: initial version created 08/23 by Ellie Gurini, Krish Chaudhary, Mark Toner as part of a University of St Andrews STEP project, and updated 08/25 by tdhc.
  
[This work is licensed under CC BY-NC-SA 4.0.](https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1)
